### ISSUE TITLE
failed to create vm from ISO on v 4.17.0

### ISSUE THREAD

**Issue by lijinlongpq** [apache/cloudstack#6565] opened 2022-07-24 18:11 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Compute Instance
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Management server on Ubuntu 20.04

##### SUMMARY

Previously I was able to create VM using ISOs. After upgrade to latest version which is 4.17.0.0 there is error prompt up when creating VM using ISO. The error is : 
Request failed. (431)
VM Creation failed. Volume size: -1GB is out of allowed range. Max: 1024 Min:1

Below is the log:
2022-07-23 15:32:53,223 DEBUG [c.c.a.ApiServlet] (qtp1850777594-3316:ctx-715a5e90) (logid:2e732721) ===START===  127.0.0.1 -- POST  command=deployVirtualMachine&response=json
2022-07-23 15:32:53,230 DEBUG [c.c.a.ApiServer] (qtp1850777594-3316:ctx-715a5e90 ctx-c19e21bc) (logid:2e732721) CIDRs from which account 'Acct[00f6ff47-9094-11ec-a1ef-005056931d8a-admin] -- Account {"id": 2, "name": "admin", "uuid": "00f6ff47-9094-11ec-a1ef-005056931d8a"}' is allowed to perform API calls: 0.0.0.0/0,::/0
2022-07-23 15:32:53,241 DEBUG [c.c.u.AccountManagerImpl] (qtp1850777594-3316:ctx-715a5e90 ctx-c19e21bc) (logid:2e732721) Access granted to Acct[00f6ff47-9094-11ec-a1ef-005056931d8a-admin] -- Account {"id": 2, "name": "admin", "uuid": "00f6ff47-9094-11ec-a1ef-005056931d8a"} to org.apache.cloudstack.quota.vo.ServiceOfferingVO$$EnhancerByCGLIB$$6d2c4d16@6dfe26b by AffinityGroupAccessChecker
2022-07-23 15:32:53,242 DEBUG [c.c.u.AccountManagerImpl] (qtp1850777594-3316:ctx-715a5e90 ctx-c19e21bc) (logid:2e732721) Access granted to Acct[00f6ff47-9094-11ec-a1ef-005056931d8a-admin] -- Account {"id": 2, "name": "admin", "uuid": "00f6ff47-9094-11ec-a1ef-005056931d8a"} to com.cloud.storage.DiskOfferingVO$$EnhancerByCGLIB$$15f5ca09@40092078 by AffinityGroupAccessChecker
2022-07-23 15:32:53,247 INFO  [c.c.a.ApiServer] (qtp1850777594-3316:ctx-715a5e90 ctx-c19e21bc) (logid:2e732721) VM Creation failed. Volume size: -1GB is out of allowed range. Max: 1024 Min:1
2022-07-23 15:32:53,247 DEBUG [c.c.a.ApiServlet] (qtp1850777594-3316:ctx-715a5e90 ctx-c19e21bc) (logid:2e732721) ===END===  127.0.0.1 -- POST  command=deployVirtualMachine&response=json

##### STEPS TO REPRODUCE

~~~
![image](https://user-images.githubusercontent.com/9441400/180660270-37dac278-20fb-439c-a176-34b090151f83.png)

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by nvazquez** [comment] 2022-07-25 11:10
Hi @lijinlongpq this is a duplicate of the issue: https://github.com/apache/cloudstack/issues/6447 - it will be fixed on 4.17.1.

For 4.17.0 there are some workarounds, can you please consider some of these?
- Using the API and specifying the rootdiskparameter as well. An example on cloudmonkey: `deploy virtualmachine networkids=<NETWORKID> templateid=<ISOID> serviceofferingid=<OFFERINGID> diskofferingid=<CUSTOM_OFFERING_ID> zoneid=<ZONEID> hypervisor=<HW> size=<SIZE> rootdisksize=<SIZE>`
- Using the UI: create a fixed offering matching the requested resources and create a VM from ISO using the fixed offering

**Closed** 2022-07-26 06:45 UTC
Labels: type:bug
