### ISSUE TITLE
Adding S3 secondary storage fails with NPE

### ISSUE THREAD

**Issue by rajujith** [apache/cloudstack#8956] opened 2024-04-22 06:30 UTC
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME

~~~
S3 secondary storage
~~~

##### CLOUDSTACK VERSION

~~~
ACS 4.19.0.0
~~~

##### CONFIGURATION

Minio S3 bucket created 
Access key and secret key generated in MiniO

##### SUMMARY

Tried adding an S3 secondary storage created out of locally installed MiniIO but it failed with NPE. It is good to have it fixed. 

##### STEPS TO REPRODUCE

~~~
1. Install a new cloudstack environment or remove NFS based secondary storages if added already. 
2. Install a MiniIO server and create a bucket , generate access and secret keys
3. Add the S3 secondary storage bucket as secondary storage while adding a zone or add secondary storage later on. Make sure to use NFS based staging storage.
4. S3 based secondary storage addition fails with NPE. 
~~~

##### EXPECTED RESULTS

~~~
We should be able to use the S3 bucket as a secondary storage.
~~~

##### ACTUAL RESULTS

~~~
Unable to add S3 bucket as a secondary storage 
~~~

```
2024-04-17 06:28:38,508 ERROR [c.c.a.ApiServer] (qtp940584193-13:ctx-0f5fb4bb ctx-79c01836) (logid:227bc7bf) unhandled exception executing api command: [Ljava.lang.String;@333fb5d
java.lang.NullPointerException
        at org.apache.cloudstack.storage.endpoint.DefaultEndPointSelector.findEndpointForImageStorage(DefaultEndPointSelector.java:334)
        at org.apache.cloudstack.storage.endpoint.DefaultEndPointSelector.select(DefaultEndPointSelector.java:444)
        at org.apache.cloudstack.storage.endpoint.DefaultEndPointSelector.select(DefaultEndPointSelector.java:395)
        at com.cloud.storage.download.DownloadMonitorImpl.initiateTemplateDownload(DownloadMonitorImpl.java:155)
        at com.cloud.storage.download.DownloadMonitorImpl.downloadTemplateToStorage(DownloadMonitorImpl.java:247)
```

**Comment by philtreF** [comment] 2024-04-25 15:06
Got the exact same issue with 4.18.1
I am using Ceph as a storage backend.
As a side-note I also tried Swift, ends with a SQL error : 

```
Failed to add data store: DB Exception on: com.mysql.cj.jdbc.ClientPreparedStatement: INSERT INTO image_store_details (image_store_details.store_id, image_store_details.name, image_store_details.value, image_store_details.display) VALUES [...]
```

NFS works but once I put NFS into production I will be stuck with NFS for this region as far as I understood...

**Comment by DaanHoogland** [comment] 2024-04-26 07:12
@philtreF if you have the chance to build yourself, please try #8986

**Comment by philtreF** [comment] 2024-04-26 08:49
I really would like but can't help you right now. If I find some time to compile (and learn to compile) I will let you know.

**Comment by shwstppr** [comment] 2024-05-22 10:38
@rajujith @DaanHoogland if the issue is fixed, should we close this?

@philtreF maybe you can try the latest nightly to test the fix, https://download.cloudstack.org/testing/nightly/latest/

**Comment by rajujith** [comment] 2024-05-24 08:53
@shwstppr  Yes, we can close it.

**Closed** 2024-05-24 08:54 UTC
Labels: component:secondary-storage, Severity:Critical, component:object-storage, affects:4.19.0, affects:4.18.1
