### ISSUE TITLE
UI - notification stacking on error messages

### ISSUE THREAD

**Issue by slavkap** [apache/cloudstack#5538] opened 2021-09-30 07:07 UTC
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
UI
~~~

##### SUMMARY

If you have multiple errors messages there is a need to clean them all one by one, which is not user-friendly. Is there an option to move the error messages a little further down from the alert and profile menus and to group or collapse the notications like this?

##### EXPECTED RESULTS
Something like this
![image](https://user-images.githubusercontent.com/51903378/135403646-25f6e574-853e-418f-a891-f65ecc973689.png)

To be able to clear all alerts
To be able to expand all notifications

##### ACTUAL RESULTS
![image](https://user-images.githubusercontent.com/51903378/135402544-f1e6a5aa-8b9c-41db-b250-8a5d0270f56f.png)

**Comment by rhtyd** [comment] 2021-09-30 09:05
More than stacking, I'm wondering why we've repeated errors (same message). How do you reproduce/get this @slavkap ?

**Comment by slavkap** [comment] 2021-09-30 11:39
@rhtyd, this was just an example while testing (I'm not sure I could reproduce the exact error). My point is if it's possible to collapse those notifications and to move them a bit below.
![image](https://user-images.githubusercontent.com/51903378/135448388-6ef7a31f-5e8a-497e-960c-d27e1b032566.png)

**Comment by rhtyd** [comment] 2021-10-02 09:47
cc @utchoang @nvazquez @sureshanaparti

**Comment by utchoang** [comment] 2021-10-04 01:51
@slavkap cc @rhtyd @davidjumani Currently, ant design does not have a feature to support grouping notifications together. In my opinion, it would be more reasonable to have a button that allows users to clear all notifications. What do you think?

**Comment by davidjumani** [comment] 2021-10-04 03:53
@slavkap The reason the failure notification persists is to get the user's attention. Success messages automatically disappear after 5 seconds. @utchoang where are you planning to add a clear all button ?

**Comment by utchoang** [comment] 2021-10-04 03:56
@davidjumani I'm still figuring out where to put the clear button. I think it will be next to the transliteration tool. What do you think?
![image](https://user-images.githubusercontent.com/13766648/135790530-2b21d794-627b-41e8-b61b-53df0a549008.png)

**Comment by slavkap** [comment] 2021-10-04 05:26
@utchoang, the clear all button sounds nice. Next to the translate button is OK, or you could put the button on top of the first error msg. @davidjumani, you are right. Probably it's only me who is distracted to clean such messages while manually testing because they're hiding the buttons.

**Comment by rohityadavcloud** [comment] 2021-12-30 10:54
Fixed in https://github.com/apache/cloudstack/pull/5549
@slavkap pl check latest 4.16 or the merged PR, re-open if not satisfied.

**Closed by rohityadavcloud** 2021-12-30 10:54 UTC
Labels: component:UI
