### ISSUE TITLE
Why do nodes restart when an NFS mount fails?

### ISSUE THREAD

**Issue by Overv** [apache/cloudstack#3082] opened 2018-12-06 08:47 UTC
It seems that the CloudStack agent forces a restart of a node when one of the primary storage NFS mounts fails, even if there are no VMs currently using a volume on it. That means that it takes just one NFS hickup to take down an entire cluster. Why was this design decision made and will it be changed at some point?

**Comment by rhtyd** [comment] 2018-12-06 19:34
Good points, we can review if it's possible for the agent to be intelligent about this. I certainly see the point that a host need not be rebooted when failing NFS node is not used by any of the VMs running on it. This was done to avoid data corruption cases, when VM HA kicks in and would start a HA enabled VM on a different host leading of disk corruption and rebooting the host seems the best option (not ideal). I'll tag few people to get their view on way forward - @PaulAngus @wido @rafaelweingartner @GabrielBrascher  @nvazquez and others.

**Comment by rhtyd** [comment] 2018-12-06 19:50
Similar: https://github.com/apache/cloudstack/issues/2657

**Comment by rhtyd** [comment] 2019-05-27 13:49
Addressed and replied, this is not a bug but a question that is better placed on the users ML. Closing on this remark, thanks.

**Closed by rhtyd** 2019-05-27 13:49 UTC
Labels: kvm
