### ISSUE TITLE
Listsnapshots.physicalsize has been 0

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#5019] opened 2021-05-12 03:58 UTC
The physicalsize field in the listsnapshots interface is always displayed as 0

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
libvirt 6.0.0
qemu 6.0.0
ceph 15.2.10
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by rhtyd** [comment] 2021-05-12 12:06
It's probably a limitation of ceph, as far as I know ceph does not support snapshots @div8cn (because you cannot have snapshots on raw disks unless snapshot is stored externally)
@wido @GabrielBrascher can you check and advise?

**Comment by wido** [comment] 2021-05-12 18:03
> It's probably a limitation of ceph, as far as I know ceph does not support snapshots @div8cn (because you cannot have snapshots on raw disks unless snapshot is stored externally)
> @wido @GabrielBrascher can you check and advise?

Ceph supports snapshots. You can snapshot and clone RBD images from Ceph.

See: https://docs.ceph.com/en/latest/rbd/rbd-snapshot/

**Comment by nvazquez** [comment] 2021-08-02 03:26
@GabrielBrascher @wido is there any update on this issue?

**Comment by rhtyd** [comment] 2021-08-31 09:07
Ping @GabrielBrascher @wido

**Comment by rhtyd** [comment] 2021-09-21 07:41
@GabrielBrascher @nvazquez @sureshanaparti @davidjumani @shwstppr @Pearl1594 @DaanHoogland @weizhouapache - any update on this, who's assigned/working on this? Thanks.

**Comment by nvazquez** [comment] 2021-09-23 05:01
Moved to the 4.16.1 milestone

**Comment by sureshanaparti** [comment] 2021-12-16 12:55
ping @GabrielBrascher @wido any update on this issue?

**Comment by GabrielBrascher** [comment] 2021-12-30 15:07
@sureshanaparti @div8cn 

I've tested on KVM with different primary storage pools: `Local storage`, `NFS`, and `Ceph`.
I have been able to reproduce this issue but it was not related to the storage pool. The factor that seems to be playing the key role (at least on my tests) here is the OS type.

To show that, here follows an output from _cloudmonkey_:
```
(cloudstack) 🐱 > list snapshots filter=name,osdisplayname,physicalsize,virtualsize
count = 6
snapshot:
+-----------------------------+-------------------------------+-----------------+-----------------+
|            NAME             |         OSDISPLAYNAME         |  PHYSICALSIZE   |   VIRTUALSIZE   |
+-----------------------------+-------------------------------+-----------------+-----------------+
| test-local-snapshot         | Other PV Virtio-SCSI (64-bit) | 3.408003072e+09 | 1.073741824e+10 |
| migration-rbd-test-snapshot | Other PV Virtio-SCSI (64-bit) | 3.59661568e+09  | 5.36870912e+10  |
| snap-123                    | Other PV (64-bit)             |               0 | 2.14749184e+08  |
| primary-nfs-snap2           | Other PV (64-bit)             |               0 | 2.14749184e+08  |
| primary-nfs-snap            | Other PV (64-bit)             |               0 | 2.14749184e+08  |
| test-snap1                  | Other PV (64-bit)             |               0 | 2.14749184e+08  |
+-----------------------------+-------------------------------+-----------------+-----------------+
```

@div8cn can you please confirm if that is also observed on your tests?

**Comment by sureshanaparti** [comment] 2022-01-13 16:56
Hi @div8cn Can you confirm on your test results please. Thanks.

**Comment by sureshanaparti** [comment] 2022-01-20 08:07
> Hi @div8cn Can you confirm on your test results please. Thanks.

Hi @div8cn Any update on the test results.

**Comment by rohityadavcloud** [comment] 2022-01-31 08:20
Tested this, couldn't reproduce this against 4.16.0:
```
> list snapshots  filter=name,osdisplayname,physicalsize,virtualsize,
count = 3
snapshot:
+---------------------------------+------------------+--------------+--------------+
|              NAME               |  OSDISPLAYNAME   | PHYSICALSIZE | VIRTUALSIZE  |
+---------------------------------+------------------+--------------+--------------+
| homelab_ROOT-107_20220131003215 | Ubuntu 20.04 LTS |  24328011776 | 107374182400 |
| homelab_ROOT-107_20220124003215 | Ubuntu 20.04 LTS |  22850371584 | 107374182400 |
| homelab_ROOT-107_20220117003215 | Ubuntu 20.04 LTS |  20795097088 | 107374182400 |
+---------------------------------+------------------+--------------+--------------+
```

**Comment by rohityadavcloud** [comment] 2022-01-31 08:20
@div8cn pl reopen if you still are able to reproduce this. Based on comment and reproduction attempts by Gabriel and me, I'll close this as it doesn't appear an issue now.

**Closed by rohityadavcloud** 2022-01-31 08:20 UTC
Labels: component:ceph, Severity:Minor
