### ISSUE TITLE
Missing completion events on project operations

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#9432] opened 2024-07-22 22:47 UTC
##### ISSUE TYPE
 * Improvement Request

##### COMPONENT NAME
~~~
Events
~~~

##### CLOUDSTACK VERSION
~~~
4.18, 4.19, 4.20
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
<img width="1372" alt="Screenshot 2024-07-22 at 19 45 08" src="https://github.com/user-attachments/assets/b943101b-0113-4657-bb18-6ad34fe6b55b">

There are missing completion events for project related operations:
- Project creation
- Add user to project
- Remove user from project
- Delete project
(probably more..)

**Comment by damonb123** [comment] 2024-08-06 17:02
The events are a feature and appear to be broken in some cases right now in 1.19.x.
Should this be listed as a bug instead of a improvement, since they used to work?
There are several tickets that look similar: #9292, #8771, #8052, and possibly a few others?
Is it possible they are all the same root cause?

**Comment by DaanHoogland** [comment] 2024-08-12 12:42
> The events are a feature and appear to be broken in some cases right now in 1.19.x. Should this be listed as a bug instead of a improvement, since they used to work? There are several tickets that look similar: #9292, #8771, #8052, and possibly a few others? Is it possible they are all the same root cause?

@damonb123 , @nvazquez marked this as affects 4.18.1 so it is not a regression in 4.19. It might be compared to older versions for sure. Some might be related, yes. Did you do any investigation/have any clues for us?

**Comment by sureshanaparti** [comment] 2024-08-27 10:41
Fixed in #9572

**Closed by sureshanaparti** 2024-08-27 10:41 UTC
Labels: type:improvement, affects:4.18.1
