### ISSUE TITLE
You are in developer mode, build and run UI using npm

### ISSUE THREAD

**Issue by Prashankalikotayt** [apache/cloudstack#5817] opened 2021-12-30 10:40 UTC
I am trying to add some plugin to Cloudstack. I have followed the steps in the developers guide however I do not see any UI after a successful build and run. In the web UI instead of getting the login prompt I see 'You are in developer mode, build and run using npm'.
I am a newbie, Any help is much appreciated.

**Comment by shwstppr** [comment] 2021-12-30 10:43
@Prashankalikotayt Run UI using npm https://github.com/apache/cloudstack/tree/main/ui#development

**Comment by Prashankalikotayt** [comment] 2021-12-30 10:52
I have tried doing this. How ever I see warnings during 'npm install' and finally fails. PFA for the log
[2021-12-30T10_48_01_531Z-debug-0.log](https://github.com/apache/cloudstack/files/7792581/2021-12-30T10_48_01_531Z-debug-0.log)

**Comment by rohityadavcloud** [comment] 2021-12-30 12:13
Hi @Prashankalikotayt please use the dev@ ML https://cloudstack.apache.org/mailing-lists.html to ask questions. To get started, you can follow the link shared by @shwstppr and ensure to install and use nodejs 12.x LTS.
```
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
```
Closing this as this is not a bug report.

**Closed by rohityadavcloud** 2021-12-30 12:13 UTC
