### ISSUE TITLE
UI doesn't allow login if sessionkey and JSESSIONID cookies are deleted 

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4136] opened 2020-06-09 12:18 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI (old UI, not Primate)
~~~

##### CLOUDSTACK VERSION

~~~
4.14+ (probably present on all older versions as well)
~~~

To consistently reproduce this, this is what I did:
- Login into UI, then open devtools->Application-> cookies
- Delete the sessionkey and JSESSIONID cookies (to simulate session expiry, in browser but not on mgmt server)
- Refresh UI and try to log in, you won't be able to login
- You've to wait until the previous session expires, or clear cache

The solution is for legacy UI to call the logout API when 401/unauthorised happens (logout will expire session on backend mgmt server) and clear cookies.

**Comment by rhtyd** [comment] 2020-06-10 04:17
The issue happens because from code we're unable to clear HttpOnly cookie[1], this cookie can only be cleared by CloudStack (i.e. the server, not the client) and the fix is to call the logout API (which Primate does as well) when we get 401 error on the first API we call to validate auth (listCapabilities).

[1] https://owasp.org/www-community/HttpOnly

**Comment by rhtyd** [comment] 2020-06-10 04:18
@davidjumani please pick this up. Thanks.

**Comment by davidjumani** [comment] 2020-06-15 06:22
Calling a logout after a 401 does not appear to solve this

**Comment by andrijapanicsb** [comment] 2020-06-15 09:20
When the issue happens (not able to login to /client), you can go to /client/primate, login and logout - then all is fine and you can login back to /client.
Once this expires, you need to repeat the exercise again or clear all cookies (for some reason, manually deleting cookies via Developer Tools --> Application --> Cookies, did not work for me)

**Comment by rhtyd** [comment] 2020-06-15 10:20
@davidjumani can you experiment by removing all cookies and then call logout API?

**Comment by davidjumani** [comment] 2020-06-16 09:05
Yup. Tried clearing before and after logging out. Was still unable to login. Only clearing everything in the browser appeared to work

**Comment by rhtyd** [comment] 2020-06-18 08:14
@davidjumani are you blocked, is there no solution to this otherwise? (perhaps a backend fix?)

**Comment by davidjumani** [comment] 2020-06-19 12:08
@rhtyd Looks like there's nothing that can be done from the front end. Need to look into the backend

**Comment by borisstoyanov** [comment] 2020-11-11 12:19
@rhtyd @davidjumani @andrijapanicsb, I've managed to reproduce this after upgrading to 4.15 master.

**Comment by borisstoyanov** [comment] 2020-11-11 12:19
I had to clear session id from cookies and then it worked.

**Comment by DaanHoogland** [comment] 2020-11-11 12:55
@borisstoyanov to be clear; You did reproduce this with primate, did you?

**Comment by rhtyd** [comment] 2020-11-11 13:35
@borisstoyanov is that login issue in Primate or old UI? Did it work in incognito mode vs your usual browser?

**Comment by rhtyd** [comment] 2020-11-11 13:35
@Pearl1594 can you discuss with Bobby and look into why cookies are not getting cleared/removed? In latest old UI code, we call logout that would destroy all old cookies, before we log in.

**Comment by rhtyd** [comment] 2020-11-20 08:44
Looks like #4465 is fixed, closing.

**Closed by rhtyd** 2020-11-20 08:44 UTC
Labels: Severity:Critical, type:bug, type:regression
