### ISSUE TITLE
Impossible to configure any RBD primary storage

### ISSUE THREAD

**Issue by bragonznx** [apache/cloudstack#5056] opened 2021-05-31 14:10 UTC
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
Primary storage RBD
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0
~~~

##### CONFIGURATION

~~~
basic network 
~~~

##### OS / ENVIRONMENT

~~~
full ubuntu 20.04
~~~

##### SUMMARY

~~~
we have from every manager and KVM host this commande who is fully working : 
rbd ls -p cloudstack
Every node have access to the RBD
and each time we are trying to configure the RBD as a primary storage for nodes we are getting a "Failed to add data store: Failed to access storage pool"

it's impossible it's not the case at all ! 

##### STEPS TO REPRODUCE
<!--
For bugs, show exactly how to reproduce the problem, using a minimal test-case. Use Screenshots if accurate.

For new features, show how the feature would be used.
-->

<!-- Paste example playbooks or commands between quotes below -->
~~~

~~~

<!-- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!-- What did you expect to happen when running the steps above? -->

~~~
to add a primary storage
~~~

##### ACTUAL RESULTS
<!-- What actually happened? -->

<!-- Paste verbatim command output between quotes below -->
~~~
2021-05-31 14:08:15,132 WARN  [c.c.a.AlertManagerImpl] (qtp1644231115-329:ctx-8ba0ed07 ctx-75a8f9db) (logid:b24c8b46) AlertType:: 7 | dataCenterId:: 1 | podId
:: 1 | clusterId:: null | message:: Unable to attach storage pool45 to the host3
2021-05-31 14:08:15,138 WARN  [o.a.c.s.d.l.CloudStackPrimaryDataStoreLifeCycleImpl] (qtp1644231115-329:ctx-8ba0ed07 ctx-75a8f9db) (logid:b24c8b46) Unable to e
stablish a connection between Host[-3-Routing] and org.apache.cloudstack.storage.datastore.PrimaryDataStoreImpl@2b497993
com.cloud.utils.exception.CloudRuntimeException: Unable establish connection from storage head to storage pool 45 due to java.lang.NumberFormatException: For 
input string: ""
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.base/java.lang.Integer.parseInt(Integer.java:662)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at com.cloud.hypervisor.kvm.resource.LibvirtStoragePoolXMLParser.parseStoragePoolXML(LibvirtStoragePoolXMLParser.java:58)
        at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.getStoragePoolDef(LibvirtStorageAdaptor.java:413)
        at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.getStoragePool(LibvirtStorageAdaptor.java:439)
        at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.getStoragePool(LibvirtStorageAdaptor.java:424)
        at com.cloud.hypervisor.kvm.storage.LibvirtStorageAdaptor.createStoragePool(LibvirtStorageAdaptor.java:654)
        at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.createStoragePool(KVMStoragePoolManager.java:329)
        at com.cloud.hypervisor.kvm.storage.KVMStoragePoolManager.createStoragePool(KVMStoragePoolManager.java:323)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtModifyStoragePoolCommandWrapper.execute(LibvirtModifyStoragePoolCommandWrapper.java:42)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtModifyStoragePoolCommandWrapper.execute(LibvirtModifyStoragePoolCommandWrapper.java:35)
        at com.cloud.hypervisor.kvm.resource.wrapper.LibvirtRequestWrapper.execute(LibvirtRequestWrapper.java:78)
        at com.cloud.hypervisor.kvm.resource.LibvirtComputingResource.executeRequest(LibvirtComputingResource.java:1643)
        at com.cloud.agent.Agent.processRequest(Agent.java:661)
        at com.cloud.agent.Agent$AgentRequestHandler.doTask(Agent.java:1079)
        at com.cloud.utils.nio.Task.call(Task.java:83)
        at com.cloud.utils.nio.Task.call(Task.java:29)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
45
        at org.apache.cloudstack.storage.datastore.provider.DefaultHostListener.hostConnect(DefaultHostListener.java:86)
        at com.cloud.storage.StorageManagerImpl.connectHostToSharedPool(StorageManagerImpl.java:1028)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy96.connectHostToSharedPool(Unknown Source)
        at org.apache.cloudstack.storage.datastore.lifecycle.CloudStackPrimaryDataStoreLifeCycleImpl.attachCluster(CloudStackPrimaryDataStoreLifeCycleImpl.jav
a:451)
        at com.cloud.storage.StorageManagerImpl.createPool(StorageManagerImpl.java:741)
        at com.cloud.storage.StorageManagerImpl.createPool(StorageManagerImpl.java:210)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy96.createPool(Unknown Source)
        at org.apache.cloudstack.api.command.admin.storage.CreateStoragePoolCmd.execute(CreateStoragePoolCmd.java:163)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:156)
        at com.cloud.api.ApiServer.queueCommand(ApiServer.java:764)
        at com.cloud.api.ApiServer.handleRequest(ApiServer.java:588)
        at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:321)
        at com.cloud.api.ApiServlet$1.run(ApiServlet.java:134)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:131)
        at com.cloud.api.ApiServlet.doPost(ApiServlet.java:98)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1386)

~~~

**Comment by rhtyd** [comment] 2021-05-31 14:26
@bragonznx are you using the legacy UI or the new/default UI? Can you try by putting the port when you add the storage, the issue has been fixed for 4.15.1 - https://github.com/apache/cloudstack/pull/4565
Please test and close, and maybe search for closed issues/pull request before entering a new bug. If you're just testing 4.15, kindly use the nightly builds - http://download.cloudstack.org/testing/nightly

(We'll be cutting 4.15.1 RC1 this week)

**Comment by bragonznx** [comment] 2021-05-31 14:30
@rhtyd I have the same issue with : 192.168.70.204:6789 as address for the monitor !

**Comment by rhtyd** [comment] 2021-05-31 14:39
Thanks for confirming @bragonznx as the issue is already fixed for 4.15.1 milestone, you may either wait for 4.15.1 or test using the nightlies build for 4.15 branch; or use a workaround to specify the port. Closing on your remark.

**Comment by bragonznx** [comment] 2021-05-31 14:40
@rhtyd I just upgrade to the last version with both packages :   
dpkg -i cloudstack-common_4.15.1.0-snapshot.20210531~xenial_all.deb cloudstack-management_4.15.1.0-snapshot.20210531~xenial_all.deb
And now i'm not able to login to the WEBUI anymore !!!!

**Comment by rhtyd** [comment] 2021-05-31 14:46
@bragonznx :facepalm: of course, I didn't mean you should upgrade. As the name implies, snapshots or `nightlies` builds are not official builds and daily builds of development branches and should be used for testing purposes on fresh environments.

For the UI, you need to check your management server logs at /var/log/cloudstack/... path for exceptions and errors: /var/log/cloudstack/management/management-server.log For example, if you were on 4.15.0.0 and upgraded to the 4.15 nightlies then you did not perform the upgrade step (for example register the 4.15.1 systemvmtemplate http://download.cloudstack.org/systemvm/4.15/). 

Assuming you're testing and not in a production env, you would generally create a new environment. If that's not the case you can simply (a) pass explicit host/port when adding Ceph, or (b) create a fresh env with nightlies.

**Comment by bragonznx** [comment] 2021-05-31 14:51
Next time perhaps you should be more precise ....
This env isn't in production hopfully, but we definitely need the RBD CEPH support to work !
Last question ....
Do I need to upgrade the agent in 4.15.1 too ? or can I keep them ?

**Comment by bragonznx** [comment] 2021-05-31 15:02
We upgraded and we restart from a fresh DB
And the issue is still present ! we can't add a RBD storage from the WEBUI

**Comment by rhtyd** [comment] 2021-05-31 15:25
@bragonznx well I imagine users would know the nightly build are not official releases (https://en.m.wikipedia.org/wiki/Daily_build) and are meant for testing only. Glad this wasn't your production env. 

 As advised earlier, while adding the Ceph pool did you specify the port, for example ceph-pool.example.com:1234 (or whatever is the configured port). Another approach would be to try with the url or hostname/port fixed the DB in the cloud.storage_pool table and restart management server (note: I've not tested this but this may just work). 

cc @wido @GabrielBrascher @weizhouapache @andrijapanicsb - have you tested Ceph with 4.15 lately?

**Comment by rhtyd** [comment] 2021-05-31 15:25
@bragonznx yes on your other question, you need to upgrade the agent package as well on all hosts, same as the management server version.

**Comment by rhtyd** [comment] 2021-05-31 16:28
Closing this as Alexandre has confirmed over email that with 4.15.1 snapshot builds after upgrading agents pools are Up.

**Closed by rhtyd** 2021-05-31 16:28 UTC
