### ISSUE TITLE
When at sub domain level, click on add ldap account, admin is displayed with error saying LDAP is not configured for root domain

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3753] opened 2019-12-09 08:35 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY

Seems like a UI error that the form is set to list root domain instead of the sub level, which the admin is currently at 
![4964377f-4140-4324-acef-1b93554aeb77](https://user-images.githubusercontent.com/13551960/70420117-9dd69800-1a6f-11ea-82ca-196a1af6947d.png)

##### EXPECTED RESULTS

~~~
filter the sub domain
~~~

##### ACTUAL RESULTS

~~~
filters the root domain and gets obvious errors 
~~~

**Comment by DaanHoogland** [comment] 2019-12-13 08:32
the error is valid but the request should not be made for ROOT but for the "current" domain associated with the origin of the request.

**Comment by DaanHoogland** [comment] 2020-12-11 13:52
@borisstoyanov can you recheck in the current (new) UI, so we can if needed address there? tnx

**Comment by nvazquez** [comment] 2021-07-27 04:04
@borisstoyanov is this still an issue with the new UI?

**Comment by rhtyd** [comment] 2021-09-21 07:32
Tested on qa.cloudstack.cloud, unable to reproduce this in modern UI. Closing this.

**Closed by rhtyd** 2021-09-21 07:32 UTC
Labels: component:UI, component:LDAP
