### ISSUE TITLE
When using multiple NICs, VM HA does not work if you have configured zone wide NFS.

### ISSUE THREAD

**Issue by jms345** [apache/cloudstack#2708] opened 2018-06-13 11:38 UTC
**ISSUE TYPE**

Bug Report 

**COMPONENT NAME** 

HA, Storage 

**CLOUDSTACK VERSION** 

4.11.0

**CONFIGURATION** 

Basic networking,  3 NICs,  management, Guest, storage, zone wide NFS storage 

**OS /ENVIRONMENT**

CentOS Linux release 7.5.1804 (Core)

**SUMMARY** 

When using multiple NICs as described above VM HA does not work if you have configured zone wide NFS.  

When the power is disconnected from one of the compute nodes the management server logs show the ping timeouts but it never confirms that the host is down so in the UI its state is "Alert" not "Down".  Because of this there is no attempt to restart the VMs on another of the compute nodes. 

With cluster wide NFS instead VM HA works with multiple NICs. 

The same happens with 2 as opposed to 3 NICs so I think it is just if you split traffic across the NICs. 

I ran two comparison tests - 

1) all traffic over single NIC, zone wide NFS -  worked 
2) management/storage on one NIC, guest on another, zone wide NFS - did not work 

and I have the management server logs for both tests if needed ?

**Comment by rafaelweingartner** [comment] 2018-06-20 09:58
@jms345 is this still a valid issue? If it is not, we can close it.

**Comment by jms345** [comment] 2018-06-20 10:00
Still valid.

I removed it because of some further testing that complicated things but it
is still a bug as far as I know.

Do you want me to update with details ?



*Jon Marshall *| *Network Engineer*

*Datacentreplus *| 4 Quays Reach | Carolina Way | Manchester | M50 2ZY

T: 0161 4646101

www.datacentreplus.co.uk

[image: dcplogo]

**Comment by rafaelweingartner** [comment] 2018-06-20 10:03
Yes please. Otherwise, someone might close it.

**Comment by jms345** [comment] 2018-06-20 10:05
TEST

**Comment by jms345** [comment] 2018-06-20 10:29
updated


*Jon Marshall *| *Network Engineer*

*Datacentreplus *| 4 Quays Reach | Carolina Way | Manchester | M50 2ZY

T: 0161 4646101

www.datacentreplus.co.uk

[image: dcplogo]

**Comment by DaanHoogland** [comment] 2020-01-29 14:14
@jms345 have you ran into this on newer versions as well? Any work done on this?

**Comment by rhtyd** [comment] 2020-08-12 08:29
@jms345 are you able to reproduce this with latest master or 4.14.0.0?

**Comment by DaanHoogland** [comment] 2021-01-04 10:06
@jms345 there seems to be low interest in this issue. How are you dealing with this and is it still an issue?

**Comment by weizhouapache** [comment] 2021-06-17 10:00
this can be fixed by 
https://github.com/apache/cloudstack/pull/4708/files#diff-5762d5f6db9d0479cc84ad9f76d4ba8cf3c6628147c572a160372803d8157f88R88-R96

**Comment by DaanHoogland** [comment] 2021-06-18 11:57
@jms345 can you review @weizhouapache ' s suggestion? And confirm it solves the issue?

**Comment by rhtyd** [comment] 2021-07-05 06:21
Fixed in https://github.com/apache/cloudstack/pull/5164

**Closed by rhtyd** 2021-07-05 06:21 UTC
Labels: Severity:Minor, complexity:complex, component:basic-network
