### ISSUE TITLE
Extraconfig values cannot be added for VMs that are shut down

### ISSUE THREAD

**Issue by Arceoavs** [apache/cloudstack#6937] opened 2022-12-01 13:47 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VM Management
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When a user (with admin rights or without) creates an extraconfig under Settings for a VM that is switched off, one cannot enter a value in the Value input field.
The UI refuses any keyboard input and the browser displays error messages. 

![image](https://user-images.githubusercontent.com/16841883/205068736-2b3a5ae3-fbd4-4735-903c-71b86b267eea.png)

##### STEPS TO REPRODUCE

~~~
Create a VM.
Switch it off. 
Go to Settings and try to add a configuration. 
Look at the Browser console. 
~~~

##### EXPECTED RESULTS

~~~
Values can be set. 
~~~

##### ACTUAL RESULTS

~~~
Values cannot be set. 
~~~

Output in the Browser console:
```
config and theme applied [App.vue:40:12](webpack:///src/App.vue)
Object { data: {…}, status: 401, statusText: "Unauthorized", headers: {…}, config: {…}, request: XMLHttpRequest }
[request.js:37:12](webpack:///src/utils/request.js)
Some cookies are misusing the recommended “SameSite“ attribute 22
Cookie “rl_anonymous_id” has been rejected because it is already expired. [api](https://sparci-cloudstack.uni-koblenz.de/client/api/?command=logout&response=json)
Cookie “rl_page_init_referrer” has been rejected because it is already expired. [api](https://sparci-cloudstack.uni-koblenz.de/client/api/?command=logout&response=json)
Cookie “rl_page_init_referring_domain” has been rejected because it is already expired. [api](https://sparci-cloudstack.uni-koblenz.de/client/api/?command=logout&response=json)
Cookie “rl_user_id” has been rejected because it is already expired. [api](https://sparci-cloudstack.uni-koblenz.de/client/api/?command=logout&response=json)
Cookie “rl_trait” has been rejected because it is already expired. [api](https://sparci-cloudstack.uni-koblenz.de/client/api/?command=logout&response=json)
Object { data: {…}, status: 432, statusText: "432", headers: {…}, config: {…}, request: XMLHttpRequest }
[request.js:37:12](webpack:///src/utils/request.js)
Error: Request failed with status code 432
    exports createError.js:16
    exports settle.js:17
    c xhr.js:54
[SamlDomainSwitcher.vue:85:18](webpack:///src/components/header/SamlDomainSwitcher.vue)
Object { data: {…}, status: 431, statusText: "Request Header Fields Too Large", headers: {…}, config: {…}, request: XMLHttpRequest }
[request.js:37:12](webpack:///src/utils/request.js)
Uncaught (in promise) Error: Request failed with status code 431
    exports createError.js:16
    exports settle.js:17
    c xhr.js:54
[createError.js:16:14](webpack:///node_modules/axios/lib/core/createError.js)
TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    Babel 2
    C generate.js:341
    run reactivity.esm-bundler.js:167
    get value reactivity.esm-bundler.js:1101
    Q generate.js:553
    run reactivity.esm-bundler.js:167
    get value reactivity.esm-bundler.js:1101
    setup generate.js:558
    g runtime-core.esm-bundler.js:155
    C runtime-core.esm-bundler.js:164
    u runtime-core.esm-bundler.js:1726
    run reactivity.esm-bundler.js:167
    h runtime-core.esm-bundler.js:1790
    tn runtime-core.esm-bundler.js:328
    P runtime-core.esm-bundler.js:5168
    e runtime-core.esm-bundler.js:5080
    run reactivity.esm-bundler.js:167
    U runtime-core.esm-bundler.js:4968
    W runtime-core.esm-bundler.js:4901
    C runtime-core.esm-bundler.js:4489
    e runtime-core.esm-bundler.js:5107
    run reactivity.esm-bundler.js:167
    U runtime-core.esm-bundler.js:4968
    W runtime-core.esm-bundler.js:4901
    C runtime-core.esm-bundler.js:4489
    e runtime-core.esm-bundler.js:5107
    run reactivity.esm-bundler.js:167
    U runtime-core.esm-bundler.js:4968
```

**Comment by DaanHoogland** [comment] 2022-12-27 13:13
@Arceoavs have you tried adding an extraconfig with the API?

**Comment by MejdiB** [comment] 2022-12-27 17:50
@DaanHoogland @Arceoavs I have the same issue on ACS 4.17.2. For some reason, adding an extraconfig-2 value via the GUI is not working since 4.17.x. As a workaround, we can assign extraconfig value via cloudmonkey. The global parameters are already set since we set up our ACS environment. For me the issue is GUI related

**Comment by weizhouapache** [comment] 2023-08-10 14:55
@Arceoavs 
this is a missing UI feature
I have created an issue for followup: https://github.com/apache/cloudstack/issues/7849

closing

**Closed by weizhouapache** 2023-08-10 14:55 UTC
Labels: type:bug, component:UI, Severity:Major, status:has-work-around
