### ISSUE TITLE
VM Snapshot will fail if last_host_id points to a removed host

### ISSUE THREAD

**Issue by Doni7722** [apache/cloudstack#3889] opened 2020-02-17 10:23 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, UI, DB-related
~~~

##### CLOUDSTACK VERSION

~~~
4.11.3
~~~

##### CONFIGURATION

Hypervisor used is VMware ESXi but may happen on other Hypervisor types too

##### OS / ENVIRONMENT

N/A

##### SUMMARY

If a stopped VM is on a Host which will be removed the last_host_id will still point to the removed host. If you now try to create a VM Snaphost (may other actions will fail too but not tested yet) it will create a NPE as it can't connect to the old Host.

##### STEPS TO REPRODUCE

~~~
1. stop a VM which is on Host 1
2. remove Host 1 from the inventory
3. try to create a snapshot on the stopped VM
~~~

##### EXPECTED RESULTS

~~~
VM Snapshot should succeed as there are other Hosts which can take care of it
~~~

##### ACTUAL RESULTS

~~~
NPE as it tries to create the Snapshot over the Host which was removed. Here the exception:


2020-02-17 10:05:45,096 ERROR [cloud.api.ApiAsyncJobDispatcher] (API-Job-Executor-78:ctx-299e1e51 job-2404677) Unexpected exception while executing org.apache.cloudstack.api.command.user.vmsnapshot.CreateVMSnapshotCmd
java.lang.RuntimeException: Unexpected exception
        at com.cloud.vm.snapshot.VMSnapshotManagerImpl.createVMSnapshot(VMSnapshotManagerImpl.java:482)
        at sun.reflect.GeneratedMethodAccessor1021.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:338)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
        at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy199.createVMSnapshot(Unknown Source)
        at org.apache.cloudstack.api.command.user.vmsnapshot.CreateVMSnapshotCmd.execute(CreateVMSnapshotCmd.java:113)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:150)
        at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:108)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:581)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:529)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.cloud.vm.snapshot.VMSnapshotManagerImpl.orchestrateCreateVMSnapshot(VMSnapshotManagerImpl.java:1199)
        at sun.reflect.GeneratedMethodAccessor1022.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        ... 26 more

~~~

**Comment by rhtyd** [comment] 2020-08-12 09:15
@Doni7722 is this still an issue with 4.14 or master?

**Comment by Doni7722** [comment] 2020-08-13 09:43
@rhtyd I could not reproduce it under 4.14

**Comment by DaanHoogland** [comment] 2020-08-17 13:17
@Doni7722 please compare
https://github.com/apache/cloudstack/issues/3264
searching for "snapshot fail" gives 560 closed PRs alone so I couldn't tell which one to backport.
As a workaround you may try to first restart or migrate the VM and then try again.

**Comment by Doni7722** [comment] 2020-08-18 22:48
@DaanHoogland in #3264 was nothing changes as the issue was closed. I searched a little as well but had no success.

**Comment by DaanHoogland** [comment] 2020-09-18 12:51
@Doni7722 it was closed as not-a-bug, and you could not reproduce in a newer version... can we close this one?

**Comment by Doni7722** [comment] 2020-09-18 13:04
@DaanHoogland I guess so - if I see smth similar under 4.14 I'll open a new one.

**Closed** 2020-09-18 13:40 UTC
