### ISSUE TITLE
Load balancer protocols bug

### ISSUE THREAD

**Issue by DagSonsteboSB** [apache/cloudstack#3252] opened 2019-04-01 14:52 UTC
##### ISSUE TYPE
 * Bug Report
 * Improvement Request

##### COMPONENT NAME
* ACS 4.11 VR load balancer
* ACS 4.11 CreateLoadBalancerRule API call

##### CLOUDSTACK VERSION
* ACS 4.11.x

##### CONFIGURATION
* Advanced zone
* Isolated guest network
* Load balancer rules

##### OS / ENVIRONMENT
* N/A

##### SUMMARY
* Load balancer protocols for UDP and TCP-proxy are not labelled correctly in the GUI: 
** ![image](https://user-images.githubusercontent.com/12859582/55336601-1888f580-5495-11e9-8253-76d96433ccbd.png)
** Note label is label.lb.protocol_udp / label.lb.protocol_tcp-proxy (underscores used to signify the inserted space)
** Whatever protocol is chosen is persisted in the DB with the above strings.
* However HAproxy and iptables configuration will always be configured with "TCP". 
* This may or may not be down to two protocol parameters here: https://github.com/apache/cloudstack/blob/4.11.2.0/api/src/org/apache/cloudstack/api/command/user/loadbalancer/CreateLoadBalancerRuleCmd.java#L316 where the first one is always set to "TCP"

##### STEPS TO REPRODUCE
* Create LB rule using each protocol
* Observe the configuration which ends up on the HAproxy configuration on the VR does NOT change and always uses TCP.

##### EXPECTED RESULTS
* Protocols UDP and TCP-proxy being honoured

##### ACTUAL RESULTS
* All LB rules are configured as TCP.

**Comment by rhtyd** [comment] 2019-06-28 07:24
This exists in master:
```
ui/l10n/en.js:"label.lb.protocol.http":"HTTP",
ui/l10n/en.js:"label.lb.protocol.ssl":"SSL",
ui/l10n/en.js:"label.lb.protocol.tcp":"TCP",
ui/l10n/en.js:"label.lb.protocol.udp":"UDP",
```

**Comment by PaulAngus** [comment] 2019-11-20 14:43
I believe that the issue is here:
https://github.com/apache/cloudstack/blob/master/ui/scripts/network.js#L6846-L6862

![image](https://user-images.githubusercontent.com/4810220/69247933-341b4a80-0ba3-11ea-9c6e-d46d1aa6f115.png)

Enumerating the protocols is introducting a space after '.protocol.', the label cannot then be resolved by the language files.

```
    var protocols = protocolCapabilities.value.split(',');

        if (!protocols) {
            return [];
        }

        var data = [];
        $(protocols).each(function() {
            data.push({id: this.valueOf(), name: this.valueOf(), description: _l('label.lb.protocol.' + this.valueOf())});
        });

```

**Comment by DaanHoogland** [comment] 2019-11-28 14:27
Did a quick fix replacing spaces but only half fixed it: 
<img width="936" alt="image" src="https://user-images.githubusercontent.com/2486961/69813960-90114f00-11f3-11ea-93b1-fa3784953372.png">

maybe the other half is in the actual label missing.

**Comment by DaanHoogland** [comment] 2019-11-28 14:50
right i am; 'tcp.proxy' and 'tcp-proxy' are used interchangably. will create a PR to try and unify

**Closed** 2019-12-20 15:43 UTC
Labels: component:UI
