### ISSUE TITLE
vmware hosts reconnect handling

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#6141] opened 2022-03-21 07:54 UTC
When in an vmware envirements ESXi hosts have disconnected with the vcenter, they won't be marked as reconnected in ACS after they reconnect to vcenter. The MS needs to be restarted for them to get back to connected state. This issue occurs when there is an underlying infra problem that caused the connectivity between ESXi hosts and the vcenter to be broken.  It would be nice if the MS would *not* have to restart to re-establish that the hosts are connected again.

##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
vmware
~~~

##### CLOUDSTACK VERSION

~~~
all before 4.17
~~~

##### STEPS TO REPRODUCE

~~~
install an vmware datacenter in ACS.
disconnect one of the ESXi from vcenter
when it is marked as disconnected in ACS, reconnect it
~~~

##### EXPECTED RESULTS

~~~
the hosts gets marked connected in ACS after a while.
~~~

##### ACTUAL RESULTS

~~~
The hosts stays in disconnected state.
~~~

**Comment by harikrishna-patnala** [comment] 2022-07-11 03:05
cc @DaanHoogland @sureshanaparti @nvazquez 

I've tried multiple cases to disconnect the host from vCenter and tried to connect back. Every time I've observed the direct agent map being updated accordingly and hosts are back to UP state.

Not during this testing, but I've observed this issue happening in some environments but not sure about the reason

Do you think this is something related to multiple management servers or any other case you know!

**Comment by harikrishna-patnala** [comment] 2022-07-11 07:56
One other observation is the API "reconnectHost" is not actually trying to reconnect. It does only disconnection of the host. Later when direct agent thread tries to get the host status, then it tries to connect. So it could be a reason that global settings which controls the host pings and direct agent thread are not triggered on time and host remains in disconnected state.

**Comment by shwstppr** [comment] 2022-08-16 12:39
@DaanHoogland @harikrishna-patnala @nvazquez as this is not reproducible do we need to improve the behaviour in any way?

**Comment by DaanHoogland** [comment] 2022-08-17 16:33
@shwstppr we can try to improve what @harikrishna-patnala sugests:

> One other observation is the API "reconnectHost" is not actually trying to reconnect. It does only disconnection of the host. Later when direct agent thread tries to get the host status, then it tries to connect. So it could be a reason that global settings which controls the host pings and direct agent thread are not triggered on time and host remains in disconnected state.

As we don´t know what triggers the behaviour, trying to improve behaviour is going to be an open ended effort. Let's not try to do this perfect in the first go.

**Comment by rohityadavcloud** [comment] 2022-09-20 09:23
As we can't reproduce this, I propose we close this and revisit in future as/if and when we've more information.

**Closed by rohityadavcloud** 2022-09-20 09:23 UTC
Labels: component:vmware, type:improvement
