### ISSUE TITLE
[Usage] Duplicate entries after volume resize

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#3452] opened 2019-07-01 17:14 UTC
##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME
~~~
Usage
~~~

##### CLOUDSTACK VERSION
~~~
4.11, 4.12
~~~

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Resize a volume multiple times
On the next run of the usage server, verify the usage.log file

##### STEPS TO REPRODUCE
~~~
Resize a volume multiple times
On the next run of the usage server verify the usage.log
~~~

##### EXPECTED RESULTS
~~~
No errors on usage.log
~~~

##### ACTUAL RESULTS
~~~
2019-07-01 17:00:00,209 ERROR [cloud.usage.UsageManagerImpl] (Usage-Job-1:null) (logid:) Found duplicate usage entry for volume: 4 assigned to account: 2; marking as deleted...
2019-07-01 17:00:00,219 ERROR [cloud.usage.UsageManagerImpl] (Usage-Job-1:null) (logid:) Found duplicate usage entry for volume: 4 assigned to account: 2; marking as deleted...
~~~

**Comment by borisstoyanov** [comment] 2019-07-05 09:46
I cannot reproduce this with master @nvazquez I've created a data disk and resized it 3 times and then the usage cycle passed and no errors were observed in the log

[log.txt](https://github.com/apache/cloudstack/files/3362079/log.txt)

**Comment by rhtyd** [comment] 2019-07-10 12:25
@nvazquez kindly re-test and try to reproduce against latest master with a fresh environment, if you're unable to reproduce it kindly close it otherwise tag it against 4.13 milestone. Thanks.

**Closed** 2019-08-01 17:23 UTC
