### ISSUE TITLE
CloudStack uses 1st cdrom of VM to mount ConfigDrive ISO

### ISSUE THREAD

**Issue by aleskxyz** [apache/cloudstack#4808] opened 2021-03-12 17:37 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
ConfigDrive
~~~

##### CLOUDSTACK VERSION

~~~
4.14.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

ESXi 6.5
CentOS7

##### SUMMARY

This bug report actually has 2 root cause that solving each of them can solve the bug. 

1. Based on [design document](https://cwiki.apache.org/confluence/display/CLOUDSTACK/Using+ConfigDrive+for+Metadata%2C+Userdata+and+Password) of ConfigDrive feature, the iso should be mounted on 2nd cdrom drive of VM but CS don't even create it.

1. When user tries to attach an ISO to the created VM, CloudStack tries to replace the ISOs but don't answer the esxi question about unmounting iso, so the operation fails.

##### STEPS TO REPRODUCE

~~~
Create a network with ConfigDrive as userdata
Create a VM attached to that network and start it
Attach an ISO to the VM
~~~

##### EXPECTED RESULTS

~~~
CloudStack creates the 2nd cdrom drive for VM and mount ConfigDrive ISO on it
or
CloudStack answer the question of ESXi about unmounting ConfigDrive ISO
~~~

##### ACTUAL RESULTS

~~~
CloudStack tries to unmount ConfigDrive iso but leave the esxi question unanswered so operation fails. 
~~~

**Comment by DaanHoogland** [comment] 2021-03-15 15:12
@aleskxyz is this a regression compared to 4.14.0, that you know?
have you tried this on master?

**Comment by aleskxyz** [comment] 2021-03-16 08:15
> @aleskxyz is this a regression compared to 4.14.0, that you know?
> have you tried this on master?

@DaanHoogland 
I see this bug in 4.14.0 too.
I didn't test it on master.

**Comment by DaanHoogland** [comment] 2021-03-18 10:55
ok, @aleskxyz tnx for reporting

**Comment by rhtyd** [comment] 2021-03-30 09:01
It's not a blocker, but an issue with the proposed design. @aleskxyz are you facing any operation issue due to this? We've tested cloud-init based template in our labs where it works.

**Comment by aleskxyz** [comment] 2021-03-30 11:13
> It's not a blocker, but an issue with the proposed design. @aleskxyz are you facing any operation issue due to this? We've tested cloud-init based template in our labs where it works.

@rhtyd 
As I describe in bug description, this bug prevents attaching iso to VM.

**Comment by Pearl1594** [comment] 2021-04-09 08:33
@aleskxyz attaching configdrive ISO to the 2nd drive would involve considerable design changes on vmware end which is something we can target for the next major release - 4.16. As an immediate fix to mitigate this issue, we can work on facilitating a force unmount of the attached configdrive iso - i.e., enable ACS to answer the ESXi question.

**Comment by rhtyd** [comment] 2021-04-28 08:16
Fixed in https://github.com/apache/cloudstack/pull/4907

**Closed by rhtyd** 2021-04-28 08:16 UTC
Labels: Severity:Major, component:vmware, type:bug, type:config
