### ISSUE TITLE
CloudStack Simulator 4.11 - not working 

### ISSUE THREAD

**Issue by kgoik** [apache/cloudstack#3512] opened 2019-07-23 20:40 UTC
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME

~~~
Simulator
~~~

##### CLOUDSTACK VERSION

~~~
4.11
4.12
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ubuntu 18.04

##### SUMMARY

Build for both branches works fine. While trying to start the simulator I get following error (master branch works just fine).

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'templateServiceImpl' defined in URL [jar:file:/root/.m2/repository/org/apache/cloudstack/cloud-engine-storage-image/4.11.4.0-SNAPSHOT/cloud-engine-storage-image-4.11.4.0-SNAPSHOT.jar!/META-INF/cloudstack/core/spring-engine-storage-image-core-context.xml]: Circular depends-on relationship between 'templateServiceImpl' and 'dataStoreManagerImpl'
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean (AbstractBeanFactory.java:300)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean (AbstractBeanFactory.java:200)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons (DefaultListableBeanFactory.java:758)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization (AbstractApplicationContext.java:868)
    at org.springframework.context.support.AbstractApplicationContext.refresh (AbstractApplicationContext.java:549)
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext (DefaultModuleDefinitionSet.java:145)
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$2.with (DefaultModuleDefinitionSet.java:122)
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule (DefaultModuleDefinitionSet.java:245)
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule (DefaultModuleDefinitionSet.java:250)
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule (DefaultModuleDefinitionSet.java:250)
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule (DefaultModuleDefinitionSet.java:233)
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContexts (DefaultModuleDefinitionSet.java:117)
    at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load (DefaultModuleDefinitionSet.java:79)
    at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules (ModuleBasedContextFactory.java:37)
    at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init (CloudStackSpringContext.java:71)
    at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init> (CloudStackSpringContext.java:58)
    at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init> (CloudStackSpringContext.java:62)
    at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized (CloudStackContextLoaderListener.java:52)
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized (ContextHandler.java:800)
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized (ServletContextHandler.java:444)
    at org.eclipse.jetty.server.handler.ContextHandler.startContext (ContextHandler.java:791)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext (ServletContextHandler.java:294)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp (WebAppContext.java:1349)
    at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp (JettyWebAppContext.java:297)
    at org.eclipse.jetty.webapp.WebAppContext.startContext (WebAppContext.java:1342)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart (ContextHandler.java:741)
    at org.eclipse.jetty.webapp.WebAppContext.doStart (WebAppContext.java:505)
    at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart (JettyWebAppContext.java:366)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start (ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart (ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart (AbstractHandler.java:61)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart (ContextHandlerCollection.java:163)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start (ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart (ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart (AbstractHandler.java:61)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start (ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start (Server.java:387)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart (ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart (AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart (Server.java:354)
    at org.eclipse.jetty.maven.plugin.JettyServer.doStart (JettyServer.java:73)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:68)
    at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty (AbstractJettyMojo.java:535)
    at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute (AbstractJettyMojo.java:358)
    at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute (JettyRunMojo.java:167)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[WARNING] !RequestLog
[INFO] Started ServerConnector@68076f57{HTTP/1.1}{0.0.0.0:8080}
[INFO] Started @27603ms
[INFO] Started Jetty Server
`

##### STEPS TO REPRODUCE

~~~
Checkout stable/LTS branch:

    git checkout 4.11

Build:

    mvn clean install -Dsimulator -P developer,systemvm

Deploy database:

    mvn -q -Pdeveloper -pl developer -Ddeploydb
    mvn -q -Pdeveloper -pl developer -Ddeploydb-simulator


Install Marvin test library:

    pip install --user --upgrade tools/marvin/dist/Marvin-*.tar.gz

Run the CloudStack management server: (ctrl+c to stop)

    mvn -pl :cloud-client-ui jetty:run  -Djava.net.preferIPv4Stack=true -Dsimulator

~~~

##### EXPECTED RESULTS

~~~
Jetty starting fine with simulator, being able to access /client 
~~~

##### ACTUAL RESULTS

~~~
Startup of the server fails, /client endpoint is not available.
~~~

**Comment by rhtyd** [comment] 2019-07-24 05:37
Looks like simulator against latest 4.11 works okay: https://travis-ci.org/apache/cloudstack/builds/556807454
@kgoik what was your mvn and jdk version? 4.11 must be built using JDK1.8.

**Comment by rhtyd** [comment] 2019-07-24 07:10
Tested again seems to be working: https://travis-ci.org/apache/cloudstack/builds/562920058

**Comment by rhtyd** [comment] 2019-07-24 08:16
Tested locally unable to reproduce, closing.

**Closed by rhtyd** 2019-07-24 08:16 UTC

**Comment by kgoik** [comment] 2019-07-24 09:11
I used the ShapeBlue  test VM:

root@cloudstack-fizzbuzz-kvm:~# mvn --version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-20-generic", arch: "amd64", family: "unix"
root@cloudstack-fizzbuzz-kvm:~# java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

**Comment by edtoktay** [comment] 2019-07-28 11:44
While building and Running in ShapeBlue Test VM:
I faced the same problems with @kgoik.  
Java and mvn versions same as @kgoik 's post.

Jetty starts with Circular depends-on exception. However, that exception lets spring not to initiate and create beans. So; services are unavailable on that point.

**Comment by edtoktay** [comment] 2019-07-29 04:04
I tried other tags 4.11.2.0 even can not build. On the other hand, 4.11.3.0 works fine built and started flawlessly
