### ISSUE TITLE
IPMI/Redfish module issue when starting management-server

### ISSUE THREAD

**Issue by tonymmm1** [apache/cloudstack#9485] opened 2024-08-03 19:03 UTC
##### ISSUE TYPE

* Bug Report
##### COMPONENT NAME

~~~
Management-server
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.0
~~~

##### CONFIGURATION

Restarting management-server

##### OS / ENVIRONMENT

```bash
ubuntu@management:/etc/cloudstack/management$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy
```
```bash
ubuntu@management:/etc/cloudstack/management$ uname -r
5.15.0-117-generic
```

##### STEPS TO REPRODUCE

~~~
systemctl restart management-server
~~~

##### ACTUAL RESULTS

~~~
ubuntu@management:/etc/cloudstack/management$ sudo tail -f /var/log/cloudstack/management/management-server.log 
2024-08-03 10:44:37,129 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [xenserver-discoverer] context.
2024-08-03 10:44:37,129 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [xenserver-discoverer]
2024-08-03 10:44:37,129 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [outofbandmanagement] context.
2024-08-03 10:44:37,129 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [outofbandmanagement]
2024-08-03 10:44:37,129 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [ipmitool] context.
2024-08-03 10:44:37,129 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [ipmitool]
2024-08-03 10:44:37,129 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [nested-cloudstack] context.
2024-08-03 10:44:37,129 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [nested-cloudstack]
2024-08-03 10:44:37,130 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [redfish] context.
2024-08-03 10:44:37,130 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [redfish]

~~~

**Comment by tonymmm1** [comment] 2024-08-03 19:09
More context if helpful

```log
2024-08-03 14:08:29,595 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [redfish] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.19.1.0.jar!/META-INF/cloudstack/redfish/spring-redfish-context.xml]
2024-08-03 14:08:29,595 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [redfish] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.19.1.0.jar!/META-INF/cloudstack/outofbandmanagement/spring-core-lifecycle-outofbandmanagement-context-inheritable.xml]
2024-08-03 14:08:29,596 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [redfish] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.19.1.0.jar!/META-INF/cloudstack/core/spring-core-lifecycle-core-context-inheritable.xml]
2024-08-03 14:08:29,596 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [redfish] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.19.1.0.jar!/META-INF/cloudstack/system/spring-core-system-context-inheritable.xml]
2024-08-03 14:08:29,596 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [redfish] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.19.1.0.jar!/META-INF/cloudstack/system/spring-framework-config-system-context-inheritable.xml]
2024-08-03 14:08:29,596 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [redfish] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.19.1.0.jar!/META-INF/cloudstack/system/spring-contrail-system-context-inheritable.xml]
2024-08-03 14:08:29,596 INFO  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Loading module context [redfish] from URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.19.1.0.jar!/META-INF/cloudstack/bootstrap/spring-bootstrap-context-inheritable.xml]
2024-08-03 14:08:29,617 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Failed to start module [redfish] due to: [Error creating bean with name 'org.springframework.beans.factory.config.PropertyPlaceholderConfigurer#0' defined in URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.19.1.0.jar!/META-INF/cloudstack/bootstrap/spring-bootstrap-context-inheritable.xml]: Cannot resolve reference to bean 'DefaultConfigResources' while setting bean property 'locations'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'DefaultConfigResources' available].
2024-08-03 14:08:29,617 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) module start failure of module [redfish] was due to: 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.beans.factory.config.PropertyPlaceholderConfigurer#0' defined in URL [jar:file:/usr/share/cloudstack-management/lib/cloudstack-4.19.1.0.jar!/META-INF/cloudstack/bootstrap/spring-bootstrap-context-inheritable.xml]: Cannot resolve reference to bean 'DefaultConfigResources' while setting bean property 'locations'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'DefaultConfigResources' available
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1707)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1452)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:171)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:748)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext(DefaultModuleDefinitionSet.java:173)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$2.with(DefaultModuleDefinitionSet.java:142)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:273)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:278)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:278)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:278)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:278)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:261)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContexts(DefaultModuleDefinitionSet.java:130)
	at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:78)
	at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37)
	at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:70)
	at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:57)
	at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:61)
	at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized(CloudStackContextLoaderListener.java:52)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1073)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:1002)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:765)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:426)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:423)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:387)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
	at org.apache.cloudstack.ServerDaemon.start(ServerDaemon.java:198)
	at org.apache.cloudstack.ServerDaemon.main(ServerDaemon.java:111)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'DefaultConfigResources' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:874)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:309)
	... 57 more
2024-08-03 14:08:29,618 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [bootstrap] context.
2024-08-03 14:08:29,618 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Could not get module [bootstrap] context bean.
2024-08-03 14:08:29,618 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [system] context.
2024-08-03 14:08:29,618 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [system]
2024-08-03 14:08:29,618 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [core] context.
2024-08-03 14:08:29,618 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [core]
2024-08-03 14:08:29,618 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [allocator] context.
2024-08-03 14:08:29,618 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [allocator]
2024-08-03 14:08:29,618 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [host-allocator-random] context.
2024-08-03 14:08:29,618 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [host-allocator-random]
2024-08-03 14:08:29,618 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [planner] context.
2024-08-03 14:08:29,618 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [planner]
2024-08-03 14:08:29,618 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [api-planner] context.
2024-08-03 14:08:29,618 WARN  [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Application context not found for module definition [api-planner]
2024-08-03 14:08:29,618 DEBUG [o.a.c.s.m.m.i.DefaultModuleDefinitionSet] (main:null) (logid:) Trying to obtain module [baremetal-planner] context.
```

**Comment by tonymmm1** [comment] 2024-08-22 01:00
Hi sorry I ended up doing a clean reinstall of the full cloudstack deployment and the issues seemed to go away.

**Comment by JoaoJandre** [comment] 2024-08-22 11:41
> Hi sorry I ended up doing a clean reinstall of the full cloudstack deployment and the issues seemed to go away. If you want to close the issue you can but pretty sure its something to do with mismatch/db upgrade between versions.

@tonymmm1 That is pretty much what I was expecting. That's the reason I asked for the full logs ;) . But if the problem is fixed, I'll be closing the issue.

**Closed by JoaoJandre** 2024-08-22 11:41 UTC
Labels: type:question, status:needs-investigation
