### ISSUE TITLE
Error 404 - Hosts

### ISSUE THREAD

**Issue by chriscc12345** [apache/cloudstack#4733] opened 2021-02-28 16:43 UTC
![image](https://user-images.githubusercontent.com/60073902/109426119-7eb98280-79f4-11eb-8347-70b1ea75e5ca.png)

![image](https://user-images.githubusercontent.com/60073902/109426146-ae688a80-79f4-11eb-9593-6aed20bf806f.png)

After fresh install, this happens when I want to view hosts

**Comment by abdelouahabb** [comment] 2021-03-01 03:05
Try `/legacy` in case of `404` or something related to html

**Comment by rhtyd** [comment] 2021-03-01 07:14
@chriscc12345 are you trying to search? Can you check your mgmt server logs for any exception or error, as well as Chrome dev tools for the HTTP request sent and error seen.

**Comment by weizhouapache** [comment] 2021-03-01 08:48
@chriscc12345 
did this happen when you tried to access a resource which does not exist or has been removed ?

**Comment by chriscc12345** [comment] 2021-03-01 18:44
> @chriscc12345 are you trying to search? Can you check your mgmt server logs for any exception or error, as well as Chrome dev tools for the HTTP request sent and error seen.

![chrome_apache](https://user-images.githubusercontent.com/60073902/109543449-f52ab300-7ace-11eb-8884-19e7a53228ab.PNG)

**Comment by chriscc12345** [comment] 2021-03-01 18:51
> @chriscc12345
> did this happen when you tried to access a resource which does not exist or has been removed ?

No not at all, just after clean install
![zone_create](https://user-images.githubusercontent.com/60073902/109544142-e1338100-7acf-11eb-9941-5441ded152a4.PNG)

**Comment by chriscc12345** [comment] 2021-03-01 18:57
It lloks like its reying to create the 2 systems VM's but they also fail

![image](https://user-images.githubusercontent.com/60073902/109544770-a251fb00-7ad0-11eb-8fac-6b4f6ae2eb96.png)

**Comment by chriscc12345** [comment] 2021-03-01 18:59
[MNGMNT_LOG.txt](https://github.com/apache/cloudstack/files/6063847/MNGMNT_LOG.txt)

**Comment by mib1185** [comment] 2021-03-01 20:16
@DK101010 Sounds well known 🤔

**Comment by mkriegs** [comment] 2021-03-01 20:16
Hey, i can confirm the bug appears for me aswell.
Something with the API Call of the GUI, one of the Parameter is wrong. Try API call with monkey. But i cant remember.

During the zone deployment the Interface mapping with the brigdes not working aswell. We use cloudbr0 - 2 and use different VLAN ranges. After deploy the mgmt provides to First Host only cloudbr0 and bindes ranges to wrong Interfaces. So the Array of the values are not going right order. So it isnt really good for new users they know how the stuffs go.

Best regards Michael

**Comment by chriscc12345** [comment] 2021-03-01 20:43
> It lloks like its reying to create the 2 systems VM's but they also fail
> 
> ![image](https://user-images.githubusercontent.com/60073902/109544770-a251fb00-7ad0-11eb-8fac-6b4f6ae2eb96.png)

Manage to get systems vms going
![image](https://user-images.githubusercontent.com/60073902/109556474-8dc92f00-7adf-11eb-9f78-576513d1ec43.png)

**Comment by chriscc12345** [comment] 2021-03-01 20:46
[MNGMNT_LOG2.txt](https://github.com/apache/cloudstack/files/6064366/MNGMNT_LOG2.txt)

**Comment by DK101010** [comment] 2021-03-02 09:45
Hi @chriscc12345,
I had a similar problem. In my case switch my system locals to german and replace all decimal separators to comma instead of dot. the result was an exception in backend and a 431 in the frontend.  

Perhaps it helps

**Comment by chriscc12345** [comment] 2021-03-05 13:22
any update yet

**Comment by DaanHoogland** [comment] 2021-03-05 14:27
@chriscc12345 no news but I think the UI problem is a minor bug and concequential:
```
2021-03-01 20:57:17,947 DEBUG [c.c.a.t.Request] (Work-Job-Executor-140:ctx-f5bde6f7 job-4/job-158 ctx-df43ae87) (logid:a48d9078) Seq 1-763641611816010008: Sending  { Cmd , MgmtId: 2692192521, via: 1(kvm.chriscoetzer.co.za), Ver: v1, Flags: 100111, [{"org.apache.cloudstack.storage.command.CopyCommand":{"srcTO":{"org.apache.cloudstack.storage.to.TemplateObjectTO":{"path":"template/tmpl/1/3/","origUrl":"https://download.cloudstack.org/systemvm/4.15/systemvmtemplate-4.15.0-kvm.qcow2.bz2","uuid":"9ae90677-0b9a-4af5-9773-00ba3480d0ed","id":"3","format":"QCOW2","accountId":"1","checksum":"81b3e48bb934784a13555a43c5ef5ffb","hvm":"false","displayText":"SystemVM Template (KVM)","imageDataStore":{"com.cloud.agent.api.to.NfsTO":{"_url":"nfs://192.168.170.5/nfs_2_Data/","_role":"Image"}},"name":"routing-3","hypervisorType":"KVM","bootable":"false","uniqueName":"routing-3","directDownload":"false","deployAsIs":"false"}},"destTO":{"org.apache.cloudstack.storage.to.TemplateObjectTO":{"origUrl":"https://download.cloudstack.org/systemvm/4.15/systemvmtemplate-4.15.0-kvm.qcow2.bz2","uuid":"9ae90677-0b9a-4af5-9773-00ba3480d0ed","id":"3","format":"QCOW2","accountId":"1","checksum":"81b3e48bb934784a13555a43c5ef5ffb","hvm":"false","displayText":"SystemVM Template (KVM)","imageDataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"519bf693-e6a9-39fa-a70f-4af935839d4f","id":"1","poolType":"NetworkFilesystem","host":"192.168.170.4","path":"/nfs_1_Data","port":"2049","url":"NetworkFilesystem://192.168.170.4/nfs_1_Data/?ROLE=Primary&STOREUUID=519bf693-e6a9-39fa-a70f-4af935839d4f","isManaged":"false"}},"name":"routing-3","hypervisorType":"KVM","bootable":"false","uniqueName":"routing-3","directDownload":"false","deployAsIs":"false"}},"executeInSequence":"true","options":{},"options2":{},"wait":"10800"}}] }
2021-03-01 20:57:18,023 DEBUG [c.c.a.t.Request] (AgentManager-Handler-11:null) (logid:) Seq 1-763641611816010008: Processing:  { Ans: , MgmtId: 2692192521, via: 1, Ver: v1, Flags: 110, [{"org.apache.cloudstack.storage.command.CopyCmdAnswer":{"result":"false","details":"com.cloud.utils.exception.CloudRuntimeException: org.libvirt.LibvirtException: internal error: Child process (/usr/bin/mount 192.168.170.5:/nfs_2_Data/template/tmpl/1/3 /mnt/0b6d4b75-09cd-3927-8ca1-a718eb32091f -o nodev,nosuid,noexec) unexpected exit status 32: mount.nfs: mounting 192.168.170.5:/nfs_2_Data/template/tmpl/1/3 failed, reason given by server: No such file or directory
","wait":"0"}}] }
```
the systemvms can't be started and that is your main issue. Have you seeded the systemtemplates?

**Comment by rhtyd** [comment] 2021-03-06 09:58
@chriscc12345 can you share details of your environment, is this a test/virtualised environment where you're running nested KVM hosts? Instead of the new UI, you can also access the legacy UI (use <host|ip>:8080/client/legacy in browser)

**Comment by chriscc12345** [comment] 2021-03-06 10:24
> @chriscc12345 can you share details of your environment, is this a test/virtualised environment where you're running nested KVM hosts? Instead of the new UI, you can also access the legacy UI (use <host|ip>:8080/client/legacy in browser)

Hi I am running this in a test environment, I can confirm in legacy view that the host does show. as well as the system vm's, and I have enabled the nested cpu support in Hyper V.
![legacy _host](https://user-images.githubusercontent.com/60073902/110203382-9ec6c700-7e76-11eb-810b-963b95c10c92.PNG)
![legacy_vm](https://user-images.githubusercontent.com/60073902/110203385-9ff7f400-7e76-11eb-8259-d69e2e1b1bba.PNG)

**Comment by rhtyd** [comment] 2021-03-06 10:35
@chriscc12345 can you try disabling the `ca.plugin.root.auth.strictness` global setting to false, destroy or restart your systemvms? And then see if the agent come online?

**Comment by mkriegs** [comment] 2021-03-06 13:47
@rhtyd is the 404 allready solved in some ptr for 4.15.1 or 4.16?

**Comment by rhtyd** [comment] 2021-03-07 14:46
@mkriegs @chriscc12345 we're unable to reproduce this issue with latest 4.15/master branches, I think it's due to some env/setup issue. To help investigate, can you check if you're able to see the list of hosts via the legacy UI (in 4.15.0.0 release, assuming that's what you're testing) and also try executing these API as the root admin - `listHosts` and `listHostsMetrics` (see https://github.com/apache/cloudstack-cloudmonkey/wiki/Getting-Started). When you do open the hosts page either in the new UI or legacy UI, can you tail the management server logs (on mgmt server: `tail -f /var/log/cloudstack/management/management-server.log`) and see/share if you see any error or exception. Hope this helps.

**Comment by rhtyd** [comment] 2021-03-07 14:48
Screenshots from my 4.15.0.0 based env:

![Screenshot from 2021-03-07 20-17-24](https://user-images.githubusercontent.com/95203/110243865-3d8c1a00-7f82-11eb-86a2-62100704d135.png)
![Screenshot from 2021-03-07 20-17-30](https://user-images.githubusercontent.com/95203/110243866-3f55dd80-7f82-11eb-8daa-f03ad93559b7.png)
![Screenshot from 2021-03-07 20-17-37](https://user-images.githubusercontent.com/95203/110243868-3fee7400-7f82-11eb-84b8-53ea16d2cceb.png)

**Comment by DaanHoogland** [comment] 2021-03-19 09:16
@chriscc12345 can you give more information? for instance an more detailed content of you javascript console log, or a log from the server while you are trying the failing API from cloudmonkey for instance?

**Comment by mhoffmann21** [comment] 2021-03-19 10:26
@mkriegs @rhtyd 
I can confirm the 404 exception for the Host tab.
It only occurs with the new UI. Unfortunately, because of this, I can only add hosts through the old UI. Since the legacy UI is maybe removedin the near future, this some kind of critical for me.

The acutal request seems to be (regarding the management log):
` -- GET  listall=true&type=routing&page=1&pagesize=20&command=listHostsMetrics&response=json`

The management-log further says, right after the GET request:
`2021-03-19 11:21:06,252 WARN  [c.c.a.d.ParamGenericValidationWorker] (qtp587003819-436:ctx-60659048 ctx-5f09f808) (logid:9619489a) Received unknown parameters for command listHostsMetrics. Unknown parameters : listall`

Is there a workaround?
My problem is that I do not know what I can actually to do further investigate and solve this problem.

**Comment by DaanHoogland** [comment] 2021-03-19 15:44
@mhoffmann21 the WARN , you can ignore. it is not harmfull, did you see any other messages in the log, after this?
I have not heard of a workaround yet and only a few people seem to get this , indicating that there is some specific configuration that triggers this.
could you for instance try issuing listHostMetrics through cloudmonkey? and capture the logging.

**Comment by mhoffmann21** [comment] 2021-03-23 14:51
@DaanHoogland hey, sorry for the late answer.
There are no other messages in the log after the click on the host tab and the described WARN message...yeah of course the typical messages which occur on a regular basis, but nothing new for me.

I tried to make the API call (listHosts) and got a valid JSON answer back, which lists all of my hosts.
If I try to make the listHostMetrics call, I get: `(HTTP 431, error code 9999) For input string: ` and a random number for string.

The log messages:
```
2021-03-23 15:41:19,865 DEBUG [c.c.a.q.QueryManagerImpl] (qtp587003819-420:ctx-cda8fde0 ctx-10656beb) (logid:32f94509) >>>Searching for hosts>>>
2021-03-23 15:41:19,888 DEBUG [c.c.a.q.QueryManagerImpl] (qtp587003819-420:ctx-cda8fde0 ctx-10656beb) (logid:32f94509) >>>Generating Response>>>
2021-03-23 15:41:20,117 INFO  [c.c.a.ApiServer] (qtp587003819-420:ctx-cda8fde0 ctx-10656beb) (logid:32f94509) For input string: "1,5"
2021-03-23 15:41:20,117 DEBUG [c.c.a.ApiServlet] (qtp587003819-420:ctx-cda8fde0 ctx-10656beb) (logid:32f94509) ===END===  141.57.168.21 -- GET  command=listHostsMetrics&response=json&sessionkey=...
```

As you can see, the generated answer consists the random number, in this case "1,5".

**Comment by DaanHoogland** [comment] 2021-03-23 15:07
@mhoffmann21 just a hunch but that looks like a localisation issue: 1,5 in dutch or german vs 1.5 in english???

**Comment by mhoffmann21** [comment] 2021-03-23 15:14
@DaanHoogland 1,5 like in dutch or german.

**Comment by MoeRT09** [comment] 2021-03-23 19:54
@DaanHoogland It is definitely related to the system locale. Changing it to en_US.UTF-8 fixes this issue. So probably the problem is caused by the number format.  

On Ubuntu you can achieve changing the system language by issuing `dpkg-reconfigure locales` and following the prompts.
This needs to be done for all managers in the cluster (or you will get inconsistent results).

**Comment by DaanHoogland** [comment] 2021-03-23 21:46
@mhoffmann21 both dutch and german use comma for decimal separation and english uses point. This is the issue as confirmed by @MoeRT09/ I'm not sure if this should be solved by setting the server or client locale though. It'll be a good workaround nonetheless.
cc @rhtyd @davidjumani @shwstppr @utchoang I'm not sure but this sounds like a doable ui fix. Do you agree?

**Comment by mhoffmann21** [comment] 2021-03-24 07:34
@DaanHoogland to clear a thing: @MoeRT09/ and I work together on the same system. :)
So yes, the proposed solution works fine as described.

**Comment by DaanHoogland** [comment] 2021-03-24 17:43
tnx @mhoffmann21 can you clarify if you consider this a proper way of installing or as a temporary workaround that needs fixing and close or update the description as appropriate?

**Comment by MoeRT09** [comment] 2021-03-24 17:48
In my opinion this should be fixed and only seen as a workaround. At least it should be clearly mentioned in the documentation.

**Comment by DaanHoogland** [comment] 2021-03-24 17:51
Ok, please @MoeRT09 please add as much data on the error config and the workaround as possible so a any volunteer knows what and how to fix.

**Comment by MoeRT09** [comment] 2021-03-24 18:56
The error always was triggered by the UI requesting the API endpoint `https://<host>/client/api/?listall=true&type=routing&page=1&pagesize=20&command=listHostsMetrics&response=json`, with the response mentioned [here](https://github.com/apache/cloudstack/issues/4733#issuecomment-804967083).

The request should return something like this:
```json
{
  "listhostsmetricsresponse": {
    "count": 1,
    "host": [
      {
        "powerstate": "Disabled",
        "instances": "0 / 0",
        "cputotalghz": "25.60 Ghz (x 1.0)",
        "cpuusedghz": "0.00 Ghz",
        "cpuallocatedghz": "0.00 Ghz",
        "cpuloadaverage": 0.02,
        "memorytotalgb": "124.81 GB (x 1.0)",
        "memoryusedgb": "1.04 GB",
        "memoryallocatedgb": "0.00 GB",
        "networkread": "0.43 GB",
        "networkwrite": "0.00 GB",
        "cputhreshold": false,
        "cpudisablethreshold": false,
        "cpuallocatedthreshold": false,
        "cpuallocateddisablethreshold": false,
        "memorythreshold": false,
        "memorydisablethreshold": false,
        "memoryallocatedthreshold": false,
        "memoryallocateddisablethreshold": false,
      //...
      }
    ]
  }
}
```

As we never saw it working with a non english locale, I can only assume, that somewhere on one of those numbers, it gets formatted with the system number scheme. Looking at the numbers of the "For input string: "*,**" error, the `"cpuloadaverage"` property looks most suspicious for me as it fits the number scheme and is the only decimal number not enclosed in hyphens, which would definitely cause JSON parsing errors, if the period were a comma.

As a workaround, as already mentioned, the system language of the host running the Cloudstack Manager  should be set to `en_US.UTF-8`. On Ubuntu this can be accomplished by running `dpkg-reconfigure locales` and selecting `en_US.UTF-8` as default. Afterwards, the system should be restarted.

**Comment by DaanHoogland** [comment] 2021-03-24 19:01
@MoeRT09 is what is the locale and on what machine, please? I know locale is the problem but is it server side (and which) or client side (and which).

cc @utchoang @davidjumani can one of you assess if I'm asking the right question here?

**Comment by MoeRT09** [comment] 2021-03-24 19:04
I just edited the comment. Our Cloudstack manager hosts were configured with german locale (`de_DE.UTF-8`). The KVM hosts themselves are also configured with German locale, but the problem was solved by changing only the manager to `en_US.UTF-8`.

**Comment by DK101010** [comment] 2021-03-29 09:00
> Hi @chriscc12345,
> I had a similar problem. In my case switch my system locals to german and replace all decimal separators to comma instead of dot. the result was an exception in backend and a 431 in the frontend.
> 
> Perhaps it helps

Hi, in my case, the error occurs in HostDaoImpl.java in line 165.
DecimalFormat decimalFormat = new DecimalFormat("#.##"); This object use the jvm locals to decide which separator should be used. the jvm locals depends on the sytem/user locals

During my search I switch my system locals to english but the error continue occurs. After this I checked jvm settings (java -XshowSettings -version | grep lang) and find out that my default format language was already german. After a system reboot, my jvm settings switch to english. Not quite sure but I think the jvm setting will be set on time during the start of the jvm. Additional changes after this start have no effects. 

I hope it helps.

**Comment by rhtyd** [comment] 2021-03-30 08:58
@utchoang @davidjumani can you try to reproduce this by changing the CloudStack management server locale to non-English (say German) and see how it affects the host metrics response and if the UI break when the metrics have ',' instead of '.' for example instead of some value as `100.123` you get `100,123`. The change may require backend change.

**Comment by DK101010** [comment] 2021-03-31 07:22
> DecimalFormat decimalFormat

Sorry, prescribed.... I means the error occurs in HostJoinDaoImpl.java. Line 177.

**Comment by rhtyd** [comment] 2021-04-06 06:35
Ping @utchoang @davidjumani

**Comment by utchoang** [comment] 2021-04-06 07:03
@rhtyd cc @davidjumani I changed the local language to German and the test failed to get the same error. I think this error from the backend instead of the UI.

**Comment by rhtyd** [comment] 2021-04-06 07:14
Thanks for testing @utchoang, we'll discuss this and raise a PR then

**Comment by rhtyd** [comment] 2021-04-13 12:38
Fixed in https://github.com/apache/cloudstack/pull/4900
@chriscc12345 can you test pull request https://github.com/apache/cloudstack/pull/4900 in your environment? @utchoang has tested in his local env. Thanks.

**Closed** 2021-04-13 12:37 UTC
Labels: Severity:Major, component:UI, component:api
