### ISSUE TITLE
Password in plaintext in management and access logs

### ISSUE THREAD

**Issue by CodeBleu** [apache/cloudstack#9512] opened 2024-08-09 17:02 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Logs
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.0, 4.18.1.0
~~~

##### SUMMARY

Password and sensitive information are shown in plaintext in the management and access logs on the management server.

##### STEPS TO REPRODUCE

~~~
Looking in log files.
~~~

##### EXPECTED RESULTS

~~~
No sensitive passwords or secrets in logs
~~~

##### ACTUAL RESULTS

~~~
/var/log/cloudstack/management/access.log:1077542308:10.30.0.61 - - [09/Aug/2024:16:42:01 +0000] "GET /client/api?account=joe-again-1286&apiKey=<apikey>&command=addVpnUser&domainid=c91a0528-377b-48aa-9c7b-2c7ead68200d&password=TOPSECRETPASSWORD&response=json&username=seantest2&signature=Ek%2BC7EGsrmNi0ONFL%2BxJBJxSGe0%3D HTTP/1.1" 200 115 "-" "GuzzleHttp/7" 86

/var/log/cloudstack/management/management-server.log:122775505:{u'vpn_users': [{u'add': True, u'password': u'TOPSECRETPASSWORD', u'user': u'seantest2'}], u'type': u'vpnuserlist', u'delete_from_processed_cache': False}


~~~

**Comment by rajujith** [comment] 2024-08-12 04:56
It is best to send credentials in a POST.

**Comment by CodeBleu** [comment] 2024-08-14 15:01
@rohityadavcloud Is there anyway this can be bumped up to a release sooner than 4.20.0.0?  Being that this is a Security and Auditing issue, It would be nice to have this resolved sooner than later.

**Comment by weizhouapache** [comment] 2024-08-22 09:16
the first issue with `access.log` has been discussed before
users can redirect the file access.log to /dev/null as suggested by @DaanHoogland 

the second issue (vpn user password are displayed in management-server.log) seems to only impact vpn user.
I was able to reproduce the issue. it may not deserve a security release.
I will have a look


cc @rohityadavcloud @DaanHoogland @sureshanaparti

**Comment by CodeBleu** [comment] 2024-08-22 23:06
> the first issue with `access.log` has been discussed before users can redirect the file access.log to /dev/null as suggested by @DaanHoogland
> 
> the second issue (vpn user password are displayed in management-server.log) seems to only impact vpn user. I was able to reproduce the issue. it may not deserve a security release. I will have a look
> 
> cc @rohityadavcloud @DaanHoogland @sureshanaparti

@DaanHoogland do you have the link to what @weizhouapache is talking about for the `access.log` to /dev/null?

Depending on what that says, I'm not sure if that is an acceptable solution for me, because I want to see the `access.log`, but I don't want to see the passwords in it.

**Comment by DaanHoogland** [comment] 2024-08-23 08:29
> Depending on what that says, I'm not sure if that is an acceptable solution for me, because I want to see the `access.log`, but I don't want to see the passwords in it.

in that case it is not acceptable for you and you'll need to sanitise the access log somehow.

**Comment by CodeBleu** [comment] 2024-08-24 13:25
> > Depending on what that says, I'm not sure if that is an acceptable solution for me, because I want to see the `access.log`, but I don't want to see the passwords in it.
> 
> in that case it is not acceptable for you and you'll need to sanitise the access log somehow.

But It makes more sense ( from a security perspective ) to not have the passwords/secrets hit the log in the first place.  Sanitizing it after the fact is kinda pointless.

@rohityadavcloud @weizhouapache Can you please look into removing or obfuscating password information that is making it to access.log or any log for that matter from the actual code and not a retro solution or access.log > /dev/null ?

**Comment by weizhouapache** [comment] 2024-08-26 07:55
> > > Depending on what that says, I'm not sure if that is an acceptable solution for me, because I want to see the `access.log`, but I don't want to see the passwords in it.
> > 
> > 
> > in that case it is not acceptable for you and you'll need to sanitise the access log somehow.
> 
> But It makes more sense ( from a security perspective ) to not have the passwords/secrets hit the log in the first place. Sanitizing it after the fact is kinda pointless.
> 
> @rohityadavcloud @weizhouapache Can you please look into removing or obfuscating password information that is making it to access.log or any log for that matter from the actual code and not a retro solution or access.log > /dev/null ?

it looks like all credentials in access.log are plain text.
ACS uses `NCSARequestLog` class to log request logs. I am not sure if it is possible to hide some information 
If not ,  then need to look for another solution.

at this moment, I think you have to make a decision @CodeBleu 
since the API calls are also saved in apilog.log and management-server.log, maybe you can just redirect access.log to /dev/null

**Comment by rohityadavcloud** [comment] 2024-09-04 06:27
Fixed by https://github.com/apache/cloudstack/pull/9568

**Closed by rohityadavcloud** 2024-09-04 06:27 UTC
Labels: type:bug, Severity:Major, affects:4.19.0, affects:4.18.1
