### ISSUE TITLE
Issues with 4.19 RC4 UI on EL8

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#8576] opened 2024-01-30 12:36 UTC
Found some UI quirks and issues:

1. Unable to copy the console URL by clicking the copy button in the VM instance view

2. Upon deployment of a VM the notification will not go away and found these errors in console:

<img width="1389" alt="Screenshot 2024-01-30 at 6 00 54 PM" src="https://github.com/apache/cloudstack/assets/95203/8f4ec8ed-c7da-438d-a7b1-3e020e1911dc">

<img width="1409" alt="Screenshot 2024-01-30 at 6 01 07 PM" src="https://github.com/apache/cloudstack/assets/95203/e8b91272-072f-4253-8c1d-dd0c1fafd5b6">

3. It seems some background API is always running (needs more tracing, and this could be related to (2) above)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0 RC4
~~~

**Comment by shwstppr** [comment] 2024-06-14 09:36
1. Couldn't reproduce with a Rocky8 MS and 2x Rocky8 KVM hosts. @rohityadavcloud could it be some caching issue or do I need to follow some specific steps?

https://github.com/apache/cloudstack/assets/153340/1ecbe0ce-6acb-437f-9712-918f2257b49a


2 and 3. Fixed by https://github.com/apache/cloudstack/commit/f86c62e49a58c628edc934fb86cc8f61b94fb33a

**Closed** 2024-08-09 10:33 UTC
Labels: component:UI, status:needs-reproducing
