### ISSUE TITLE
VM not migrating to alive KVM host, when KVM host down

### ISSUE THREAD

**Issue by happyalexkg** [apache/cloudstack#8326] opened 2023-12-07 04:14 UTC
ISSUE TYPE
Bug Report

##### CLOUDSTACK VERSION
CloudStack 4.18.1.0 

CONFIGURATION
Advance networking

OS / ENVIRONMENT
All on AlmaLinux 8.8.
Primary Storage: NFS
Secondary Storage: NFS
OOB - configured

VM
HA enabled:true

SUMMARY
If we triger shutdown KVM Host and when checking UI - VM showing - Running and not migrating to another KVM Host.
In Infrastructure->Host 
Host marked as Down and Resource state:Maintenance, HA state:Fenced
Ha.tag sets to : cloud
same tag having KVM Hosts
Service offering having Offer HA

STEPS TO REPRODUCE
Shutdown KVM host with running VM

EXPECTED RESULTS
VM Should migrate to alive KVM Host

ACTUAL RESULTS
It is still showing Running status and not migrate to alive KVM Host

**Comment by happyalexkg** [comment] 2023-12-07 15:20
After investigating log, i find this. When host is down in logs
2023-12-07 21:18:39,560 WARN  [o.a.c.h.HAManagerImpl] (pool-1-thread-25:null) (logid:c1f8c520) Unable to find next HA state for current HA state=[Checking] for event=[HealthCheckFailed] for host=[2].
com.cloud.utils.fsm.NoTransitionException: Unable to transition to a new state from Checking via HealthCheckFailed
        at com.cloud.utils.fsm.StateMachine2.getTransition(StateMachine2.java:108)
        at com.cloud.utils.fsm.StateMachine2.getNextState(StateMachine2.java:94)
        at org.apache.cloudstack.ha.HAManagerImpl.transitionHAState(HAManagerImpl.java:155)
        at jdk.internal.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy339.transitionHAState(Unknown Source)
        at org.apache.cloudstack.ha.task.HealthCheckTask.processResult(HealthCheckTask.java:59)
        at org.apache.cloudstack.ha.task.BaseHATask.call(BaseHATask.java:104)
        at org.apache.cloudstack.ha.task.BaseHATask.call(BaseHATask.java:36)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

may be it's cause why vm not migrating

**Comment by happyalexkg** [comment] 2023-12-11 03:35
New update
I;m noticed that if change
storage UUID and console UUID in Configuration to new Service Offering. (I created new Service Offering for SecondStorage and Console - to use NFS as disk) .. so HA will never happend :(
but if you revert it to Default - HA will work, but may be 1 or 2 times ...

**Comment by rajujith** [comment] 2023-12-11 05:13
@happyalexkg  
The VMs should be restarted on the available hosts, looks like the error is causing a trouble.

**Comment by DaanHoogland** [comment] 2024-01-19 09:54
@happyalexkg any update on this?

**Comment by happyalexkg** [comment] 2024-01-27 04:56
Hi, seems that .. i did smth wrong ... 
Ok. For example:
If i will shutdown server with command (shutdown now) or from OOB (ShutDown) - HA Will never happen
But if for example will unplug power from server - or shutdown server with long press power button - HA will happen as it expected

**Comment by DaanHoogland** [comment] 2024-01-30 08:09
so we can close this issue, @happyalexkg ?

**Comment by rohityadavcloud** [comment] 2024-04-30 12:40
Closing this as stale, please re-open if the issue isn't resolved yet or you have further input or steps for reproducing. Thanks.

**Closed by rohityadavcloud** 2024-04-30 12:40 UTC
