### ISSUE TITLE
Volume migration across pools sometimes loses volume

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#3958] opened 2020-03-10 14:13 UTC
##### ISSUE TYPE

 * Bug Report
##### CLOUDSTACK VERSION

~~~
4.11.*
4.13.0
~~~

##### SUMMARY

When migrating between volumes across primary storage, if the zone's secondary storage has made the capacity> 90%, migration will fail. It also deletes VOLUME on the source primary storage.

In this case the data is lost ...

**Comment by weizhouapache** [comment] 2020-04-23 08:54
this seems to be a blocker issue

**Comment by luhaijiao** [comment] 2020-04-23 10:45
This might be a corner case but one of our clients has been hit by this issue.  VM data was expunged.

**Comment by borisstoyanov** [comment] 2020-04-23 13:44
So just to confirm, secondary storage is almost fully occupied and you try to migrate a volume to different storage. I'll try to reproduce with the following steps: 

1. Create a volume 
2. Make sure capacity of the secondary storage cannot facilitate the volume
3. migrate to volume from primary a to primary b. 

Please comment if I got this steps wrong? @div8cn and @luhaijiao

**Comment by andrijapanicsb** [comment] 2020-04-23 19:30
closed via #4043

**Closed by andrijapanicsb** 2020-04-23 19:30 UTC
Labels: Severity:BLOCKER
