### ISSUE TITLE
Unexpected exception while executing org.apache.cloudstack.api.command.user.kubernetes.cluster.CreateKubernetesClusterCmd

### ISSUE THREAD

**Issue by sm97** [apache/cloudstack#4241] opened 2020-08-03 22:04 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
kubernetes
~~~

##### CLOUDSTACK VERSION

~~~
4.14.0
~~~

##### CONFIGURATION

Advanced networking

##### OS / ENVIRONMENT

CentOS7 on MS, XCP-NG 8.2 on hypervisors

##### SUMMARY

Cannot create kubernetes cluster from classic/primate UIs. It fails to create master/worker VMs. Other Linux/Winsows VMs are created by MS without issues on the same hypervisor.
I'm getting exception in management-server.log

##### STEPS TO REPRODUCE

~~~
0. Login under admin account
1. Enable the kubernetes service / restart MS
2. Register new kubernetes from UI:
add kubernetessupportedversion name=v1.16.3 semanticversion=1.16.3 url=http://packages.shapeblue.com.s3-eu-west-1.amazonaws.com/cks/setup-1.16.3.iso mincpunumber=2 minmemory=2048
3. Register CoreOS template from http://dl.openvm.eu/cloudstack/coreos/x86_64/coreos_production_cloudstack_image-xen.vhd.bz2
4. Wait till its ready
5. Now create a kubernetes cluster from UI with 2 nodes
~~~

##### EXPECTED RESULTS

~~~
Expected kubernetes cluster to be created successfully
~~~

##### ACTUAL RESULTS

Getting pop-up with "Command failed due to Internal Server Error".  CKS is in "Starting" state until I stop/destroy it.

~~~
2020-08-03 17:16:20,000 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (API-Job-Executor-30:ctx-fe4f9ce8 job-3345) (logid:492b8e9c) Add job-3345 into job monitoring
2020-08-03 17:16:20,016 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-30:ctx-fe4f9ce8 job-3345) (logid:bfd9221f) Executing AsyncJobVO {id:3345, userId: 9, accountId: 9, instanceType: VirtualMachine, instanceId: 3, cmd: org.apache.cloudstack.api.command.user.kubernetes.cluster.CreateKubernetesClusterCmd, cmdInfo: {"keypair":"example@example.com","description":"kuber test","httpmethod":"GET","ctxAccountId":"9","uuid":"090ac64f-a796-4cf3-ab78-885025d89ff8","cmdEventType":"KUBERNETES.CLUSTER.CREATE","kubernetesversionid":"4841cf7a-9033-462f-9bfe-f7425303daf2","size":"1","serviceofferingid":"48611534-7524-4d94-97f3-81d1d3f135c9","response":"json","ctxUserId":"9","name":"kubetest","zoneid":"1be9f1f9-e6d2-4133-942d-8582d645ca8f","networkid":"02e37ff6-48ab-4c87-888e-09f248845fd0","ctxStartEventId":"5601","id":"3","ctxDetails":"{\"interface com.cloud.offering.ServiceOffering\":\"48611534-7524-4d94-97f3-81d1d3f135c9\",\"interface com.cloud.kubernetes.version.KubernetesSupportedVersion\":\"4841cf7a-9033-462f-9bfe-f7425303daf2\",\"interface com.cloud.dc.DataCenter\":\"1be9f1f9-e6d2-4133-942d-8582d645ca8f\",\"interface com.cloud.network.Network\":\"02e37ff6-48ab-4c87-888e-09f248845fd0\"}"}, cmdVersion: 0, status: IN_PROGRESS, processStatus: 0, resultCode: 0, result: null, initMsid: 46783616671, completeMsid: null, lastUpdated: null, lastPolled: null, created: null, removed: null}
2020-08-03 17:16:20,542 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-30:ctx-fe4f9ce8 job-3345) (logid:bfd9221f) Unexpected exception while executing org.apache.cloudstack.api.command.user.kubernetes.cluster.CreateKubernetesClusterCmd
java.lang.NullPointerException
        at com.cloud.vm.UserVmManagerImpl.createVirtualMachine(UserVmManagerImpl.java:3764)
        at com.cloud.vm.UserVmManagerImpl.createAdvancedVirtualMachine(UserVmManagerImpl.java:3405)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy176.createAdvancedVirtualMachine(Unknown Source)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterStartWorker.createKubernetesMaster(KubernetesClusterStartWorker.java:203)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterStartWorker.provisionKubernetesClusterMasterVm(KubernetesClusterStartWorker.java:271)
        at com.cloud.kubernetes.cluster.actionworkers.KubernetesClusterStartWorker.startKubernetesClusterOnCreate(KubernetesClusterStartWorker.java:498)
        at com.cloud.kubernetes.cluster.KubernetesClusterManagerImpl.startKubernetesCluster(KubernetesClusterManagerImpl.java:1057)
        at org.apache.cloudstack.api.command.user.kubernetes.cluster.CreateKubernetesClusterCmd.execute(CreateKubernetesClusterCmd.java:273)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:156)
        at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:108)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:603)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:551)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2020-08-03 17:16:20,545 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-30:ctx-fe4f9ce8 job-3345) (logid:bfd9221f) Complete async job-3345, jobStatus: FAILED, resultCode: 530, result: org.apache.cloudstack.api.response.ExceptionResponse/null/{"uuidList":[],"errorcode":530}
2020-08-03 17:16:20,546 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-30:ctx-fe4f9ce8 job-3345) (logid:bfd9221f) Publish async job-3345 complete on message bus
2020-08-03 17:16:20,546 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-30:ctx-fe4f9ce8 job-3345) (logid:bfd9221f) Wake up jobs related to job-3345
2020-08-03 17:16:20,546 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-30:ctx-fe4f9ce8 job-3345) (logid:bfd9221f) Update db status for job-3345
2020-08-03 17:16:20,547 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-30:ctx-fe4f9ce8 job-3345) (logid:bfd9221f) Wake up jobs joined with job-3345 and disjoin all subjobs created from job- 3345
2020-08-03 17:16:20,549 DEBUG [o.a.c.f.j.i.AsyncJobManagerImpl] (API-Job-Executor-30:ctx-fe4f9ce8 job-3345) (logid:bfd9221f) Done executing org.apache.cloudstack.api.command.user.kubernetes.cluster.CreateKubernetesClusterCmd for job-3345
2020-08-03 17:16:20,549 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (API-Job-Executor-30:ctx-fe4f9ce8 job-3345) (logid:bfd9221f) Remove job-3345 from job monitoring
~~~

Hi @DaanHoogland 
Could you please help?

**Comment by rhtyd** [comment] 2020-08-04 05:59
cc @shwstppr

**Comment by shwstppr** [comment] 2020-08-04 11:22
@sm97 Couple of things,

- Have you tried it with a different hypervisor? XCP-NG 8.2 support is not present in 4.14 and not even in master. Did you add all OS mappings? Though at this point I'm not sure if that's all we will need for XCP-ng 8.2.
- Does the deployment of VMs outside CKS plugin work fine with CoreOS template?

**Comment by sm97** [comment] 2020-08-04 14:48
@shwstppr Thanks for prompt reply,
* No, I have no extra server to test different hypervisor. Test stand is in my plans, but not nearest one :( I know that XCP-NG 8.2 is not listed in supported ACS configurations, but it does works well for me for regular usage.
* I have tested CoreOS template outside of CKS plugin and it runs well. But CKS just fails to create new VMs. That's the root cuase of my issue.

**Comment by shwstppr** [comment] 2020-08-04 15:13
@sm97 It is failing at https://github.com/apache/cloudstack/blob/6f96b3b2b391a9b7d085f76bcafa3989d9832b4e/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L3764

Hypervisor must be coming as null here. Will check code for more. Till then, ca you please check/answer,
- While adding XCP-ng 8.2 hosts did you add guest OS mappings for XCP-ng 8.2.0 version?
- Please share cloudmonkey response for your CoreOS template
- To reproduce this, MS is CentOS 7, hosts XCP-ng 8.2, advance networking zone?

**Comment by sm97** [comment] 2020-08-04 17:53
> @sm97 It is failing at
> 
> https://github.com/apache/cloudstack/blob/6f96b3b2b391a9b7d085f76bcafa3989d9832b4e/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L3764
> 
> Hypervisor must be coming as null here. Will check code for more. Till then, ca you please check/answer,
> 
> * Please share cloudmonkey response for your CoreOS template
~~~
(local) � > list templates id=d99a8aa6-acb1-4e9b-944c-41c1b017fd9c templatefilter=all
count = 1
template:
id = d99a8aa6-acb1-4e9b-944c-41c1b017fd9c
name = Kubernetes-Service-Template-Xenserver-20200803
account = admin
bits = 0
checksum = 6d68e13f102acb3b003c4523caa28458c8bbf2f93864a0eb22e18f7f8d89f042796fa9e727b0219997c66c3f9ef96c7fb3edcb8e3c6c57914db316a5eaabcc50
created = 2020-08-03T18:58:00+0300
crossZones = True
details:
hypervisortoolsversion = xenserver61
directdownload = False
displaytext = Kubernetes-Service-Template-Xenserver-20200803
domain = ROOT
domainid = 2209783f-b5fa-11ea-8b15-000ae485569f
format = VHD
hypervisor = XenServer
isdynamicallyscalable = False
isextractable = False
isfeatured = False
ispublic = True
isready = True
ostypeid = 7c24f587-b5fa-11ea-8b15-000ae485569f
ostypename = CoreOS
passwordenabled = True
physicalsize = 4765639168
requireshvm = True
size = 4756340736
sshkeyenabled = True
status = Download Complete
tags:
templatetype = USER
zoneid = 1be9f1f9-e6d2-4133-942d-8582d645ca8f
zonename = devzone
~~~

> * While adding XCP-ng 8.2 hosts did you add guest OS mappings for XCP-ng 8.2.0 version?
> * To reproduce this, MS is CentOS 7, hosts XCP-ng 8.2, advance networking zone?
Sorry, I do not understand how I can check this?

**Comment by shwstppr** [comment] 2020-08-05 11:09
@sm97 4.14 didn't have XCP-ng 8.1+ support officially. I couldn't see 8.2 released on XCP-ng site. With guest os mappings I meant something like, https://github.com/apache/cloudstack/pull/4068/commits/b9edc955ed0a83fbb3bbc5a060cffe87d448dab0#diff-1ce878cd8ce12c2ca2fbe9c3639af33eR28-R32

I've tried to reproduce this locally but couldn't see NPE, will try to dig further.
Template seems okay. Can you please verify cluster was using same template for deployment (by checking cluster VMs).
If possible, please share management server logs for complete k8s cluster deployment.

**Comment by sm97** [comment] 2020-08-05 17:11
@shwstppr 

I changed max_guests_limit to 100 for hypervisor_version ='default' only:
https://gist.github.com/sm97/966037be4c3366cfb24c8c63822e92ec

I don't see any records for 8.1.0. But I see CoreOS records for 'default' version of XenServer. Is it Ok?
https://gist.github.com/sm97/98f4bb3e5be877aa060a2c903c7073a9

> Can you please verify cluster was using same template for deployment (by checking cluster VMs).

It seems that correct template is used. This is nfs mount from MS host:
~~~
$ cat /var/cloudstack/mnt/46783616671.5d4051c7/template/tmpl/2/241/template.properties
#
#Mon Aug 03 15:59:42 UTC 2020
uniquename=241-2-1666096b-aa90-3b43-af53-75cf72214d1a
vhd.size=4765639168
description=Kubernetes-Service-Template-Xenserver-20200803
filename=fff7ff82-37e5-38ae-a658-cc1b47bc50b9.vhd
vhd=true
size=4765639168
public=true
vhd.filename=fff7ff82-37e5-38ae-a658-cc1b47bc50b9.vhd
vhd.virtualsize=4756340736
id=241
hvm=true
virtualsize=4756340736

$ ls -l /var/cloudstack/mnt/46783616671.5d4051c7/template/tmpl/2/241/fff7ff82-37e5-38ae-a658-cc1b47bc50b9.vhd
-rw-rw-rw-. 1 root root 4765639168 Aug  3 18:59 /var/cloudstack/mnt/46783616671.5d4051c7/template/tmpl/2/241/fff7ff82-37e5-38ae-a658-cc1b47bc50b9.vhd
~~~

> If possible, please share management server logs for complete k8s cluster deployment.
Sure. This is log for unsuccessfull cluster creation named _kubetest_: https://gist.github.com/sm97/eab813ec255ee4dc07c99b46e4357737

**Comment by sm97** [comment] 2020-08-10 09:41
@shwstppr Do I need to supply additional info?

**Comment by shwstppr** [comment] 2020-08-10 09:44
@sm97 sorry got occupied with some stuff last week. WIll get back to you on this later today.

**Comment by shwstppr** [comment] 2020-08-11 21:09
@sm97 can you please try deploying k8s cluster after setting `vm.instancename.flag` to false.
Issue here doesn't seem to be with CKS itself, the code in UserVmManagerImpl.java seems to be checking the wrong variable for hypervisor type at line 3764
https://github.com/apache/cloudstack/blob/6f96b3b2b391a9b7d085f76bcafa3989d9832b4e/server/src/main/java/com/cloud/vm/UserVmManagerImpl.java#L3764
I'll add a fix for this.

**Comment by sm97** [comment] 2020-08-12 08:41
@shwstppr Setting vm.instancename.flag to false did the trick :)
Thank you!

**Closed** 2020-08-13 10:23 UTC
Labels: Severity:Major, component:kubernetes, type:bug
