### ISSUE TITLE
After update to 4.15.1 all windows vms switch to uefi and they don't boot (xcp-ng 8.2)

### ISSUE THREAD

**Issue by AlexanderKgr** [apache/cloudstack#5204] opened 2021-07-14 05:41 UTC
##### ISSUE TYPE

 * Bug Report

##### CLOUDSTACK VERSION

~~~
4.15.1
~~~

##### CONFIGURATION

CS 4.15.1
Hypervisor: xcp-ng 8.2

##### OS / ENVIRONMENT

ubuntu server 18.04

##### SUMMARY

Before update all windows vms were working perfect and they had option as bios on Xen Orchestra.
After update only windows vms are switched to  uefi which causes the vms to stuck on first screen.

##### STEPS TO REPRODUCE

~~~
Boot an existing vm, or deploy a vm from template, or deploy a vm from iso you have the same boot screen with the error.

Before update was booting without issues
This happens only in windows vms. Linux vms are working perfect
~~~
![image](https://user-images.githubusercontent.com/25532758/125569222-74017902-1a2b-43e4-b5c7-42c942d592c4.png)

##### EXPECTED RESULTS

~~~
When i shutdown the vm from hypervisor and change from uefi to bios it works.
~~~

##### ACTUAL RESULTS

~~~
Something is wrong with the command from cloudstack to xcp-ng to boot the windows vm.
~~~

**Comment by rhtyd** [comment] 2021-07-14 05:57
cc @nvazquez @sureshanaparti

**Comment by nvazquez** [comment] 2021-07-14 11:32
Hi @AlexanderKgr as I read you have upgraded from 4.15.0 to 4.15.1, but have also performed a hypervisor upgrade to XCP-ng 8.2? I'm asking as XCP-ng 8.2 has not been supported until version 4.15.1. Also, please check this: https://xcp-ng.org/docs/release-8-2.html#uefi-windows-compatibility

**Comment by AlexanderKgr** [comment] 2021-07-14 21:06
> Hi @AlexanderKgr as I read you have upgraded from 4.15.0 to 4.15.1, but have also performed a hypervisor upgrade to XCP-ng 8.2? I'm asking as XCP-ng 8.2 has not been supported until version 4.15.1. Also, please check this: https://xcp-ng.org/docs/release-8-2.html#uefi-windows-compatibility

I was working with xcp-ng 8.2 before updating to 4.15.1. Windows vms were working with bios option without issue.
After upgrading to 4.15.1 vms trying to boot in uefi mode which causes the issue.
When i manually change from uefi to bios it is booting normally (with xen orchestrao), but when i start vm from cloudstack it is starting with uefi - cannot boot.

I am wondering...xcp-ng 8.2 supports both bios and uefi and it is supported in version 4.15.1 of cloudstack.... But there is no option in cloudstack gui to select bios or uefi for the vm....

**Comment by rhtyd** [comment] 2021-07-15 07:01
@AlexanderKgr does it work for you if you deploy the VM with explicit boot type setting in the advance section of the VM deployment form:
![Screenshot from 2021-07-15 12-30-16](https://user-images.githubusercontent.com/95203/125743641-47030071-9a5f-4468-be61-64cebbd1f031.png)

We can investigate if there was any regression. Any ideas @DaanHoogland @nvazquez @sureshanaparti ?

**Comment by AlexanderKgr** [comment] 2021-07-15 08:03
> @AlexanderKgr does it work for you if you deploy the VM with explicit boot type setting in the advance section of the VM deployment form:
> ![Screenshot from 2021-07-15 12-30-16](https://user-images.githubusercontent.com/95203/125743641-47030071-9a5f-4468-be61-64cebbd1f031.png)
> 
> We can investigate if there was any regression. Any ideas @DaanHoogland @nvazquez @sureshanaparti ?

these are my options.

![image](https://user-images.githubusercontent.com/25532758/125752086-ecb20aa3-7538-4663-82a4-246406064dde.png)

**Comment by nvazquez** [comment] 2021-07-16 03:40
@davidjumani can you please check if this is a regression in the UI?

**Comment by rhtyd** [comment] 2021-07-16 05:02
It's possible UEFI support was only for kvm/vmware and not xenserver or xcp

**Comment by davidjumani** [comment] 2021-07-16 05:23
@nvazquez The UI only supports boot type / mode for VMware (non deployasis) and KVM since the beginning

**Comment by AlexanderKgr** [comment] 2021-07-16 06:36
xcp-ng 8.2 is capable for both bios and uefi

**Comment by DaanHoogland** [comment] 2021-07-16 08:51
@AlexanderKgr , I guess what @rhtyd and @davidjumani are saying is that this is a feature/enhancement request and not a bug.

marking it as such

**Comment by AlexanderKgr** [comment] 2021-07-16 10:01
> @AlexanderKgr , I guess what @rhtyd and @davidjumani are saying is that this is a feature/enhancement request and not a bug.
> 
> marking it as such

After 4.15.1 all my windows vms cannot boot. It's it considered as a bug?

**Comment by DaanHoogland** [comment] 2021-07-16 13:53
> After 4.15.1 all my windows vms cannot boot. It's it considered as a bug?

those VMs were installed and booting before an upgrade in that env? I that case it is definitely a bug.

**Comment by AlexanderKgr** [comment] 2021-07-16 14:29
> > After 4.15.1 all my windows vms cannot boot. It's it considered as a bug?
> 
> those VMs were installed and booting before an upgrade in that env? I that case it is definitely a bug.

Exactly. In 4.15.0 everything was working perfect

**Comment by DaanHoogland** [comment] 2021-07-19 07:29
Ok @AlexanderKgr , I misunderstood, so the Xen resource mistakenly considers boot type for Xen templates to be UEFI instead of BIOS, right?

is this only for Windows templates (that you know)?

**Comment by AlexanderKgr** [comment] 2021-07-19 07:31
> Ok @AlexanderKgr , I misunderstood, so the Xen resource mistakenly considers boot type for Xen templates to be UEFI instead of BIOS, right?
> 
> is this only for Windows templates (that you know)? To be clear, do you know that linux templates that are surely BIOS based do boot correctly?

yes all my linux vms are working with bios option. only windows have the issue.

**Comment by matheusfontes** [comment] 2021-07-27 00:53
Same issue here.
All vms using templates that using windows 2016 or 2019 was changed to uefi boot.
As a workaround we need to:
1 - go to instance, on details tab choose Edit and set OS to "Windows 2012 R2"
2 - go to Settings and edit setting platform and replace work qemu-upstream-uefi to qemu-upstream-compat

Do you found another solution?

**Comment by nvazquez** [comment] 2021-07-28 11:07
@matheusfontes were you running XCP-ng 8.2 on 4.15.0 as well before upgrading? If not, please specify which version

**Comment by shwstppr** [comment] 2021-07-28 11:46
@AlexanderKgr @matheusfontes did you notice any change in the OS version of the VM in XCP-ng center/CLI before and after starting (failed with uefi) the VM?

**Comment by matheusfontes** [comment] 2021-07-28 13:41
> @AlexanderKgr @matheusfontes did you notice any change in the OS version of the VM in XCP-ng center/CLI before and after starting (failed with uefi) the VM?

We were using cloudstack 4.14 with xcp 7.6. We upgraded to 4.15.1 to install new cluster of xcp 8.2
Everything works perfect but when I try to migrate a windows vm on version 2016, 2019 or windows 10 from old cluster xcp 7.6 to 8.2 cludstack create vm as uefi boot.
On citrix documentation (https://docs.citrix.com/en-us/citrix-hypervisor/vms/windows.html) there is a SO boot matrix compatibility and apparently this windows versions are using by default uefi boot.
I think cloudstack 4.15.1 need to set this old vms as BIOS boot unless the vms was specifically set to boot as uefi.
This applies to secure boot also. But secure boot now is not a problem because it isn't set enable by default.

 xe vm-param-set uuid=<UUID> HVM-boot-params:firmware=<MODE> (where MODE is BIOS OR UEFI)
 xe vm-param-set uuid=<UUID> platform:secureboot=<OPTION> (where OPTION is true or false)

**Comment by AlexanderKgr** [comment] 2021-07-29 07:28
I was using already xcp-ng 8.2 with 4.15.0. after updating 4.15.1 the issue happened. No update to xcp-ng

**Comment by AlexanderKgr** [comment] 2021-07-29 07:35
> @AlexanderKgr @matheusfontes did you notice any change in the OS version of the VM in XCP-ng center/CLI before and after starting (failed with uefi) the VM?

Nothing changed. Only boot option as uefi. When i manually change boot option to bios everything works

**Comment by matheusfontes** [comment] 2021-07-29 13:06
> > @AlexanderKgr @matheusfontes did you notice any change in the OS version of the VM in XCP-ng center/CLI before and after starting (failed with uefi) the VM?
> 
> Nothing changed. Only boot option as uefi. When i manually change boot option to bios everything works

How do you manually change boot option in cloudstack? do you do this by new interface? legacy interface? or direct by hypervisor?

**Comment by AlexanderKgr** [comment] 2021-07-29 15:27
> > > @AlexanderKgr @matheusfontes did you notice any change in the OS version of the VM in XCP-ng center/CLI before and after starting (failed with uefi) the VM?
> > 
> > 
> > Nothing changed. Only boot option as uefi. When i manually change boot option to bios everything works
> 
> How do you manually change boot option in cloudstack? do you do this by new interface? legacy interface? or direct by hypervisor?

Using advanced options of vm in xen orchestra. First force shutdown, then change the option and boot again. In cs ui there is no such option

**Comment by sureshanaparti** [comment] 2021-08-05 06:41
> > @AlexanderKgr @matheusfontes did you notice any change in the OS version of the VM in XCP-ng center/CLI before and after starting (failed with uefi) the VM?
> 
> We were using cloudstack 4.14 with xcp 7.6. We upgraded to 4.15.1 to install new cluster of xcp 8.2
> Everything works perfect but when I try to migrate a windows vm on version 2016, 2019 or windows 10 from old cluster xcp 7.6 to 8.2 cludstack create vm as uefi boot.
> On citrix documentation (https://docs.citrix.com/en-us/citrix-hypervisor/vms/windows.html) there is a SO boot matrix compatibility and apparently this windows versions are using by default uefi boot.
> I think cloudstack 4.15.1 need to set this old vms as BIOS boot unless the vms was specifically set to boot as uefi.
> This applies to secure boot also. But secure boot now is not a problem because it isn't set enable by default.
> 
> xe vm-param-set uuid= HVM-boot-params:firmware= (where MODE is BIOS OR UEFI)
> xe vm-param-set uuid= platform:secureboot= (where OPTION is true or false)

@matheusfontes @AlexanderKgr these VM level boot params are not set for the VM created in Xen/XCP from CloudStack, and so the VM would boot with the hypervisor's default firmware for the guest OS.

**Comment by davidjumani** [comment] 2021-08-09 11:01
From what I gather, xcp-ng decides the boot mode based on the VM type. Explicitly passing BIOS from CloudStack will restrict the capabilities of xcp-ng. I think it will be a good idea to add a note in the documentation mentioning that migrating VMs between xcp / xen versions can cause this issue and how to change the boot mode if it happens.
Once that's done, can look into supporting BIOS as well as UEFI boot modes from CloudStack

**Comment by nvazquez** [comment] 2021-08-16 02:44
@davidjumani looks good, can you please create a documentation PR?

**Comment by davidjumani** [comment] 2021-08-17 06:40
Added a note https://github.com/apache/cloudstack-documentation/pull/237

**Comment by tsinik-dw** [comment] 2021-08-17 08:51
I can also confirm the problem of Windows VMs switching to UEFI boot mode.
We are using XenServer 7.0 hypervisors (among others) orchestrated by ACS v4.13.1 in our production environment. We were planning to upgrade our cloud orchestrator to ACS v4.15.1 and move from XenServer 7.0 to XCP-NG 8.2.
During a PoC lab, we encountered the aforementioned problem. The upgrade of ACS to 4.15.1 went smoothly as expected but after the upgrade of XenServer 7.0 to XCP-NG 8.2 several of our test Windows VMs froze. No problems were detected on Linux VMs.
This event became a major no-go decision factor for our company to immediately stop and postpone our plans for the upgrade of our infrastructure. We are willing to help by testing any updates on the codebase in our lab environment.

**Comment by shwstppr** [comment] 2021-08-17 09:45
My proposal on this is to allow ACS to specify boot mode for the VM using UI and API (using `details`) and in the Xen orchestration classes use BIOS as default boot mode unless VM explicitly specifies it.
However, I don't think the issue is caused by ACS 4.15.1 upgrade alone. Something must have changed in the XCP-ng 8.2 LTSR itself and it is just that ACS doesn't provide any option to specify boot mode for VMs for Xen/XCP-ng as of now.

**Comment by tsinik-dw** [comment] 2021-08-17 10:43
@shwstppr I think your approach to solving the problem is a clever one! Being able to specify the boot mode within UI and API will be beneficial for cloud administrators. Most important, declaring BIOS as the default boot mode will immediately overcome this issue .
I am pretty sure, too, that the problem lies in XCP-NG 8.2 boot mode handling, and Cloudstack should come to the rescue.
As stated earlier we are willing to test any code modifications towards solving this issue.

**Comment by rhtyd** [comment] 2021-08-18 11:37
+1 let's see if we can implement boot mode property in form of VM and template `details`, that way users can specify the boot mode type without going using xe/xcp-ng manually (I however don't think it's a cloudstack bug if it's originating from XenServer/Xcp-ng's side)

**Comment by nvazquez** [comment] 2021-08-18 11:43
Thanks @shwstppr for the proposed fix, as discussed offline please work on this issue

**Comment by AlexanderKgr** [comment] 2021-08-18 11:55
> +1 let's see if we can implement boot mode property in form of VM and template `details`, that way users can specify the boot mode type without going using xe/xcp-ng manually (I however don't think it's a cloudstack bug if it's originating from XenServer/Xcp-ng's side)

i think this option was available on legacy ui.

**Comment by shwstppr** [comment] 2021-08-20 11:41
@AlexanderKgr don't think the values form UI were honored by ACS Xen orchestration code. Don't see anything there.

Hi guys, any idea how to check if a Xen/XCP-ng host has UEFI supported? cc @nvazquez @rhtyd @davidjumani

**Comment by rhtyd** [comment] 2021-08-20 11:48
@shwstppr the dom0 is linux so you check if `/sys/firmware/efi` exists
https://askubuntu.com/questions/162564/how-can-i-tell-if-my-system-was-booted-as-efi-uefi-or-bios

**Comment by tcp-dw** [comment] 2021-08-20 12:09
@shwstppr I think that the only way to do it is to check the destination hypervisor's version. Citrix Hypervisor 8.0 and XCP-ng 8.0 firstly supported UEFI as experimental feature. In Citrix Hypervisor v8.2 and XCP-ng v8.2 it is just fully supported for first time. So, I think that by checking that you have Xen v8.2 (either Citrix Hypervisor 8.2 or XCP-ng 8.2) you can be sure that UEFI is supported.

**Comment by rhtyd** [comment] 2021-08-31 10:43
Closing based on PR merged.

**Closed by rhtyd** 2021-08-31 10:43 UTC
Labels: type:bug, component:UI, component:orchestration

**Comment by shwstppr** [comment] 2021-08-31 11:01
@tcp-dw sorry forgot to reply earlier. Thanks for your suggestion. I used that approach in my fix.

**Comment by AlexanderKgr** [comment] 2021-09-17 15:12
issue is still there. old vms does not boot at all after update to 4.15.2.0
this is a windows server 16
![image](https://user-images.githubusercontent.com/25532758/133806463-c55cfaf7-6eb0-4b2a-96f2-362b354dee8f.png)


also there is no option to change the bios or uefi at old instances

**Comment by AlexanderKgr** [comment] 2021-09-17 15:44
on 1st boot vm works perfect. when i shut down it and restart it i have this error

![image](https://user-images.githubusercontent.com/25532758/133816479-6d026445-a867-472f-8af0-e5f153a888a1.png)

have changed something from settings

![image](https://user-images.githubusercontent.com/25532758/133816605-ab6f1d4d-5b5a-42ad-853c-4d21ea056e16.png)

**Comment by shwstppr** [comment] 2021-09-17 16:35
@AlexanderKgr you have `UEFI` detail set in your VM. Is that on purpose. You can stop the VM, remove the UEFI detail and then start the VM. This should make VM start in BIOS boot type.

For changing, boottype and bootmode for an existing VM. VM should be in the `Stopped` state.
- For UEFI, you can add a detail for the VM. Key=`UEFI`, Value=`SECURE` or `LEGACY`
- For BIOS, you can delete the detail with key `UEFI`

**Comment by shwstppr** [comment] 2021-09-17 16:38
@AlexanderKgr also, rebooting the VM with `rebootVirtualMachine` or with Reboot action in UI won't work. You will have to stop-start the VM.

**Comment by AlexanderKgr** [comment] 2021-09-17 16:45
> @AlexanderKgr you have `UEFI` detail set in your VM. Is that on purpose? You can stop the VM, remove the UEFI detail and then start the VM. This should make VM start in BIOS boot type.
> 
> For changing, boottype and bootmode for an existing VM. VM should be in the `Stopped` state.
> 
> * For UEFI, you can add a detail for the VM. Key=`UEFI`, Value=`SECURE` or `LEGACY`
> * For BIOS, you can delete the detail with key `UEFI`

I made a new vm from a old template with 4.15.1 and it was windows with uefi option.
Selected at advanced details uefi and legacy.
Booted without issues. Shutdown it down from cs ui.
Tried to start it after some minutes and i have the above issue 
Tried all combinations of vm settings key uefi and value secure or legacy and none worked

**Comment by AlexanderKgr** [comment] 2021-09-17 16:48
On first boot everything is working. I haven't tried to reboot it. Shut down wait some minutes and then boot. Error appears

**Comment by tsinik-dw** [comment] 2021-09-17 17:36
Cloudstack 4.15.2  is now capable to handle Xenserver/XCP-NG versions that support UEFI, but if the template was made with 4.15.1 I guess that the key/value pair related to boottype couldn't be declared to VM details. 
@AlexanderKgr Did you try to create a windows template with UEFI option using the 4.15.2?

**Comment by AlexanderKgr** [comment] 2021-09-17 17:47
> Cloudstack 4.15.2 is now capable to handle Xenserver/XCP-NG versions that support UEFI, but if the template was made with 4.15.1 I guess that the key/value pair related to boottype couldn't be declared to VM details.
> @AlexanderKgr Did you try to create a windows template with UEFI option using the 4.15.2?

No i haven't tried to make new templates. With 4.15.1 i had to create again new templates because all windows vms were booting with uefi. Now all my existent windows vms are not booting.

When i create a new vm with template from 4.15.1 it will boot without issue. But when i shut it down and booted again i have error.

**Comment by AlexanderKgr** [comment] 2021-09-18 09:30
> @AlexanderKgr you have `UEFI` detail set in your VM. Is that on purpose? You can stop the VM, remove the UEFI detail and then start the VM. This should make VM start in BIOS boot type.
> 
> For changing, boottype and bootmode for an existing VM. VM should be in the `Stopped` state.
> 
> * For UEFI, you can add a detail for the VM. Key=`UEFI`, Value=`SECURE` or `LEGACY`
> * For BIOS, you can delete the detail with key `UEFI`

for uefi and existing vm does not work. please check it.

**Comment by AlexanderKgr** [comment] 2021-09-18 09:34
this is a uefi vm working with 4.15.1.0

![image](https://user-images.githubusercontent.com/25532758/133884263-18a0e39f-4e3b-43bc-89c9-0ae764c5be29.png)
i have these options, and it does not boot.

also from logs i have this error
![image](https://user-images.githubusercontent.com/25532758/133884295-9d5167a7-4777-45fe-82b5-f866764321c9.png)

i understood that with key UEFI and value SECURE OR LEGACY bios option is disabled. but look the error

**Comment by AlexanderKgr** [comment] 2021-09-18 09:50
> Cloudstack 4.15.2 is now capable to handle Xenserver/XCP-NG versions that support UEFI, but if the template was made with 4.15.1 I guess that the key/value pair related to boottype couldn't be declared to VM details.
> @AlexanderKgr Did you try to create a windows template with UEFI option using the 4.15.2?

made today a new instance with iso from the scratch. Everything worked. 
When i shutdown the instance and tried to boot it, without even touching the settings...
Again the same issue!

![image](https://user-images.githubusercontent.com/25532758/133884716-4798186a-b5e4-4f63-a9ba-6df64eb89a2b.png)

and from the logs

![image](https://user-images.githubusercontent.com/25532758/133884723-171961aa-fd00-4207-86a7-7fdc9640d8b6.png)


seems that every instance is trying to boot with boot but has options for uefi.

this is critical i think

@rhtyd @DaanHoogland @shwstppr @nvazquez
