### ISSUE TITLE
Online docs search results takes to the superseded docs

### ISSUE THREAD

**Issue by abdelouahabb** [apache/cloudstack#4661] opened 2021-02-08 02:22 UTC
##### ISSUE TYPE

 * Documentation

##### COMPONENT NAME
~~~
Search
~~~

Online docs search results send to the deprecated docs

- Search a keyword
- After results, choose any resultat
- It will take the user to the 4.12 page showing `Warning NOTICE: THIS DOCUMENTATION SITE HAS BEEN SUPERSEDED.`

**Comment by DaanHoogland** [comment] 2021-02-08 11:16
@abdelouahabb would you know why this is and how to solve it (for other users) ?

**Comment by abdelouahabb** [comment] 2021-02-08 19:11
From the online documentation there is the `PRE 4.11 DOCUMENTATION` in the navbar, so if we take the example of the Installation Guide, there are two versions :
- the old one who sends to `http://docs.cloudstack.apache.org/projects/archived-cloudstack-installation`
- the other one (latest) stays in the latest docs `http://docs.cloudstack.apache.org/en/latest/installguide/` 

So from here, the search results send to `/project/` instead of the `/latest/` 

> @abdelouahabb would you know why this is and how to solve it (for other users) ?

**Comment by DaanHoogland** [comment] 2021-02-10 08:23
Can you add screenshots and hyperlinks to the problamatic location, please.
at http://docs.cloudstack.apache.org/en/latest/index.html there is no `PRE 4.11` :
![image](https://user-images.githubusercontent.com/2486961/107483555-291e5280-6b79-11eb-8da0-d4c89d161c3d.png)

where are you looking?

**Comment by abdelouahabb** [comment] 2021-02-10 15:38
It is already in the sidebar : 
![Sans titre](https://user-images.githubusercontent.com/2527234/107532621-60632280-6bbe-11eb-958e-9721a9e74724.png)

**Comment by DaanHoogland** [comment] 2021-02-11 13:53
@abdelouahabb sorry I can't reproduce your description:

    Search a keyword
    After results, choose any resultat
    It will take the user to the 4.12 page showing Warning NOTICE: THIS DOCUMENTATION SITE HAS BEEN SUPERSEDED.

so trying to reproduce:
- i went to the docs
- and typed network,
- choose the first entry: http://docs.cloudstack.apache.org/en/latest/adminguide/networking/basic_zone_config.html?highlight=network

can you add the precise reproduction steps of your problem please?

**Comment by abdelouahabb** [comment] 2021-02-11 17:09
> @abdelouahabb sorry I can't reproduce your description:
> 
> ```
> Search a keyword
> After results, choose any resultat
> It will take the user to the 4.12 page showing Warning NOTICE: THIS DOCUMENTATION SITE HAS BEEN SUPERSEDED.
> ```
> 
> so trying to reproduce:
> 
> * i went to the docs
> * and typed network,
> * choose the first entry: http://docs.cloudstack.apache.org/en/latest/adminguide/networking/basic_zone_config.html?highlight=network
> 
> can you add the precise reproduction steps of your problem please?

Because it gives duplicate results, one from the latest docs, the other one from the archived : 
![Sans titre](https://user-images.githubusercontent.com/2527234/107671593-4a279600-6c94-11eb-820d-a8804d107c38.png)

**Comment by DaanHoogland** [comment] 2021-02-12 09:33
yes, it does. This is intentional. What is it that you would want to see different?

**Comment by abdelouahabb** [comment] 2021-02-13 02:50
> yes, it does. This is intentional. What is it that you would want to see different?

Maybe if there is a big difference between the LTS and the normal release, it would be good to have two results, but i think having two results seems ambiguous ?

**Comment by DaanHoogland** [comment] 2021-02-13 10:27
we changed the documentation method at 4.11 that's why. It is marked as `from archived` so I don't see a problem. as 4.11 is quite old we might considder phasing it out, but on the other hand I know of companies still at 4.7 and 4.9.

**Comment by DaanHoogland** [comment] 2021-02-19 10:45
closing this @abdelouahabb . if you feel action is still needed please reopen and comment or create a new issue with specifics.

**Closed by DaanHoogland** 2021-02-19 10:45 UTC
Labels: component:documentation, status:not-a-bug
