### ISSUE TITLE
VM stopped while Migration with Maintenance Mode (KVM)

### ISSUE THREAD

**Issue by svenvogel** [apache/cloudstack#3720] opened 2019-11-26 21:56 UTC
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
Management Server
~~~

##### CLOUDSTACK VERSION

~~~
Master but maybe 4.8 upwards
~~~

##### OS / ENVIRONMENT

KVM with QEMU 2.12 and libwirtd 5.0.0, i think other other versions are also affected because not always there is the problem.

##### STEPS TO REPRODUCE

1. Set a Host in Maintenance Mode
2. VM Migration is started
2. If a VM cant migrate it will hard stopped

after @andrijapanicsb started a discussion on mailing list "VMs crashing/stopped during live migration?"  i opened this issue request to track down the problems.

@ustcweizhou gave some interesting hints to this problem.

i picked up specially your point three. i think its most interesting to track this down.

> 3. vm is stopped due to some cloudstack bugs. for example, when we put a
host to maintenance, the vm will be stopped if (1) no other host is Up in
same cluster, or (2) vm migration fails and no retry in cloudstack, or (3)
multiple vms are migrated to same destination at the same time but there is
no enough memory on the destination.
##### EXPECTED RESULTS

~~~
The expected result should be to stop the maintenance mode but dont switch off the virtual machines
~~~

##### ACTUAL RESULTS

virtual machines will be hard stopped

**Comment by svenvogel** [comment] 2019-11-26 21:57
@ustcweizhou do you have some idea how we can these part 3?

**Comment by andrijapanicsb** [comment] 2019-11-26 23:24
I believe the biggest problem I saw was VM crashing due to qemu bugs/issue (i.e. recently saw this one “qemu-kvm general protection error in libtcmalloc.so.4.4.5”) – can’t speak for other issues, since I don’t recall having them with ACS 4.5/4.8 with Ubuntu 14.04 (qemu 2.0 initially, later upgraded to 2.5)

If not mistaken, there is indeed a behavior that if there is no enough capacities in the cluster (test with a single KVM host in the cluster), the VMs will be stopped – and that is a thing to change in my opinion. Maintenance should fail and host should be in ErrorInMaintenance mode.
If you want to do maintenance of that host, put the storage into the maintenance mode and you are good to go. Even better, make an additional parameter like “forceMaintenance” which will indeed stop VMs in order to reach Maintenance mode. Othewise will simply be in ErrorInMaintenance.

I really don’ recall having issues with 5 VMs/agent threads – and I’ve been doing a lot of maintenance with couple of hunders of VMs 2-3 years ago (ACS 4.8). This one should be reproduced first.

Regards,
Andrija Panic




Andrija Panic
Cloud Architect
s: +44 20 3603 0540  |   m: +381 69 272 3690
e: andrija.panic@shapeblue.com  |  w: www.shapeblue.com  |  t:  @shapeblue
a: Amadeus House, Floral Street, London  WC2E 9DPUK


Shape Blue Ltd is a company incorporated in England &amp; Wales. ShapeBlue Services India LLP is a company incorporated in India and is operated under license from Shape Blue Ltd. Shape Blue Brasil Consultoria Ltda is a company incorporated in Brasil and is operated under license from Shape Blue Ltd. ShapeBlue SA Pty Ltd is a company registered by The Republic of South Africa and is traded under license from Shape Blue Ltd. ShapeBlue is a registered trademark.This email and any attachments to it may be confidential and are intended solely for the use of the individual to whom it is addressed. Any views or opinions expressed are solely those of the author and do not necessarily represent those of Shape Blue Ltd or related companies. If you are not the intended recipient of this email, you must neither take any action based upon its contents, nor copy or show it to anyone. Please contact the sender if you believe you have received this email in error.

Find out more about ShapeBlue and our range of CloudStack related services:
IaaS Cloud Design &amp; Build    |    CSForge - rapid IaaS deployment framework
CloudStack Consulting    |    CloudStack Software Engineering
CloudStack Infrastructure Support    |    CloudStack Bootcamp Training Courses

**Comment by weizhouapache** [comment] 2019-11-27 08:39
@svenvogel @andrijapanicsb 

I think @andrijapanicsb 's suggestion is good.  Suppose we have a new parameter forceMaintenance in the command

(1) if there are vms running on the host.  if there is no any other server in Up status and Enabled state in the cluster
(1.1) if forceMaintenance  = true, stop all vms
(1.2) if forceMaintenance  = false, throw exception, host is put to ErrorInMaintenance or Up status.

(2) if there are other servers in the cluster, all vms will be migrated away from the host
(2.1) if all vm migrations succeed, then host is put to Maintenance.
(2.2) if vm migration failed, then try to migrate vm to another host . If vm migration failed after 5 times (this can be configured)), then
(2.2.1) if  forceMaintenance  = true, schedule a task to stop/start the vm.
(2.2.2) if forceMaintenance  = false, throw exception, host is put to ErrorInMaintenance.

any suggestion ?

**Comment by svenvogel** [comment] 2019-11-27 09:49
@ustcweizhou @andrijapanicsb i think this sounds good. 

one question.
>(2.2.1) if forceMaintenance = true, schedule a task to stop/start the vm.

@ustcweizhou why we should stop and start them?

additional we encounter the following problem.

1. iso could not be mounted or storage pool on destination host, i dont know why this is a problem, manually mounting was no problem. maybe anyone has information about that?
2. if QEMU or Host Version version are different machine type will change the flags ```<type arch='x86_64' machine='pc-i440fx-rhel7.6.0'>hvm</type>```
i think this should be on view of the infrastructure admin.

**Comment by andrijapanicsb** [comment] 2019-11-27 10:42
@weizhouapache that sounds OK to me - I assume you handle capacity issues on a per VM basis.

@svenvogel 2.2.1 - if VM can't be live migrated - then stop it and start on another host to avoid permanent downtime - makes sense perfectly (if forceMaint=true)

**Comment by andrijapanicsb** [comment] 2019-11-27 10:47
CC @anuragaw since you were aware of the issue and want to review any code produced...

**Comment by andrijapanicsb** [comment] 2019-11-27 10:58
CC @rhtyd @PaulAngus @nvazquez

**Comment by weizhouapache** [comment] 2019-11-27 11:00
> @ustcweizhou @andrijapanicsb i think this sounds good.
> 
> one question.
> 
> > (2.2.1) if forceMaintenance = true, schedule a task to stop/start the vm.
> 
> @ustcweizhou why we should stop and start them?
> 
@svenvogel if vm cannot be migrated after 5 times, to continue with the maintenance (because forceMaintenance is true), we need to stop it and start it on another server. make sense ?
> additional we encounter the following problem.
> 
> 1. iso could not be mounted or storage pool on destination host, i dont know why this is a problem, manually mounting was no problem. maybe anyone has information about that?
yes, it is one root cause of failed migration.
> 2. if QEMU or Host Version version are different machine type will change the flags `<type arch='x86_64' machine='pc-i440fx-rhel7.6.0'>hvm</type>`
>    i think this should be on view of the infrastructure admin.
If hosts have different cpu model or qemu version, they should use custom cpu or cpu flags. It is not an issue in my point of view.

**Comment by andrijapanicsb** [comment] 2019-11-27 11:29
Agree on that last point of QEMU or HOST versions - not an issue and has been like that forever (nor I think would be possible since that would change what the OS sees and might crash it).

**Comment by svenvogel** [comment] 2019-11-27 15:26
@andrijapanicsb @ustcweizhou yes make sense. Agree. now i understand it.

**Comment by GabrielBrascher** [comment] 2019-11-27 16:30
@andrijapanicsb “_forceMaintenance_” is something that could help indeed; in some specific _corner cases_ it would be interesting to have such a workaround.

> I believe the biggest problem I saw was VM crashing due to qemu bugs/issue (i.e. recently saw this one “qemu-kvm general protection error in libtcmalloc.so.4.4.5”) – can’t speak for other issues, since I don’t recall having them with ACS 4.5/4.8 with Ubuntu 14.04 (qemu 2.0 initially, later upgraded to 2.5) If not mistaken, there is indeed a behavior that if there is no enough capacities in the cluster (test with a single KVM host in the cluster), the VMs will be stopped – and that is a thing to change in my opinion. Maintenance should fail and host should be in ErrorInMaintenance mode. If you want to do maintenance of that host, put the storage into the maintenance mode and you are good to go. Even better, make an additional parameter like “forceMaintenance” which will indeed stop VMs in order to reach Maintenance mode. Othewise will simply be in ErrorInMaintenance.

**Comment by anuragaw** [comment] 2019-11-27 16:49
My 2 cents - adding forceMaintenance is really going to complicate code unnecessarily. Perhaps sticking to the general theory - `If Migrations cannot be completed and host cannot be put to maintenance safely, we put the host to ErrorInMaintenance state`. At the same time we log/throw exception for informing the admins.

Admins can put the VMs off or snapshot or whatever works best - then they can manually shutdown all VMs on a host as needed and retry maintenance transition.

**Comment by weizhouapache** [comment] 2019-11-27 22:03
let's wait @anuragaw 's PR #3425 to be done.

**Comment by borisstoyanov** [comment] 2019-12-03 08:32
Guys are you sure you've seen this with QEMU 2.12 (assuming also that would be the QEMU-EV repo)?

In my testing on 3425 I cannot see this with 2.12 qemu-ev, but it's still reproducible with stock qemu-1.5.3

cc: @andrijapanicsb @svenvogel

**Comment by andrijapanicsb** [comment] 2019-12-03 08:51
With qemu 2.12 you can't get systemVMs running - so I haven't tested, to be honest (tried briefly but gave up)

I have opened an ML thread on these crashes) - user reporting crashed on different versions of ACS and qemu - so a somewhat common thing as it seems.

**Comment by andrijapanicsb** [comment] 2019-12-03 08:58
@svenvogel  - please re-explain the problem by changing the description of the issues. Stopped VMs and crashed VMs are 2 different things. Current behaviour might be to stop VMs when no free resources - but NOT crash them. And this behaviour (stopping VMs when no free resources) is @weizhouapache trying to address. Crashes are not related, afaik.

Crashes I've seen have nothing to do with that behaviour we are trying to improve (i.e. I had enough free resources in my cluster) - VMs were migrated fine, then crashed later on the new host.

i.e. let's not mix different things?

**Comment by weizhouapache** [comment] 2019-12-03 09:16
@svenvogel @andrijapanicsb 
```
vm is stopped due to some cloudstack bugs. for example, when we put a
host to maintenance, the vm will be stopped if (1) no other host is Up in
same cluster, or (2) vm migration fails and no retry in cloudstack, or (3)
multiple vms are migrated to same destination at the same time but there is
no enough memory on the destination.
```
(1) has been tracked in #3707 
(2) is changed in #3425 but not done.
(3) is fixed by #3727 and #3728. which caused crashed vm in host maintenance on our platforms.

**Comment by rhtyd** [comment] 2020-03-03 07:40
Is this fixed/addressed @svenvogel @weizhouapache @andrijapanicsb ?

**Comment by svenvogel** [comment] 2020-03-06 13:09
@rhtyd we will test this in the next week. i lost this in our track.

**Comment by svenvogel** [comment] 2020-03-06 13:11
@andrijapanicsb changed. yes it stopped the VM thats right.

**Comment by DaanHoogland** [comment] 2020-12-11 11:37
this is on hold it seems, any volunteers to specify this and #3707 to sum up the desired outcome ? it seems to me there are a lot of ideas here but no consensus on functionality, @svenvogel @andrijapanicsb @weizhouapache @rhtyd @borisstoyanov @GabrielBrascher @anuragaw .

**Comment by GabrielBrascher** [comment] 2020-12-15 00:33
My 2 cents on this one would be to add a force maintenance parameter or global settings (I would prefer a force parameter though).

Here follows a draft of a proposal for this issue:
1. call maintenance of a host with _force_ parameter
2. normal flow where CloudStack tries to migrate all VMs
3. if not possible to migrate a VM, stop it
4. place the host in maintenance state once all VMs are migrated or stopped

PR #4212 is focused on migrating or stopping local storage VMs of a host put in maintenance. However, it holds some similarities with this issue.

**Comment by rohityadavcloud** [comment] 2022-06-30 06:45
is this still an issue @GabrielBrascher @svenvogel and others?

**Comment by GabrielBrascher** [comment] 2022-06-30 11:06
@rohityadavcloud @svenvogel should be fixed by PR https://github.com/apache/cloudstack/pull/4212 which gives autonomy for admins to choose a strategy for such VMs, via global settings name `host.maintenance.local.storage.strategy`.

With that PR Admins can choose (wisely and knowing eventual risks on each option) between?
1. error in maintenance when there are local storage VMs
2. stop local storage VMs and put in maintenance
3. or. migrate local storage VMs and put it in maintenance

Might require some upgrades on CloudStack documentation thought.

**Comment by rohityadavcloud** [comment] 2022-08-17 12:13
As per comment on PR, it appears fixed by https://github.com/apache/cloudstack/pull/4534 and https://github.com/apache/cloudstack/pull/4212 is also merged
Pl re-open if we got that wrong, thanks.

**Closed by rohityadavcloud** 2022-08-17 12:13 UTC
Labels: type:bug, component:kvm, status:needs-functional-definition
