### ISSUE TITLE
Virtual Router VM fails to boot with kernel panic when overprovisioinig is > 1

### ISSUE THREAD

**Issue by MilanHofmann** [apache/cloudstack#7430] opened 2023-04-13 08:24 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Virtual Router VM / service offering / shared storage
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

Advanced Zone with NFS primary Storage.

##### OS / ENVIRONMENT

Ubuntu Focal Fossa

##### SUMMARY

When overprovisioning factors are > 1, the virtual router vm for a new zone is not able to boot and ends up in a kernel panic while trying to mount the root volume.
By default a local storage service offering is picked for the router.
If an id of a service offering that uses shared storage is specified in the global settings under router.service.offering it is ignored.
Somehow the Volumes attached to the working system and router vms (when overprovisioning == 1) are not accessible via the UI and lead to 404.
Taking a look at the db entry they look like:

                        id: 26
                account_id: 1
                 domain_id: 1
                   pool_id: 4
              last_pool_id: NULL
               instance_id: 21
                 device_id: 0
                      name: ROOT-21
                      uuid: 29537b97-e6d1-484b-9e06-92cd905ead8e
                      size: 5242880000
                    folder: NULL
                      path: 29537b97-e6d1-484b-9e06-92cd905ead8e
                    pod_id: NULL
            data_center_id: 4
                iscsi_name: NULL
                   host_ip: NULL
               volume_type: ROOT
                 pool_type: NULL
          disk_offering_id: 12
               template_id: 3
               first_snapshot_backup_uuid: NULL
               recreatable: 1
                   created: 2023-04-10 11:51:38
                  attached: NULL
                   updated: 2023-04-10 11:51:40
                   removed: NULL
                     state: Ready
                chain_info: NULL
              update_count: 2
                 disk_type: NULL
    vm_snapshot_chain_size: NULL
                    iso_id: NULL
            display_volume: 1
                    format: QCOW2
                  min_iops: NULL
                  max_iops: NULL
             hv_ss_reserve: NULL
         provisioning_type: thin
             external_uuid: NULL
             passphrase_id: NULL
            encrypt_format: NULL

The disk offering for the volume is type "shared".

In addition there is a second primary storage that was setup by accident, always comes up again (after disabling), but has no visible resources attached to it.

##### STEPS TO REPRODUCE

Set overprovisioning to > 1 and create a new VPC.

~~~

~~~

##### EXPECTED RESULTS

~~~
The virtual router vm should use the shared storage offering and boot.
~~~

##### ACTUAL RESULTS

~~~
It ends up ina kernel panic mounting the root volume.
~~~

**Comment by MilanHofmann** [comment] 2023-04-21 13:45
I have no re-setup everything from scratch, the system offerings are beeing picked up.
But still the routers run out of memory when booting if overprovisioning > 1.
Is there anybody that can help me with this issue?

**Comment by rajujith** [comment] 2023-05-05 04:10
@MilanHofmann  what is the hypervisor type and version you are using? please review this thread https://lists.apache.org/thread/77rgh7qqk0ro90mhgbw0kr6jmsc785wk

**Comment by MilanHofmann** [comment] 2023-05-05 06:59
@rajujith Thank you very much for the hint!
I am using KVM with Cloudstack 4.18, so this thread makes sense.
But how can I enable ballooning via cloudstack?
As far as I understand memory ballooning is a per-guest setting, so I'd have to make cloudstack make use of these options anytime a new vm is created, right?

**Comment by weizhouapache** [comment] 2023-05-05 07:40
@MilanHofmann 
what's the memory overprovision factor in global setting and cluster setting ?
it is suggested to set to 1 on kvm environments.

if you want to enable VM dynamic scaling , please refer to https://www.shapeblue.com/granular-control-of-dynamic-scaling-of-vms-cpu-ram/

**Comment by rajujith** [comment] 2023-05-05 08:10
@MilanHofmann  you can go ahead with Wei's suggestion without using memory overcommit. I would like the below to understand what is causing the issue:
 1) OS version for KVM 
2)memory overcommit value at the cluster or VM level. 
3) Output of  ‘virsh dumpxml vm-name’ on KVM

**Comment by rajujith** [comment] 2023-06-21 06:15
I would propose this solution: 
Retain the 'memory' to the offering RAM value, set the currentMemory to offering RAM value/ memory over provisioning value. Also set the autodeflate='on' for the balloon driver. With this the guest will get the RAM specified in the offering. 

```
<memory unit='KiB'>1048576</memory>
  <currentMemory unit='KiB'>524288</currentMemory>
```
```

  <memballoon model='virtio' autodeflate='on'>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </memballoon>

```

**Comment by GutoVeronezi** [comment] 2023-07-20 12:15
Hello @MilanHofmann,

Could you provide the value of configurations `vm.min.memory.equals.memory.divided.by.mem.overprovisioning.factor` and `vm.min.cpu.speed.equals.cpu.speed.divided.by.cpu.overprovisioning.factor` at cluster level?

Best regards

**Comment by DaanHoogland** [comment] 2023-07-31 06:59
fixed in #7663

**Closed by DaanHoogland** 2023-07-31 06:59 UTC
Labels: component:kvm, Severity:Critical, component:orchestration

**Comment by DaanHoogland** [comment] 2023-08-02 12:25
@MilanHofmann @rajujith , this solution leeds to regressions for centos7 based zones. What version of KVM are you using? we need to re-implement this in a version specific way.

**Comment by rohityadavcloud** [comment] 2023-08-03 03:59
Hi, sorry to join the party late. I found this is a feature and not a bug, probably needs better documentation cc @weizhouapache @DaanHoogland @rajujith (the fix may be still valid if we don't want to revert).

By default, the VM memory balloon feature is enabled for KVM, https://github.com/apache/cloudstack/blob/main/agent/conf/agent.properties#L220 so if the memory overcommit is > 1, CloudStack assumes the guest have necessary drives and starts the VMs with the minimum memory (which is allocated memory divided by the memory overprovisioning factor) and assumes the guest can dynamically request for more memory. 

To have the VMs start with the allocated memory by default, for example if ksm or memory compression etc options are enabled on the host; then simply add the setting `vm.memballoon.disable=true` in agent.properties on kvm hosts when memory overprovisioning is > 1 and VMs will start with allocated memory (not cause panic) and you've overcommitted memory.

**Comment by rohityadavcloud** [comment] 2023-08-03 04:34
@MilanHofmann with the issue fixed, if you'd prefer to not use the memory balloon feature you can disable it for KVM hosts in your cluster where memory overprovisioning is > 1, and set the `vm.memballoon.disable` to `true` in agent.properties. This will force CloudStack KVM agent to not start VMs with the minimum memory, instead use the max memory.
