### ISSUE TITLE
Can't create Isolated network after update

### ISSUE THREAD

**Issue by UAnton** [apache/cloudstack#9350] opened 2024-07-08 08:40 UTC
Duplicate

**Comment by DaanHoogland** [comment] 2024-07-08 11:06
@UAnton , what is this a duplicate off?
can we close it?

**Comment by UAnton** [comment] 2024-07-09 07:12
@DaanHoogland https://github.com/apache/cloudstack/issues/9193
I was getting this problem. Reinstalling my test env resolves the problem but this is not a good way.

**Comment by DaanHoogland** [comment] 2024-07-12 09:58
@UAnton , I have yet again tried this (updating from 4.18 to 4.19) and see no issues :(

**Comment by UAnton** [comment] 2024-07-12 10:32
@DaanHoogland OK, you can close the issue. If I get this problem again - I will open a new ticket.
Thanks!

**Closed** 2024-07-12 10:33 UTC
Labels: status:needs-reproducing

**Comment by tdtmusic2** [comment] 2024-07-25 09:53
Hello. Same issue here, ACS v4.19.1.0, clean deployment. Zone is created, everything looks good, no network offerings in dropdown when trying to create a guest network.

**Comment by DaanHoogland** [comment] 2024-07-25 12:40
can you investigate further @tdtmusic2 , this is some intermittent issue that seems to occur only sometimes, so any extra info is welcome.

**Comment by tdtmusic2** [comment] 2024-07-25 12:55
> can you investigate further @tdtmusic2 , this is some intermittent issue that seems to occur only sometimes, so any extra info is welcome.

Would love to but I'm not really sure what to look for, the behavior is exactly like it was described on issue #9193 . All I did was add a zone then I wanted to create a guest network. The dropdown is empty, but before adding the zone it was ok. None of the offerings have zone ids and if I set the availability to the actual zone still doesn't show the offering in the dropdown. Setting it to All zones does nothing, the Zone column remains empty.
This is really weird, up until yesterday I did 5 or 6 installations and never had this issue. All on the same vms, same hosts, storage, etc., so nothing different between installations.

**Comment by tdtmusic2** [comment] 2024-07-25 13:22
Update: I checked another 2 installations of ACS, both on 4.19.0.1, one with Basic zone, one with Advanced. On the Basic zone, if I try to add an L2 network I can see the templates. Nothing for Shared network. On the Advanced zone I see only a few offerings, for each network type.
![Screenshot 2024-07-25 162008](https://github.com/user-attachments/assets/bb92508b-237b-4483-8977-4f79e08c3e2d)
![Screenshot 2024-07-25 161956](https://github.com/user-attachments/assets/3dff2c0f-5995-463d-ae6a-d02d472f9dfe)
![Screenshot 2024-07-25 161944](https://github.com/user-attachments/assets/f7a24168-9c58-4fd9-80e2-b5241b460b08)

**Comment by tdtmusic2** [comment] 2024-07-25 13:36
> ok @tdtmusic2, that seems like normal behaviour , except for the shared networks in basic-zone.

I thought it might be relevant, I find it weird that in the Advanced zone (1st screenshot) there are only a few offerings in the dropdown. However, in my 4.19.1 installation there are none. Also, I forgot to mention, if I create a new offering results in the same behavior, it shows up on the Network Offerings list but not in the dropdown when trying to add a new guest network. So it's not specific to default, built-in, offerings.

**Comment by DaanHoogland** [comment] 2024-07-25 14:21
@tdtmusic2 , also for custom offering is goes that they are only shown if they are applicablefor the type of network you are requesting. So also for this case we need more data.

Stands that (I think) you should see some offering for shared networks in basic zones.

**Comment by weizhouapache** [comment] 2024-07-29 07:17
Creating shared networks should not be allowed in Basic zone, the tab can be hidden

**Comment by tdtmusic2** [comment] 2024-07-29 13:06
I think this can be reproduced, at least it works in my case. It seems that IF you add a zone with only the management traffic label set up, it's all good (and this was actually the case in my tests before, I only had the bridge label set up on the management traffic type, that's why I never had the offerings issue). 
If you add the bridge label to Guests and Public traffic, you get the offerings issue after creating the zone. Also, if you want to split the traffic types for example, and select only Management and Storage traffic on one physical interface and add another one for guests and public, after the zone creation you have the isssue again. And I think the same happens if you delete the physical network from the zone and just recreate it.
