### ISSUE TITLE
Management network is on a VLAN error when using XenServer/XCP-NG.

### ISSUE THREAD

**Issue by selaing** [apache/cloudstack#6641] opened 2022-08-15 17:28 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Hypervisor (XenServer/XCP-NG) support.
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0
4.17.0.1
main branch
~~~

##### CONFIGURATION

Advanced networking configuration with VLANs used on the management network.

##### OS / ENVIRONMENT

XCP-NG version 8.2 (latest)

##### SUMMARY

When attempting to add an XCP-NG host where the management network is configured to be on a VLAN the host will fail to add with the log message "Unsupported configuration.  Management network is on a VLAN."

##### STEPS TO REPRODUCE

~~~
- Configure a zone in CloudStack with the management network on a VLAN.
- Configure an XCP-NG host with its management network on the same VLAN.
- In the CloudStack UI add a host using Infrastructure -> Hosts -> Add Host.
- Adding the host will fail with the log message "Unsupported configuration.  Management network is on a VLAN."
~~~

##### EXPECTED RESULTS

~~~
The expected behaviour is that the host should be successfully added since both XenServer/XCP-NG and CloudStack do support having the management network on a VLAN.
~~~

##### ACTUAL RESULTS

The actual result is that adding the host fails with the log message "Unsupported configuration.  Management network is on a VLAN." This log message is generated from the check in lines 108-119 in https://github.com/apache/cloudstack/blob/main/plugins/hypervisors/xenserver/src/main/java/com/cloud/hypervisor/xenserver/resource/wrapper/xenbase/CitrixSetupCommandWrapper.java 
Log output is contained below.

~~~
com.cloud.utils.exception.CloudRuntimeException: Unsupported configuration.  Management network is on a VLAN.  host=fcffd52b-011e-4d13-bb47-d25c5717b37a; pif=0a4c9e7b-2553-eeef-b7c0-3a838d6d5e5d; vlan=417
	at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.getManagementNetwork(CitrixResourceBase.java:2790)
	at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.getHostInfo(CitrixResourceBase.java:2224)
	at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.initialize(CitrixResourceBase.java:3675)
	at com.cloud.hypervisor.xenserver.resource.XenServer56Resource.initialize(XenServer56Resource.java:130)
	at org.apache.cloudstack.hypervisor.xenserver.XenServerResourceNewBase.initialize(XenServerResourceNewBase.java:69)
	at com.cloud.resource.ResourceManagerImpl.createHostAndAgent(ResourceManagerImpl.java:2357)
	at com.cloud.resource.ResourceManagerImpl.discoverHostsFull(ResourceManagerImpl.java:861)
	at com.cloud.resource.ResourceManagerImpl.discoverHosts(ResourceManagerImpl.java:644)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy196.discoverHosts(Unknown Source)
	at org.apache.cloudstack.api.command.admin.host.AddHostCmd.execute(AddHostCmd.java:142)
	at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:163)
	at com.cloud.api.ApiServer.queueCommand(ApiServer.java:776)
	at com.cloud.api.ApiServer.handleRequest(ApiServer.java:600)
	at com.cloud.api.ApiServlet.processRequestInContext(ApiServlet.java:327)
	at com.cloud.api.ApiServlet$1.run(ApiServlet.java:145)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at com.cloud.api.ApiServlet.processRequest(ApiServlet.java:142)
	at com.cloud.api.ApiServlet.doPost(ApiServlet.java:101)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
~~~

**Comment by shwstppr** [comment] 2022-08-16 12:16
I checked the code and it seems the behaviour has been the same for a long with ACS not allowing host to connect when they are on VLAN management network. I feel this is an improvement request and not sure if we will be able to have it in 4.17.1.
What should be the correct check here? Checking if VLAN is same as the VLAN of ACS public network or the pod range? @DaanHoogland @rohityadavcloud

**Comment by DaanHoogland** [comment] 2022-08-17 16:29
I agree this is not a bug, @shwstppr . There is an explicit guard against using vlan for managemenet network. It might be that we can remove the guard after extensive testing, but it was intented. I have no idea why the guard was initially implemented, so I would not know what to look out for. I think we can considder if anyone wants to submit a PR that removes it.

**Comment by shwstppr** [comment] 2022-08-18 06:38
Moving this to next milestone for now

**Comment by DaanHoogland** [comment] 2022-12-30 12:23
@selaing are you still interested in this/creating a PR?

**Comment by selaing** [comment] 2023-01-03 22:56
Unfortunately I don't have the time to create a PR for this.

**Comment by weizhouapache** [comment] 2023-01-04 13:37
this is same as #4286

**Comment by DaanHoogland** [comment] 2023-01-04 13:59
good catch. closing as doublure

**Closed by DaanHoogland** 2023-01-04 13:59 UTC
Labels: type:improvement

**Comment by weizhouapache** [comment] 2023-01-04 14:03
> good catch. closing as doublure

@DaanHoogland unfortunately #4286 is not fixed yet
