### ISSUE TITLE
Compute resources are not automatically released after vm stop

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#3482] opened 2019-07-10 13:50 UTC
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
Management Server
Usage Server
~~~

##### CLOUDSTACK VERSION

~~~
4.9/4.11/4.11.2/4.11.3
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The computing resource cannot be released after the VM is stopped. You must execute delete to release the computing resource.

After the VM is stopped, it does not consume any computing resources. We should not think that it still occupies computing resource quota (aws azure google cloud is designed in this way).

##### STEPS TO REPRODUCE

~~~
1. Create an account and update the following resource quotas
    Instance Limits=5
    CPU limits=8
    Memory limits (MiB)=32G
2. Create and run two VMs under the new account:
    Name=vm1,vcpu=4,ram=16
    Name=vm2,vcpu-4,ram=16

3. Stoped vm1, vm2

4. Create a third VM under account (test1)
    Name=vm3,vcpu=4,ram=16 
~~~

##### EXPECTED RESULTS

~~~
vm3 can be successfully created and run
~~~

##### ACTUAL RESULTS

~~~
Error:
Maximum amount of resources of Type = 'cpu' for Account Name = test1 in Domain Id = 4 is exceeded: Account Resource Limit = 8, Current Account Resource Amount = 8 Requested Resource Amount = 4.
~~~

**Comment by rhtyd** [comment] 2019-07-10 18:03
This is by design, perhaps a global settings can be introduced for this use case.

**Comment by ustcweizhou** [comment] 2019-07-12 09:44
@rhtyd @div8cn 
we have some changes for this in 4.7.1
If nobody objects, I will work on the porting to 4.13.

**Comment by DaanHoogland** [comment] 2020-01-29 15:04
@weizhouapache @rhtyd did this make it in already? (can we close?)

**Comment by rhtyd** [comment] 2020-08-12 08:51
@weizhouapache @ustcweizhou can you check and advise if we can close this? Thanks.

**Comment by DaanHoogland** [comment] 2021-01-04 10:11
@weizhouapache any update for us?

**Comment by weizhouapache** [comment] 2021-01-04 10:27
@DaanHoogland @rhtyd this should be fixed by #3760

**Comment by DaanHoogland** [comment] 2021-01-04 10:33
@div8cn can you check in 4.14?

**Comment by rhtyd** [comment] 2021-01-19 14:54
Ping @div8cn can you test 4.14.0.0? Per @weizhouapache 's comment the issue has been fixed.

**Comment by div8cn** [comment] 2021-01-19 15:00
ok, I will test on 4.14 AND 4.15 this week and provide test conclusions

**Comment by div8cn** [comment] 2021-01-20 03:05
4.14.0.0 global configuration resource.count.running.vms.only It can control whether VM in stopped status performs consumption statistics



The problem has been solved

**Closed** 2021-01-20 03:06 UTC
Labels: type:cleanup, type:improvement
