### ISSUE TITLE
Wrong API call from the UI on the 'Network >  VNF appliances' page

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack#8979] opened 2024-04-25 14:59 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The 'VNF appliances' view generates an error on loading.

##### STEPS TO REPRODUCE

~~~
Go to Network >  VNF appliances. You can also click 'Refresh' to see the error again.
~~~

##### EXPECTED RESULTS

~~~
No error message.
~~~

##### ACTUAL RESULTS

~~~
The following error is displayed:
"Unable to execute API command listtemplates due to missing parameter templatefilter"

Here is the actual API call sent by the UI:
listall=true&details=servoff,tmpl,nics&isvnf=true&page=1&pagesize=20&command=listVnfTemplates&response=json
~~~
![image](https://github.com/apache/cloudstack/assets/12384665/f61f0c1e-7da5-4440-868d-a51e9aeb12f8)

**Comment by weizhouapache** [comment] 2024-04-25 15:08
@vladimirpetrov 
thanks for reporting
this seems to be caused by he change in my pr #8668
let me fix it

**Comment by vishesh92** [comment] 2024-06-19 14:20
Fixed in https://github.com/apache/cloudstack/pull/8994

**Closed by vishesh92** 2024-06-19 14:20 UTC
Labels: component:UI
