### ISSUE TITLE
ACS 4.19.1 | Full Network List visible for Domain Admin

### ISSUE THREAD

**Issue by midhunpjos** [apache/cloudstack#9456] opened 2024-07-26 11:06 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1
~~~

##### CONFIGURATION

~~~
4.19.1
Advanced Zone / Without Security Groups
Hypervisor : XCP-ng
~~~

##### OS / ENVIRONMENT

~~~
Ubuntu 20.04
~~~

##### STEPS TO REPRODUCE

~~~
Login To Cloudstack UI using a Domain Admin Credentials
Domain Admin is able to see Networks that belongs to other Domains 
~~~

##### EXPECTED RESULTS

~~~
Domain Admin Should See Only Networks Belonging to His Domain
~~~

##### ACTUAL RESULTS

~~~
Domain Admin is able to see Networks that belongs to other Domains. 

Note: He cannot perform any account actions on other domain accounts
![Untitled](https://github.com/user-attachments/assets/fcd97b35-ebfb-4c6e-9ad4-88f994e15c33)

~~~

**Comment by nvazquez** [comment] 2024-07-26 13:31
Thanks @midhunpjos - I tested 4.19.0 as well and couldn't reproduce the issue. I can reproduce it on 4.19.1

**Comment by nvazquez** [comment] 2024-07-26 13:40
Confirmed on 4.19.1:
- Domain admins from a domain can see other domain networks
- Users cannot see other domain networks

**Comment by winterhazel** [comment] 2024-07-27 04:40
Adding to @nvazquez's comment that this is not exclusive to domain admins: normal users are able to see networks that belong to other domains by using the "shared" filter.

**Comment by rohityadavcloud** [comment] 2024-07-27 10:09
@nvazquez @winterhazel thanks for the investigation and comments; Fair to say we’ve established it only affects 4.19.1, while we work on this - suggested workaround is for users to downgrade or not upgrade to 4.19.1.0. 

cc @JoaoJandre @weizhouapache @shwstppr @sureshanaparti @harikrishna-patnala @DaanHoogland  @borisstoyanov and others

**Comment by winterhazel** [comment] 2024-07-29 00:27
Hey everyone, I sent a PR to fix this issue in https://github.com/apache/cloudstack/pull/9461, could you guys take a look and tell me what you think?

**Comment by rohityadavcloud** [comment] 2024-08-22 06:26
Closing as the issue was reverted, confirmed by @shwstppr

**Closed by rohityadavcloud** 2024-08-22 06:26 UTC
Labels: Severity:BLOCKER
