### ISSUE TITLE
VMware cluster: renaming root volume after disk migration in vShpere

### ISSUE THREAD

**Issue by top-secrett** [apache/cloudstack#7536] opened 2023-05-16 07:42 UTC
##### ISSUE TYPE

 * Bug Report

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### CONFIGURATION

~~~
advanced zone
vmware 6.7 cluster
~~~

##### OS / ENVIRONMENT

~~~
OracleLinux 8
~~~

##### SUMMARY

After disk migration via CS or vShpere ROOT disk is renamed according to the VM name. Fox example, ROOT-3163_2.vmdk to i-155-3163-VM_2.vmdk
And VM cannot start after shutdown.
When a fully automated DRS is enabled in vShpere this becomes a more seriuos problem
![image](https://github.com/apache/cloudstack/assets/92435079/498587f9-f685-4fc7-8336-cdbc46ea0802)

##### STEPS TO REPRODUCE

1. Create VM in CS on VMware cluster
2. Migrate volune to another stotage via CS
3. Stop the VM and start it.
4. Get error
5. Check disk name in VMware

**Comment by kiranchavala** [comment] 2023-05-22 09:13
@top-secrett  I am not able to reproduce the issue, after following the steps

**1. Create a vm in cs on VMware cluster which has 2 primary storages** 

<img width="1171" alt="Screenshot 2023-05-22 at 2 28 04 PM" src="https://github.com/apache/cloudstack/assets/1401014/12fd90ed-f2d6-48b3-a9ee-48f85e2ed667">

```
MariaDB [cloud]> select pool_id,path,chain_info from volumes where id=5 \G;
*************************** 1. row ***************************
   pool_id: 2
      path: i-2-5-VM
chain_info: {"diskDeviceBusName":"ide0:1","diskChain":["[ae50040e92af3351a0e0532a260d7599] i-2-5-VM/ROOT-5.vmdk","[ae50040e92af3351a0e0532a260d7599] ec1d3f72d8633bc3975d34abac67ba8c/ec1d3f72d8633bc3975d34abac67ba8c.vmdk"]}
```
**2. Stop the vm  from CS**

**3. Migrate the vm's root disk from CS to another primary storage**

The root disk name is updated from ROOT-5 to i-2-5-vmdk

<img width="1169" alt="Screenshot 2023-05-22 at 2 32 50 PM" src="https://github.com/apache/cloudstack/assets/1401014/936ef823-81ea-414a-b593-88b571fe37fb">



4. Start the vm - No error observerd 

The database is also synced to the correct entries 

MariaDB [cloud]> select pool_id,path,chain_info from volumes where id=5 \G;
*************************** 1. row ***************************
   pool_id: 2
      path: i-2-5-VM
chain_info: {"diskDeviceBusName":"ide0:1","diskChain":["[f4476e352c6c39148d964f6d894257d3] i-2-5-VM/i-2-5-VM.vmdk"]}

**Comment by top-secrett** [comment] 2023-05-22 10:21
@kiranchavala sorry, I missed an important step №2. Error occurs after volume live migration
STEPS TO REPRODUCE
1. Create VM in CS on VMware cluster
2. Migrate volume to another stotage via CS
3. Stop the VM and start it.
4. Get error
5. Check disk name in VMware

**Comment by top-secrett** [comment] 2023-05-23 14:50
@kiranchavala we checked all steps agaian and after CS restarting almosts all problems were resolved by themselves. Strange things...
But we could find only one. When you create VM from ISO its volume has path like "7e3ad920079a4bcab94e4a79c4a87c15". Then volume is migrated via vShpere (automated DRS) within storage cluster and VM cannot start after shutdown.
~~~
"2023-05-23 17:42:06,569 INFO  [c.c.h.v.r.VmwareResource] (DirectAgent-249:ctx-7c1e4808 esx-sr184-u2324.aisrp.local, job-38749/job-38751, cmd: StartCommand) (logid:bae69e4e) Found existing disk from from chain device bus information: scsi0:0
2023-05-23 17:42:06,569 INFO  [c.c.h.v.r.VmwareResource] (DirectAgent-249:ctx-7c1e4808 esx-sr184-u2324.aisrp.local, job-38749/job-38751, cmd: StartCommand) (logid:bae69e4e) Chose disk controller for vol ROOT -> lsilogic, based on root disk controller settings at global configuration setting.
2023-05-23 17:42:06,574 INFO  [c.c.h.v.r.VmwareResource] (DirectAgent-249:ctx-7c1e4808 esx-sr184-u2324.aisrp.local, job-38749/job-38751, cmd: StartCommand) (logid:bae69e4e) Detected disk-chain top file change on volume: 3416 7e3ad920079a4bcab94e4a79c4a87c15 -> i-60-3262-VM
2023-05-23 17:42:06,578 INFO  [c.c.h.v.r.VmwareResource] (DirectAgent-249:ctx-7c1e4808 esx-sr184-u2324.aisrp.local, job-38749/job-38751, cmd: StartCommand) (logid:bae69e4e) Found existing disk info from volume path: i-60-3262-VM
2023-05-23 17:42:06,588 INFO  [c.c.h.v.r.VmwareResource] (DirectAgent-249:ctx-7c1e4808 esx-sr184-u2324.aisrp.local, job-38749/job-38751, cmd: StartCommand) (logid:bae69e4e) Detected datastore uuid change on volume: 3416 26a5b88a-6956-3439-aebc-6baac89549ba -> aeb66841-98b1-3dff-bb31-c1035474ee95
2023-05-23 17:42:06,598 DEBUG [c.c.u.LogUtils] (DirectAgent-249:ctx-7c1e4808 esx-sr184-u2324.aisrp.local, job-38749/job-38751, cmd: StartCommand) (logid:bae69e4e) Failed to log object [VirtualMachineMO] using GSON.
2023-05-23 17:42:06,598 DEBUG [c.c.h.v.u.VmwareHelper] (DirectAgent-249:ctx-7c1e4808 esx-sr184-u2324.aisrp.local, job-38749/job-38751, cmd: StartCommand) (logid:bae69e4e) Trying to prepare disk device to virtual machine [error to decode], using the following details: Virtual device [], ManagedObjectReference [{"value":"datastore-344","type":"Datastore"}], ControllerKey [1000], VMDK path chain [["[ds-sr183_185_os5500-nlsas-1] i-60-3262-VM/i-60-3262-VM.vmdk"]], DeviceNumber [0], ContextNumber [2] and max IOPS [0].
2023-05-23 17:42:06,603 DEBUG [c.c.u.LogUtils] (DirectAgent-249:ctx-7c1e4808 esx-sr184-u2324.aisrp.local, job-38749/job-38751, cmd: StartCommand) (logid:bae69e4e) Failed to log object [VirtualMachineMO] using GSON.
2023-05-23 17:42:06,603 DEBUG [c.c.h.v.u.VmwareHelper] (DirectAgent-249:ctx-7c1e4808 esx-sr184-u2324.aisrp.local, job-38749/job-38751, cmd: StartCommand) (logid:bae69e4e) Prepared disk device, to attach to virtual machine [error to decode], has the following details: Virtual device [], ManagedObjectReference [{"value":"datastore-344","type":"Datastore"}], ControllerKey [1000], VMDK path chain [["[ds-sr183_185_os5500-nlsas-1] i-60-3262-VM/i-60-3262-VM.vmdk"]], DeviceNumber [0], ContextNumber [2] and max IOPS [0], is: [{"capacityInKB":0,"key":-2,"backing":{"diskMode":"persistent","fileName":"[ds-sr183_185_os5500-nlsas-1] i-60-3262-VM/i-60-3262-VM.vmdk","datastore":{"value":"datastore-344","type":"Datastore"}},"connectable":{"startConnected":true,"allowGuestControl":false,"connected":true},"controllerKey":1000,"unitNumber":0}].
"
~~~
![image](https://github.com/apache/cloudstack/assets/92435079/b5d1c1cc-c9d5-436e-a7f7-eae95d215ea3)
![image](https://github.com/apache/cloudstack/assets/92435079/e2d45ed4-2811-4f47-9844-6454dba940d4)

LOG:
[vm-from-iso.txt](https://github.com/apache/cloudstack/files/11545429/vm-from-iso.txt)

**Comment by kiranchavala** [comment] 2023-05-29 05:20
@harikrishna-patnala  @DaanHoogland 

Can this issue be a bug with CS 

Are the above steps valid for reproducing the issue ?

**Comment by DaanHoogland** [comment] 2023-06-22 11:59
@top-secrett Any update (did you doi as @harikrishna-patnala suggested?)

**Comment by DaanHoogland** [comment] 2023-06-23 10:43
@top-secrett what is the version of your production environment? 

> But I don't understand why does CS use disk names different from VM names?

I think the initial name of the volume is always a uuid, but vmware renames it to the VM name on migration.

**Comment by top-secrett** [comment] 2023-06-23 10:56
@DaanHoogland I use 4.18.0 version on both CS

**Comment by DaanHoogland** [comment] 2023-06-23 11:42
¿any reseason for the difference, @top-secrett ? that you know of that is.

**Comment by top-secrett** [comment] 2023-06-23 22:15
@DaanHoogland on prod CS I have clustered datastore, on test CS don't. Maybe that is the reason

**Comment by DaanHoogland** [comment] 2023-06-26 07:18
@top-secrett ,
If you have no clustered datastore you have no storage DRS, so what happened in your test environment exactly?
I.E. what could be the reason for volume path change if Storage DRS is not there, any manual migrations ?

**Comment by top-secrett** [comment] 2023-06-27 06:56
@DaanHoogland This problem occurs when VM is created from ISO and migrated manually from vSphere Client or automatically via DRS

**Comment by DaanHoogland** [comment] 2023-07-03 08:37
@top-secrett you should not use DRS with cloudstack and not migrate out-of-bounds. only storage-DRS is supported when using cluster-storage.
cc @harikrishna-patnala

**Comment by rohityadavcloud** [comment] 2023-08-28 05:33
@top-secrett like Daan advised, DRS shouldn't be used with CloudStack; we've an upcoming CloudStack-led hypervisor-agnostic DRS feature that may be used in future ACS releases https://github.com/apache/cloudstack/pull/7723

As a workaround - you could disable DRS and manually fix the chain_info for the cloud.volume table in CloudStack for affected VMs. Stop/start the VM could fix/update this as well. Closing on this remark, kindly reopen of submit a new issue if you've further information on reproducing this consistently without DRS enabled for the vsphere cluster. Thank you.

**Closed by rohityadavcloud** 2023-08-28 05:33 UTC
Labels: component:management-server, component:vmware, component:primary-storage, status:needs-reproducing, Severity:Minor
