### ISSUE TITLE
Destroying VMs also deleting the associated VM Snapshots

### ISSUE THREAD

**Issue by gg4126** [apache/cloudstack#6604] opened 2022-08-02 18:46 UTC
##### ISSUE TYPE

 * Improvement Request

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
CloudStack 4.17.0.1
~~~

##### CONFIGURATION

advanced networking

##### OS / ENVIRONMENT

RHEL 7.9

##### SUMMARY

The VM Snapshots and VM “Backup & Recovery” are two different things; Currently CloudStack supports the VM backup & recovery by means of third party Veeam Plugin which requires paid subscription. We noticed that when we destroy (without Expunging) VMs, it is also deleting the associated VM Snapshots, in fact we wanted to use these VM snapshots as our recovery points. So, Is it possible to retain the VM snapshots even when the VMs are getting destroyed so that we can pick and choose the desired VM snapshot to recover the VM.

##### STEPS TO REPRODUCE

~~~
step1: Navigate to the desired instances under compute tab, and click "Take VM Snapshot" w/ Snapshot memory & Quiesce VM Enabled
step2: Navigate to Instances, pick the VM and destroy it (without choosing Expunge).
step3: After the VM is destroyed, you will notice that the associated VM Snapshots under Storage tab are also deleted.
~~~

##### EXPECTED RESULTS

~~~
Destroying VMs should NOT delete the associated VM Snapshots coz these snapshots can be used to recreate the VM using the desired VM snapshot from of these backed-up VM snapshots.
~~~

##### ACTUAL RESULTS

~~~
Destroying VMs also deleting the associated VM Snapshots - the whole chain parent and children VM snapshots
~~~

**Comment by shwstppr** [comment] 2022-08-08 05:37
@gg4126 this would require some major changes as currently VM snapshots are not backed up on to secondary storage and live in the same dir as the VM  (atleast on VMware which I checked). For now using B&R plugin would be a better option

**Comment by damonb123** [comment] 2022-08-10 15:00
I think the issue is the snapshots are deleted on "VM.DESTROY", instead of on "VM.EXPUNGING".
Since the VM can be recovered after being destroyed, but cant be recovered after expunging.
So in the "VM.DESTROYED" event process, the snapshots should not be deleted.

**Comment by shwstppr** [comment] 2022-08-10 15:13
@gg4126 I will test again but in my case snapshot wasn't deleted when VM was destroyed and only deleted when the VM was expunged. I was using VMware as hypervisor. Are you using KVM?

**Comment by shwstppr** [comment] 2022-08-10 15:14
@gg4126 I will test again but in my case snapshot wasn't deleted when VM was destroyed and only deleted when the VM was expunged. I was using VMware as hypervisor. Are you using KVM?

**Comment by gg4126** [comment] 2022-08-10 15:28
Yes, we saw this behavior on KVM based VMs.

**Comment by weizhouapache** [comment] 2023-01-10 08:58
@gg4126 
on KVM, the vm snapshots are saved as in the qcow2 image file of the vm instance.
If the vm is expunged (cloudstack will expunge vm in Destroy state after a period), the vm image is removed, as well as the vm snapshots.

it would be better to use volume snapshots (a.k.a snapshots), which are persisted on primary or secondary storage, instead of vm snapshots.

**Comment by rohityadavcloud** [comment] 2024-04-30 09:57
By design, it's not possible to retain VM snapshot and delete the VM with VM snapshots. The suggest approach is to take volume snapshots and convert them into templates when needed to restore VMs. Or, take backup using the B&R framework.

Due to this design we can't support retaining VM snapshots across support hypervisors and volumes. Closing on this remark.

**Closed by rohityadavcloud** 2024-04-30 09:57 UTC
Labels: type:enhancement, type:improvement, component:orchestration
