### ISSUE TITLE
VM snapshot failure without memory

### ISSUE THREAD

**Issue by matheusfontes** [apache/cloudstack#6294] opened 2022-04-20 14:45 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Snapshot,Xcp-ng
~~~

##### CLOUDSTACK VERSION

~~~
4.16.1
~~~

##### OS / ENVIRONMENT

Xcp-ng 8.2 (Build 2022-02-11)

##### SUMMARY

VM snapshot, take or revert failure without memory
2022-04-19 20:08:31,192 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-26:ctx-71ff1196 job-202173) (logid:751c997c) Unexpected exception while executing org.apa
che.cloudstack.api.command.user.vmsnapshot.CreateVMSnapshotCmd
java.lang.RuntimeException: Unexpected exception
        at com.cloud.vm.snapshot.VMSnapshotManagerImpl.createVMSnapshot(VMSnapshotManagerImpl.java:570)
        at jdk.internal.reflect.GeneratedMethodAccessor1845.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.apache.cloudstack.network.contrail.management.EventUtils$EventInterceptor.invoke(EventUtils.java:107)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at com.cloud.event.ActionEventInterceptor.invoke(ActionEventInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy226.createVMSnapshot(Unknown Source)
        at org.apache.cloudstack.api.command.user.vmsnapshot.CreateVMSnapshotCmd.execute(CreateVMSnapshotCmd.java:114)
        at com.cloud.api.ApiDispatcher.dispatch(ApiDispatcher.java:156)
        at com.cloud.api.ApiAsyncJobDispatcher.runJob(ApiAsyncJobDispatcher.java:108)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.cloud.utils.exception.CloudRuntimeException: Failed to create vm snapshot: 674
        at com.cloud.vm.snapshot.VMSnapshotManagerImpl.orchestrateCreateVMSnapshot(VMSnapshotManagerImpl.java:606)
        at com.cloud.vm.snapshot.VMSnapshotManagerImpl.orchestrateCreateVMSnapshot(VMSnapshotManagerImpl.java:1286)
        at jdk.internal.reflect.GeneratedMethodAccessor1846.invoke(Unknown Source)
        ... 27 more
Caused by: com.cloud.utils.exception.CloudRuntimeException: Creating VM snapshot: i-2-4813-VM_VS_20220419230830 failed due to com.cloud.utils.exception.CloudRuntimeExc
eption:  Hypervisor com.cloud.hypervisor.xenserver.resource.XenServer650Resource doesn't support guest OS type CentOS 7.2. you can choose 'Other install media' to run
it as HVM

##### STEPS TO REPRODUCE

~~~
On Running or Stopped instance
task vm snapshot (Do not select Snapshot memory)
Or
Try to revert a old vm snapshot (without memory)
~~~

##### EXPECTED RESULTS

~~~
Take or Revert snapshot success
~~~

##### ACTUAL RESULTS

~~~
Take or Revert snapshot failure
~~~

**Comment by harikrishna-patnala** [comment] 2022-06-27 12:11
@matheusfontes I could not reproduce the issue. The reason for your issue could be the missing entries for guest os in guest_os_hypervisor table. Please add that in your setup and try it once.

**Comment by rohityadavcloud** [comment] 2022-06-30 06:16
@matheusfontes it's possible on your hypervisor host setup/installation the guest os wasn't properly set in it. Is it a new host or newly upgraded host? If so, can you retry installation and try again?

**Comment by harikrishna-patnala** [comment] 2022-07-26 03:56
@matheusfontes I'm closing this issue as I could not reproduce it. Please feel free to reopen if you still face the issue.

**Closed by harikrishna-patnala** 2022-07-26 03:56 UTC
Labels: type:bug, component:storage
