### ISSUE TITLE
Public template is not visible

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#3059] opened 2018-11-27 09:27 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Management Server, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### CONFIGURATION

Advanced Network without SG, KVM, Public Zone

##### OS / ENVIRONMENT

CentOS 7.4

##### SUMMARY

Template is created (inside Project) and marked as Public - despite of this fact, it's not visible to other accounts in other domains.
[Docs](http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/4.11/templates.html#private-and-public-templates) say that it have to.

##### STEPS TO REPRODUCE

1) Create template under Project view and mark it as Public
2) Switch to Project in another domain and try to find it in "Templates" section in UI

**Comment by izenk** [comment] 2018-11-27 09:29
In the same time, if I try to create VM in project where public template is **not** visible in "Templates" section, I **can** choose this template in VM creation form..

**Comment by rhtyd** [comment] 2018-12-04 12:06
@izenk a public template in a project will be restricted to that project only. If you want to share the template to another project or account, you need to manually grant permissions using the following API:
```
update templatepermissions
updateTemplatePermissions: Updates a template visibility permissions. A public template is visible to all accounts within the same domain. A private template is visible only to the owner of the template. A priviledged template is a private template with account permissions added. Only accounts specified under the template permissions are visible to them.
Required params: id, 
API Params               Type     Description
==========               ====     ===========
accounts                 list     a comma delimited list of accounts. If sp
                                  ecified, "op" parameter has to be passed
                                   in.
id                       uuid     the template ID
isextractable            boolean  true if the template/iso is extractable, 
                                  false other wise. Can be set only by roo
                                  t admin
isfeatured               boolean  true for featured template/iso, false oth
                                  erwise
ispublic                 boolean  true for public template/iso, false for p
                                  rivate templates/isos
op                       string   permission operator (add, remove, reset)
projectids               list     a comma delimited list of projects. If sp
                                  ecified, "op" parameter has to be passed
                                   in.

```
Perhaps we can add a UI button for the above API.
What you've reported is not a bug, please close the ticket. Thanks.

**Comment by izenk** [comment] 2018-12-06 15:45
@rhtyd 
Thanks for info, but I do not agree that this is not a bug. If template is visible only for project it was created in, why I can create vm based on this template?
I cant see in UI template in "Templates" section, but can create vm based in this template, because it's visible in vm creation form.

**Comment by izenk** [comment] 2018-12-07 11:14
@rhtyd 
I read [docs](http://docs.cloudstack.apache.org/projects/cloudstack-administration/en/4.11/templates.html#private-and-public-templates) and it says that "When a user marks a template as “public,” the template becomes available to all users in all accounts in the user’s domain, as well as users in any other domains that have access to the Zone where the template is stored."

**Comment by anuragaw** [comment] 2018-12-19 05:31
What is the conclusion on this ticket? @rhtyd / @izenk . I also feel marking something as public should ideally be available as per what @izenk points out. But this is based on a new CloudStack user perception that I am.

**Comment by rhtyd** [comment] 2019-06-26 09:28
When a template is created under a project, the owner of the template is the project account; and the public access is limited to the project. So, you would only be allowed to use the template to deploy a VM within the project. This PR adds functionality to share a template that belongs to a project to be shared with other accounts that you can use in 4.13: https://github.com/apache/cloudstack/pull/3241

Closing as this is not a bug.

**Closed by rhtyd** 2019-06-26 09:28 UTC
Labels: component:templates, status:not-a-bug
