### ISSUE TITLE
UI: After wrong pass/login, the UI does not load any more

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#8803] opened 2024-03-19 23:31 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0.0
~~~

Try logging in with a wrong password - the auth attempt never fails, the UI will continue to load forever... and if you close the tab/window, and open the same UI login page - it never opens up - see the recording below:

https://somup.com/cZeq0ZCX3O

**Comment by vishesh92** [comment] 2024-03-20 07:03
This is a duplicate of https://github.com/apache/cloudstack/issues/8662 and PR for the fix is https://github.com/apache/cloudstack/pull/8671

**Comment by andrijapanicsb** [comment] 2024-03-20 11:09
Excellent, thx @vishesh92 !

**Comment by DaanHoogland** [comment] 2024-03-25 09:47
closing as duplicate of #8662

**Closed by DaanHoogland** 2024-03-25 09:47 UTC
Labels: Severity:Critical
