### ISSUE TITLE
HTML code displayed in Setup Network wizard when adding zone

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#2768] opened 2018-07-25 08:25 UTC
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION
~~~
4.12 and prev
~~~

##### SUMMARY

Some HTML code displayed in description

##### STEPS TO REPRODUCE
~~~
Goto Add Zone, step3 'Setup Network'
Note that the following is displayed:
.<br/><br/><strong>Drag and drop one or more traffic types</strong> onto each physical network.
~~~
![screen shot 2018-07-25 at 11 20 36](https://user-images.githubusercontent.com/13551960/43188613-37e40666-8ffd-11e8-822c-7f0377e5e8ab.png)

**Comment by anuragaw** [comment] 2019-06-27 09:10
I am unable to reproduce the issue on latest master on Ubuntu Chrome.
@borisstoyanov - can you please see if it still breaks for you and if yes can you please advise the environment (indluding browser) that it breaks on.
CC/ @rhtyd

**Comment by rhtyd** [comment] 2019-06-27 10:51
LGTM, I'm unable to reproduce as well. Closing this.

**Closed by rhtyd** 2019-06-27 10:51 UTC
Labels: component:UI, type:bug
