### ISSUE TITLE
KVM: Cannot recreate system VMs after upgrade from 4.17.1.0 to 4.18.0

### ISSUE THREAD

**Issue by slavkap** [apache/cloudstack#7258] opened 2023-02-17 17:38 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
System VMs
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0
~~~

##### OS / ENVIRONMENT

on management and agents: Rocky Linux VERSION="8.4 (Green Obsidian)"

##### SUMMARY

After the upgrade from 4.17.1.0 to 4.18 RC1 cannot recreate the SSVM/CPVM

> 2023-02-17 19:35:41,461 WARN  [resource.wrapper.LibvirtStartCommandWrapper] (agentRequest-Handler-5:null) (logid:d27dcb39) LibvirtException 
> org.libvirt.LibvirtException: Hook script execution failed: internal error: Child process (LC_ALL=C PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin /etc/libvirt/hooks/qemu v-17171-VM prepare begin -) unexpected exit status 1: Traceback (most recent call last):
>   File "/etc/libvirt/hooks/qemu", line 24, in <module>
>     from cloudutils.configFileOps import configFileOps
> ModuleNotFoundError: No module named 'cloudutils'
> 
>         at org.libvirt.ErrorHandler.processError(Unknown Source)
>         at org.libvirt.ErrorHandler.processError(Unknown Source)
>         at org.libvirt.Connect.domainCreateXML(Unknown Source

##### STEPS TO REPRODUCE

~~~
Following the procedure for the Upgrade of CloudStack
~~~

##### EXPECTED RESULTS

~~~
Successful system VMs deployment
~~~

##### ACTUAL RESULTS

~~~
ModuleNotFoundError: No module named 'cloudutils'
~~~

**Comment by slavkap** [comment] 2023-02-17 17:40
I've spoke with @nvazquez offline, and he was able to reproduce the issue

**Comment by nvazquez** [comment] 2023-02-17 17:47
Thanks @slavkap, I can see this issue is not present on upgrades on centos7. The cloudutils file gets copied correctly:

````
[root@ref-trl-4484-k-M7-vladimir-petrov-kvm2 ~]# python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib(1))"
/usr/lib64/python3.6/site-packages
[root@ref-trl-4484-k-M7-vladimir-petrov-kvm2 ~]# ls -lh /usr/lib64/python3.6/site-packages
total 772K
-rw-r--r--. 1 root root  119 Dec 23  2018 README.txt
drwxr-xr-x. 2 root root 4.0K Feb 17 08:46 __pycache__
-rw-r--r--. 1 root root  40K Jul 14  2022 cloud_utils.py
drwxr-xr-x. 3 root root 4.0K Feb 17 08:46 cloudutils
-rw-r--r--. 1 root root 324K Dec 11  2019 libvirt.py
-rw-r--r--. 1 root root 1.7K Dec 11  2019 libvirt_lxc.py
-rw-r--r--. 1 root root  875 Dec 11  2019 libvirt_python-4.5.0-py3.6.egg-info
-rw-r--r--. 1 root root 3.2K Dec 11  2019 libvirt_qemu.py
-rw-r--r--. 1 root root  16K Dec 11  2019 libvirtaio.py
-rwxr-xr-x. 1 root root 308K Dec 11  2019 libvirtmod.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x. 1 root root  28K Dec 11  2019 libvirtmod_lxc.cpython-36m-x86_64-linux-gnu.so
-rwxr-xr-x. 1 root root  29K Dec 11  2019 libvirtmod_qemu.cpython-36m-x86_64-linux-gnu.so
````

However, it is not there for Rocky8 and is not copied anywhere

**Comment by weizhouapache** [comment] 2023-02-17 21:15
it might be an issue caused by packaging.
the scripts should be installed at /usr/share/cloudstack-common/python-site/cloudutils/

**Comment by nvazquez** [comment] 2023-02-17 22:45
It is weird that is only an issue on upgrade but vanilla environment creation works fine for centos8. Could worth verifying the upgrade on suse as well as it uses the same spec file as centos8

**Comment by slavkap** [comment] 2023-02-18 11:14
@weizhouapache, yes the script should be installed but the directory isn't full after the upgrade

```
[root@lab-cs-test-b1-block-server-mgmt-bridge packages]# ls -latr /usr/share/cloudstack-common/python-site/cloudutils/
total 8
drw-r--r--.  2 root root 4096 18 фев 13,04 __pycache__
drwxr-xr-x.  3 root root   25 18 фев 13,04 .
drwxr-xr-x. 24 root root 4096 18 фев 13,04 ..
```

If I reinstall the 4.18 packages everything works fine:
```

[root@lab-cs-test-b1-block-server-mgmt-bridge packages]# yum reinstall cloudstack-common-4.18.0.0-1.x86_64.rpm cloudstack-agent-4.18.0.0-1.x86_64.rpm
Last metadata expiration check: 1:39:36 ago on 18.02.2023 (сб) 11:28:02 EET.
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                                 Architecture                                 Version                                             Repository                                          Size
===================================================================================================================================================================================================================
Reinstalling:
 cloudstack-agent                                        x86_64                                       4.18.0.0-1                                          @commandline                                        86 M
 cloudstack-common                                       x86_64                                       4.18.0.0-1                                          @commandline                                        86 M

Transaction Summary
===================================================================================================================================================================================================================

Total size: 172 M
Installed size: 187 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                           1/1 
  Running scriptlet: cloudstack-common-4.18.0.0-1.x86_64                                                                                                                                                       1/1 
  Running scriptlet: cloudstack-common-4.18.0.0-1.x86_64                                                                                                                                                       1/4 
  Reinstalling     : cloudstack-common-4.18.0.0-1.x86_64                                                                                                                                                       1/4 
  Running scriptlet: cloudstack-agent-4.18.0.0-1.x86_64                                                                                                                                                        2/4 
  Reinstalling     : cloudstack-agent-4.18.0.0-1.x86_64                                                                                                                                                        2/4 
  Running scriptlet: cloudstack-agent-4.18.0.0-1.x86_64                                                                                                                                                        2/4 
Running /usr/bin/cloudstack-agent-upgrade to update bridge name for upgrade from CloudStack 4.0.x (and before) to CloudStack 4.1 (and later)
Upgrade succeed

  Running scriptlet: cloudstack-agent-4.18.0.0-1.x86_64                                                                                                                                                        3/4 
Redirecting to /bin/systemctl stop cloudstack-agent.service

  Cleanup          : cloudstack-agent-4.18.0.0-1.x86_64                                                                                                                                                        3/4 
  Cleanup          : cloudstack-common-4.18.0.0-1.x86_64                                                                                                                                                       4/4 
  Running scriptlet: cloudstack-agent-4.18.0.0-1.x86_64                                                                                                                                                        4/4 

Thank you for installing Apache CloudStack Agent 4.18.0.0 !

 * Project website:     https://cloudstack.apache.org/
 * Documentation:       https://docs.cloudstack.apache.org/en/4.18.0.0/
 * Release notes:       https://docs.cloudstack.apache.org/en/4.18.0.0/releasenotes/
 * Join mailing lists:  https://cloudstack.apache.org/mailing-lists.html
 * Take the survey:     https://cloudstack.apache.org/survey.html
 * Report issues:       https://github.com/apache/cloudstack/issues/new


  Running scriptlet: cloudstack-common-4.18.0.0-1.x86_64                                                                                                                                                       4/4 
  Verifying        : cloudstack-common-4.18.0.0-1.x86_64                                                                                                                                                       1/4 
  Verifying        : cloudstack-common-4.18.0.0-1.x86_64                                                                                                                                                       2/4 
  Verifying        : cloudstack-agent-4.18.0.0-1.x86_64                                                                                                                                                        3/4 
  Verifying        : cloudstack-agent-4.18.0.0-1.x86_64                                                                                                                                                        4/4 

Reinstalled:
  cloudstack-agent-4.18.0.0-1.x86_64                                                                      cloudstack-common-4.18.0.0-1.x86_64                                                                     

Complete!
```

```
[root@lab-cs-test-b1-block-server-mgmt-bridge packages]# ls -latr /usr/share/cloudstack-common/python-site/cloudutils/
total 108
-rw-r--r--.  1 root root 10001 17 фев 14,26 utilities.py
-rw-r--r--.  1 root root  9908 17 фев 14,26 syscfg.py
-rw-r--r--.  1 root root  4601 17 фев 14,26 serviceConfigServer.py
-rw-r--r--.  1 root root 36434 17 фев 14,26 serviceConfig.py
-rw-r--r--.  1 root root  5639 17 фев 14,26 networkConfig.py
-rw-r--r--.  1 root root   785 17 фев 14,26 __init__.py
-rw-r--r--.  1 root root  1778 17 фев 14,26 globalEnv.py
-rw-r--r--.  1 root root  2734 17 фев 14,26 db.py
-rw-r--r--.  1 root root  6379 17 фев 14,26 configFileOps.py
-rw-r--r--.  1 root root  1540 17 фев 14,26 cloudException.py
drwxr-xr-x. 24 root root  4096 18 фев 13,07 ..
drwxr-xr-x.  3 root root   241 18 фев 13,07 .
drw-r--r--.  2 root root  4096 18 фев 13,08 __pycache__
```

**Comment by nvazquez** [comment] 2023-02-18 16:55
@weizhouapache @slavkap I confirm the same issue is present on upgrading from 4.17.2 to 4.18 RC1 on Suse15 KVM hosts

**Comment by weizhouapache** [comment] 2023-02-18 18:03
@slavkap @nvazquez 
This seems to be cause python-site is a symbolic link, not a directory. The process is different on centos7 (cloud.spec)

an idea is, install files to python-site and then move to site-packages

**Comment by weizhouapache** [comment] 2023-02-19 12:30
@nvazquez @slavkap 
It is because the "%files common" part have some differences in cloud.spec between 4.17.2.0 and 4.18.0.0

```
 %files common
-%dir %attr(0755,root,root) %{python_sitearch}/cloudutils
+%dir %attr(0755,root,root) %{_datadir}/%{name}-common/python-site/cloudutils
 %dir %attr(0755,root,root) %{_datadir}/%{name}-common/vms
 %attr(0755,root,root) %{_datadir}/%{name}-common/scripts
 %attr(0755,root,root) /usr/bin/cloudstack-sccs
 %attr(0644, root, root) %{_datadir}/%{name}-common/vms/agent.zip
 %attr(0644, root, root) %{_datadir}/%{name}-common/vms/cloud-scripts.tgz
 %attr(0644, root, root) %{_datadir}/%{name}-common/vms/patch-sysvms.sh
-%attr(0644,root,root) %{python_sitearch}/cloud_utils.py
-%attr(0644,root,root) %{python_sitearch}/__pycache__/*
-%attr(0644,root,root) %{python_sitearch}/cloudutils/*
+%attr(0644,root,root) %{_datadir}/%{name}-common/python-site/cloud_utils.py
+%attr(0644,root,root) %{_datadir}/%{name}-common/python-site/__pycache__/*
+%attr(0644,root,root) %{_datadir}/%{name}-common/python-site/cloudutils/*
 %attr(0644, root, root) %{_datadir}/%{name}-common/lib/jasypt-1.9.3.jar
+%attr(0644, root, root) %{_datadir}/%{name}-common/lib/%{name}-utils.jar
 %{_defaultdocdir}/%{name}-common-%{version}/LICENSE
 %{_defaultdocdir}/%{name}-common-%{version}/NOTICE
 ```

The files in 4.17.2.0 but not in 4.18.0.0 are removed AFTER cloudstack-common upgrade. To be clear, these files are removed
```
%dir %attr(0755,root,root) %{python_sitearch}/cloudutils
%attr(0644,root,root) %{python_sitearch}/cloud_utils.py
%attr(0644,root,root) %{python_sitearch}/__pycache__/*
%attr(0644,root,root) %{python_sitearch}/cloudutils/*
```

It looks the directory/file path should be same. cc @rohityadavcloud

**Comment by rohityadavcloud** [comment] 2023-02-20 07:44
Apologies from my side, I think I caused this. This is because I had merged the pkging for el8/el9/suse and to support EL9 I had to use the 'python-site' in the pkging to use it as a distro/agnostic path, but at the time I didn't consider/test for upgrade scenarios.

Ref:
https://github.com/apache/cloudstack/pull/6995
https://github.com/apache/cloudstack/pull/6844

I think the python_sitearch was removed as part of this. I think this can be fixed by having the hook script (in fact any of the script that import or use cloudutils to search from the python path, something like this: https://github.com/apache/cloudstack/blob/main/setup/bindir/cloud-setup-databases.in#L39 and PYTHON DIR can be made to replace from https://github.com/apache/cloudstack/blob/main/packaging/centos8/replace.properties#L51)

@weizhouapache @DaanHoogland can you use above to fix this blocker and also check if there are other scripts that may be importing/using cloudutils. Alternatively, in the deb and rpm install/upgrade script (post section) we can make it install in the right python-path by detecting the distro specific python site-arch path.

**Comment by weizhouapache** [comment] 2023-02-20 13:16
> Apologies from my side, I think I caused this. This is because I had merged the pkging for el8/el9/suse and to support EL9 I had to use the 'python-site' in the pkging to use it as a distro/agnostic path, but at the time I didn't consider/test for upgrade scenarios.
> 
> Ref: #6995 #6844
> 
> I think the python_sitearch was removed as part of this. I think this can be fixed by having the hook script (in fact any of the script that import or use cloudutils to search from the python path, something like this: https://github.com/apache/cloudstack/blob/main/setup/bindir/cloud-setup-databases.in#L39 and PYTHON DIR can be made to replace from https://github.com/apache/cloudstack/blob/main/packaging/centos8/replace.properties#L51)
> 
> @weizhouapache @DaanHoogland can you use above to fix this blocker and also check if there are other scripts that may be importing/using cloudutils. Alternatively, in the deb and rpm install/upgrade script (post section) we can make it install in the right python-path by detecting the distro specific python site-arch path.

@rohityadavcloud 
thanks for the hint.

I think it should work if all files are moved to correct directory after upgrade/installation. Let me test it

**Closed** 2023-02-21 11:27 UTC
Labels: component:packaging, Severity:BLOCKER
