### ISSUE TITLE
Failed to create instances and VR

### ISSUE THREAD

**Issue by fangyi1008** [apache/cloudstack#7064] opened 2023-01-06 10:33 UTC
ISSUE TYPE

   Bug Report

COMPONENT NAME

   VR

CLOUDSTACK VERSION

   4.17.10

CONFIGURATION

   basic network

OS / ENVIRONMENT

   Centos8.5

SUMMARY

   VR can't start

STEPS TO REPRODUCE
![image](https://user-images.githubusercontent.com/89246132/210986466-50427233-2228-4f1d-a752-f4118dc6e49c.png)
![image](https://user-images.githubusercontent.com/89246132/210986742-652a5d2e-bf51-40dc-a65d-16d9017f42e6.png)
The following is the management log：
![image](https://user-images.githubusercontent.com/89246132/210987017-af0e1a33-5dff-4ce9-9c21-0e560c9f032a.png)
![image](https://user-images.githubusercontent.com/89246132/210987203-84dccb1c-7451-4443-bfdc-dfeb08648c6f.png)
I found out by looking at the system virtual machine：
    Command 'nft list tables ip6 | grep ip6_firewall
    l' returned non-zero exit status 1

I don't understand what's wrong, hope to get your help, thank you

EXPECTED RESULTS

   Instances and VR can be created successfully

ACTUAL RESULTS

   Failed to create instances and VR

Looking forward to your reply~~~

**Comment by weizhouapache** [comment] 2023-01-06 11:35
@fangyi1008 
do you install from official cloudstack packages ?
do you use official systemvm template ?

**Comment by fangyi1008** [comment] 2023-01-06 12:26
> do you install from official cloudstack packages ?
> do you use official systemvm template ?

Yes, I downloaded the package and template from the official, otherwise the system virtual machine would not be able to start successfully. It's that instancing and VR keeps failing.

**Comment by fangyi1008** [comment] 2023-01-06 12:59
> that's strange. I have created a Basic zone, everything looks good.
> can you double check the cloudstack version on management server and centos hosts ? please also check the `/etc/cloudstack-release` in the system vms.

OK, I'll check it out on Monday. Should be all right. At that time, they were all official download packages. Create an instance using the ubuntu-14.04.6-server-amd64.iso file uploaded by yourself.
thanks.
Get back to you next Monday and have a great weekend.

**Comment by weizhouapache** [comment] 2023-01-16 08:24
@fangyi1008 
any update on this issue ?

**Comment by fangyi1008** [comment] 2023-01-16 08:52
> @fangyi1008 any update on this issue ?

Feel sorry. I have been busy with other things recently and have not responded to you. I have checked everything and there is no problem. I really don't know where the problem is

**Comment by weizhouapache** [comment] 2023-02-02 07:32
@fangyi1008 
does the issue still exist ?

**Comment by fangyi1008** [comment] 2023-02-02 07:44
> 
Yes, temporarily give up processing.

**Comment by weizhouapache** [comment] 2023-06-29 08:10
this seems to be caused by host error
the host should be Up and Enabled.

@fangyi1008 
I am closing this ticket, please feel free to reopen it if you still face the problem

**Closed by weizhouapache** 2023-06-29 08:10 UTC
Labels: status:needs-reproducing, Severity:Minor
