### ISSUE TITLE
VM's ROOT disk created from ISO, honors Service offering instead of Disk offering

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#3520] opened 2019-07-24 12:41 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
disk/service offerings
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2 (didn't test previous or newer ones)
~~~

##### CONFIGURATION

- 2 x Primary Storage pools with different Storage Tags, 
- hypervisor (VMware tested) is irrelevant
- (for simplicity) service offerings configured (storage tags) to be created on storage Primary1, while disk offerings configured to point to Primary2 storage.

##### OS / ENVIRONMENT

NA

##### SUMMARY

Problem:
When VM is created from a template, ROOT disk will inherit service offering setup - and will be created on Primary1 storage, as required (by storage tags). Disk offering is not used in this GUI/API call. - ALL GOOD.

When VM is created from ISO, ROOT disk *should* honour the Disk offering details and choose Primary2 storage as required by storage tags - but instead, ROOT volume still honours the Service offering and gets created on Primary1 storage - WRONG.

##### EXPECTED RESULTS

When VM is created from ISO, ROOT disk *should* honour the Disk offering details and choose Primary2 storage as required by storage tags, intead horouring the Service offering details.

**Comment by andrijapanicsb** [comment] 2019-07-24 12:45
@rhtyd @GabrielBrascher @rafaelweingartner @shwstppr - please consider this one for 4.13.0.0 - might be simple to fix.

**Comment by rhtyd** [comment] 2019-07-24 15:38
Ack, it's possible something like this was fixed in master. We'll need to test/reproduce it.

**Comment by Doni7722** [comment] 2019-07-25 13:48
Did test this with 4.11.3 and there it's reproducible.

**Comment by DaanHoogland** [comment] 2019-11-19 13:33
investigating this request/report I noticed that the diskoffering has a one to one relation with the service offering, basically meaning that it is one record and that different tags are a potential conflict. I am not completely clear on how this is intended but the proposed wont work, without data redesign and thus backwards compatibility problems.

**Comment by DaanHoogland** [comment] 2020-01-29 13:32
@rhtyd @GabrielBrascher @shwstppr @PaulAngus @andrijapanicsb, please see my remark above. I have a mind of removing this from milestones. It is a DB designe issue and will have other design consequences.
/cc @weizhouapache @wido @theworld

**Comment by DaanHoogland** [comment] 2020-02-03 12:32
moving to future...

**Comment by davidjumani** [comment] 2021-07-28 09:56
Looks like a commit was added years ago to respect the service offering tags over the disk offering tags https://github.com/apache/cloudstack/commit/b25ee92c348118d084fbc4d6103f3fb81fab0e68

**Closed** 2021-07-29 11:12 UTC
Labels: Severity:Major, age:2years_plus
