### ISSUE TITLE
Xenserver/XCP-NG Inter-cluster VM migration with ROOT on managed storage

### ISSUE THREAD

**Issue by tsinik-dw** [apache/cloudstack#5924] opened 2022-02-02 10:05 UTC
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0
~~~

##### CONFIGURATION

ACS 4.16.0
1 Zone 
Cluster A: Two Xenserver 7.0 hosts
Cluster B: Two XCP-NG 8.2 hosts

Each Cluster has each own NFS primary storage
There is a Zone-wide Solidfire Storage (managed storage)

##### OS / ENVIRONMENT

VM-A1, on Cluster A,  has a ROOT disk  on managed storage

##### SUMMARY

The objective is to migrate VM-A1 from Cluster A to Cluster B 
                    
VM-A1 migration fails and throws the following message:

Migration failed
Migration of the VM: i-2-11-VM (ID: c87de296-e0e4-4052-81a2-53798cfadd6c) from host xen1 (ID: 7e374139-b522-44da-9ea5-2a03b369f787) to destination host xcp1 (ID: 99d6b992-d6b9-49f2-9cec-3e0394251664) doesn't involve migrating the volumes

##### STEPS TO REPRODUCE

~~~
1. Create VM on Xenserver 7.0 cluster with ROOT disk on managed storage
2. Migrate VM from Xenserver 7.0 Cluster to XCP-NG Cluster
~~~

##### EXPECTED RESULTS

~~~
VM should be migrated from xenserver cluster to xcp-ng cluster
~~~

##### ACTUAL RESULTS

~~~
VM-A1 migration fails and throws the following message:

Migration failed
Migration of the VM: i-2-11-VM (ID: c87de296-e0e4-4052-81a2-53798cfadd6c) from host xen1 (ID: 7e374139-b522-44da-9ea5-2a03b369f787) to destination host xcp1 (ID: 99d6b992-d6b9-49f2-9cec-3e0394251664) doesn't involve migrating the volumes
~~~

**Comment by nvazquez** [comment] 2022-02-04 00:07
Hi @shwstppr, you have worked on inter-cluster migration, is it only supported on Vmware?

**Comment by shwstppr** [comment] 2022-02-04 09:16
@nvazquez I've not tested it myself but I don't remember code conditions that prevent it on other hypervisors. Also, recently in issue https://github.com/apache/cloudstack/issues/5894 it was reported to be working with NFS stores on 4.16 so this could be an issue only with managed storages

**Comment by nvazquez** [comment] 2022-02-15 15:05
Hi @tsinik-dw are you attempting a live VM migration? In that case, do you get the hosts from the different cluster listed on the UI or are using the API? If not using the UI, can you check if the target host is listed on the output of the `findSuitableHostsForMigration` API?

**Comment by nvazquez** [comment] 2022-02-16 02:08
Can you also please upload the management server logs for the migration attempt? @tsinik-dw

**Comment by nvazquez** [comment] 2022-02-16 03:17
I suspect the issue is that the underlying API invoked is `migrateVirtualMachineWithVolume` instead of `migrateVirtualMachine` - can you please try using a client such as cloudmonkey the following API attempt?
````
migrate virtualmachine virtualmachineid=<VM_UUID> hostid=<HOST_UUID>
````

**Comment by tsinik-dw** [comment] 2022-02-16 07:10
Hi, @nvazquez, I am setting up a test environment and reporting the results in a while along with the log.

**Comment by tsinik-dw** [comment] 2022-02-16 09:17
Hi @nvazquez,
 
I tried a live VM migration from Xen to XCP. The destination host (XCP, Host 9 in log) is presented as expected  in the UI along with the AutoSelect option. I checked the XCP host as destination and tried the migration.
In the log I can see that  _findHostsForMigration_ command is able to identify the XCP host as a possible destination but the migration fails. Management  log attached [live_intercluster_vm_migr_Xen70_to_Xcp82.txt](https://github.com/apache/cloudstack/files/8078394/live_intercluster_vm_migr_Xen70_to_Xcp82.txt)

Your guess is right!... Indeed, the API invoked is _migrateVirtualMachineWithVolume_ instead of _migrateVirtualMachine_.
But, when the same migration tried using cmk the VM migration fails with the following output: 

~~~
(localcloud) 🐱 > migrate virtualmachine virtualmachineid=c87de296-e0e4-4052-81a2-53798cfadd6c hostid=73cd3fa4-01ce-4b55-970f-14efd0143aa1
cmd = org.apache.cloudstack.api.command.admin.vm.MigrateVMCmd
jobstatus = 2
jobprocstatus = 0
jobresultcode = 530
accountid = 48ae3b86-8032-11ec-8660-4626a7ce6ce6
userid = 48bd974a-8032-11ec-8660-4626a7ce6ce6
created = 2022-02-16T10:07:28+0200
completed = 2022-02-16T10:07:30+0200
jobid = be5805f5-2330-4033-a314-bde52e666da2
jobresulttype = object
jobresult = map[errorcode:534 errortext:Resource [Host:9] is unreachable: Host 9: Unable to prepare for migration due to Exception: com.cloud.utils.exception.CloudRuntimeException
Message: There are 0 VMs named i-2-11-VM
Stack: com.cloud.utils.exception.CloudRuntimeException: There are 0 VMs named i-2-11-VM
        at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.prepareISO(CitrixResourceBase.java:4157)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixPrepareForMigrationCommandWrapper.execute(CitrixPrepareForMigrationCommandWrapper.java:59)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixPrepareForMigrationCommandWrapper.execute(CitrixPrepareForMigrationCommandWrapper.java:36)
        at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixRequestWrapper.execute(CitrixRequestWrapper.java:122)
        at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.executeRequest(CitrixResourceBase.java:1757)
        at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
~~~

The corresponding management log during this cmk operation is attached too [cmk_vm_migr_mgmt_log.txt](https://github.com/apache/cloudstack/files/8078397/cmk_vm_migr_mgmt_log.txt)

PS.1 I also tried to specify on cmk both hostid and storageid but got the (expected): "Only one of hostId and storageId can be specified". Log available if desired.
P.2 If I stop the VM on Xen cluster, then I can start it on the XCP cluster as normal. This is easy for my test environment, but (almost) impossible in production :-)

**Comment by weizhouapache** [comment] 2022-02-16 10:53
@tsinik-dw 
Hi, is global setting `migrate.vm.across.clusters` set to `true` ?

**Comment by tsinik-dw** [comment] 2022-02-16 11:33
Hi @weizhouapache, 
Yes, the `migrate.vm.across.clusters` is set to `true`.

Just checked (for fun) the migration with this global setting to `false` and got the exact same error message  (:trollface:), if that is of any help.

**Comment by nvazquez** [comment] 2022-02-16 11:37
Thanks @tsinik-dw - can you please check the output of xe vm-list on the host 9 (xcp1.noc-dev.localdomain)? It seems like the VM is not found somehow

**Comment by tsinik-dw** [comment] 2022-02-16 12:05
Hi @nvazquez,

the thing is that host 9 is the destination host (the XCP). So the VM is not present there because the migration didn't took place.

Initially, the VM is on host 4 (XEN) , see xe vm-list on XEN:
~~~
[root@xen1 ~]# xe vm-list
uuid ( RO)           : ad62d6a1-aed9-a5dc-4c91-9cca448e2fd3
     name-label ( RW): s-22-VM
    power-state ( RO): running

uuid ( RO)           : c391332d-ea29-b6da-fce8-367c75606a5a
     name-label ( RW): i-2-11-VM
    power-state ( RO): running

uuid ( RO)           : 1cad5d03-b217-f99e-aba8-7e50f42e77fd
     name-label ( RW): v-23-VM
    power-state ( RO): running

uuid ( RO)           : db65d88e-8441-3a45-cc61-3210bae79cbc
     name-label ( RW): r-20-VM
    power-state ( RO): running

uuid ( RO)           : 5b6a6762-8845-41fe-9fc8-ba465f668f01
     name-label ( RW): Control domain on host: xen1
    power-state ( RO): running
~~~

the same command on host 9 (XCP) is
~~~
[13:53 xcp1 ~]# xe vm-list
uuid ( RO)           : 94091d89-92b8-4de6-8297-c9221a3d9d70
     name-label ( RW): Control domain on host: xcp1.noc-dev.localdomain
    power-state ( RO): running
~~~

I also attach the host details from DB, in CSV format [hosts.txt](https://github.com/apache/cloudstack/files/8079675/hosts.txt)

**Comment by nvazquez** [comment] 2022-02-16 14:13
Thanks @tsinik-dw, I've been investigating and it seems like the `migrateVirtualMachine` API does not support this type of migration and indeed the `migrateVirtualMachineWithVolume` API should be used.

Can you please try passing the `migrateto` parameter to the `migrateVirtualMachineWithVolume` API and send the management server logs?

````
migrate virtualmachinewithvolume virtualmachineid=<VM_UUID> hostid=<HOST_UUID> migrateto[0].volume=<VOLUME_UUID> migrateto[0].pool=<ZONEWIDE_POOL_UUID>
````
Reference: https://cloudstack.apache.org/api/apidocs-4.16/apis/migrateVirtualMachineWithVolume.html

**Comment by tsinik-dw** [comment] 2022-02-17 08:27
Hi @nvazquez, 

I've got good news!... I tried the command you proposed and the VM named MIGR-VM-SF-2 was successfully migrated from XEN to XCP with the following output on cmk:

~~~
(localcloud) 🐱 > migrate virtualmachinewithvolume virtualmachineid=28fb0eed-4277-4f2e-a179-38ed3051c723 hostid=73cd3fa4-01ce-4b55-970f-14efd0143aa1 migrateto[0].volume=291563e5-2ea0-4aaa-b14e-b747d48231cd migrateto[0].pool=2a30020a-76f9-4f47-89f1-a447739b934d
virtualmachine = map[account:admin affinitygroup:[] cpunumber:2 cpuspeed:1200 cpuused:3.68% created:2022-02-16T20:53:28+0200 details:map[hypervisortoolsversion:xenserver61 platform:vga:std;videoram:8;apic:true;viridian:false;device_id:0001;timeoffset:-1;pae:true;acpi:1;hpet:true;secureboot:false;nx:true rootdisksize:6] diskioread:0 diskiowrite:0 diskkbsread:2.2594307e+07 diskkbswrite:1.1737023e+07 diskofferingid:ed9e9144-c46a-4b33-a16d-6a16a32cbafa diskofferingname:VOL-on-SF-200 displayname:MIGR-VM-SF-2 displayvm:true domain:ROOT domainid:ce4fbcaf-8031-11ec-8660-4626a7ce6ce6 guestosid:1dcfb598-8032-11ec-8660-4626a7ce6ce6 haenable:false hasannotations:false hostid:73cd3fa4-01ce-4b55-970f-14efd0143aa1 hostname:xcp1.noc-dev.localdomain hypervisor:XenServer id:28fb0eed-4277-4f2e-a179-38ed3051c723 instancename:i-2-37-VM isdynamicallyscalable:false isodisplaytext:CentOS-7-x86_64-Minimal-2009 isoid:129a82d9-86cd-4323-a5af-f2f0767bb70e isoname:CentOS-7-x86_64-Minimal-2009 lastupdated:2022-02-16T22:20:34+0200 memory:2048 memoryintfreekbs:0 memorykbs:2.09714e+06 memorytargetkbs:2.097152e+06 name:MIGR-VM-SF-2 networkkbsread:0 networkkbswrite:0 nic:[map[broadcasturi:vlan://138 deviceid:0 extradhcpoption:[] gateway:10.1.1.1 id:08b1c5b0-3846-4aa8-a25f-2841254d7aed ipaddress:10.1.1.53 isdefault:true isolationuri:vlan://138 macaddress:02:00:1e:11:00:0d netmask:255.255.255.0 networkid:78a105a3-0e08-4077-89f5-fa929be5d833 networkname:xenserver-net-1 secondaryip:[] traffictype:Guest type:Isolated]] osdisplayname:CentOS 7 ostypeid:1dcfb598-8032-11ec-8660-4626a7ce6ce6 passwordenabled:false pooltype:Iscsi receivedbytes:0 rootdeviceid:0 rootdevicetype:ROOT securitygroup:[] sentbytes:0 serviceofferingid:e3a933aa-269e-4de7-9876-4b79dab6b885 serviceofferingname:SF-200 state:Running tags:[] templatedisplaytext:CentOS-7-x86_64-Minimal-2009 templateid:129a82d9-86cd-4323-a5af-f2f0767bb70e templatename:CentOS-7-x86_64-Minimal-2009 userid:48bd974a-8032-11ec-8660-4626a7ce6ce6 username:admin zoneid:7980e0b4-ebbd-425a-97d3-c09af5890cee zonename:ZONE1]
+
+
(localcloud) 🐱 > 
~~~

I attach the related management log [nv_interclust_vm_migr_sf_success.txt](https://github.com/apache/cloudstack/files/8086515/nv_interclust_vm_migr_sf_success.txt)

It is also **important** that I was able to migrate a VM with ROOT disk on managed storage (Solidfire) and a DATA disk on non-managed (NFS) storage by adding the appropriate entries in the command  for this extra disk!

The cmk output was :
~~~
(localcloud) 🐱 > migrate virtualmachinewithvolume virtualmachineid=28fb0eed-4277-4f2e-a179-38ed3051c723 hostid=73cd3fa4-01ce-4b55-970f-14efd0143aa1 migrateto[0].volume=291563e5-2ea0-4aaa-b14e-b747d48231cd  migrateto[0].pool=2a30020a-76f9-4f47-89f1-a447739b934d migrateto[1].volume=e64b3984-65e2-4786-8189-d654deda52ec migrateto[1].pool=bda4aa2b-d38b-341b-a968-98762ac528cf
virtualmachine = map[account:admin affinitygroup:[] cpunumber:2 cpuspeed:1200 cpuused:9.4% created:2022-02-16T20:53:28+0200 details:map[Message.ReservedCapacityFreed.Flag:false hypervisortoolsversion:xenserver61 platform:device-model:qemu-upstream-compat;vga:std;videoram:8;apic:true;viridian:false;device_id:0001;timeoffset:-1;pae:true;acpi:1;hpet:true;secureboot:false;nx:true rootdisksize:6] diskioread:0 diskiowrite:0 diskkbsread:3.0130144e+07 diskkbswrite:1.651675e+07 diskofferingid:ed9e9144-c46a-4b33-a16d-6a16a32cbafa diskofferingname:VOL-on-SF-200 displayname:MIGR-VM-SF-2 displayvm:true domain:ROOT domainid:ce4fbcaf-8031-11ec-8660-4626a7ce6ce6 guestosid:1dcfb598-8032-11ec-8660-4626a7ce6ce6 haenable:false hasannotations:false hostid:73cd3fa4-01ce-4b55-970f-14efd0143aa1 hostname:xcp1.noc-dev.localdomain hypervisor:XenServer id:28fb0eed-4277-4f2e-a179-38ed3051c723 instancename:i-2-37-VM isdynamicallyscalable:false lastupdated:2022-02-17T10:21:24+0200 memory:2048 memoryintfreekbs:1346 memorykbs:2.09714e+06 memorytargetkbs:668210 name:MIGR-VM-SF-2 networkkbsread:51031 networkkbswrite:51031 nic:[map[broadcasturi:vlan://138 deviceid:0 extradhcpoption:[] gateway:10.1.1.1 id:08b1c5b0-3846-4aa8-a25f-2841254d7aed ipaddress:10.1.1.53 isdefault:true isolationuri:vlan://138 macaddress:02:00:1e:11:00:0d netmask:255.255.255.0 networkid:78a105a3-0e08-4077-89f5-fa929be5d833 networkname:xenserver-net-1 secondaryip:[] traffictype:Guest type:Isolated]] osdisplayname:CentOS 7 ostypeid:1dcfb598-8032-11ec-8660-4626a7ce6ce6 passwordenabled:false pooltype:Iscsi receivedbytes:0 rootdeviceid:0 rootdevicetype:ROOT securitygroup:[] sentbytes:0 serviceofferingid:e3a933aa-269e-4de7-9876-4b79dab6b885 serviceofferingname:SF-200 state:Running tags:[] templatedisplaytext:CentOS-7-x86_64-Minimal-2009 templateid:129a82d9-86cd-4323-a5af-f2f0767bb70e templatename:CentOS-7-x86_64-Minimal-2009 userid:48bd974a-8032-11ec-8660-4626a7ce6ce6 username:admin zoneid:7980e0b4-ebbd-425a-97d3-c09af5890cee zonename:ZONE1]
~~~

Here is the management log for this second trial [nv_interclust_vm_migr_sf_nfs_success.txt](https://github.com/apache/cloudstack/files/8086805/nv_interclust_vm_migr_sf_nfs_success.txt)

**Comment by nvazquez** [comment] 2022-02-17 10:21
Great news @tsinik-dw! It is the UI missing the `migrateto` parameter in this case, can you please post a screenshot of the migrate dialog you get on the UI? From your logs shared earlier, I the findSuitableHostsForMigration information retrieved is:
````
2022-02-16 09:56:37,628 DEBUG [c.c.s.ManagementServerImpl] (qtp1603198149-21:ctx-69ab5152 ctx-32f4cdb3) (logid:c71a4e95) Hosts having capacity and suitable for migration: [Host {"id": "9", "name": "xcp1.noc-dev.localdomain", "uuid": "73cd3fa4-01ce-4b55-970f-14efd0143aa1", "type"="Routing"}] 
````

**Comment by shwstppr** [comment] 2022-02-17 10:59
@nvazquez @tsinik-dw on the `migrateto` parameter, support was added in https://github.com/apache/cloudstack/pull/5145 and should be available in 4.17.0

**Comment by nvazquez** [comment] 2022-02-17 11:17
Excellent, thanks @shwstppr - closing this issue

**Closed by nvazquez** 2022-02-17 11:17 UTC
Labels: component:XenServer, component:migration

**Comment by tsinik-dw** [comment] 2022-02-17 11:20
@nvazquez,

This is a screenshot of the migrate dialog on the UI (ACS 4.16.0)

![2022-02-17 13_14_36-Window](https://user-images.githubusercontent.com/87693561/154470819-90b4135c-0139-441e-81b8-ae05380489df.png)

...looking forward to see the https://github.com/apache/cloudstack/pull/5145 UI 😄 which is great!

**Comment by nvazquez** [comment] 2022-02-17 11:23
@tsinik-dw this PR is already merged and should be available on the nightly packages, if you can test it please let us know your results

**Comment by nvazquez** [comment] 2022-02-18 15:27
Excellent thanks @tsinik-dw!
