### ISSUE TITLE
Libvirt exception on live migrate

### ISSUE THREAD

**Issue by PeterS-gd** [apache/cloudstack#5717] opened 2021-11-24 20:03 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR, VM
~~~

##### CLOUDSTACK VERSION

~~~
4.15.2
~~~

##### CONFIGURATION

Advanced Networking

##### OS / ENVIRONMENT

Ubuntu 20.04, KVM hypervisor

##### SUMMARY

I am unable to live migrate any of my VMs.
This issue seems relevant (https://issues.apache.org/jira/browse/CLOUDSTACK-7743), but there is no solution listed.

Original email thread: https://lists.apache.org/thread/9yjz248tk0l7y8w4rvzp0r0s3bx8tv8z

##### STEPS TO REPRODUCE

~~~
Create a shared or isolated network and then try to migrate a VM instance from one host to another.

Interfaces and brctl output: https://gist.github.com/PeterS-gd/fc97d165ef46e4b9b4026f6450a9dd54
Host1 agent log (source of migration): https://gist.github.com/PeterS-gd/221ad3affeb77da0828323ca2c2ae119
Host2 agent log (destination of migration): https://gist.github.com/PeterS-gd/d250c240f63538a6bd541b7870dffe0d
Here are the agents' properties: https://gist.github.com/PeterS-gd/230c6e2b843901b71feb54c39270a4a8

Traffic labels:
Management: cloudbr1
Guest: cloudbr0
Public: cloudbr0
~~~

##### EXPECTED RESULTS

~~~
That the VM would live migrate
~~~

##### ACTUAL RESULTS

~~~
Exception during migrate: org.libvirt.LibvirtException: Cannot get interface MTU on 'brenp3s0f0-3128': No such device
~~~

**Comment by weizhouapache** [comment] 2021-11-29 11:51
I have discussed with @PeterS-gd 
the issue is caused by different dev name attached by cloudbr0 on hosts (enp3s0f0 on source host, enp3s0f1 on destination host but it also has enp3s0f0)
this is a very rare use case
it can be improved with low priority

**Comment by sureshanaparti** [comment] 2022-02-09 14:36
Hi @PeterS-gd Discussed with Wei, and this seems to be env specific issue. The migration doesn't succeed in this case as the destination host in the migration has the interface with the same interface name of source host on which guest network bridge is configured. Good that, you solved this by adding a bond between cloud bridge and physical interface. Created a doc PR here https://github.com/apache/cloudstack-documentation/pull/263 suggesting guest bridge configuration for live migration. cc @weizhouapache Can I close this ticket with this note?

**Comment by sureshanaparti** [comment] 2022-02-10 07:44
> Hi @PeterS-gd Discussed with Wei, and this seems to be env specific issue. The migration doesn't succeed in this case as the destination host in the migration has the interface with the same interface name of source host on which guest network bridge is configured. Good that, you solved this by adding a bond between cloud bridge and physical interface. Created a doc PR here [apache/cloudstack-documentation#263](https://github.com/apache/cloudstack-documentation/pull/263) suggesting guest bridge configuration for live migration. cc @weizhouapache Can I close this ticket with this note?

ping @PeterS-gd can you update on this please. thanks.

**Comment by weizhouapache** [comment] 2022-02-10 07:45
@sureshanaparti 
agree to close this ticket.

**Comment by DaanHoogland** [comment] 2022-02-10 08:14
closing on above remarks, @PeterS-gd please reopen or create a new ticket if it persists and you have new information.

**Closed by DaanHoogland** 2022-02-10 08:14 UTC
Labels: component:kvm

**Comment by PeterS-gd** [comment] 2022-02-10 13:06
Yes, it was not migrating because the interfaces were not named the same. When I created bonds on both hosts that had the same name over the interface, it worked and has continued to work since then. So, yes this problem has been solved and the ticket can be closed.

----------------------------------------
