### ISSUE TITLE
Switch instance to another compute/service offering

### ISSUE THREAD

**Issue by pbankonier** [apache/cloudstack#3332] opened 2019-05-16 12:47 UTC
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
Server
~~~~
##### CLOUDSTACK VERSION
~~~
Master
~~~
##### CONFIGURATION
~~~
N/A 
~~~
##### OS / ENVIRONMENT
~~~
We are using managed storage (Solidfire).
~~~

##### SUMMARY
Not possible to change a service offering for an instance to a newly created compute offering.
The problem are the changes in https://github.com/apache/cloudstack/pull/3133/files in the ConfigurationManagerImpl.java.
When issystem is passed as false and iscusstomizediops is null when you create a compute offering the values gets set to 0 instead of null.

##### STEPS TO REPRODUCE
~~~
Create a new compute offering.
Change the service offering of an instance to the newly created compute offering.
~~~
##### EXPECTED RESULTS
~~~
The values for minIops and maxIops are set to null and it is possible to change the
offering for the instance.
~~~
##### ACTUAL RESULTS
~~~
The values for minIops and maxIops are set to 0.
An error is thrown ("The minIOPS value must be between 50 and 15000").
~~~
![image](https://user-images.githubusercontent.com/5433844/58049398-09e1c500-7b4d-11e9-8648-863659d333c4.png)
![image](https://user-images.githubusercontent.com/5433844/58049317-d4d57280-7b4c-11e9-85e0-75255f97a720.png)
![image](https://user-images.githubusercontent.com/5433844/58049605-896f9400-7b4d-11e9-990c-1f03fb1039fb.png)

**Comment by nathanejohnson** [comment] 2019-05-16 16:52
I will take a look

**Comment by nathanejohnson** [comment] 2019-05-16 20:33
@pbankonier from looking at the code prior to this PR, it looks like this behavior predates it.  Are you using the UI or creating the service offering via API?

**Comment by svenvogel** [comment] 2019-05-16 21:23
@nathanejohnson we use the UI.

**Comment by pbankonier** [comment] 2019-05-20 15:01
@nathanejohnson The problem is from line 2371 in the ConfigurationManagerImpl.java. You changed the condition from 'isCustomizedIops != null' to 'Boolean.TRUE.equals(isCustomizedIops)' and removed the else case where minIops and maxIops gets set to null;
This changes the behavior in case isCustomizedIops is null. Now the minIops and maxIops values get set to 0 instead of null.

**Comment by nathanejohnson** [comment] 2019-05-20 18:50
@pbankonier the UI sends icsucomizediops=false every time it looks like.  if you look at the previous logic, it still sets miniops and maxiops to 0 in this case.

**Comment by nathanejohnson** [comment] 2019-05-20 18:51
@svenvogel if you use cloudmonkey to create the service offering and omit the iscusomizediops flag, I believe it should do what you want it to.

**Comment by svenvogel** [comment] 2019-05-20 20:10
@nathanejohnson we dont use really cloudmonkey. you mean logic was not changed?

@syed @mike-tutkowski can you take a look?

> @pbankonier the UI sends icsucomizediops=false or true every time it looks like. if you look at the previous logic, it still sets miniops and maxiops to 0 in this case. Which is what it still does. I agree that it probably shouldn't, but this is why I asked on the PR for someone more familiar with managed storage (@mike-tutkowski ) to weigh in.

@pbankonier what do you think? why it worked before?

**Comment by nathanejohnson** [comment] 2019-05-21 02:51
@svenvogel long-term we should make sure that this works from the UI.  in the short term, I believe a workaround for you might be to use cloudmonkey.  https://cwiki.apache.org/confluence/display/CLOUDSTACK/CloudStack+cloudmonkey+CLI

If you need help setting it up, please feel free to pop into the slack channel or the freenode irc channel.

**Comment by pbankonier** [comment] 2019-05-28 09:41
@nathanejohnson @svenvogel @DennisKonrad I close this issue since we resolved it in the PR.

**Comment by rhtyd** [comment] 2019-07-03 14:02
Looks like a backend regression, in the UI I see this:
![Screenshot from 2019-07-03 19-31-13](https://user-images.githubusercontent.com/95203/60597855-4e59b500-9dc9-11e9-880c-925932635c41.png)

@anuragaw since you may be working on outstanding UI issue can you have a look at this?

**Comment by anuragaw** [comment] 2019-07-03 15:49
Copy @rhtyd

**Comment by anuragaw** [comment] 2019-07-08 11:02
Starting work on this ticket.

**Comment by rhtyd** [comment] 2019-07-09 07:27
cc @shwstppr

**Comment by rhtyd** [comment] 2019-07-10 11:19
cc @shwstppr can you check this? Thanks.

**Comment by rhtyd** [comment] 2019-07-11 07:49
Looks like this is merged in https://github.com/apache/cloudstack/pull/3345

**Closed by rhtyd** 2019-07-11 07:49 UTC
Labels: component:UI, component:managed-storage, type:bug
