### ISSUE TITLE
systemvm/VR Volumes left in Destroy state after pool set to maintenance 

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#7196] opened 2023-02-11 07:29 UTC
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME

~~~
VR, SSVM, storage
~~~

##### CLOUDSTACK VERSION

~~~
4.18
~~~

##### CONFIGURATION

NFS storage, but could be others as well, discovered with KVM

##### SUMMARY

When a primary pool is set to prepare for maintenance and there are running system-vms and/or VRs  volumes on it, it fails to destroy the remaining volumes on storage, therefore pool not removable and volume still present.

They appear in Destroy state which does not go into Expunged. 
In my env I get 
```
mysql> select id,state,pool_id,removed,name,vm_id,vm_name from volume_view;
+----+----------+---------+---------------------+--------+-------+-----------------------------------------+
| id | state    | pool_id | removed             | name   | vm_id | vm_name                                 |
+----+----------+---------+---------------------+--------+-------+-----------------------------------------+
|  1 | Ready    |       2 | NULL                | ROOT-1 |     1 | s-1-VM                                  |
|  2 | Destroy  |       1 | NULL                | ROOT-2 |     2 | v-2-VM                                  |
|  3 | Expunged |       1 | 2023-02-11 07:00:24 | ROOT-3 |  NULL | NULL                                    |
|  4 | Destroy  |       1 | NULL                | ROOT-4 |     4 | r-4-VM                                  |
|  5 | Ready    |       2 | NULL                | ROOT-2 |     2 | v-2-VM                                  |
|  6 | Ready    |       2 | NULL                | ROOT-4 |     4 | r-4-VM                                  |
|  7 | Ready    |       2 | NULL                | ROOT-3 |     3 | VM-5b0a2d7b-ed32-4d33-b13e-ccc609210540 |
+----+----------+---------+---------------------+--------+-------+-----------------------------------------+
7 rows in set (0.00 sec)
``` 

and expunge delay and wait settings are both on 100, so I would've expected within 5 mins those to get Expunge, but they never do. 

Also in UI:

![Screenshot 2023-02-11 at 9 18 24](https://user-images.githubusercontent.com/13551960/218246218-8dbfd040-5c4a-471b-a8fe-954ee39ae6db.png)

##### STEPS TO REPRODUCE

~~~
Run 2 or more NFS pools
Create VR and systemvms on one of the pools
Set the pool to maintenance
Observe the systemvms and VR are migrated, but old volumes still present
~~~

##### EXPECTED RESULTS

~~~
Old volumes should be removed 
~~~

##### ACTUAL RESULTS

~~~
They are still there
~~~

##### Workaround: 

I guess the workaround is to manually check the leftover volumes are migrated successfully to other storage and if they systemvm/VR their VMs are running. Then I think it's safe to manually delete them on storage and set the state to 'Expunge' and removed  to now() with mysql.

**Comment by weizhouapache** [comment] 2023-02-11 08:40
Thanks Bobby @borisstoyanov 
Have you tested running user vms ?

**Comment by borisstoyanov** [comment] 2023-02-11 10:15
They don’t get migrated when you maintenance a pool. They get stopped.

**Comment by weizhouapache** [comment] 2023-02-13 09:16
Thanks Bobby @borisstoyanov 

I can reproduce the issue in 4.18. The volume should be expunged by background task.
it seems like a regression caused by #6868 

https://github.com/apache/cloudstack/pull/6868/files#diff-cf68e132ad7711cfa9250cda5819c09f51cba9933aa595cd82ad5a02b4edbe64R1331-R1338

```
                        if (Type.ROOT.equals(vol.getVolumeType())) {
                             VMInstanceVO vmInstanceVO = _vmInstanceDao.findById(vol.getInstanceId());
                             if (vmInstanceVO != null && vmInstanceVO.getState() == State.Destroyed) {
                                 s_logger.debug(String.format("ROOT volume [%s] will not be expunged because the VM is [%s], therefore this volume will be expunged with the VM"
                                         + " cleanup job.", vol.getUuid(), vmInstanceVO.getState()));
                                 continue;
                             }
                        }
```

I will look into it

**Comment by weizhouapache** [comment] 2023-02-13 09:39
@borisstoyanov 
after restarting mgmt server with new global settings, it seems to be working
![image](https://user-images.githubusercontent.com/57355700/218423176-f7e78826-295a-4048-914c-6ede0fd63544.png)

**Comment by weizhouapache** [comment] 2023-02-13 09:45
@borisstoyanov 
can you restart the mgmt server and wait a while to seem if volumes are Expunged ?

**Comment by harikrishna-patnala** [comment] 2023-03-15 06:11
@weizhouapache @borisstoyanov I've tested the scenario and it seems to be working as expected.

I've set the storage.cleanup.delay and storage.cleanup.interval to 100 seconds and the old volumes get expunged 

![image](https://user-images.githubusercontent.com/3348673/225221939-5e983190-e60f-44c9-8726-156385733727.png)

I think you have set expunge.delay and expunge.interval, but those wrt VMs

**Comment by weizhouapache** [comment] 2023-05-08 12:01
this cannot be reproduced, closing it

**Closed by weizhouapache** 2023-05-08 12:01 UTC
Labels: status:needs-reproducing
