### ISSUE TITLE
CloudStack doesn't respect rootDiskController in template settings

### ISSUE THREAD

**Issue by aleskxyz** [apache/cloudstack#5100] opened 2021-06-10 15:58 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
management
~~~

##### CLOUDSTACK VERSION

~~~
4.14.1
~~~

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

vCenter 6.5

##### SUMMARY

CloudStack tries to deploy VM from template by using osdefault as the value for rootdiskcontroller and doesn't respect rootDiskController in the template settings.

##### STEPS TO REPRODUCE

1. Create a template from root disk of a VM
2. Set the OS of the template to 'Other SUSE Linux(64-bit)'
3. Set rootDiskController of the template to pvscsi in settings tab
4. Create a VM from the template.

##### EXPECTED RESULTS

Create a new VM from the template with pvscsi disk controller

##### ACTUAL RESULTS

CloudStack cannot create the VM and raise this error in logs

~~~
2021-06-10 02:39:06,210 ERROR [c.c.h.v.m.ClusterMO] (DirectAgent-249:ctx-b8c83045 host01, job-15403/job-15409, cmd: StartCommand) (logid:249f18c6) Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster Cluster01
2021-06-10 02:39:06,211 INFO  [c.c.h.v.u.VmwareHelper] (DirectAgent-249:ctx-b8c83045 host01, job-15403/job-15409, cmd: StartCommand) (logid:249f18c6) [ignored]failed to get message for exception: Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster Cluster01
2021-06-10 02:39:06,211 WARN  [c.c.h.v.r.VmwareResource] (DirectAgent-249:ctx-b8c83045 host01, job-15403/job-15409, cmd: StartCommand) (logid:249f18c6) StartCommand failed due to Exception: com.cloud.utils.exception.CloudRuntimeException
Message: Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster Cluster01

com.cloud.utils.exception.CloudRuntimeException: Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster Cluster01
        at com.cloud.hypervisor.vmware.mo.ClusterMO.getRecommendedDiskController(ClusterMO.java:744)
        at com.cloud.hypervisor.vmware.mo.HostMO.getRecommendedDiskController(HostMO.java:1113)
        at com.cloud.hypervisor.vmware.mo.HypervisorHostHelper.createBlankVm(HypervisorHostHelper.java:1472)
        at com.cloud.hypervisor.vmware.mo.HostMO.createBlankVm(HostMO.java:798)
        at com.cloud.hypervisor.vmware.resource.VmwareResource.execute(VmwareResource.java:1884)
        at com.cloud.hypervisor.vmware.resource.VmwareResource.executeRequest(VmwareResource.java:530)
        at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:56)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:103)
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:53)
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
~~~

**Comment by andrijapanicsb** [comment] 2021-06-11 10:35
Hi @aleskxyz ,

can you share the screenshot of the Settings tab of your template you created?

While ACS code should not even check for the recommends controller of the OS when there is one explicitly supplied/defined (and I believe it does anyway...yeah, silly) - this seems that there is a bug during that specific action "Unable to retrieve recommended disk controller for guest OS : suse64Guest in cluster Cluster01" - even though it would, probably (based on my memory...) still try to define PVSCSI as the controller....

I've seen an issue myself when I had mixed clusters with ESXi 5.5 + 6.5 and choosing an OS type not recognised by ESXi 5.5 (older one)  - i.e. when I was choosing CentOS 7.2 as the OS type.

1. Can you please paste the screenshot of your Settings tab of the template you created
2. Can you please confirm you are not running a mixed cluster with an older hypervisor as well (probably not, but just to confirm)
3. Best shot - can you change your template OS type to CentOS 7.2 or 6.x and try to deploy VM again - and see what is the result

Reason being:
I can see here https://vdc-download.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html that "opensuse64Guest" (NOT your case) is supported since vSphere API 5.1, but for "suse64Guest" it doesn't say at all from which API version this is supported... - i.e. let's try with a different OS type like CentOS 7/6.

**Comment by aleskxyz** [comment] 2021-06-11 11:59
Hi @andrijapanicsb 

1. ![image](https://user-images.githubusercontent.com/39186039/121682166-bb802580-ca89-11eb-8435-68c2b308816c.png)
2. No it is not a mixed environment. I'm using ESXi 6.5
3. I can say the reason behind this behavior is unknown (or unsupported/deprecated in this case. When I try to choose the same os from web ui of vCenter I get a warning that this os type is not supported.) guest os type. When I use a well defined os type, CloudStack uses values from setting tab. For example in this case I resolve the problem by using "SUSE Linux Enterprise Server 12 (64-bit)" OS type which is mapped to "sles12_64Guest" in database.

**Comment by andrijapanicsb** [comment] 2021-06-11 12:16
Good, so VMware issue as it seems, right? If so, we can then close this case.

Thanks,

**Comment by aleskxyz** [comment] 2021-06-11 12:24
@andrijapanicsb 
Not exactly! I think CloudStack should not check for recommends controller of the OS when it is explicitly defined in template settings. If the OS type is unsupported, CloudStack should raise an appropriate error.

**Comment by andrijapanicsb** [comment] 2021-06-11 12:26
I agreed with that, but I can tell that even though this check is performed, if the specific model is set as a Setting of the template, it will get applied. 

Let's leave the issue open, for improvement, but I'm wondering if your specific use case would work even if it would NOT query the recommended controller type - as you said, you can't even deploy a VM with that guest OS in Center directly (if I got that correctly).

**Comment by aleskxyz** [comment] 2021-06-11 12:53
@andrijapanicsb 
At time of creating this issue I didn't find out the workaround so I thought that the CloudStack totally ignores the template settings.
But now I know that it will consider it if it can find the recommends controller of the OS from ESXi.
This should be vice versa at least.

**Comment by andrijapanicsb** [comment] 2021-06-11 12:55
no problem - the check is, indeed, senseless, since you have the setting.... so should be refractored to NOT do the check if there is an explicit setting in place.

**Comment by rhtyd** [comment] 2021-06-14 18:37
@nvazquez @harikrishna-patnala cc @Pearl1594 @shwstppr is this something known or already fixed?

**Comment by nvazquez** [comment] 2021-06-15 19:19
This is still not fixed for non-deploy-as-is templates, if the template OS is not found the deployment fails and if the OS descriptor is found then the template setting for root disk controller is ignored in favour of the recommended controller by Vmware - moving it for 4.16

**Comment by weizhouapache** [comment] 2021-07-30 07:04
@nvazquez 
I have created a pr for this issue, see #5258

**Comment by nvazquez** [comment] 2021-08-07 03:42
@aleskxyz the PR #5258 fixes the issue, however we've noticed the guest OS you have mentioned on the 'Steps to reproduce' is unsupported with VMware version 6.5. Even VM deployments fail with the error:

````
Message: The guest operating system 'suse64Guest' is not supported.
````

Were you able to create VMs from templates with that guest OS?

**Comment by aleskxyz** [comment] 2021-08-07 05:41
> @aleskxyz the PR #5258 fixes the issue, however we've noticed the guest OS you have mentioned on the 'Steps to reproduce' is unsupported with VMware version 6.5. Even VM deployments fail with the error:
> 
> ```
> Message: The guest operating system 'suse64Guest' is not supported.
> ```
> 
> Were you able to create VMs from templates with that guest OS?

@nvazquez 
The '' is not
It seems that 'suse64Guest' is a deprecated guest os type for vmware but is still exist in documents:
[vim.vm.GuestOsDescriptor.GuestOsIdentifier](https://code.vmware.com/apis/196/vsphere/doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html)
I could create a VM with that os type in vCenter 6.5 directly but I get a warning (not error) that this os type is not supported.

**Comment by nvazquez** [comment] 2021-08-10 04:55
@aleskxyz thanks, I have tried through CloudStack and couldn't deploy any VM selecting that guest OS. I think the original problem raised in this issue is handled by the PR, if needed please raise a new issue for the specific guest OS problem

**Comment by nvazquez** [comment] 2021-08-16 02:41
PR #5258 merged, closing this issue

**Closed by nvazquez** 2021-08-16 02:41 UTC
Labels: type:bug, component:vmware, component:templates
