### ISSUE TITLE
Record still left in snapshot_store_ref after primary storage has been removed causing 530 when listSanpshots is called

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack#7093] opened 2023-01-13 10:24 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
Storage

##### CLOUDSTACK VERSION
4.17.2 (maybe before as well)

##### OS / ENVIRONMENT
VMware 6.7.3

##### SUMMARY
When a primary storage is deleted, the corresponding record in the snapshot_store_ref table is not deleted
Noted specifically in VMware

##### STEPS TO REPRODUCE

- Take ROOT volume snapshot(This primary storage is Storage1.)
- Migrate ROOT volume to other storage(as Storage2) with the API - migrateVirtualMachine -
- Confirm the snapshot has two entries in cloud.snapshot_store_ref - one for primary and one for image.
- Then remove Storage1.
- Confirm that two entries remain in cloud.snapshot_store_ref.
- Do a listSnapshots API call against the snapshot and observe Error:(HTTP 530, error code 9999) - Due to an NPE in the DB record refering to the deleted storage pool

##### EXPECTED RESULTS

The record in the table pointing to the now deleted primary storage is still present

##### ACTUAL RESULTS

The DB record is deleted

Similar to https://github.com/apache/cloudstack/issues/3264

**Comment by weizhouapache** [comment] 2023-01-27 15:38
@davidjumani 
the issue with snapshot_store_ref might have been fixed by #6057

**Comment by weizhouapache** [comment] 2023-01-30 09:26
I am able to reproduce the issue in 4.15.2, but not in 4.17.2  it seems to be fixed by #6057 .

For those who have problem caused by the bug, please refer to what @andrijapanicsb said in https://github.com/apache/cloudstack/issues/3264#issuecomment-583536016

`DELETE FROM snapshot_store_ref  WHERE store_role="Primary" AND store_id IN (SELECT id FROM storage_pool WHERE removed IS NOT NULL);`

**Comment by DaanHoogland** [comment] 2023-02-20 10:26
@davidjumani , please verify #7205.

**Closed** 2023-02-21 13:48 UTC
Labels: status:needs-testing, component:storage
