### ISSUE TITLE
L2 Virtual Network - vNIC issues on Guests "Static IP disappears"

### ISSUE THREAD

**Issue by Ankit1999Raikwar** [apache/cloudstack#7457] opened 2023-04-24 08:52 UTC
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
* Networking
* Virtual Machine
~~~

##### CLOUDSTACK VERSION
~~~
 4.16.1.0
~~~

##### CONFIGURATION
~~~
Controller Nodes: 3
Compute Nodes: 4
Cloudstack Version: 4.16.1.0
Hypervisor: KVM
Network backend: VLAN
~~~

##### OS / ENVIRONMENT
~~~
 Ubuntu Server 20.04 LTS on both Management and Compute Hosts
~~~

##### SUMMARY
We are created the L2-Network nic  and attach that nic to the Vm then assign the static ip to the nic inside the vm . for the backup purpose  but when the VM got reboot or start/stop from the cloudstack . after that l2 nic is completely go into the disbale state and new nic comes up with the blank ip.

This affects Virtual Networks of type "L2". The vNIC from the L2 network "vNIC" actually gets replaced with a new one everytime the VM is stopped and started from the WebUI or API.

##### STEPS TO REPRODUCE
~~~
1. Create L2 network offering as per the infrastructure networking.
2. Create an L2 virtual network from that offering.
3. The L2 network will be successfully created.
4. Attach the L2 network to the Virtual Machine.
5. From inside the Virtual Machine, configure a Static IP for that NIC.
6. Stop the Virtual Machine from WebUI / API.
7. Start the Virtual Machine from WebUI / API.
8. The IP address configured on the VM's NIC is gone.
9. If we show "hidden devices", the NIC appears to be in "disabled" state with the IP address configured, but is in "disabled" state.
10. On Linux-based Virtual Machines, the new NIC appears.

This is affected the most when this L2 network is a non-default NIC of the Virtual Machine.
~~~

##### EXPECTED RESULTS

~~~
The Static IP address should be present even after reboots.

~~~

##### ACTUAL RESULTS
~~~
The older NIC disappears, but the new NIC comes online.
~~~

**Comment by weizhouapache** [comment] 2023-04-24 12:22
@Ankit1999Raikwar 
what's the OS distribution and version (vm)?

It seems to be related to udev
please remove /etc/udev/rules.d/70-persistent-net.rules and retry

**Comment by Ankit1999Raikwar** [comment] 2023-04-25 04:32
@weizhouapache Thanks for response .  we are using several different OS distribution,but the Windows operating system is most affected.

**Comment by weizhouapache** [comment] 2023-04-25 06:43
> @weizhouapache Thanks for response . we are using several different OS distribution,but the Windows operating system is most affected.

@Ankit1999Raikwar 
in case of Windows vm, is virtio-win installed in the vm ? What's the OS type of the vm (check it in the vm details page) ?

**Comment by Ankit1999Raikwar** [comment] 2023-04-25 11:12
@weizhouapache Yes, virtio drivers are installed. The OS type is "Windows PV".

**Comment by Ankit1999Raikwar** [comment] 2023-05-05 04:18
@weizhouapache  Yes, virtio drivers are installed. The OS type is "Windows PV".

**Comment by zap51** [comment] 2023-05-05 05:51
@weizhouapache It looks like I'm able to reproduce this behaviour.

**Comment by weizhouapache** [comment] 2023-05-05 07:42
@zap51 
do you also use windows vm with virtio drivers and same OS type ?

**Comment by zap51** [comment] 2023-05-07 13:10
> @zap51 do you also use windows vm with virtio drivers and same OS type ?

@weizhouapache Yes, I do. Have installed VirtIO stable drivers.

**Comment by zap51** [comment] 2023-07-23 03:51
@weizhouapache It affects linux-based distributions as well. Every time the VM is rebooted / stop & start from WebUI or API, the L2 NIC appears as a new device and hence the IP address configured is lost as the interface is no longer known to the kernel of the guest.

**Comment by weizhouapache** [comment] 2023-07-24 03:32
> @weizhouapache It affects linux-based distributions as well. Every time the VM is rebooted / stop & start from WebUI or API, the L2 NIC appears as a new device and hence the IP address configured is lost as the interface is no longer known to the kernel of the guest. It occurs only when the L2 NIC is attached as non-default one.

@zap51 
if vm is a linux machine, can you remove  /etc/udev/rules.d/70-persistent-net.rules and retry ?

**Comment by zap51** [comment] 2023-07-24 03:49
> > @weizhouapache It affects linux-based distributions as well. Every time the VM is rebooted / stop & start from WebUI or API, the L2 NIC appears as a new device and hence the IP address configured is lost as the interface is no longer known to the kernel of the guest. It occurs only when the L2 NIC is attached as non-default one.
> 
> @zap51 if vm is a linux machine, can you remove /etc/udev/rules.d/70-persistent-net.rules and retry ?

@weizhouapache Sure, will try and update here.

**Comment by weizhouapache** [comment] 2023-08-24 08:19
moved to 4.18.2.0

**Comment by DaanHoogland** [comment] 2023-09-22 08:21
Any update @zap51 ?

**Comment by zap51** [comment] 2023-10-08 07:01
Hi @DaanHoogland I'm sorry for the delay. I'll test this out this week and let you know.

**Comment by zap51** [comment] 2023-11-09 17:49
Hi @DaanHoogland, Unfortunately even under multiple attempts I'm unable to reproduce this issue. I'll keep you updated with my other test cases.

**Comment by weizhouapache** [comment] 2023-11-09 18:52
> Hi @DaanHoogland, Unfortunately even under multiple attempts I'm unable to reproduce this issue. I'll keep you updated with my other test cases.

maybe an issue with the template or guest OS ?

**Comment by zap51** [comment] 2023-11-10 16:05
> > Hi @DaanHoogland, Unfortunately even under multiple attempts I'm unable to reproduce this issue. I'll keep you updated with my other test cases.
> 
> maybe an issue with the template or guest OS ?

Could be, @weizhouapache. We can close this issue then.

Regards,
Jayanth Reddy

**Closed** 2023-11-10 16:26 UTC
Labels: type:bug, component:kvm, Severity:Major
