### ISSUE TITLE
VMs in "Error" state are not expunged from vSphere when deleted with Expunge from ACS

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#4290] opened 2020-08-27 16:23 UTC
Testing master (PR #4250) - and with vSphere 6.7, I've noticed that VMs which are in Error state (failed to deploy due to some internal logic failure - not Vsphere failure...):
- when the VM is deleted with Expunge option - the VM is NOT deleted on vSphere
- I've verified that if VM is Running/Stopped - then it get's properly deleted from vSphere.

So seems just the VMs which failed to be deployed, are not being properly deleted in vSphere.
I've also tested chaning from Error to Stopped - and that didn't make difference.

No exception in mgmt log.

**Comment by andrijapanicsb** [comment] 2020-08-27 22:45
Not strictly a blocker, but I wanted to draw some attention here, as the garbage is left on vSphere.
See the other garbage-related VMware issue here: https://github.com/apache/cloudstack/issues/4292

**Comment by rhtyd** [comment] 2020-08-28 07:07
With @Spaceman1984 to attempt

**Comment by rhtyd** [comment] 2020-08-28 07:07
@andrijapanicsb you can still draw attention by giving a lower severity like critical or major

**Comment by Spaceman1984** [comment] 2020-09-02 08:09
I was able to verify that the vm will be left on vmware if it fails to start due to a broken template. The vm status on cloudstack would be error. If you try to delete the vm from the cloudstack ui, it will be removed from cloudstack, but in vsphere the vm will remain. I have not created a fix for this as I can't spend more time on this right now.

**Comment by Spaceman1984** [comment] 2020-09-21 10:12
I am no longer able to get the Vms into an error state by passing garbage parameters on the reported branch, this issue seems to have been resolved.

**Comment by rhtyd** [comment] 2020-09-21 11:44
@andrijapanicsb can you test #4307 and if you're able to reproduce it, please ask @nvazquez / @harikrishna-patnala to fix this, tnx

**Comment by rhtyd** [comment] 2020-09-23 07:54
@andrijapanicsb I'm closing this as it's not reproducible

**Closed by rhtyd** 2020-09-23 07:54 UTC
Labels: Severity:Critical
