### ISSUE TITLE
Support setting boot parameter via template settings

### ISSUE THREAD

**Issue by Pearl1594** [apache/cloudstack#5913] opened 2022-01-31 12:42 UTC
##### ISSUE TYPE

 * Enhancement Request

##### COMPONENT NAME

~~~
template, VM
~~~

##### CLOUDSTACK VERSION

~~~
ACS 4.15.2
~~~

##### SUMMARY

When a template is configured with UEFI setting - UEFI=secure and a VM is deployed with the template, the boot parameters passed via the template settings does not take effect on the first boot. However, powering off the VM and restarting it, will bring up the instance using UEFI i.e., the template settings take effect

##### STEPS TO REPRODUCE

~~~
1. Register a template as deploy-as-is and specify UEFI=SECURE in the template settings
2. Deploy a VM using the above registered template - VM doesn't boot using uefi
3. Stop & start the VM - the boot parameters are considered

~~~

##### EXPECTED RESULTS

~~~
Consider template settings on the initial boot, or if not possible, prompt the user (by means of logs) that the specific setting wasn't considered
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment] 2022-01-31 13:00
@Pearl1594 this warrants a discussion on the functionality; if it is a deploy-as-is template, the contents of the template should be honoured. I.E. it should not be altered during initial instantiation. Altering it after that no longer has anything to do with the template and is ok, afaiac.
We should either forbid altering parameters on a deploy as is template or make very explicit what is going on (and maybe apply it immediately.
what you encountered is a strange situation but is as designed, i think.

**Comment by nvazquez** [comment] 2022-02-04 00:27
I agree with @DaanHoogland, however I think it is a bug as per design boot parameters should not be considered on deploy-as-is VMs IMO. @borisstoyanov @rohityadavcloud @andrijapanicsb what's your input on this?

**Comment by andrijapanicsb** [comment] 2022-02-04 07:25
with deployasis, everything should be honoured from the template, NOT from the template settings

**Comment by kricud** [comment] 2022-02-04 09:16
IMHO- template settings should be honored.
How I will explain to end users/customers that this template is for BIOS and this one is for UEFI and if you do not do correct selection, it will not boot.
I think it’s a bug that deployment wizard is not obeying settings from template.
If its not "Read VM settings from OVA" with this all settings should come from OVA.

Create #5932 same problem different description.

**Comment by kricud** [comment] 2022-02-04 09:30
@andrijapanicsb @DaanHoogland @nvazquez
Compromise could be that if deployment wizards see that template settings contain UEFI/SECURE it changes them to UEFI/SECURE, and if users changes them to BIOS deployment wizard assumes that he knows what he is doing and obeys.

**Comment by andrijapanicsb** [comment] 2022-02-04 09:43
@kricud you are wrong/missing the point:

when "read VM settings from OVA" is ticked/selected - than all the template details come from the OVF (OVA) file - and nothing can be set as template details in ACS (i.e. you can't chose OS type, disk controllers, nic controller, etc, and also can't chose bios vs uefi)

when "read VM setting from OVA" is NOT ticked/selcted - then yes, whatever is configured in ACS as the template properties, should apply.

This is how it is supposed to work, by design (i.e. supply template details from ACS vs supplying those via OVF/OVA)

**Comment by andrijapanicsb** [comment] 2022-02-04 09:45
But yes, after stopping VM, editing the VM settings (not the template settings), then some/all of those should apply (I know some do not apply, such as disk controller change, etc)

**Comment by nvazquez** [comment] 2022-02-04 10:14
Thanks @kricud @andrijapanicsb - so you are saying it is ok that CloudStack applies VM settings on stopped deploy-as-is VM? In this case, this is not a bug then?

**Comment by kricud** [comment] 2022-02-04 12:08
If it would be only for admins not users/customers it would be ok to instruct every admin 
and force him red manual from cover to cover and shame him if he hasn’t done that. 

Not in case of users/customers.

For windows I need two templates one for BIOS and one for UEFI/SECURE.
As BIOS is legacy (this can be argued lets assume that it is) we are dropping support for it.

We have templates only with UEFI/SECURE and maybe after 10 years 
all of ours VM will use UEFI/SECURE as no one will intentionally reinstall working BIOS VM to UEFI.

In its existing state it’s not possible to make seamless user-friendly experience 
when template is prepared for UEFI/SECURE it is deployed with it by default from first start.
No users intervention is needed.

And I don’t have ticket, from every new customer who doesn’t know that he must set UEFI/SECURE 
for this templet or it will not boot, in service desk system.

**Comment by kricud** [comment] 2022-02-04 12:38
@andrijapanicsb @nvazquez 
In case of deploy-as-is “Root disk controller” and “NIC adapter type” are set from template settings. 
Same can be done for BIOS, UEFI/SECURE
![image](https://user-images.githubusercontent.com/30048481/152530213-0da17767-5110-411c-8562-5d54a5536d56.png)

It hasn’t been communicated clearly - reason for this need of setting boot type is that 
Windows and also Linux for BIOS has one partitioning and for UEFI/SECURE another and they 
are not compatible, you cant switch between them seamlessly.

For BIOS:
Linux: /boot, /
Win: System Reserved, OS partition

For EFI:
Linux: /boot , /boot/efi
Win: EFI system Partition, OS partition, Recovery Partition
(why recovery partition now is at end is another topic)

**Comment by nvazquez** [comment] 2022-02-05 14:47
Sorry @kricud - when @andrijapanicsb and I mentioned 'deploy-as-is', we are meaning 'Read VM settings from OVA'. When you select this option, the CloudStack won't let you select any setting and will clone the OVA template without any modification to its controllers or boot type
In the image you shared the option is not selected, which allows to select controller as expected. Are you proposing to also allow to select the boot type in that UI wizard?

**Comment by kricud** [comment] 2022-02-05 15:47
Thant you @nvazquez for explain I have understood it incorrectly and base on that answered wrong also to @andrijapanicsb and @DaanHoogland

In #5932 I’m showing that if you add UEFI/SECURE to template settings it’s not working.

Adding this selection to template upload menu would make it admin friendly. 
Making it work from temple settings also would work and maybe with this it can be assigned to 4.16.1 - if its fast fix.

Now I also agree with you that ‘’deploy-as-is/Read VM settings from OVA’’ is working exactly as it should work 
and all settings must be taken from OVA.

@Pearl1594 There are many vendor OVA with custom settings for example from Juniper/PaloAlto/Aruba/Cisco that contain specific settings to run appliance and without ‘’deploy-as-is/Read VM settings from OVA’’ it would be close to impossible run them on ACS.

**Closed** 2022-02-17 02:44 UTC
Labels: type:enhancement, component:vmware
