### ISSUE TITLE
VM operation fail after storage drs in VMware datastore cluster

### ISSUE THREAD

**Issue by mib1185** [apache/cloudstack#5091] opened 2021-06-09 08:13 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VMware
~~~

##### CLOUDSTACK VERSION

~~~
4.15.1.0-rc
~~~

##### CONFIGURATION

- Hypervisor: VMware, 2x VMware 6.7.0 ESXi hosts
- datastore cluster:

|id|name|uuid|pool_type|port|data_center_id|pod_id|cluster_id|used_bytes|capacity_bytes|host_address|user_info|path|created|removed|update_time|status|storage_provider_name|scope|hypervisor|managed|capacity_iops|parent|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|59|iosctx01_1504_fp01_ns_0393|39c0a3b5-203c-3ee3-8703-4af20d640eac|PreSetup|0|1|1|3|4695523328|1099243192320|iosvvct1.esx-tst.os.itelligence.de|NULL|/DC_Salzenforst/iosctx01_1504_fp01_ns_0393|"2021-05-27 14:07:57"|NULL|"2021-06-09 07:10:18"|Up|DefaultPrimary|CLUSTER|NULL|0|NULL|63|
|63|DatastoreCluster_CS|9cd3cb24-a43a-338d-a61b-d7fb0abf3556|DatastoreCluster|0|1|1|3|626064883712|2198486384640|iosvvct1.esx-tst.os.itelligence.de|NULL|/DC_Salzenforst/DatastoreCluster_CS|"2021-06-08 15:51:05"|NULL|"2021-06-09 07:10:18"|Up|DefaultPrimary|CLUSTER|NULL|0|NULL|0|
|64|iosctx01_1504_fp01_ns_0394|b4f65ef4-8ee3-3776-a14a-d209c498204b|PreSetup|0|1|1|3|621369360384|1099243192320|iosvvct1.esx-tst.os.itelligence.de|NULL|/DC_Salzenforst/iosctx01_1504_fp01_ns_0394|"2021-06-08 15:51:05"|NULL|"2021-06-09 07:10:18"|Up|DefaultPrimary|CLUSTER|NULL|0|NULL|63|

##### SUMMARY

After storage DRS (_volumes were migrated to different datastore in same datastore cluster_) volume swere not found during next stop/start of vm (maybe related to #4674).

##### STEPS TO REPRODUCE

1. ingest VM online with only root volume and afterwards create new volume via CloudStack and attach to ingested vm
2. simulate storage DRS recommendation run (_migrate volumes to other datastore in same datastore-cluster on vCenter_)
3. stop instance
4. start instance

**volumes on DB after each step**

1.

|id|account_id|domain_id|pool_id|last_pool_id|instance_id|device_id|name|uuid|size|folder|path|pod_id|data_center_id|iscsi_name|host_ip|volume_type|pool_type|disk_offering_id|template_id|first_snapshot_backup_uuid|recreatable|created|attached|updated|removed|state|chain_info|update_count|disk_type|vm_snapshot_chain_size|iso_id|display_volume|format|min_iops|max_iops|hv_ss_reserve|provisioning_type|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|5329|10|2|64|NULL|1727|0|drs-test-02_2|42734603-a177-409b-92ac-ae15ca38d92a|10737418240|NULL|drs-test-02_2|NULL|1|NULL|NULL|ROOT|NULL|182|214|NULL|0|"2021-06-09 07:29:10"|NULL|NULL|NULL|Ready|"{"diskDeviceBusName":"scsi0:0","diskChain":["[iosctx01_1504_fp01_ns_0394] drs-test-02/drs-test-02_2.vmdk"]}"|0|NULL|NULL|214|1|OVA|NULL|NULL|NULL|fat|
|5330|10|2|64|55|1727|1|drs-test-02-data-01|265333cd-3676-4e2e-bf70-b42b5f8e1ee5|5368709120|/DC_Salzenforst/iosctx01_1504_fp01_ns_0394|drs-test-02|1|1|NULL|NULL|DATADISK|NULL|54|NULL|NULL|0|"2021-06-09 07:42:01"|"2021-06-09 07:42:15"|"2021-06-09 07:44:10"|NULL|Ready||6|NULL|NULL|NULL|1|OVA|NULL|NULL|0|fat|

2.

|id|account_id|domain_id|pool_id|last_pool_id|instance_id|device_id|name|uuid|size|folder|path|pod_id|data_center_id|iscsi_name|host_ip|volume_type|pool_type|disk_offering_id|template_id|first_snapshot_backup_uuid|recreatable|created|attached|updated|removed|state|chain_info|update_count|disk_type|vm_snapshot_chain_size|iso_id|display_volume|format|min_iops|max_iops|hv_ss_reserve|provisioning_type|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|5329|10|2|64|NULL|1727|0|drs-test-02_2|42734603-a177-409b-92ac-ae15ca38d92a|10737418240|NULL|drs-test-02_2|NULL|1|NULL|NULL|ROOT|NULL|182|214|NULL|0|"2021-06-09 07:29:10"|NULL|NULL|NULL|Ready|"{"diskDeviceBusName":"scsi0:0","diskChain":["[iosctx01_1504_fp01_ns_0394] drs-test-02/drs-test-02_2.vmdk"]}"|0|NULL|NULL|214|1|OVA|NULL|NULL|NULL|fat|
|5330|10|2|64|55|1727|1|drs-test-02-data-01|265333cd-3676-4e2e-bf70-b42b5f8e1ee5|5368709120|/DC_Salzenforst/iosctx01_1504_fp01_ns_0394|drs-test-02|1|1|NULL|NULL|DATADISK|NULL|54|NULL|NULL|0|"2021-06-09 07:42:01"|"2021-06-09 07:42:15"|"2021-06-09 07:44:10"|NULL|Ready||6|NULL|NULL|NULL|1|OVA|NULL|NULL|0|fat|

3.

|id|account_id|domain_id|pool_id|last_pool_id|instance_id|device_id|name|uuid|size|folder|path|pod_id|data_center_id|iscsi_name|host_ip|volume_type|pool_type|disk_offering_id|template_id|first_snapshot_backup_uuid|recreatable|created|attached|updated|removed|state|chain_info|update_count|disk_type|vm_snapshot_chain_size|iso_id|display_volume|format|min_iops|max_iops|hv_ss_reserve|provisioning_type|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|5329|10|2|64|NULL|1727|0|drs-test-02_2|42734603-a177-409b-92ac-ae15ca38d92a|10737418240|NULL|drs-test-02_2|NULL|1|NULL|NULL|ROOT|NULL|182|214|NULL|0|"2021-06-09 07:29:10"|NULL|NULL|NULL|Ready|"{"diskDeviceBusName":"scsi0:0","diskChain":["[iosctx01_1504_fp01_ns_0394] drs-test-02/drs-test-02_2.vmdk"]}"|0|NULL|NULL|214|1|OVA|NULL|NULL|NULL|fat|
|5330|10|2|64|55|1727|1|drs-test-02-data-01|265333cd-3676-4e2e-bf70-b42b5f8e1ee5|5368709120|/DC_Salzenforst/iosctx01_1504_fp01_ns_0394|drs-test-02|1|1|NULL|NULL|DATADISK|NULL|54|NULL|NULL|0|"2021-06-09 07:42:01"|"2021-06-09 07:42:15"|"2021-06-09 07:44:10"|NULL|Ready||6|NULL|NULL|NULL|1|OVA|NULL|NULL|0|fat|

4.

|id|account_id|domain_id|pool_id|last_pool_id|instance_id|device_id|name|uuid|size|folder|path|pod_id|data_center_id|iscsi_name|host_ip|volume_type|pool_type|disk_offering_id|template_id|first_snapshot_backup_uuid|recreatable|created|attached|updated|removed|state|chain_info|update_count|disk_type|vm_snapshot_chain_size|iso_id|display_volume|format|min_iops|max_iops|hv_ss_reserve|provisioning_type|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|5329|10|2|64|NULL|1727|0|drs-test-02_2|42734603-a177-409b-92ac-ae15ca38d92a|10737418240|NULL|drs-test-02_2|NULL|1|NULL|NULL|ROOT|NULL|182|214|NULL|0|"2021-06-09 07:29:10"|NULL|NULL|NULL|Ready|"{"diskDeviceBusName":"scsi0:0","diskChain":["[iosctx01_1504_fp01_ns_0394] drs-test-02/drs-test-02_2.vmdk"]}"|0|NULL|NULL|214|1|OVA|NULL|NULL|NULL|fat|
|5330|10|2|64|55|1727|1|drs-test-02-data-01|265333cd-3676-4e2e-bf70-b42b5f8e1ee5|5368709120|/DC_Salzenforst/iosctx01_1504_fp01_ns_0394|drs-test-02|1|1|NULL|NULL|DATADISK|NULL|54|NULL|NULL|0|"2021-06-09 07:42:01"|"2021-06-09 07:42:15"|"2021-06-09 07:44:10"|NULL|Ready||6|NULL|NULL|NULL|1|OVA|NULL|NULL|0|fat|

##### EXPECTED RESULTS

~~~
instance is booted properly without any errors
~~~

##### ACTUAL RESULTS

~~~
vm cannot be started, since volumes were not found anymore (_better say, were expected to be on its old location_)
~~~
![image](https://user-images.githubusercontent.com/35783820/121317300-7681b500-c90a-11eb-9532-72ab4a85c1a2.png)

**Comment by rhtyd** [comment] 2021-06-09 09:20
@mib1185 I could be wrong but generally it's not a good idea for storage DRS to be enabled as well as CloudStack (two sets of control planes doing operations). Did this use to work for you in older versions.
cc @harikrishna-patnala @nvazquez @sureshanaparti @andrijapanicsb @borisstoyanov @vladimirpetrov

**Comment by mib1185** [comment] 2021-06-09 09:42
@rhtyd storage DRS is one of the main reason, why to use datastore clusters, those this should work absolutely transparent to CloudStack. In addition - as I know - CloudStack does not control load balancing of data between datastores inside a datastore cluster 🤔 .
This could not work on older version, since support for datastore cluster was introduced with 4.15.

**Comment by harikrishna-patnala** [comment] 2021-06-09 09:52
@mib1185 may I know if this is happening only with ingested VMs or also on VMs deployed directly in CloudStack?

**Comment by mib1185** [comment] 2021-06-09 10:01
@harikrishna-patnala issue also ocurs with cloudstack deployed instances - tested like follows
- deploy new instance with only root volume
- create and attach new data volume to instance
- migrate new data volume into datastore-cluster, since it was created on another available primary storage
- perform storage DRS on vCenter
- stop instance
- start instance -> fails

**Comment by andrijapanicsb** [comment] 2021-06-09 10:12
@harikrishna-patnala I don't recall we ever supported "STORAGE DRS" vs the regular "DRS" (which just live migrates VMs)

@mib1185 can you test Storage DRS with other "regular" datastore type (i.e. NFS or iSCSI etc) - I'm not aware we support this, but I might be wrong.

cc @rhtyd ^^^

**Comment by mib1185** [comment] 2021-06-09 10:18
@andrijapanicsb I'm sorry, but we do not have iSCSI nor NFS datastores available on our test lab (_even not in our productive environment_). Nevertheless, I guess it is independent on used child-datastore-technology, since Storage DRS is part of datastore cluster logic on top of the child-datastores. Storage DRS is part of the newly integrated Datastore Cluster support.

**Comment by andrijapanicsb** [comment] 2021-06-09 10:38
@mib1185 NFS is so easy to add (on any Linux box, for testing purposes), but @harikrishna-patnala has just advised that this should work, if I read his reply correctly, so I will back up to my cave now and slowly disappear :)

**Comment by harikrishna-patnala** [comment] 2021-06-09 10:50
@mib1185 how did you simulate DRS on data volume ? I tried to move it manually on vCenter but failed with lock issues since it is attached to the VM
On the other hand, I tried these steps and it is successful to me.
1. Created a VM with only root disk
2. Attached a data disk to VM (data disk on another primary storage)
3. Migrated the data disk to Datastore cluster
4. Simulate storage DRS on data disk. I manipulated the chain_info and pool_id of the data disk in 'volumes' table.
5. Stop instance
6. Start instance => succeeded 

I also observed chain_info is missing in the "volumes" table entries that you posted.  Can you observe the chain_info column of the "volumes" table and let us know

**Comment by mib1185** [comment] 2021-06-09 11:06
Simulating storage DRS is very simples as you would only drag&drop the vm from one datastore to the other:

![image](https://user-images.githubusercontent.com/35783820/121342053-91abef00-c921-11eb-8493-0c728c6da25e.png)

There was no manipulating of any db entries done by us.

Yeah, I also noticed that `chain_info` is empty for data volume.
Meanwhile I observed, that `chain_info` got lost after migrating data volume to data store cluster (also `folder` and `path` is changed):

- "volumes" after additional data volumes is created (_on different primary storage_) and attached

|id|account_id|domain_id|pool_id|last_pool_id|instance_id|device_id|name|uuid|size|folder|path|pod_id|data_center_id|iscsi_name|host_ip|volume_type|pool_type|disk_offering_id|template_id|first_snapshot_backup_uuid|recreatable|created|attached|updated|removed|state|chain_info|update_count|disk_type|vm_snapshot_chain_size|iso_id|display_volume|format|min_iops|max_iops|hv_ss_reserve|provisioning_type|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|5333|10|2|59|NULL|1729|0|ROOT-1729|43e29773-d630-4a59-8a22-c5aa3fd92fe9|17179869184|NULL|ROOT-1729_2|NULL|1|NULL|NULL|ROOT|NULL|182|223|NULL|0|"2021-06-09 10:57:26"|NULL|"2021-06-09 10:57:54"|NULL|Ready|"{"diskDeviceBusName":"scsi0:0","diskChain":["[iosctx01_1504_fp01_ns_0393] i-10-1729-VM/ROOT-1729_2.vmdk"]}"|2|NULL|NULL|NULL|1|OVA|NULL|NULL|0|fat|
|5334|10|2|55|NULL|1729|1|drs-test-04-data-01|91b72972-2442-4abb-b921-47a1fdff848b|10737418240|NULL|c15a6e7da9374f3aad71804b16b7fafe|NULL|1|NULL|NULL|DATADISK|NULL|54|NULL|NULL|0|"2021-06-09 10:58:42"|"2021-06-09 10:59:05"|"2021-06-09 10:59:05"|NULL|Ready|"{"diskDeviceBusName":"scsi0:1","diskChain":["[iosctx01_1504_fp01_ns_0396] i-10-1729-VM/c15a6e7da9374f3aad71804b16b7fafe.vmdk"]}"|4|NULL|NULL|NULL|1|OVA|NULL|NULL|0|fat|

- "volumes" after additional data volumes is migrated to datastore cluster

|id|account_id|domain_id|pool_id|last_pool_id|instance_id|device_id|name|uuid|size|folder|path|pod_id|data_center_id|iscsi_name|host_ip|volume_type|pool_type|disk_offering_id|template_id|first_snapshot_backup_uuid|recreatable|created|attached|updated|removed|state|chain_info|update_count|disk_type|vm_snapshot_chain_size|iso_id|display_volume|format|min_iops|max_iops|hv_ss_reserve|provisioning_type|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|5333|10|2|59|NULL|1729|0|ROOT-1729|43e29773-d630-4a59-8a22-c5aa3fd92fe9|17179869184|NULL|ROOT-1729_2|NULL|1|NULL|NULL|ROOT|NULL|182|223|NULL|0|"2021-06-09 10:57:26"|NULL|"2021-06-09 10:57:54"|NULL|Ready|"{"diskDeviceBusName":"scsi0:0","diskChain":["[iosctx01_1504_fp01_ns_0393] i-10-1729-VM/ROOT-1729_2.vmdk"]}"|2|NULL|NULL|NULL|1|OVA|NULL|NULL|0|fat|
|5334|10|2|64|55|1729|1|drs-test-04-data-01|91b72972-2442-4abb-b921-47a1fdff848b|10737418240|/DC_Salzenforst/iosctx01_1504_fp01_ns_0394|i-10-1729-VM|1|1|NULL|NULL|DATADISK|NULL|54|NULL|NULL|0|"2021-06-09 10:58:42"|"2021-06-09 10:59:05"|"2021-06-09 11:00:17"|NULL|Ready||6|NULL|NULL|NULL|1|OVA|NULL|NULL|0|fat|

**Comment by harikrishna-patnala** [comment] 2021-06-09 11:19
I suspect the chain_info being empty is the reason for failure, can you please try this. Before applying storage DRS on the data disk, can you detach and attach the data disk to the VM to reflect the chain info and then apply storage DRS. That should work.

By the way, I tried the same, migrating the data disk from nfs primary storage to datastore cluster but chain_info is not empty in my case. I'll try it again.

**Comment by mib1185** [comment] 2021-06-09 11:34
Please find attached the log file from management server for migration job execution, where afterwardy `chain_info` got lost:
[MigrateVolumeCmdByAdmin.log](https://github.com/apache/cloudstack/files/6623401/MigrateVolumeCmdByAdmin.log)

**Comment by mib1185** [comment] 2021-06-09 11:42
> I suspect the chain_info being empty is the reason for failure, can you please try this. Before applying storage DRS on the data disk, can you detach and attach the data disk to the VM to reflect the chain info and then apply storage DRS. That should work.

You are right - after detach and attach the `chain_info` is filled and correct again 👍 
But honestly this should not be the solution 🙈

**Comment by rhtyd** [comment] 2021-06-09 11:55
Since this is an edge case for a new feature it shouldn't affect existing users and workloads, and a workaround has been found and tested by @mib1185 so it can't be classified as a blocker, I've however marked it as a critical issue. From one of the comments looks like the issue is not reproducible so I suggest @mib1185 @harikrishna-patnala work out the exact steps of reproduction (maybe @mib1185 try again with a new/fresh VM in your env?).

I'll cut RC2 early next week, however, note - since it's not a blocker I may rollover this to 4.15.2.0 if we don't have the issue reproduced/fixed. I'm happy to wait a couple of days if we can get a fix in, and tentatively moving the issue to 4.15.1.0 milestone. All PRs are welcome.

**Comment by mib1185** [comment] 2021-06-09 12:08
@rhtyd  +1 for "cut RC2 early next week"

Nevertheless, I have already tested with a fresh vm (see https://github.com/apache/cloudstack/issues/5091#issuecomment-857562021) with same negativ result ... additionally I have provided the DEBUG log of the migration job here https://github.com/apache/cloudstack/issues/5091#issuecomment-857619680 @harikrishna-patnala maybe you could have a look into this and check if there are any abnormalities.
For me it is always reproduceable when migrating an attached data-volume from any other datastore to the datastore-cluster, `chain_info` got lost.

**Comment by harikrishna-patnala** [comment] 2021-06-09 12:09
@mib1185 Thanks for confirming. As mentioned before I cannot reproduce the case of losing chain_info after migrating the data disk from NFS primary storage to a datastore cluster. I've tested on a fresh 4.15.1 setup with a new data disk created, attached to a VM deployed in CloudStack and migrated to datastore cluster.

Let me know if anything else we need to do to reproduce the issue @mib1185

**Comment by mib1185** [comment] 2021-06-09 12:14
@harikrishna-patnala Maybe lost `chain_info` data is related to line 32-33 in logfile from https://github.com/apache/cloudstack/issues/5091#issuecomment-857619680 🤔 

```
32: 2021-06-09 13:00:16,961 INFO  [c.c.h.v.m.DatastoreMO] (DirectAgent-337:ctx-a82378da iospemt1.esx-tst.os.itelligence.de, job-12867/job-12868, cmd: MigrateVolumeCommand) (logid:817ae709) Search file c15a6e7da9374f3aad71804b16b7fafe.vmdk on [iosctx01_1504_fp01_ns_0394] i-10-1729-VM
33: 2021-06-09 13:00:17,148 INFO  [c.c.h.v.m.DatastoreMO] (DirectAgent-337:ctx-a82378da iospemt1.esx-tst.os.itelligence.de, job-12867/job-12868, cmd: MigrateVolumeCommand) (logid:817ae709) File [iosctx01_1504_fp01_ns_0394] i-10-1729-VM/c15a6e7da9374f3aad71804b16b7fafe.vmdk does not exist on datastore
```

**Comment by rhtyd** [comment] 2021-06-09 12:19
@mib1185 just to re-confirm are you indeed testing packages from 4.15.1.0-RC1, from http://download.cloudstack.org/testing/4.15.1.0-RC1 ? What is your source datastore cluster (is it NFS, or something else)?
@harikrishna-patnala can you investigate code for possible cases which could lead to chain_info being set to null?

**Comment by harikrishna-patnala** [comment] 2021-06-09 12:20
No @mib1185 I also see these lines in my testing. In my case chainInfo is there in the volume response
79-37b2-83d7-cb872d359959","chaininfo":"{"diskDeviceBusName":"scsi0:0","diskChain":["[9480106731023fc0a1e342a76a2e7128] i-2-6-VM/i-2-6-VM_7.vmdk"]}","quiescevm":"false","clusterid":"6b1679e3-4c38-

But in your logs it is missing
a43a-338d-a61b-d7fb0abf3556","chaininfo":"","quiescevm":"false","clusterid":"ee84917e-73fa-4022-915a-5e

I'll check if there is any case like that from the code analysis.

**Comment by mib1185** [comment] 2021-06-09 12:29
@rhtyd we using our own fork based on aaac4b17099ba838a3f7b57400277ca9b23f98f5 (_4.15.1.0-rc1_) with some additional commits/backports - for details I need to ask our developer @DK101010 .

**Comment by rhtyd** [comment] 2021-06-09 12:32
I see @mib1185 can you try the RC1 pkgs instead just to confirm if it's a valid issue to be fixed or something that is caused by your fork? Without being able to reproduce the issue, or information on how to it would be not possible to fix it.

**Comment by mib1185** [comment] 2021-06-09 12:45
@rhtyd yeah I see, but need to check if we can go with the rc1 packages, since we are using "multiple host tags" (_backport of #4398_) on our test lab. Nevertheless I will ask @DK101010 to have also a look into this issue from developer point of view

**Comment by mib1185** [comment] 2021-06-09 13:03
UPDATE: `chain_info` got lost on every volume migration, it doesn't matter if from regular datastore to datastore-cluster, or between two regular datastores. Not sure if this is noteworthy, but we are using multiple Tags for our primary storages and therefore also in the used disk-offerings.

**Comment by mib1185** [comment] 2021-06-09 13:17
@harikrishna-patnala could you please try to reproduce it, but this time with Tags on primary storages and disk-offerings?

**Comment by harikrishna-patnala** [comment] 2021-06-10 04:33
@mib1185 may I know the datastore names and the chain_info you got after detach and attach workaround?

**Comment by harikrishna-patnala** [comment] 2021-06-10 05:46
I think I found the problem with how we handle migrate answer. I'm working on the fix.

**Comment by rhtyd** [comment] 2021-06-10 07:07
Great thanks for sharing @harikrishna-patnala

**Comment by harikrishna-patnala** [comment] 2021-06-10 12:08
Just to update PR#5097 is already raised to fix the issue

**Comment by rhtyd** [comment] 2021-06-11 14:36
Fixed in https://github.com/apache/cloudstack/pull/5097

**Closed by rhtyd** 2021-06-11 14:36 UTC
Labels: Severity:Critical, component:vmware
