### ISSUE TITLE
UI doesn't allow creating Guest Traffic on more than one Physical Network when existing Guest Traffic is not tagged.

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#8279] opened 2023-11-29 12:08 UTC
Somewhere in past (4.18.1 ?) there was a PR that introduced a requirement that when having Guest Traffic on more than 1 Physical network, at most 1 guest traffic can be untagged, while additional Guest Traffic needs to be tagged.

This is fine on its own, however, the UI was never updated to handle adding additional Guest Traffic (i.e. to allow passing the "tag" API parameter during the API call to create Guest Traffic)

Things to be fixed:

1. Zone creation wizard - if an operator is creating Guest Traffic on more than just 1 Physical network - we need to allow the operator to tag Guest Traffic types, to fulfil the tagging restriction/requirement that were introduced in 4.18.1 (or before) - so that Zone creation wizard completes

1. When adding additional Guest Traffic for an existing Zone (on another Physical network) - there is no field to allow passing the tag for that Guest Traffic, so it fails to create it (if the existing Guest Traffic doesn't have the tag already).

This should be considered a regression bug in the UI, as it used to work before for users who were creating Guest Traffic on more than a single Physical Network.

**Comment by weizhouapache** [comment] 2023-12-01 08:21
The issue is caused by #6781 in 4.18.0.0
the UI points out the error is caused by "There are more than 1 physical network without tags in the zone= 1".

since the issue has existed for around 1 year, I think we do not need to fix it, as the users can get the same by

- create traffic type Guest to 1 physical network
- tag the physical network
- create traffic type Guest to another physical network
- tag the new physical network (optional)

to replace the old configurations (1) create 2 physical neworks with Guest traffic type; (2) tag both physical networks

**Comment by vishesh92** [comment] 2024-02-08 06:51
@andrijapanicsb I have fixed the first part in #8625. 

I am not sure what exactly is the issue with the second part. I am able to add a new physical network. When I add guest traffic type it fails if there is already an existing untagged physical network. I can edit the physical network to add the tags to either of them to resolve the issue. Is the second part really an issue?

**Comment by andrijapanicsb** [comment] 2024-02-08 07:53
@vishesh92  Can you specify tags DURING the creation of the GUEST traffic?

**Comment by vishesh92** [comment] 2024-02-08 07:56
@andrijapanicsb This is the new UI for adding physical networks.
![image](https://github.com/apache/cloudstack/assets/8760112/3b3bbca7-d8c3-4fef-b7fd-50eccf8dc883)

**Comment by vishesh92** [comment] 2024-02-08 12:32
>     2. When adding additional Guest Traffic for an existing Zone (on another Physical network) - there is no field to allow passing the tag for that Guest Traffic, so it fails to create it (if the existing Guest Traffic doesn't have the tag already).
> 

Discussed separately with @andrijapanicsb and part 2 is already fixed.

**Comment by DaanHoogland** [comment] 2024-02-09 15:33
fixed in #8625

**Closed by DaanHoogland** 2024-02-09 15:33 UTC
