### ISSUE TITLE
If only domainid is passed VM gets deployed on root domain

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#3637] opened 2019-10-15 12:10 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.14
~~~

##### STEPS TO REPRODUCE

~~~
(localcloud) SBCM5> > deploy virtualmachine templateid=d79b8c85-4bb8-40d0-9306-c136b87c3e15 zoneid=7ae6a8d0-69d4-4005-b0b2-096b22c710fb serviceofferingid=2d1bade8-1d27-4ad3-aa12-2fad9de35174 domainid=1482160b-37f5-40dd-9fe5-9a085a8073f1
{
  "virtualmachine": {
    "account": "admin",
    "affinitygroup": [],
    "cpunumber": 1,
    "cpuspeed": 500,
    "created": "2019-10-15T11:53:06+0000",
    "details": {
      "cpuOvercommitRatio": "2.0",
      "dataDiskController": "osdefault",
      "memoryOvercommitRatio": "1.0",
      "rootDiskController": "ide"
    },
    "displayname": "VM-623275bb-d2a7-4b9a-b6fb-162187884291",
    "displayvm": true,
    "domain": "ROOT",
    "domainid": "1e9c626d-ef1f-11e9-ab49-1e007c01071d",
    "guestosid": "1f996ba5-ef1f-11e9-ab49-1e007c01071d",
~~~

##### EXPECTED RESULTS

~~~
The passed domain should be used when adding the VM
~~~

##### ACTUAL RESULTS

~~~
VM is added to root domain
~~~

**Comment by ustcweizhou** [comment] 2019-10-15 13:01
@borisstoyanov the owner/account is determined by domain and account name. if account name is not passed, the caller will be the owner. this sounds ok.

**Comment by rhtyd** [comment] 2020-08-12 09:01
This is not a bug, we cannot force a VM to be associated to a domain directly. We need to deploy to an account that belongs to a domain to force VMs deployed in a domain (i.e. owned by an account in that domain). Closing on this remark.

**Closed by rhtyd** 2020-08-12 09:01 UTC
