### ISSUE TITLE
CPU cores per socket setting not functional

### ISSUE THREAD

**Issue by DagSonsteboSB** [apache/cloudstack#2583] opened 2018-04-19 12:17 UTC
##### ISSUE TYPE
 * Bug Report
 * Enhancement Request

##### COMPONENT NAME
* Cores per socket setting in user_vm_details / vm_template_details table when using XenServer hypervisor

##### CLOUDSTACK VERSION
* CloudStack version 4.9.2
* Not attempted reproduced in other versions but assumption is issue is still present in 4.11.x

##### CONFIGURATION,  OS / ENVIRONMENT
* CloudStack 4.9.2
* XenServer 6.2 and 7.0 - fully licensed with Citrix licensing
* Advanced zone

##### SUMMARY
* Even with cpu.corespersocket (or cpuid.coresPerSocket as suggested in some mailing list threads) specified CloudStack will ignore this setting.
* All ACS specifications for cores and sockets will translate to "sockets" in XenServer
* Overall problem is some VMs when given a higher core count does not see all it's CPU cores/sockets.

##### STEPS TO REPRODUCE
* Create a VM with cpu count 4 cores
* Add entry for cpu.corespersocket=2 in user_vm_details
* Start VM
* Check allocation in XenCentre

##### EXPECTED RESULTS
* VM with 2 sockets and 2 cores per socket

##### ACTUAL RESULTS
* VM with 4 sockets

**Comment by rhtyd** [comment] 2018-05-01 14:45
Tentatively marked for 4.11.1.0 milestone, for testing this we'll require a pro version of XenServer. @DagSonsteboSB @PaulAngus do we have a test env to test a fix against?

**Comment by bdonnahue** [comment] 2018-10-19 16:41
@PaulAngus is this still an issue? With XCP-ng, is a XenServer Pro license still required? Could the default behavior be to specify cores rather than sockets?

**Comment by rhtyd** [comment] 2018-10-19 17:07
@bdonnahue we'll need to test this, if you've a XCP-ng setup, can you test?

**Comment by bdonnahue** [comment] 2018-10-19 17:40
@rhtyd I am happy to test but I want to clarify some things and ask some dumb questions. Are you on the slack channel?

**Comment by bdonnahue** [comment] 2018-10-28 17:06
@rhtyd any updates? Building cloudstack from source was more complicated that I thought. I have not been able to make any progress here

**Comment by rhtyd** [comment] 2018-10-29 06:39
Let's revisit this after 4.11.2.0 gets released. /cc @DagSonsteboSB @PaulAngus

**Comment by bdonnahue** [comment] 2018-10-29 18:58
Sounds good, is there a scheduled release date @rhtyd ?

**Comment by rhtyd** [comment] 2018-11-12 05:54
@bdonnahue there is no strict date however we were aiming for late-oct, mid-nov; but we have had blockers/bugs because of which we're at RC4.

**Comment by bdonnahue** [comment] 2018-11-14 20:35
@rhtyd ok. I will reach out again in a few weeks to see how things are going. Thanks for the help on this!

**Comment by andrijapanicsb** [comment] 2019-01-24 18:51
Still exists for 4.11.2 with XCP-NG 7.4 - parameter is ignored, and it's always 4 sockets.

**Comment by asender** [comment] 2019-02-17 23:28
Confirmed this issue with Xenserver 7 and Cloudstack 4.11.3

           nameLabel: Async.VM.start_on
     nameDescription:
   allowedOperations: []
   currentOperations: {}
             created: Mon Feb 18 10:11:51 AEDT 2019
            finished: Mon Feb 18 10:11:51 AEDT 2019
              status: failure
          residentOn: com.xensource.xenapi.Host@904b9a65
            progress: 1.0
                type: <none/>
              result:
           errorInfo: [INVALID_VALUE, platform:cores-per-socket, VCPUs_max must be a multiple of this field]
         otherConfig: {}
           subtaskOf: com.xensource.xenapi.Task@aaf13f6f
            subtasks: []

**Comment by ToonGeneral** [comment] 2019-02-28 19:20
We have this working with:
XS 6.5 and CS 4.8
XS 6.5 and CS 4.11

Given the OP said they had the issue with 6.2, I am wondering if you're just missing something?

To get it working:
- shutdown the VM
- delete the 'platform' row for this VM ID in user_vm_details
- create a cpu.corespersocket for this VM ID in user_vm_details
- boot the VM from CS
- the 'platform' row is rebuilt from XS
- cores will be whatever you set it to

Obviously it would be much nicer if CS just supported this, but it is possible to get it working.

**Comment by bdonnahue** [comment] 2019-03-15 01:24
Hey, thanks for sharing that info about the workaround while we wait for a better solution.

**Comment by mschaepers** [comment] 2019-03-20 01:18
> We have this working with:
> XS 6.5 and CS 4.8
> XS 6.5 and CS 4.11
> 
> Given the OP said they had the issue with 6.2, I am wondering if you're just missing something?
> 
> To get it working:
> 
> * shutdown the VM
> * delete the 'platform' row for this VM ID in user_vm_details
> * create a cpu.corespersocket for this VM ID in user_vm_details
> * boot the VM from CS
> * the 'platform' row is rebuilt from XS
> * cores will be whatever you set it to
> 
> Obviously it would be much nicer if CS just supported this, but it is possible to get it working.

Hi ToonGeneral,
can you share the commands in the database? I'm not sure if I'm doing the DB Update correct ;)

**Comment by mschaepers** [comment] 2019-03-20 02:02
> > We have this working with:
> > XS 6.5 and CS 4.8
> > XS 6.5 and CS 4.11
> > Given the OP said they had the issue with 6.2, I am wondering if you're just missing something?
> > To get it working:
> > 
> > * shutdown the VM
> > * delete the 'platform' row for this VM ID in user_vm_details
> > * create a cpu.corespersocket for this VM ID in user_vm_details
> > * boot the VM from CS
> > * the 'platform' row is rebuilt from XS
> > * cores will be whatever you set it to
> > 
> > Obviously it would be much nicer if CS just supported this, but it is possible to get it working.
> 
> Hi ToonGeneral,
> can you share the commands in the database? I'm not sure if I'm doing the DB Update correct ;)

ok, got it:
select * from user_vm_details where vm_id=<number-vm> \g
delete from user_vm_details where id=<id-of-platform>

set @vmuuid='66bec96f-4694-463e-a920-1d99ef29f23d';
set @vmcores='4'
insert into cloud.user_vm_details (vm_id,`name`, `value`) (select i.id,'cpu.coresPerSocket',@vmcores from cloud.vm_instance i where i.uuid=@vmuuid);

**Comment by mschaepers** [comment] 2019-03-21 23:56
okay, this seems not to survive a server restart (with shutdown). 
After powering on the server is keeps changing back to the original behaviour

**Comment by bdonnahue** [comment] 2019-03-23 20:17
Confirmed, it does not support reboots

**Comment by ToonGeneral** [comment] 2019-03-24 20:24
Not sure what you guys are doing, but it works fine for us. Survives a reboot through CS fine.

@mschaepers your SQL looks correct, except don't delete * from user_vm_details. You only need to delete the platform value. I don't know if that's what is causing your issue.

I can also confirm this is working using the new UI controls in 4.11. The VM needs to be off and you can then delete the platform entry and add cpu.corespersocket through the UI. Still works on reboot.

**Comment by mschaepers** [comment] 2019-03-24 21:26
My original post is missing in the second statement that I delete just platform

After modifying it I do see the new platform value with the correct cores.
But as soon as the machine gets turned off a new platform value (with new ID) get’s written back to SQL.

I will try to check if the results when adding it through the UI. Just wondering if something from the template gets inherited?

________________________________

Von: ToonGeneral <notifications@github.com>
Datum: 24. März 2019 um 21:22:24 MEZ
Bis: apache/cloudstack <cloudstack@noreply.github.com>
Cc: Mauricio Schäpers <m.schaepers@vsqloud.de>, Mention <mention@noreply.github.com>
Betreff: Re: [apache/cloudstack] CPU cores per socket setting not functional (#2583)


Not sure what you guys are doing, but it works fine for us. Survives a reboot through CS fine.

@mschaepers<https://github.com/mschaepers> your SQL looks correct, except don't delete * from user_vm_details. You only need to delete the platform value. I don't know if that's what is causing your issue.

I can also confirm this is working using the new UI controls in 4.11. The VM needs to be off and you can then delete the platform entry and add cpu.corespersocket through the UI. Still works on reboot.

**Comment by mschaepers** [comment] 2019-03-24 21:54
I’m using a fork of Cloudstack.
Just to be sure that we are taking about the same, which UI controls you are talking about exactly? Can you share a screenshot?

________________________________

Von: ToonGeneral <notifications@github.com>
Datum: 24. März 2019 um 21:22:24 MEZ
Bis: apache/cloudstack <cloudstack@noreply.github.com>
Cc: Mauricio Schäpers <m.schaepers@vsqloud.de>, Mention <mention@noreply.github.com>
Betreff: Re: [apache/cloudstack] CPU cores per socket setting not functional (#2583)


Not sure what you guys are doing, but it works fine for us. Survives a reboot through CS fine.

@mschaepers<https://github.com/mschaepers> your SQL looks correct, except don't delete * from user_vm_details. You only need to delete the platform value. I don't know if that's what is causing your issue.

I can also confirm this is working using the new UI controls in 4.11. The VM needs to be off and you can then delete the platform entry and add cpu.corespersocket through the UI. Still works on reboot.

**Comment by ToonGeneral** [comment] 2019-03-24 23:36
sorry @mschaepers just don't get the same symptoms. We reboot instances all the time and they don't lose the setting.

CS 4.11 interface:
![image](https://user-images.githubusercontent.com/2943991/54887658-8fb6fc00-4e8d-11e9-99f4-a7b46220bb92.png)

**Comment by ToonGeneral** [comment] 2019-03-24 23:36
You need to stop the instance, for the Settings tab to appear.

**Comment by mschaepers** [comment] 2019-03-25 07:48
@ToonGeneral thanks, never noticed the setting menu!
![image](https://user-images.githubusercontent.com/22095221/54902053-8f901e00-4ed8-11e9-9e1c-9b5c67849a76.png)

as you can see, this is the "new" platform value which get's written back after shutdown (even if the instance was running with the correct settings, in my case 4 cores per socket).
one difference I'm spotting is that we utilize custom service offerings.

@bdonnahue you're seeing the same behaviour. Are you utilizing custom service offerings as well?

However, I will forward this here to your professional support and will keep you updated about the solution.

**Comment by progiss** [comment] 2019-12-04 09:04
Hello,
We have the same problem with version 4.13 and KVM hypervisors.
How can we solve this problem because we are trying to create offering services with 45 cores and it affects only 2 cores

**Comment by DaanHoogland** [comment] 2020-11-25 08:10
there is a PR out for 4.14 that fixes this for KVM: #4497

**Comment by AlexanderKgr** [comment] 2021-05-28 07:43
this is still happening with 4.15.0 and xcp-ng

**Comment by DaanHoogland** [comment] 2021-07-20 09:46
@AlexanderKgr can you please check if this is still an issue on a recent 4.15 or on main and close if appropriate?

**Comment by rhtyd** [comment] 2021-08-09 09:19
A PR claiming to fix this issue https://github.com/apache/cloudstack/pull/4497 has been merged.
@AlexanderKgr @DagSonsteboSB please test 4.15.1/4.14.1 and re-open this if not satisfied, thanks.

**Closed by rhtyd** 2021-08-09 09:19 UTC
Labels: component:XenServer, component:compute, age:2years_plus
