### ISSUE TITLE
ConfigDrive and all other Supported Services not available in the UI when L2 network is chosen

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#3169] opened 2019-02-06 16:53 UTC
##### ISSUE TYPE

 * Bug Report
 

##### COMPONENT NAME
UI
~~~

~~~

##### CLOUDSTACK VERSION
4.11.2 

~~~

~~~

##### CONFIGURATION
Advanced networking

##### OS / ENVIRONMENT
CentOS 7 / KVM

##### SUMMARY
Trying to add a Network offering in the UI of the type L2 results in the disappearance of Supported Services section. In this particular case I wanted to check the "ConfigDrive" option.

##### STEPS TO REPRODUCE
Try to add a new network offering, choose L2 type.. the Supported Services section disappears.

![selection_044](https://user-images.githubusercontent.com/2357012/52358292-a3b6b380-2a2f-11e9-8043-3ffcace477b6.png)

**Comment by rhtyd** [comment] 2019-02-06 16:55
@borisstoyanov @nvazquez @dhlakukucan you comment if we had fixed that already?

**Comment by borisstoyanov** [comment] 2019-02-07 08:16
I don't think so @rhtyd

**Comment by rhtyd** [comment] 2019-03-26 07:57
I think we have that option in UI on latest master, will check and fix if necessary. (possibly also on latest 4.11 branch)

**Comment by PaulAngus** [comment] 2019-05-23 19:51
Looks ok in master

![image](https://user-images.githubusercontent.com/4810220/58281731-bb763580-7d9b-11e9-9082-6194d4ba0e81.png)

**Comment by rhtyd** [comment] 2019-06-26 02:47
When L2 is selected, other services shouldn't be shown. For config drive, select the user data option. 

Closing as it's not a bug on master.

**Closed by rhtyd** 2019-06-26 02:47 UTC
