### ISSUE TITLE
data-server breaks VM root password in multi-subnet flat network

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack#4943] opened 2021-04-22 08:20 UTC
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
VM password (for cloud-init)
~~~

##### CLOUDSTACK VERSION

~~~
4.15
~~~

##### CONFIGURATION

Basiz zone with multiple subnets/CIDR

##### OS / ENVIRONMENT

VMware 6.5 (limited access to environment, not "mine")

##### SUMMARY

The VM password feature of cloud-init Cloudstack datasource attempts retrieval of the password from "data-server" host if it resolves. 
What happens in a multi-CIDR basic zone is that the passwords for the VMs are stored in separate files, according to their subnet, eg:
/var/cache/cloud/passwords-subnet1IP
/var/cache/cloud/passwords-subnet2IP and so on
The problem arises when Cloudstack adds the "data-server" hostname in /etc/hosts for dnsmasq to pick up, but because it adds it with subnet1IP, then requests for a password from a machine in subnet2 or subnet3 will go unanswered.

The Cloudstack datasource does not handle this gracefully, it just fails setting a password instead of detecting there was no valid response and try to also ask the "dhcp_identifier" host.

I suggest as a quick workaround to add a button somewhere to disable the data-server feature altogether. It seems to be Cloudstack specific, grepping for it in other data sources yielded nothing. 

On the VMs right now we have to add "0.0.0.0 data-server" in /etc/hosts to make the root password work. I guess editing the /etc/hosts on the VR and remove the data-server entry might also work, until the next restart.

##### STEPS TO REPRODUCE

~~~
Deploy basic or adv+SG zone with multiple CIDRs, 
when asking for a password from a VM not in the primary CIDR this will fail, password will not be set.
~~~

##### EXPECTED RESULTS

~~~
data-server hostname should return a valid password regardless of which CIDR the request comes from.
~~~

##### ACTUAL RESULTS

~~~
Valid password not served.
~~~

**Comment by rhtyd** [comment] 2021-04-22 08:55
@NuxRo Basic zone with SG is not supported with VMware as you cannot implement host-based firewall (security groups). Only flat basic zone without SG is feasible with Vmware. Can you check with your user's env?

**Comment by rhtyd** [comment] 2021-04-22 08:56
... meanwhile we'll see if we can replicate the issue with just basic zone (without SG) + vmware (and shared network + VMware on adv zone).

**Comment by NuxRo** [comment] 2021-04-22 09:14
That is indeed true, sorry to mislead you, this is a flat network indeed, but the problems remains regardless.
I'll update the issue.

**Comment by Spaceman1984** [comment] 2021-04-30 08:37
Hi @NuxRo, how do you go about creating multiple CIDRs? I'm not sure I understand what you mean.

**Comment by ccycv** [comment] 2021-04-30 09:14
> Hi @NuxRo, how do you go about creating multiple CIDRs? I'm not sure I understand what you mean.

Please check this, it is a bug, in 4.15 you can add only via API (or through old UI) : https://github.com/apache/cloudstack/issues/4697

**Comment by Spaceman1984** [comment] 2021-05-04 05:21
@ccycv I added a new guest IP range using the UI, but I was not able to create any instances that use the IP range. I checked the DB and saw that the 2 IP ranges use different vlan_db_ids - So when the first range was exhausted, I expected the second range to be used, but instead, I got the insufficient capacity error - This is possibly a bug. I tried to reproduce this error on a basic network without success - meaning - I can't create an instance on a different IP range so I can't test the described scenario, I will try an advanced network next.
![Guest network](https://user-images.githubusercontent.com/49917670/116963301-c97fa100-aca8-11eb-9216-73d5bc1bb356.png)

@NuxRo just to be sure, is this what you meant with multiple CIDRs?

**Comment by rhtyd** [comment] 2021-05-06 10:50
@Spaceman1984 I think all we want is a data-server to be resolvable for all sub-nets for cloud-init to work? Can you try this:
- Create a shared network (in adv zone) with some range
- Go to zone -> network -> guest network -> select shared network -> select IP -> add Range
In legacy UI it looks like this:

![Screenshot from 2021-05-06 16-18-56](https://user-images.githubusercontent.com/95203/117286505-e8d42500-ae86-11eb-815b-1367bd85655c.png)

As an example, I created shared network with 172.20.0.0/16 and then later added a 10.1.1.1/16 cidr.

Then, test if you can use something like cloud-init or manually verify that `data-server` work for VMs on either CIDRs.

**Comment by rhtyd** [comment] 2021-05-06 10:51
cc @NuxRo @weizhouapache - any other suggestion/pointers for Darrin?

**Comment by weizhouapache** [comment] 2021-05-06 12:15
@rhtyd this use case is rare I think.
I will have a look

**Comment by weizhouapache** [comment] 2021-05-06 16:21
@NuxRo @Spaceman1984 
does dhcp work in your testing ?

**Comment by ccycv** [comment] 2021-05-07 05:52
> @NuxRo @Spaceman1984
> does dhcp work in your testing ?

Yes, the IP is allocated on the VM.

**Comment by ccycv** [comment] 2021-05-07 05:55
> cc @NuxRo @weizhouapache - any other suggestion/pointers for Darrin?

I work with @NuxRo on this, try to replicate in cloudstack with basic network (multiple CIDR), not in an advanced network with shared and multiple CIRD.

**Comment by weizhouapache** [comment] 2021-05-10 07:11
@NuxRo @ccycv @Spaceman1984 
I can confirm that there are 3 bugs related to this issue.
(1) UI: Cannot deploy vm with specified IP in additional IP range. However, cloudmonkey/cmk works.
(2) DHCP does not work, if there are free IPs in the first IP range.
(3) password and userdata do not work (even if 2 works).

@rhtyd I will work on this.

**Comment by Spaceman1984** [comment] 2021-05-10 09:03
@weizhouapache I'll let you proceed and unassign myself

**Comment by rhtyd** [comment] 2021-05-13 09:02
Fixed in https://github.com/apache/cloudstack/pull/5013

**Closed by rhtyd** 2021-05-13 09:02 UTC

**Comment by ccycv** [comment] 2021-07-31 09:41
I just tested this in 4.15.1 Looks like the issue with "data-server" is persisting.
