### ISSUE TITLE
volume db update is incorrect

### ISSUE THREAD

**Issue by div8cn** [apache/cloudstack#5461] opened 2021-09-17 01:45 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VOLUME
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
4.15.0.1
~~~

##### SUMMARY

This is the VOLUME state definition

Expunging("The volume is being expunging"),
Expunged("The volume has been expunged"),
Destroy("The volume is destroyed, and can't be recovered."),
Destroying("The volume is destroying, and can't be recovered."),

After online reinstall vm, volume has two data in DB, the first one becomes Expunged;
Its status should be "Destroy", right?

`MariaDB [cloud]> select id,pool_id,instance_id,name,uuid,state,removed from volumes where name='ROOT-56';`
`+-----+---------+-------------+---------+--------------------------------------+----------+---------------------+`
`| id  | pool_id | instance_id | name    | uuid                                 | state    | removed             |`
`+-----+---------+-------------+---------+--------------------------------------+----------+---------------------+`
`| 216 |       3 |        NULL | ROOT-56 | 60df5680-23dd-422b-bf7d-d6db2eaa66a0 | Expunged | 2021-09-17 01:13:21 |`
`| 219 |       3 |          56 | ROOT-56 | e28b34c3-7377-4c36-8729-a6715c97e2e1 | Ready    | NULL                |`
`+-----+---------+-------------+---------+--------------------------------------+----------+---------------------+`
`2 rows in set (0.001 sec)`

The following is the change process of this VOLUME event

![image](https://user-images.githubusercontent.com/35140268/133710496-3a3df7b2-b83a-46c0-9418-92cc5d6dcc6a.png)

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by div8cn** [comment] 2021-09-17 01:52
At the same time, I found that VOLUME has two states in the DB after being deleted

1. removed!=null, state=Expunged, pool_id !=null
2. removed!=null, state=Destroy, pool_id=null

![image](https://user-images.githubusercontent.com/35140268/133711079-92e3093f-1ba7-4ca3-863c-a500d5e35870.png)

**Comment by DaanHoogland** [comment] 2021-09-17 08:56
I don;t think there is a problem, even when there is more states signifying the same condition. Expunged means it is gone and can't be recovered. the statemachine could do with a cleanup but isn't broken.

**Comment by slavkap** [comment] 2021-11-27 06:23
@DaanHoogland, I think it's a bug. After reinstalling a VM, CS creates new volumes, and the old ones in DB are marked as destroyed but still exist on the hypervisor side. I've tested this on 4.16 (I think it's the same on 4.15), hypervisor KVM.

> mysql> SELECT uuid,instance_id, state, pool_id FROM cloud.volumes where name="ROOT-6531";
+--------------------------------------+-------------+---------+---------+
| uuid                                 | instance_id | state   | pool_id |
+--------------------------------------+-------------+---------+---------+
| 156e1612-ff54-4d77-a29e-87cea3303fc4 |        NULL | Destroy |     117 |
| 0af8094b-9766-4f42-8e08-9e2013980cc6 |        NULL | Destroy |     117 |
| 02e9022d-aaa3-4b73-8fc2-d0a64051499d |        NULL | Destroy |     117 |
| f8cfb72b-d879-4831-b99f-9fcd8d473238 |        6531 | Ready   |     117 |
+--------------------------------------+-------------+---------+---------+
4 rows in set (0.01 sec)


> -rw-r--r--    1 root root  22M Nov 27 07:29 156e1612-ff54-4d77-a29e-87cea3303fc4
-rw-r--r--    1 root root  23M Nov 27 07:41 0af8094b-9766-4f42-8e08-9e2013980cc6
-rw-r--r--    1 root root  23M Nov 27 08:04 02e9022d-aaa3-4b73-8fc2-d0a64051499d
-rw-r--r--    1 root root  19M Nov 27 08:20 f8cfb72b-d879-4831-b99f-9fcd8d473238

**Comment by weizhouapache** [comment] 2022-01-06 08:28
> @DaanHoogland, I think it's a bug. After reinstalling a VM, CS creates new volumes, and the old ones in DB are marked as destroyed but still exist on the hypervisor side. I've tested this on 4.16 (I think it's the same on 4.15), hypervisor KVM.
> 
> > mysql> SELECT uuid,instance_id, state, pool_id FROM cloud.volumes where name="ROOT-6531";
> > +--------------------------------------+-------------+---------+---------+
> > | uuid                                 | instance_id | state   | pool_id |
> > +--------------------------------------+-------------+---------+---------+
> > | 156e1612-ff54-4d77-a29e-87cea3303fc4 |        NULL | Destroy |     117 |
> > | 0af8094b-9766-4f42-8e08-9e2013980cc6 |        NULL | Destroy |     117 |
> > | 02e9022d-aaa3-4b73-8fc2-d0a64051499d |        NULL | Destroy |     117 |
> > | f8cfb72b-d879-4831-b99f-9fcd8d473238 |        6531 | Ready   |     117 |
> > +--------------------------------------+-------------+---------+---------+
> > 4 rows in set (0.01 sec)
> 
> > -rw-r--r--    1 root root  22M Nov 27 07:29 156e1612-ff54-4d77-a29e-87cea3303fc4
> > -rw-r--r--    1 root root  23M Nov 27 07:41 0af8094b-9766-4f42-8e08-9e2013980cc6
> > -rw-r--r--    1 root root  23M Nov 27 08:04 02e9022d-aaa3-4b73-8fc2-d0a64051499d
> > -rw-r--r--    1 root root  19M Nov 27 08:20 f8cfb72b-d879-4831-b99f-9fcd8d473238

@slavkap 
I think this is not a bug.

when reinstall a vm, the old root disk is changed to 'Destroy' state. 
you can recover to a Ready volume, and use it like other volumes.
Otherwise, the 'Destroy' volume will be cleaned up by cloudstack after a period (depends on global setting `storage.cleanup.interval` and `storage.cleanup.delay`)

**Comment by sureshanaparti** [comment] 2022-01-06 08:43
Hi @slavkap I think, as @weizhouapache confirmed, this seems to be the expected behavior. The ROOT volume in 'Destroy' state (with instance_id null) after reinstalling VM, can be either manually expunged or auto cleaned by storage GC. Please re-check and confirm whether this behavior is Ok or if you notice any issues there. Thanks.

**Comment by slavkap** [comment] 2022-01-06 08:43
You're right @weizhouapache, it's not a bug. I forgot to check the global settings.

**Comment by slavkap** [comment] 2022-01-06 08:46
@sureshanaparti, there isn't an issue. I've set a short interval on `storage.cleanup` settings, and the volumes were deleted

**Comment by sureshanaparti** [comment] 2022-01-06 08:56
> @sureshanaparti, there isn't an issue. I've set a short interval on `storage.cleanup` settings, and the volumes were deleted

good, thanks for confirming @slavkap

**Comment by sureshanaparti** [comment] 2022-01-06 09:00
@weizhouapache Do we need to change the description of Volume's 'Destroy' state => Destroy("The volume is destroyed, and can be recovered.") ?

**Comment by weizhouapache** [comment] 2022-01-06 09:03
@sureshanaparti 
sure

**Comment by weizhouapache** [comment] 2022-01-06 09:05
@div8cn 
I am looking at this issue. it is strange that the volume was expunged sooner after it was destroyed.
did you use vmware and unmanage vmware instance ?
Could you provide some logs ?

**Comment by div8cn** [comment] 2022-01-06 15:09
We don't use VMware; KVM + CEPH is used

**Comment by weizhouapache** [comment] 2022-01-06 15:20
> We don't use VMware; KVM + CEPH is used

@div8cn 
can you upload some logs ?
I was not able to reproduce the issue you mentioned.

**Comment by weizhouapache** [comment] 2022-01-10 10:17
@div8cn 
I need some logs to investigate what triggered the volume expunging.
I suspect it is not caused by the restorevm process.

**Comment by sureshanaparti** [comment] 2022-01-20 08:03
Hi @div8cn, the volume state description is fixed in #5833, and this behavior is as expected. If you still see any issue, please reopen with details (reproduce steps and logs). Thanks.

**Closed by sureshanaparti** 2022-01-20 08:03 UTC
Labels: status:not-a-bug
