### ISSUE TITLE
XCP-ng 8.2 - Live migration fails

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#7340] opened 2023-03-15 02:17 UTC
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
API, UI
~~~

##### CLOUDSTACK VERSION
~~~
4.18 RC3
~~~

##### CONFIGURATION
Advanced networking, 1 cluster, 2 XCP- ng hosts in the cluster, 2 storage pools

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Live migration of user VMs fail

##### STEPS TO REPRODUCE
~~~
Create VM on a host, start VM = true
Attempt a live migration of the VM to the other host
~~~

##### EXPECTED RESULTS
~~~
VM migration succeeds
~~~

##### ACTUAL RESULTS
~~~
2023-03-15 02:09:01,054 DEBUG [c.c.a.t.Request] (Work-Job-Executor-11:ctx-4d6cfe4b job-48/job-49 ctx-8797bea1) (logid:603f76bc) Seq 2-3130846165952627095: Executing:  { Cmd , MgmtId: 167781012, via: 2(ref-trl-4655-x-Mr8-nicolas-vazquez-xs1), Ver: v1, Flags: 100011, [{"com.cloud.agent.api.MigrateCommand":{"vmName":"i-2-5-VM","destIp":"10.0.32.148","migrateStorageManaged":"false","migrateNonSharedInc":"false","autoConvergence":"false","hostGuid":"0239ad4f-31e8-4e38-9e41-99edf0df35cf","isWindows":"false","vmTO":{"id":"5","name":"i-2-5-VM","bootloader":"PyGrub","state":"Running","type":"User","cpus":"1","minSpeed":"500","maxSpeed":"500","minRam":"(512.00 MB) 536870912","maxRam":"(512.00 MB) 536870912","arch":"x86_64","os":"CentOS 5.6 (64-bit)","platformEmulator":"CentOS 7","bootArgs":"","enableHA":"false","limitCpuUse":"false","enableDynamicallyScaleVm":"false","params":{"cpuOvercommitRatio":"2.0","memoryOvercommitRatio":"1.0"},"uuid":"d06072e4-7a60-4c00-9794-cd392bf9c3ac","enterHardwareSetup":"false","disks":[{"data":{"org.apache.cloudstack.storage.to.VolumeObjectTO":{"uuid":"d57788a0-0667-475c-8c58-64f65461d121","volumeType":"ROOT","dataStore":{"org.apache.cloudstack.storage.to.PrimaryDataStoreTO":{"uuid":"a39e31cd-cd6b-35a1-8b60-025dde80927a","name":"ref-trl-4655-x-Mr8-nicolas-vazquez-xs-pri2","id":"2","poolType":"NetworkFilesystem","host":"10.0.32.4","path":"/acs/primary/ref-trl-4655-x-Mr8-nicolas-vazquez/ref-trl-4655-x-Mr8-nicolas-vazquez-xs-pri2","port":"2049","url":"NetworkFilesystem://10.0.32.4/acs/primary/ref-trl-4655-x-Mr8-nicolas-vazquez/ref-trl-4655-x-Mr8-nicolas-vazquez-xs-pri2/?ROLE=Primary&STOREUUID=a39e31cd-cd6b-35a1-8b60-025dde80927a","isManaged":"false"}},"name":"ROOT-5","size":"(20.00 GB) 21474836480","path":"a5cf9ac8-ca32-4d8d-9a1c-f4cd4e3d56f2","volumeId":"6","vmName":"i-2-5-VM","accountId":"2","format":"VHD","provisioningType":"THIN","poolId":"2","id":"6","deviceId":"0","bytesReadRate":"(0 bytes) 0","bytesWriteRate":"(0 bytes) 0","iopsReadRate":"(0 bytes) 0","iopsWriteRate":"(0 bytes) 0","hypervisorType":"XenServer","directDownload":"false","deployAsIs":"false"}},"diskSeq":"0","path":"a5cf9ac8-ca32-4d8d-9a1c-f4cd4e3d56f2","type":"ROOT","_details":{"storageHost":"10.0.32.4","managed":"false","storagePort":"2049","storage.pool.disk.wait":"60","volumeSize":"(20.00 GB) 21474836480"}},{"data":{"org.apache.cloudstack.storage.to.TemplateObjectTO":{"id":"0","format":"ISO","accountId":"0","hvm":"false","bootable":"false","directDownload":"false","deployAsIs":"false"}},"diskSeq":"3","type":"ISO"}],"nics":[{"deviceId":"0","networkRateMbps":"200","defaultNic":"true","pxeDisable":"false","nicUuid":"c0528515-a991-44b9-a445-35b9b7e13943","details":{"PromiscuousMode":"false","MacAddressChanges":"true","ForgedTransmits":"true","MacLearning":"false"},"dpdkEnabled":"false","uuid":"21980820-3162-43d0-a760-933203f24752","ip":"10.1.1.152","netmask":"255.255.255.0","gateway":"10.1.1.1","mac":"02:00:4b:fb:00:03","dns1":"10.0.32.1","dns2":"8.8.8.8","broadcastType":"Vlan","type":"Guest","broadcastUri":"vlan://1024","isolationUri":"vlan://1024","isSecurityGroupEnabled":"false","name":"Network1"}],"vcpuMaxLimit":"3","configDriveLabel":"config-2","configDriveLocation":"SECONDARY","guestOsDetails":{"xenserver.dynamicMin":"536870912","xenserver.dynamicMax":"17179869184"},"extraConfig":{}},"executeInSequence":"false","migrateDiskInfoList":[],"dpdkInterfaceMapping":{},"vlanToPersistenceMap":{"1024":"true"},"wait":"0","bypassHostMaintenance":"false"}}] }
2023-03-15 02:09:01,054 DEBUG [c.c.a.m.DirectAgentAttache] (DirectAgent-394:ctx-043826c7) (logid:4e4e66ee) Seq 2-3130846165952627095: Executing request
2023-03-15 02:09:01,095 WARN  [c.c.h.x.r.CitrixResourceBase] (DirectAgent-394:ctx-043826c7) (logid:603f76bc) Task failed! Task record:                 uuid: 5865769c-39d0-abbd-6463-fbe8a69e1322
           nameLabel: Async.VM.pool_migrate
     nameDescription: 
   allowedOperations: []
   currentOperations: {}
             created: Wed Mar 15 02:09:01 UTC 2023
            finished: Wed Mar 15 02:09:01 UTC 2023
              status: failure
          residentOn: com.xensource.xenapi.Host@1c19dce
            progress: 1.0
                type: <none/>
              result: 
           errorInfo: [VM_LACKS_FEATURE, OpaqueRef:9a1b9861-3dff-418f-89ba-ce31f75a3528]
         otherConfig: {}
           subtaskOf: com.xensource.xenapi.Task@aaf13f6f
            subtasks: []

2023-03-15 02:09:01,095 DEBUG [c.c.a.ApiServlet] (qtp1955920234-22:ctx-f292c428) (logid:9830e96f) ===START===  10.0.3.251 -- GET  jobId=603f76bc-0fc9-4d79-a98f-2433fc5be9e7&command=queryAsyncJobResult&response=json
2023-03-15 02:09:01,096 DEBUG [c.c.a.ApiServlet] (qtp1955920234-22:ctx-f292c428) (logid:9830e96f) Two factor authentication is already verified for the user 2, so skipping
2023-03-15 02:09:01,101 WARN  [c.c.h.x.r.CitrixResourceBase] (DirectAgent-394:ctx-043826c7) (logid:603f76bc) Unable to migrate VM(i-2-5-VM) from host(a7cd7897-f5be-4a94-bafb-600683304577)
Task failed! Task record:                 uuid: 5865769c-39d0-abbd-6463-fbe8a69e1322
           nameLabel: Async.VM.pool_migrate
     nameDescription: 
   allowedOperations: []
   currentOperations: {}
             created: Wed Mar 15 02:09:01 UTC 2023
            finished: Wed Mar 15 02:09:01 UTC 2023
              status: failure
          residentOn: com.xensource.xenapi.Host@1c19dce
            progress: 1.0
                type: <none/>
              result: 
           errorInfo: [VM_LACKS_FEATURE, OpaqueRef:9a1b9861-3dff-418f-89ba-ce31f75a3528]
         otherConfig: {}
           subtaskOf: com.xensource.xenapi.Task@aaf13f6f
            subtasks: []

	at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.checkForSuccess(CitrixResourceBase.java:508)
	at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.migrateVM(CitrixResourceBase.java:3968)
	at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixMigrateCommandWrapper.execute(CitrixMigrateCommandWrapper.java:86)
	at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixMigrateCommandWrapper.execute(CitrixMigrateCommandWrapper.java:42)
	at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixRequestWrapper.execute(CitrixRequestWrapper.java:122)
	at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.executeRequest(CitrixResourceBase.java:1782)
	at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-15 02:09:01,105 DEBUG [c.c.a.ApiServer] (qtp1955920234-22:ctx-f292c428 ctx-2c8cdcdb) (logid:9830e96f) CIDRs from which account 'Account [{"accountName":"admin","id":2,"uuid":"513b92a7-c2c9-11ed-bc47-1e000e000327"}]' is allowed to perform API calls: 0.0.0.0/0,::/0
2023-03-15 02:09:01,105 DEBUG [c.c.h.x.r.CitrixResourceBase] (DirectAgent-394:ctx-043826c7) (logid:603f76bc) unable to destroy task(com.xensource.xenapi.Task@7c4c8878) on host(a7cd7897-f5be-4a94-bafb-600683304577) due to You gave an invalid object reference.  The object may have recently been deleted.  The class parameter gives the type of reference given, and the handle parameter echoes the bad value given.
2023-03-15 02:09:01,105 WARN  [c.c.h.x.r.w.x.CitrixMigrateCommandWrapper] (DirectAgent-394:ctx-043826c7) (logid:603f76bc) Unable to migrate VM(i-2-5-VM) from host(a7cd7897-f5be-4a94-bafb-600683304577)
com.cloud.utils.exception.CloudRuntimeException: Unable to migrate VM(i-2-5-VM) from host(a7cd7897-f5be-4a94-bafb-600683304577)
	at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.migrateVM(CitrixResourceBase.java:3979)
	at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixMigrateCommandWrapper.execute(CitrixMigrateCommandWrapper.java:86)
	at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixMigrateCommandWrapper.execute(CitrixMigrateCommandWrapper.java:42)
	at com.cloud.hypervisor.xenserver.resource.wrapper.xenbase.CitrixRequestWrapper.execute(CitrixRequestWrapper.java:122)
	at com.cloud.hypervisor.xenserver.resource.CitrixResourceBase.executeRequest(CitrixResourceBase.java:1782)
	at com.cloud.agent.manager.DirectAgentAttache$Task.runInContext(DirectAgentAttache.java:315)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-03-15 02:09:01,106 DEBUG [c.c.a.m.DirectAgentAttache] (DirectAgent-394:ctx-043826c7) (logid:603f76bc) Seq 2-3130846165952627095: Response Received: 
2023-03-15 02:09:01,106 DEBUG [c.c.a.t.Request] (DirectAgent-394:ctx-043826c7) (logid:603f76bc) Seq 2-3130846165952627095: Processing:  { Ans: , MgmtId: 167781012, via: 2(ref-trl-4655-x-Mr8-nicolas-vazquez-xs1), Ver: v1, Flags: 10, [{"com.cloud.agent.api.MigrateAnswer":{"result":"false","details":"Unable to migrate VM(i-2-5-VM) from host(a7cd7897-f5be-4a94-bafb-600683304577)","wait":"0","bypassHostMaintenance":"false"}}] }
2023-03-15 02:09:01,107 DEBUG [c.c.a.t.Request] (Work-Job-Executor-11:ctx-4d6cfe4b job-48/job-49 ctx-8797bea1) (logid:603f76bc) Seq 2-3130846165952627095: Received:  { Ans: , MgmtId: 167781012, via: 2(ref-trl-4655-x-Mr8-nicolas-vazquez-xs1), Ver: v1, Flags: 10, { MigrateAnswer } }
~~~

**Comment by nvazquez** [comment] 2023-03-15 02:18
@DaanHoogland @vladimirpetrov @borisstoyanov can you please check this one?

**Comment by vladimirpetrov** [comment] 2023-03-15 10:12
I did some testing with two different templates - Macchinina and CentOS 7. Sometimes ACS reports 'success' but the VM is actually stuck and the second attempt generates a failure. I tested the same scenario on 4.17.2 though and the behavior is exactly the same - so it doesn't look like a regression.

**Comment by harikrishna-patnala** [comment] 2023-03-15 10:22
agreed with you @vladimirpetrov

**Comment by borisstoyanov** [comment] 2023-03-15 10:28
it must be due to missing xen tools, I’ve migrated the a systemvm, but was not able to migrate the default template guest vm

**Comment by nvazquez** [comment] 2023-03-15 11:11
I was able to migrate an Ubuntu18 VM without xentools, I think the issue may be related to the template used

**Comment by vladimirpetrov** [comment] 2023-03-15 11:15
The default template doesn't work on Xen from some time ago, @borisstoyanov - check the console, it cannot start. One of the template I was using though - CentOS 7, has xentools installed.

**Comment by weizhouapache** [comment] 2023-08-15 11:49
@rohityadavcloud 
I can reproduce the issue when migrate the VMs created from default template "CentOS 5.6(64-bit) no GUI (XenServer)".

```
2023-08-15 11:33:49,234 WARN  [c.c.h.x.r.CitrixResourceBase] (DirectAgent-94:ctx-c09de4aa) (logid:18131619) Task failed! Task record:                 uuid: 2ccdc5b5-85d1-b8ba-154c-8484a4e58edc
           nameLabel: Async.VM.pool_migrate
     nameDescription:
   allowedOperations: []
   currentOperations: {}
             created: Tue Aug 15 11:33:48 UTC 2023
            finished: Tue Aug 15 11:33:48 UTC 2023
              status: failure
          residentOn: com.xensource.xenapi.Host@bf938f52
            progress: 1.0
                type: <none/>
              result:
           errorInfo: [VM_LACKS_FEATURE, OpaqueRef:583b196d-5278-48c1-8648-ffaadfce7f7a]
         otherConfig: {}
           subtaskOf: com.xensource.xenapi.Task@aaf13f6f
            subtasks: []

```

The VMs are not booted successfully
![image](https://github.com/apache/cloudstack/assets/57355700/75967b07-b56d-4ed6-9e30-bd88f8f6b666)


For system vms and k8s nodes, the mgiration succeed mostly, but still face some issues, for example
- If node is booting, vm migration failed
- If migrate 2 nodes in parellel, one or both of migration failed.
- after some successful migration, vm cannot be migrated any more
```
2023-08-15 11:46:50,205 WARN  [c.c.h.x.r.CitrixResourceBase] (DirectAgent-224:ctx-7e7595e4) (logid:a0fb08b4) Task failed! Task record:                 uuid: 84d5ca07-4785-64b1-b53c-f45a3c5b1731
           nameLabel: Async.VM.pool_migrate
     nameDescription:
   allowedOperations: []
   currentOperations: {}
             created: Tue Aug 15 11:46:50 UTC 2023
            finished: Tue Aug 15 11:46:50 UTC 2023
              status: failure
          residentOn: com.xensource.xenapi.Host@bf938f52
            progress: 1.0
                type: <none/>
              result:
           errorInfo: [VM_LACKS_FEATURE, OpaqueRef:6e9db8ea-589b-4725-9e2c-49eddb2d9548]
         otherConfig: {}
           subtaskOf: com.xensource.xenapi.Task@aaf13f6f
            subtasks: []
```

**Comment by weizhouapache** [comment] 2023-08-24 08:20
moved to 4.18.2.0

**Comment by rohityadavcloud** [comment] 2023-08-28 05:27
is it still happening @nvazquez @weizhouapache @DaanHoogland

**Comment by weizhouapache** [comment] 2023-08-28 06:00
@rohityadavcloud 
yes, see my comment last week. https://github.com/apache/cloudstack/issues/7340#issuecomment-1678802129
this is a known issue with 8.2

**Comment by weizhouapache** [comment] 2023-08-28 09:29
@rohityadavcloud  has tested the vm migration in a nested env (xcpng 8.2) on kvm, all vm migrations look good.

so it seems to be because we are using nested env on vmware. (similar issue: https://www.halizard.com/forum/software-support/348-issues-with-xcp-ng-8-0-and-vm-migration)

cc @nvazquez @DaanHoogland @borisstoyanov 

closing this issue

**Closed by weizhouapache** 2023-08-28 09:29 UTC
Labels: type:bug, component:XenServer, Severity:Major, status:needs-investigation
