### ISSUE TITLE
UI sorting of elements not working on some views

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#9595] opened 2024-08-27 11:17 UTC
As a root admin, I cannot change sort order of some views such as:

* Compute offering
* System offering
* Disk offering
* Network offering
* VPC offering

<img width="1521" alt="Screenshot 2024-08-27 at 4 45 53 PM" src="https://github.com/user-attachments/assets/effd10a7-295f-4682-aef8-266f83423157">

In addition, I think the following resources should also allow sorting/ordering by the root admin:

* Guest Networks (I think very useful to list shared networks in some preferred order, for example)

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI, API
~~~

##### CLOUDSTACK VERSION

~~~
4.19.1.1
~~~

##### CONFIGURATION

Adv zone + KVM

**Comment by DaanHoogland** [comment] 2024-08-28 07:47
@rohityadavcloud , unless you think this is a regression it seems like an enhancement to me, I marked it for 4.21 for now, please let me know if you disagree.

**Comment by DaanHoogland** [comment] 2024-08-30 13:42
this is indeed a regression in comparison to 4.18. It also seems like redundant functionality as (in the UI) sort can be done on several columns. I can see in the simplest , two-row case the columns are being updated in the DB and will look into what happens in more complex situations.

**Comment by DaanHoogland** [comment] 2024-08-30 15:26
gotten too the reason in code, need to think of a solution. The fetching is a two step process, first grab the IDs (ordering applied), than use the IDs to fetch the records (ordering totally forgotten about) /me thinking about a way to preserve the ordering.

**Comment by DaanHoogland** [comment] 2024-09-04 13:41
@rohityadavcloud #9624 solves the backwards compatibility for service and disk offering, can you test please? I did not reproduce it for network and vpc offerings.
It also fixes an extra issue to contain the sorting to the current page in the UI (thanks @vishesh92 )

**Comment by DaanHoogland** [comment] 2024-09-05 09:31
fixed in #9624

**Closed by DaanHoogland** 2024-09-05 09:31 UTC
Labels: component:api, component:UI, type:improvement, type:regression
