### ISSUE TITLE
Non-admin user interface reload (ctrl+R) causes dropping session

### ISSUE THREAD

**Issue by jia3apb** [apache/cloudstack#2679] opened 2018-05-29 15:10 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Web browser

##### SUMMARY

Non-admin user interface reload (ctrl+R) causes "Session Expired" message, drops session and as a result redirects to login form. At the same time, Admin UI works correctly.

##### STEPS TO REPRODUCE

~~~
Autorize to UI by role 'User' and refresh the page with CTRL+R
~~~

##### EXPECTED RESULTS

~~~
Keep the session and just reload the interface.  
~~~

##### ACTUAL RESULTS

~~~
Interface reload drops the Non-Admin user session. 
~~~

**Comment by rafaelweingartner** [comment] 2018-06-20 09:59
@jia3apb this looks some load-balance problem that you are having, and not ACS per se. Can you provide some extra details on your setup and the steps to reproduce the problem?

**Comment by jia3apb** [comment] 2018-06-26 06:37
Problem was solved by adding **if (isAdmin()){** in cloudStack.js in line 175. Result is:

```
if (isAdmin()){
                    $.ajax({
                        type: 'GET',
                        url: createURL('listConfigurations'),
                        data: {name: 'default.ui.page.size'},
                        dataType: 'json',
                        async: false,
                        success: function(data, textStatus, xhr) {
                            if (data && data.listconfigurationsresponse && data.listconfigurationsresponse.configuration) {
                                var config = data.listconfigurationsresponse.configuration[0];
                                if (config && config.name == 'default.ui.page.size') {
                                    pageSize = parseInt(config.value);
                                }
                            }
                        },
                        error: function(xhr) { // ignore any errors, fallback to the default
                        }
                    });
                }
```


It seems like using this API method **listConfigurations** by non-admin user drop the session.

**Comment by rhtyd** [comment] 2018-08-27 10:58
@jia3apb can you send a pull request against 4.11 branch?

**Comment by rhtyd** [comment] 2018-12-06 19:52
Unable to reproduce in 4.11.1.0/4.11.2.0, closing.

**Closed by rhtyd** 2018-12-06 19:52 UTC
Labels: UI
