### ISSUE TITLE
In Fresh Install of CS 4.15.RC3 IPV6 for Public IP is not accepted. 

### ISSUE THREAD

**Issue by nxsbi** [apache/cloudstack#4563] opened 2020-12-31 22:39 UTC
##### ISSUE TYPE

 Bug Report

##### COMPONENT NAME
~~~
UI
~~~

##### CLOUDSTACK VERSION

4.15 RC3

##### CONFIGURATION

Fresh Installation of CloudStack 4.15 RC3, during default setup screens.  

##### OS / ENVIRONMENT

CloudStack 4.15 RC3 installed on CentOS 7, MySQL 5.7 CE

##### SUMMARY

UI does not accept IPv6 addresses for Public IP address. 

##### STEPS TO REPRODUCE

After performing a fresh installation of CS 4.15 RC3, follow the default setup steps on the UI.
At the Public Traffic screen, enter an IPv6 address. 

The screen gives an error message asking for valid IPv4 address for the begin and end range but not on the Gateway and Netmask.

IPv4 is hard to obtain for public facing IP if you dont already have a few, so IPv6 needs to be supported especially for Public IP
 
![image](https://user-images.githubusercontent.com/71042351/103427343-4e30a600-4b75-11eb-928c-e57a4f4cee8e.png)

##### EXPECTED RESULTS

Expected result = IPv6 is accepted

##### ACTUAL RESULTS

Getting error and not able to proceed.

**Comment by DaanHoogland** [comment] 2021-01-04 06:48
@nxsbi if I'm not mistaken this is the issue with all released versions at the moment. Did you confirm this with any other version?

**Comment by rhtyd** [comment] 2021-03-06 10:10
Did it work with legacy UI, cc @GabrielBrascher @utchoang ?

**Comment by utchoang** [comment] 2021-03-08 02:12
@rhtyd cc @GabrielBrascher I checked for legacy UI the Ipv6 doesn't work. So does this need to be fixed?
![image](https://user-images.githubusercontent.com/13766648/110265537-58947380-7fee-11eb-9289-c9e815616f13.png)

**Comment by KuasarCo** [comment] 2021-03-09 18:57
thanks @GabrielBrascher, do we have any plan to implement it in Advanced Networking with VPC for public IPv6, we ran out of IPv4.

**Comment by GabrielBrascher** [comment] 2021-03-09 19:49
@KuasarCo I am sure that it would be awesome to have such a feature; unfortunately, I am not aware of anyone implementing it at this moment.

**Comment by nvazquez** [comment] 2021-07-14 01:42
Hi @GabrielBrascher @KuasarCo has it been any progress on this issue?

**Comment by rhtyd** [comment] 2021-07-15 07:08
@nxsbi this is not a bug as Gabriel said, IPv6 public IP ranges for adv zone are not allowed/supported. You can however deploy an adv zone and then add a shared network with ipv6 range. Therefore we'll close this issue. However, I encourage you participate in this discussion on adding support for IPv6 in adv zone - https://markmail.org/message/23ttvzwmzuanlkyg

**Closed by rhtyd** 2021-07-15 07:08 UTC
Labels: Severity:Minor, complexity:normal, component:UI, component:advanced-networking, component:zone-wizard
