### ISSUE TITLE
migratevmwithvolume api migrates both disks when you point just one of them

### ISSUE THREAD

**Issue by borisstoyanov** [apache/cloudstack#4421] opened 2020-10-22 09:02 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Migration
~~~

##### CLOUDSTACK VERSION

~~~
seen in 4.14 maybe older as well 
~~~

##### OS / ENVIRONMENT

VMware 

##### STEPS TO REPRODUCE

~~~
1. Create a VM with data disk
2. Use migrateVMwithVolume api and migrate the vm to another host with just one of the volumes
~~~
API call:
`(localcloud) SBCM5> > migrate virtualmachinewithvolume virtualmachineid=bb8468ad-53cd-4e32-8ef7-50e05e1003e5 hostid=942c54bf-4252-4562-b24f-98a4a9536769 migrateto[0].volume=e1024f5f-474d-4331-9be6-8992774101e7 migrateto[0].pool=e5ff77b2-4153-34b6-8a5a-150a9f158a9f`

##### EXPECTED RESULTS

~~~
VM migrated with just one of the volumes
~~~

##### ACTUAL RESULTS

~~~
Cloudstack migrates both the Volumes but then marks only one of them migrated
~~~
![Screenshot 2020-10-22 at 11 51 50](https://user-images.githubusercontent.com/13551960/96849440-43afad00-145e-11eb-8e4f-58b4ec2932c7.png)
![Screenshot 2020-10-22 at 11 15 45](https://user-images.githubusercontent.com/13551960/96849423-40b4bc80-145e-11eb-8518-592b812c9f5c.png)
![Screenshot 2020-10-22 at 11 15 53](https://user-images.githubusercontent.com/13551960/96849433-41e5e980-145e-11eb-9147-e73587b43592.png)
![Screenshot 2020-10-22 at 11 16 03](https://user-images.githubusercontent.com/13551960/96849437-43171680-145e-11eb-9835-4b716af3e9e6.png)

**Comment by shwstppr** [comment] 2020-10-22 09:12
@borisstoyanov just confirming, the destination host where VM was migrated had access to storage pool of volume that shouldn't be migrated?

**Comment by borisstoyanov** [comment] 2020-10-22 10:46
Yes, I've reproduced this with hosts/storage on the same cluster, also with cluster vs zone scope storage. Doesn't seem to matter.

**Comment by rhtyd** [comment] 2020-11-02 08:40
cc @Spaceman1984

**Comment by DaanHoogland** [comment] 2020-11-12 13:26
@borisstoyanov what is your expectation of the 'non'-migrated disks? should these still be attached? how about cross cluster migrations? is it even allowed to migrate with less than all disks?

**Comment by Spaceman1984** [comment] 2020-11-18 07:34
Taking a look

**Comment by harikrishna-patnala** [comment] 2020-11-18 08:02
@borisroman @DaanHoogland 
I think the reason for this behaviour is the Volume is tried to migrate to a storage pool (vvol5-zone) which is at zone level.
I observed the following from and code and also tested
All the volumes will be migrated to target storage pool (even though not all volumes are selected to migrate)
  1. if the target storage pool is with Zone scope
  2. if the target storage pool and host is in different cluster (across cluster migration)

So I feel this is expected to keep all the volumes in same cluster storage pool or zone level pool.

If the same scenario is tried with in cluster storage pool, then only selected volume will be migrated to target storage pool (other volumes will still remain on old storage pool)

**Comment by Spaceman1984** [comment] 2020-11-18 08:12
Should we close this issue as expected behavior?

**Comment by borisstoyanov** [comment] 2020-11-18 08:44
@harikrishna-patnala this is not acceptable since we end up with inconsistency between VMware and Cloudstack. As you see in vCenter the volumes are on vvol5, but Cloudstack shows one of the volumes on vvol5 and the other on vvlo4. 
I'm pretty sure if you try to do something with that volume will result in failure since cloudstack will not find it.

**Comment by rhtyd** [comment] 2020-11-18 08:53
@borisstoyanov do you think the severity should be bumped for this issue?

**Comment by borisstoyanov** [comment] 2020-11-18 09:04
yes, thanks @rhtyd

**Comment by harikrishna-patnala** [comment] 2020-11-18 09:17
@borisroman I thought you identified some problem in choosing the storage pools by management server. I've got the issue now being inconsistency with storage pool mapping between CloudStack and vCenter. I'll have a look.

**Comment by rhtyd** [comment] 2020-11-18 23:13
@harikrishna-patnala any update on this?

**Comment by harikrishna-patnala** [comment] 2020-11-19 05:27
Figured out the issue @rhtyd , testing all the scenarios now with a fix. I'll raise a PR soon

**Closed** 2020-11-20 12:38 UTC
Labels: Severity:Critical, component:migration, type:bug
