### ISSUE TITLE
Prometheus integration: requiring allowed ips is too restrictive

### ISSUE THREAD

**Issue by csquire** [apache/cloudstack#2801] opened 2018-08-13 16:19 UTC
##### ISSUE TYPE
 * Enhancement Request

##### COMPONENT NAME

~~~
Prometheus
~~~

##### CLOUDSTACK VERSION

~~~
4.11
~~~

##### SUMMARY

Only allowing whitelists of ips for Prometheus is too restrictive.  Should either have a flag to allow all ips or the ability to whitelist a CIDR block. For example, I run Prometheus in Kubernetes and would want to whitelist all the K8s nodes.

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~
Request returns a 403 and shows Forbidden in a browser.

Offending code is here:
https://github.com/apache/cloudstack/blob/master/plugins/integrations/prometheus/src/main/java/org/apache/cloudstack/metrics/PrometheusExporterServerImpl.java#L51-L59
~~~

**Comment by rhtyd** [comment] 2018-08-16 12:31
This is by design @csquire. You don't want any IP to be able to see/export the metrics of your datacenter(s).

**Comment by robisonjoel** [comment] 2018-08-17 11:49
@rhtyd In enterprises with such security concerns would there not also be network ACL's that would prevent access to whatever would be deemed critical data by that company?   Folks who are using prometheus to monitor Cloudstack are likely running prometheus in an fairly ephemeral environment like Kubernetes or Rancher where guaranteeing an egress IP can be somewhat of an antipattern.

**Comment by DaanHoogland** [comment] 2020-03-10 15:08
@csquire @rhtyd @robisonjoel anybody planning to work on this? If we won't fix let's close it

**Comment by DaanHoogland** [comment] 2020-12-21 09:16
(@rhtyd, ) closing based on the comments above

**Closed by DaanHoogland** 2020-12-21 09:16 UTC
Labels: component:plugin, type:enhancement

**Comment by araujobsd** [comment] 2025-01-03 06:52
I encountered a similar issue with CloudStack 4.19 while managing a large Kubernetes cluster with 11-bit networking, which provides over 2 million IPv4 addresses! It's impractical to list all these IPs in the whitelist. It would be helpful to have at least an option or flag that allows a network range to be accepted, especially in cases where CIDR support can't be implemented. This would significantly improve usability for large-scale networks.

**Comment by NuxRo** [comment] 2025-01-03 11:48
@araujobsd Indeed, some more flexibility and support for cidr annotation would be great, but the issue can be easily worked around with a local proxy (haproxy, nginx, whatever) and then just whitelist the local IPs. Then you can implement more advanced ACLs in the proxy.
