### ISSUE TITLE
Xenserver/XCP-NG Create Instance - Override Root Disk Size

### ISSUE THREAD

**Issue by tsinik-dw** [apache/cloudstack#5918] opened 2022-02-01 11:44 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0
~~~

##### OS / ENVIRONMENT

ACS 4.16.0
1 Zone 
Cluster A: Two Xenserver 7.0 hosts
Cluster B: Two XCP-NG 8.2 hosts

Each Cluster has each own NFS primary storage 

##### SUMMARY

Override Root Disk Size during Creation of New Instance (based on template) does not work.  (same result on Xenserver/XCP-NG)

##### STEPS TO REPRODUCE

~~~
1. Create VM based on ISO with ROOT disk size 20GB
2. Create template from volume 
3. Create new instance based on aforementioned template
4. Override ROOT disk size and set size of 30GB
~~~

##### EXPECTED RESULTS

~~~
New instance VM should have Root Disk Size of 30GB
~~~

##### ACTUAL RESULTS

~~~
ACS reports that volume is of 30GB size. (DB record in volumes table is 32212254720) but lsblk output is (like) the following:
NAME      SIZE
...
xvda         30G
   xvda1      1G
   xvda2     19G
...
~~~
As a workaround we change the DB entry with correct size and then perform a resize.

(Maybe) Related: https://github.com/apache/cloudstack-primate/pull/499

**Comment by weizhouapache** [comment] 2022-02-01 12:51
@tsinik-dw 
from what you posted, `xvda` has 30GB which looks fine.
the problem is `xvda2` is still 19GB. you need to add scripts or install tools, for example cloud-init, to detect and increase paritition size automatically in startup.

**Comment by nvazquez** [comment] 2022-02-04 00:17
Thanks @weizhouapache, is that the expected behaviour or should be fixed and handled by CloudStack?

**Comment by weizhouapache** [comment] 2022-02-16 08:54
@tsinik-dw 
I used 4.16 systemvm template for testing. The new root disk size can be recognized by the vm, and the partition growed automatically. see below (new root disk size is 22 GB)

![image](https://user-images.githubusercontent.com/57355700/154228438-d9a0bca7-a7ca-45a4-b95a-760084f0bf50.png)

Please notice, systemvm template has cloud-init installed, growpart and resizefs are configured in /etc/cloud/cloud.cfg

Therefore, this is the expected behavior, not an issue.
as I advised in previous comment, please research on how to detect disk size and increase partition automatically inside your vm. cloud-init is an option for you.

**Comment by nvazquez** [comment] 2022-02-17 01:52
Thanks @weizhouapache - @tsinik-dw I'll close this issue for now, please re-open if necessary

**Closed by nvazquez** 2022-02-17 01:52 UTC
Labels: component:XenServer, status:not-a-bug

**Comment by tsinik-dw** [comment] 2022-02-17 08:38
Hi @weizhouapache, @nvazquez,

cloud-init is the way to go. Thanks!
