### ISSUE TITLE
VPC VR can't be started on VMware due to missing routes

### ISSUE THREAD

**Issue by andrijapanicsb** [apache/cloudstack#6873] opened 2022-11-07 15:14 UTC
##### ISSUE TYPE

 * Bug Report
##### COMPONENT NAME

~~~
VR agent ?
~~~

##### CLOUDSTACK VERSION

~~~
4.17.0.0+, VMware 
~~~

##### CONFIGURATION

mgmt server is in Pod1/subnet1, 
hypervisor (and thus VR's control NIC) is in Pod2/subnet2 - thus there is a routing process between mgmt and VR's NIC IP

##### OS / ENVIRONMENT

Probably affects only VMware, but has not been tested with XS/KVM (should not be a problem, but needs checking)

##### SUMMARY

Only VPC VR affected (VR for shared or simpler Isolated network is NOT affected).
There is a patching error of the VPC VR (this might be a problem or a consequence of missing routes) - either way, route from VR to the subnet of the mgmt server (subnet1) is missing/not configured, and thus VR can't talk to the mgmt server - VR configuration never completes.  CMDLINE looks fine (all parameters look fine) but things are not applied correctly on the OS level.

##### STEPS TO REPRODUCE
~~~
For bugs, show exactly how to reproduce the problem, using a minimal test-case. Use Screenshots if accurate.

For new features, show how the feature would be used.
~~~

~~~
mgmt server in subnet1, hypervisor (and thus VR's control NIC) in subnet2 - so that VR needs to send packet to the Pod2's gateway in order to reach Pod1/mgmt server.
~~~

##### EXPECTED RESULTS

~~~
VR patched up and operational
~~~

##### ACTUAL RESULTS

~~~
VR not patched, routes not present as needed.
~~~

CMD line of the VPC VR:
![image](https://user-images.githubusercontent.com/45762285/200345210-097874b6-7886-4f90-a4ca-dfc15fab31fd.png)

cloud.log
![image](https://user-images.githubusercontent.com/45762285/200345404-b8a51306-0140-4b7b-b580-8f43fcfc9bbb.png)

Routing table empty (there should be multiple routes (route to the mgmt cidr should be via 10.1.32.1 for 10.1.32.0 network - see CMDLINE output)

![image](https://user-images.githubusercontent.com/45762285/200345580-a7db6c55-2599-4f31-a686-ab00be19b892.png)

**Comment by weizhouapache** [comment] 2022-11-07 16:22
it looks the route for mgmt cidr (10.0.32.0/20) is missing. 
the problem is, where can we find the gateway of mgmt cidr (e.g. 10.0.32.1) ? cannot find it in cmdline.

xenserver/kvm should not be impacted, as they use link local ip.

**Comment by H-LK** [comment] 2022-11-07 23:06
A critical export was moved from bootstrap.sh to init.sh

When the VPC is setup it asked in Line 64 for the hypvervisor
https://github.com/apache/cloudstack/blob/296035d9a57caa62260a666da726ec45b6801c4b/systemvm/debian/opt/cloud/bin/setup/vpcrouter.sh#L64
The vpcrouter.sh gets called by the bootstrap.sh. In Version <= 4.16 it gets exported there and is available for vpcrouter.sh https://github.com/apache/cloudstack/blob/77df050160d6a5343aab97571bf891e51b4b1201/systemvm/debian/opt/cloud/bin/setup/bootstrap.sh#L215

The comit https://github.com/apache/cloudstack/commit/830f3061bcc33c0d3a22d9129e8bcf6a8ead37da removes the export in the bootstrap.sh and adds it to init.sh

**Comment by weizhouapache** [comment] 2022-11-08 07:35
> A critical export was moved from bootstrap.sh to init.sh
> 
> When the VPC is setup it asked in Line 64 for the hypvervisor
> 
> https://github.com/apache/cloudstack/blob/296035d9a57caa62260a666da726ec45b6801c4b/systemvm/debian/opt/cloud/bin/setup/vpcrouter.sh#L64
> 
> 
> The vpcrouter.sh gets called by the bootstrap.sh. In Version <= 4.16 it gets exported there and is available for vpcrouter.sh
> https://github.com/apache/cloudstack/blob/77df050160d6a5343aab97571bf891e51b4b1201/systemvm/debian/opt/cloud/bin/setup/bootstrap.sh#L215
> 
> The comit [830f306](https://github.com/apache/cloudstack/commit/830f3061bcc33c0d3a22d9129e8bcf6a8ead37da) removes the export in the bootstrap.sh and adds it to init.sh

@H-LK 
thanks for the findings.

prior to 4.17, the route is added in vpcrouter.sh which is called by cloud-early-config service.
since 4.17, two steps are added before cloud-early-config
- init.sh (called by cloud-preinit service)
- patch (transfer new files/scripts from host or management server to VRs via `scp` command)

The `scp` in `patch` step does not work, because the route is not added (`cloud-early-config` is not executed yet).
The route should be added in `init.sh`, instead of `vpcrouter.sh`

-

**Comment by weizhouapache** [comment] 2022-11-18 06:20
> 

That is strange. Can you test it again ?

**Comment by hooklee2000** [comment] 2022-11-18 06:55
system vm

**Comment by hooklee2000** [comment] 2022-11-18 08:08
we also tested main branch  pulled on 2022-11-17, it had the same problem. How ever, Using virsh list  it had not vrvm, it only  had cpvm and  ssvm.
4.18-vm-autoscaling had vrvm,but vrvm had cpvm java process.

**Comment by weizhouapache** [comment] 2022-11-18 11:01
> we also tested main branch pulled on 2022-11-17, it had the same problem. How ever, Using virsh list it had not vrvm, it only had cpvm and ssvm. 4.18-vm-autoscaling had vrvm,but vrvm had cpvm java process.

@hooklee2000 did you test with a fresh installation or upgrade existing environment ?

**Comment by hooklee2000** [comment] 2022-11-18 13:52
I tested all with a fresh installation.

**Comment by weizhouapache** [comment] 2022-11-21 20:51
> We tested all with a fresh installation. By the way, using mysql 8, we must disable mysql's validate_password :
> 
> ```sql
> set global validate_password.policy=0;
> set global validate_password.length=1;
> ```
> 
> otherwise cloudstack-setup-database printed error : We apologize for below error:
> 
> ```
> cloudstack-setup-database  cloud:xxxxxx@127.0.0.1 --deploy-as=root:xxxxxx
> ***************************************************************
> Encountering an error when executing mysql script
> ----------------------------------------------------------------------
> table:
> /usr/share/cloudstack-management/setup/create-database.sql
> 
> Error:
> b"mysql: [Warning] Using a password on the command line interface can be insecure.\nERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)\n"
> 
> Sql parameters:
> {'user': 'root', 'passwd': 'xxxxxx', 'port': 3306, 'host': '127.0.0.1'}
> ----------------------------------------------------------------------
>             
> ***************************************************************
> Please run:
> 
>     cloudstack-setup-databases -h
> 
> for full help
> ```

@hooklee2000 
can you file a new github issue for this ?

**Comment by hooklee2000** [comment] 2022-11-22 01:59
#6915

**Comment by rohityadavcloud** [comment] 2022-12-12 12:12
Fixed in https://github.com/apache/cloudstack/pull/6921

**Closed by rohityadavcloud** 2022-12-12 12:12 UTC
Labels: Severity:Critical
