### ISSUE TITLE
Several public IP with load balancer rules overwrite each other

### ISSUE THREAD

**Issue by KuasarCloud** [apache/cloudstack#5553] opened 2021-10-05 21:54 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
VR: LOAD BALANCER RULE

##### CLOUDSTACK VERSION
4.15.1.0

##### SUMMARY
When having at least 2 public IPs configured with load balancer rules, the configuration overwrite each other and
only one set of rules on 1 public IP are usable. 

##### STEPS TO REPRODUCE
1. Assign 2 public IPs
2. Create 3 rules on IP one
3. Create 1 rule on IP two

Then the rules on step 2 disappear, I could test it entering to the haproxy.cfg file and realized they're gone

##### EXPECTED RESULTS
Having multiple IP each with multiple load balancer rules

**Comment by weizhouapache** [comment] 2021-10-06 13:11
@KuasarCloud could you please give more details ? for example
* cloudstack version
* hypervisor
* vpc or network, and vpc/network offerings
* state of vm, network or vpc.

I cannot reproduce the issue in main. here is the haproxy.cfg 

```
listen 10_0_55_141-22
	bind 10.0.55.141:22
	balance roundrobin
	server 10_0_55_141-22_0 192.168.2.177:22 check
	 
listen 10_0_55_142-23
	bind 10.0.55.142:23
	balance roundrobin
	server 10_0_55_142-23_0 192.168.2.177:23 check
```

**Comment by KuasarCloud** [comment] 2021-10-07 12:27
Hi @weizhouapache,

Thanks for your prompt reply, here are some details

* Hyp: KVM
* Cloudstack Version and VR: 4.15.0.1
* VPC: Redundant VPC offering
* Network: DefaultIsolatedNetworkOfferingForVpcNetworks
* state of vm, network or vpc: enabled

These is my current haproxy.conf with 1 IP and 3 listen options (rules)

listen 172_x_x_x-xxxx
        bind 172.x.x.x:xxx
        balance roundrobin
        server 172_x_x_x-xxx_0 172.x.x.x:xxxx check

listen 172_x_x_x-xxx
        bind 172.x.x.x:xxx
        balance roundrobin
        server 172_x_x_x-xxx_0 172.x.x.x:xxx check
        server 172_x_x_x-xxx_1 172.x.x.x:xxx check
        server 172_x_x_x-xxx_2 172.x.x.x:xxx check

listen 172_x_x_x-xxx
        bind 172.x.x.x:xxx
        balance roundrobin
        server 172_x_x_x-xxx_0 172.x.x.x:xxx check
        server 172_x_x_x-xxx_1 172.x.x.x:xxx check
        server 172_x_x_x-xxx_2 172.x.x.x:xxx check
        mode http
        option httpclose

But in the UI I have two defined different IP with lb rules each, the first one with the ones as defined above and the second is not in the config but when I update (add/remove member) on my second ip, the above config disappear and got replaced with the second ip lb rules.

**Comment by KuasarCloud** [comment] 2021-10-08 14:48
@weizhouapache: find the info requested

The previous configuration was overwritten

* /var/log/cloudstack/agent/agent.log

2021-10-08 09:44:07,124 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-1:null) (logid:139f6f30) Expected 6 answers while executing IpAssocVpcCommand but received 2
2021-10-08 09:44:08,121 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-3:null) (logid:139f6f30) Expected 6 answers while executing IpAssocVpcCommand but received 2
2021-10-08 09:44:08,199 INFO  [cloud.network.HAProxyConfigurator] (agentRequest-Handler-5:null) (logid:139f6f30) Haproxy mode http enabled
2021-10-08 09:44:10,300 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-5:null) (logid:139f6f30) Expected 1 answers while executing LoadBalancerConfigCommand but received 2
2021-10-08 09:44:10,352 INFO  [cloud.network.HAProxyConfigurator] (agentRequest-Handler-2:null) (logid:139f6f30) Haproxy mode http enabled
2021-10-08 09:44:12,798 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-2:null) (logid:139f6f30) Expected 1 answers while executing LoadBalancerConfigCommand but received 2
2021-10-08 09:44:13,708 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-4:null) (logid:139f6f30) Expected 6 answers while executing IpAssocVpcCommand but received 2
2021-10-08 09:44:14,769 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-1:null) (logid:139f6f30) Expected 6 answers while executing IpAssocVpcCommand but received 2
2021-10-08 09:44:26,003 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-4:null) (logid:49a7954c) Trying to fetch storage pool 3f7ecd1c-466e-3741-b176-0d3e29a2dfdc from libvirt
2021-10-08 09:44:26,007 INFO  [kvm.storage.LibvirtStorageAdaptor] (agentRequest-Handler-4:null) (logid:49a7954c) Asking libvirt to refresh storage pool 3f7ecd1c-466e-3741-b176-0d3e29a2dfdc
2021-10-08 09:44:31,254 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-1:null) (logid:1f2a0b5a) Expected 6 answers while executing IpAssocVpcCommand but received 2
2021-10-08 09:44:32,171 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-3:null) (logid:1f2a0b5a) Expected 6 answers while executing IpAssocVpcCommand but received 2
2021-10-08 09:44:32,222 INFO  [cloud.network.HAProxyConfigurator] (agentRequest-Handler-5:null) (logid:1f2a0b5a) Haproxy mode http enabled
2021-10-08 09:44:33,900 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-5:null) (logid:1f2a0b5a) Expected 1 answers while executing LoadBalancerConfigCommand but received 2
2021-10-08 09:44:33,940 INFO  [cloud.network.HAProxyConfigurator] (agentRequest-Handler-4:null) (logid:1f2a0b5a) Haproxy mode http enabled
2021-10-08 09:44:35,590 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-4:null) (logid:1f2a0b5a) Expected 1 answers while executing LoadBalancerConfigCommand but received 2
2021-10-08 09:44:36,535 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-2:null) (logid:1f2a0b5a) Expected 6 answers while executing IpAssocVpcCommand but received 2
2021-10-08 09:44:37,509 WARN  [resource.virtualnetwork.VirtualRoutingResource] (agentRequest-Handler-1:null) (logid:1f2a0b5a) Expected 6 answers while executing IpAssocVpcCommand but received 2

* ls -rt /var/cache/cloud/processed/load_balancer.json.*.gz |tail -n1 |xargs zcat

{
   "rules":[
      {
         "configuration":[
            "global",
            "\tlog 127.0.0.1:3914   local0 warning",
            "\tmaxconn 4096",
            "\tmaxpipes 1024",
            "\tchroot /var/lib/haproxy",
            "\tuser haproxy",
            "\tgroup haproxy",
            "\tdaemon",
            "\t ",
            "defaults",
            "\tlog     global",
            "\tmode    tcp",
            "\toption  dontlognull",
            "\tretries 3",
            "\toption redispatch",
            "\toption forwardfor",
            "\toption forceclose",
            "\ttimeout connect    5000",
            "\ttimeout client     50000",
            "\ttimeout server     50000",
            "\nlisten stats_on_private\n\tbind 169.254.195.217:8081\n\tmode http\n\toption httpclose\n\tstats enable\n\tstats uri     /admin?stats\n\tstats realm   Haproxy\\ Statistics\n\tstats auth    admin1:AdMiN123\n",
            "\t ",
            "listen 172_18_0_28-8080",
            "\tbind 172.18.0.28:8080",
            "\tbalance roundrobin",
            "\tserver 172_18_0_28-8080_0 172.20.50.10:8080 check cookie 172_20_50_10-8080",
            "\tserver 172_18_0_28-8080_1 172.20.50.11:8080 check cookie 172_20_50_11-8080",
            "\tcookie cs insert  ",
            "\tmode http",
            "\toption httpclose",
            "\t ",
            "\t "
         ],
         "tmp_cfg_file_path":"/etc/haproxy/",
         "tmp_cfg_file_name":"haproxy.cfg.new.1633704272222",
         "add_rules":[
            "172.18.0.28:8080:"
         ],
         "remove_rules":[
            
         ],
         "stat_rules":[
            "169.254.195.217:8081:0/0:,"
         ],
         "router_ip":"172.20.50.120"
      }
   ],
   "type":"loadbalancer",
   "delete_from_processed_cache":false
}

**Comment by weizhouapache** [comment] 2021-10-10 06:45
> are you able to reproduce the issue by the steps in description every time ? Yes I do, please check the diagnostic from the virtual router.
> 
> haproxy_check.py | advanced | False | 2021-10-09T19:10:18-0500 | Missing section for load balancing listen 172_x_x_x-xxx

@KuasarCloud 
I think you are facing a corner case, please upload your logs for investigation.

**Comment by KuasarCloud** [comment] 2021-10-11 16:56
Can I send them to an email or something? I don't want my internal config on public access.

**Comment by weizhouapache** [comment] 2021-10-11 17:26
> Can I send them to an email or something? I don't want my internal config on public access.

@KuasarCloud my email is weizhou<at>apache.org

**Comment by weizhouapache** [comment] 2021-10-12 20:46
> Please, check your spam, I think I sent it ok. thanks
> 
> ![Screen Shot 2021-10-12 at 10 09 21 AM](https://user-images.githubusercontent.com/70651646/136982239-91e75d95-8d7a-470a-b194-05768b22006c.png)

@KuasarCloud could you please send again to `weizhouapache AT gmail.com` ?

**Comment by rhtyd** [comment] 2021-10-14 04:51
@weizhouapache are you working on a fix, or should we document that LB is limited/supported for only 1 tier. cc @nvazquez @sureshanaparti

**Comment by weizhouapache** [comment] 2021-10-14 09:36
> We may need to explore why the restriction was added in UI - perhaps this limitation is known? (also if none of the older ACS versions supported this case - likely this is not a regresssion/bug but limitation)

@rhtyd 
it might be a limitation on netscaler.
if LB provider is VpcVirtualRouter,  I think we can support it on UI (it is already supported by api or cloudmonkey), I do not see any reason it is not supported.
if LB provider is netscaler, it will be same as before (multiple vpc tiers with LB is not supported). we do not change it

make sense ?

**Comment by rhtyd** [comment] 2021-10-14 09:49
@weizhouapache that's not what I meant - if anyone can determine that this worked in an older version of ACS but doesn't work for 4.15/4.16/main - then it's a regression or bug; otherwise, it isn't a regression or a bug but a limitation which may be addressed in a future version of ACS.

**Closed** 2021-10-17 01:25 UTC
Labels: Severity:Critical

**Comment by kurushi9000** [comment] 2022-01-18 16:23
@weizhouapache have you tested it with Netcaler ?

**Comment by weizhouapache** [comment] 2022-01-18 19:36
> @weizhouapache have you tested it with Netscaler ?

@kurushi9000 no
