### ISSUE TITLE
LDAP users with similar permissions do not see each other's networks

### ISSUE THREAD

**Issue by PPisz** [apache/cloudstack#3364] opened 2019-05-30 08:45 UTC
##### ISSUE TYPE

 * Bug Report
 * Improvement Request

##### COMPONENT NAME

~~~
LDAP, Network, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.12
~~~

##### CONFIGURATION

~~~
Advanced networking with network service offering
~~~
##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

~~~
In one domain (eg. ROOT):
Admin create network offering
LDAP root admin user create network with network offering
Another LDAP root admin user not see this network
~~~
##### STEPS TO REPRODUCE

~~~
Create two LDAP users with root admin permissions and create networks.
~~~

##### EXPECTED RESULTS

~~~
All users in one domain with root admin privileges have the same capabilities (in this case, they can create a VM with a network created by another user).
~~~

##### ACTUAL RESULTS

~~~
LDAP user with root admin privileges can not see the networks created by the standard admin user (on the same domain). If such a user (ldap) with root admin privileges creates a new network, it is not visible to other users in UI
I consider this to be an error which makes work with users with root admin privileges very difficult
~~~

**Comment by andrijapanicsb** [comment] 2019-05-30 11:08
Heard a similar thing from another user.
"LDAP-authenticated" ADMIN vs. "local-authenticated" ADMIN - can't see each other's networks.

**Comment by PaulAngus** [comment] 2019-06-05 07:42
Are these the same root admin account or two accounts which both have root admin privileges?

**Comment by PPisz** [comment] 2019-06-05 07:52
Two accounts with root admin privileges:

ppisz | Root Admin | Admin | ROOT | enabled 
tome | Root Admin | Admin | ROOT | enabled

**Comment by PaulAngus** [comment] 2019-06-05 09:24
Is the other network visible through the API (when you use listall=true) ?

**Comment by PPisz** [comment] 2019-06-07 06:06
LDAP root admin sees all networks through the API (not in UI).
Real admin see all networks in UI.

**Comment by DaanHoogland** [comment] 2020-01-16 15:24
as the real admin is the one and there an be only one, i would expect this behaviour. No idea if this is true but i wouldn't expect a second 'local' root user to see all networks in the UI either. (#testingneeded)

**Comment by andrijapanicsb** [comment] 2020-01-16 15:47
root admin is a root admin, irrelevant how he was authenticated (IMO) - so both root admins should see everything...

**Comment by DaanHoogland** [comment] 2020-01-16 20:31
should, maybe, not going into that. works that way is my question, i.e. is this behaviour ldap specific? sounds a bit weird knowing the implementation but worth finding out.

**Comment by PPisz** [comment] 2020-01-17 06:15
This is the specifics of CloudStack UI, not ldap. We tested it on an external CloudStack-UI and everything works as expected (via API). Unfortunately, CloudStack-UI is intended for ordinary users, not for administrators. Primate is not ready for production use. Please fix this error :-)

**Comment by DaanHoogland** [comment] 2020-01-17 14:11
the js isAdmin() only returns true for admin never for another root-admin. please amend if you feel this should change @PPisz .

**Comment by PPisz** [comment] 2020-01-20 06:52
Yes, it should be changed. jsAdmin should return true for all root admins.

**Comment by rhtyd** [comment] 2020-07-08 06:13
Can you test Primate @PPisz we're targeting GA/1.0 now

**Comment by rhtyd** [comment] 2021-04-22 10:01
ping @PPisz cc @Spaceman1984 @shwstppr @Pearl1594

**Comment by rhtyd** [comment] 2021-04-22 10:02
cc @svenvogel @utchoang can you test in the new UI?

**Comment by rhtyd** [comment] 2021-04-23 07:06
@PPisz I reviewed the ticket again, per your comment there are two accounts:
```
Two accounts with root admin privileges:

ppisz | Root Admin | Admin | ROOT | enabled
tome | Root Admin | Admin | ROOT | enabled
```

Since resources are owned by account, they are treated different entities/owners even if they may have the same user (physical person) who has LDAP access to both accounts. If my understanding is correct, this is by design and not a CloudStack bug.

**Comment by rhtyd** [comment] 2021-04-23 07:07
@PPisz pl check and close the ticket, or help explain for further investigation. Thanks.

**Comment by PPisz** [comment] 2021-04-26 15:30
@rhtyd

**Comment by PPisz** [comment] 2021-04-26 15:31
I checked it in 4.15 on Primate, no change.
I understand that it was designed this way, I am closing the ticket.

**Comment by rhtyd** [comment] 2021-05-02 14:59
Thanks @PPisz I need one case to be checked which on behaviour when there are multiple root admins. I'm temporarily opening the ticket. Will close of it turns out to be a non issue.

**Comment by Spaceman1984** [comment] 2021-05-04 08:17
> Thanks @PPisz I need one case to be checked which on behaviour when there are multiple root admins. I'm temporarily opening the ticket. Will close of it turns out to be a non issue.

@rhtyd are you testing the case or should I go ahead?

**Comment by rhtyd** [comment] 2021-05-04 10:15
@Spaceman1984 pl test by creating two root admin accounts and compare the UI vs legacy UI.

**Comment by Spaceman1984** [comment] 2021-05-06 12:12
I tested with multiple root admin accounts, not an issue in 4.14 or 4.15. 

I didn't test 4.12. and I didn't specifically test with an LDAP admin user.

**Comment by rhtyd** [comment] 2021-05-06 14:20
Thanks Darrin, closing on your remark

**Closed by rhtyd** 2021-05-06 14:20 UTC
