### ISSUE TITLE
Ip address truncated when creating a instance

### ISSUE THREAD

**Issue by lbegault** [apache/cloudstack#6810] opened 2022-10-07 12:22 UTC
##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
User interface

~~~

##### CLOUDSTACK VERSION
4.17.1.0

~~~

~~~

##### CONFIGURATION
Isolated network with nat


##### SUMMARY
When choosing an ipv4 for a vm instance, only 10 first char are used.

~~~

##### STEPS TO REPRODUCE
At vm creation, trying to set the ip 10.200.1.254 for a vm.
~~~

~~~

##### EXPECTED RESULTS
Vm should be created with 10.200.1.254 ip.

~~~

~~~

##### ACTUAL RESULTS
Vm is created with ip 10.200.1.2

~~~

~~~

**Comment by s-seitz** [comment] 2022-10-10 15:33
As a wild guess, I don't think, the IP is getting truncated. I'ld assume, you defined 10.200.1/24, so .1 is picked as default gateway and .2 is the first free IP picked for the first VM.

**Comment by vdombrovski** [comment] 2022-10-31 09:50
Hello,

I am able to reproduce Luc's behavior. I think it is due to the fact the IP field gets reset preemptively before the VM is deployed.

To reproduce:

1. (Working case): deploy a VM without specifying (touching the IP address field). Your payload only has the networkid field:

```
iptonetworklist[0].networkid: 4c65cfff-05e7-4cfa-964b-2ae93d591d5f
```

2. (Non working case): deploy a VM and specify any IP address, or enter an IP address then empty the field. Your payload now looks like this (I've specified 10.0.0.100 as my IP)
```
iptonetworklist[0].networkid: 4c65cfff-05e7-4cfa-964b-2ae93d591d5f
iptonetworklist[0].ip: 10.0.0.2
```

As Stephan correctly pointed out, the IP gets reset to GatewayIP + 1 systematically as the field is cleared before it can be read from.

**Comment by DaanHoogland** [comment] 2022-11-01 09:55
I'll mark this as not a bug, biven the feedback.

**Comment by weizhouapache** [comment] 2023-01-10 15:50
@lbegault @s-seitz @vdombrovski @DaanHoogland 

is this same as #6974 which has been fixed by #6994  ?

**Comment by DaanHoogland** [comment] 2023-01-10 17:16
@weizhouapache no, in this case the ip address is truncated to 10 characters.
in that case the ip address is not persisted in the form.

**Comment by DaanHoogland** [comment] 2023-01-10 17:18
No @weizhouapache , in this case the ip address is not persisted in the form on purpose. I think it is different.

**Comment by shwstppr** [comment] 2023-01-10 17:37
@weizhouapache I think this issue was fixed by the PR you mentioned

**Comment by DaanHoogland** [comment] 2023-01-11 11:15
@shwstppr @weizhouapache I think it is not the same issue, but as @vdombrovski describes in [#issuecomment-1296847469](https://github.com/apache/cloudstack/issues/6810#issuecomment-1296847469),  it is not a bug but expected bahaviour. I think we can close this either way.

@lbegault please reopen with more information if you feel this is still an issue.

**Closed by DaanHoogland** 2023-01-11 11:15 UTC
Labels: status:not-a-bug
