### ISSUE TITLE
UI: creating a domain with a short name fails

### ISSUE THREAD

**Issue by DaanHoogland** [apache/cloudstack#7071] opened 2023-01-10 07:37 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
main (-4.18)
~~~

##### SUMMARY

adding a domain fails from the UI if the name is "bla" or "blob". "bla.blob" succeeds.

![image](https://user-images.githubusercontent.com/2486961/211489111-38876312-efed-4354-b392-b0792baed998.png)

##### STEPS TO REPRODUCE

~~~
go to domains and
add a domain
enter "bla" as the name
~~~

##### EXPECTED RESULTS

~~~
domain "bla" is created
~~~

##### ACTUAL RESULTS

~~~
error: Request failed.
Invalid network domain. Total length should not exceed 190 chars. Each domain label must be between 1 and 63 characters long. It can contain ASCII letters 'a' through 'z', the digits '0' through '9', and the hyphen ('-'); it cannot start or end with "-".
~~~

**Comment by CharlesQueiroz** [comment] 2023-08-24 13:30
I couldn't reproduce the problem. I made a pull of the 4.18 branch and ran it... followed the step-by-step description, but the domain was created as expected. 

See:

https://github.com/apache/cloudstack/assets/2192264/9a4db193-86f3-446b-92ca-2b4472f7fdc2

Is there anything else that I can do to validate it 100%?

**Comment by soreana** [comment] 2023-08-24 14:17
@DaanHoogland I couldn't also reproduce it with the latest 4.18 branch. Shall we close it?

**Comment by rohityadavcloud** [comment] 2023-08-25 06:36
@DaanHoogland I think you've a space or a tab in the fields, only then I can reproduce the issue. Otherwise can't reproduce the issue, closing on this remark.

**Closed by rohityadavcloud** 2023-08-25 06:36 UTC
Labels: status:needs-reproducing, Severity:Minor
