### ISSUE TITLE
plugPublicNic forgot to sort the nic devices before plug a new public network

### ISSUE THREAD

**Issue by echoidcf** [apache/cloudstack#4246] opened 2020-08-05 12:04 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
VR
~~~

##### CLOUDSTACK VERSION

~~~
All version is affected
~~~

##### CONFIGURATION

multiple public networks

##### SUMMARY

in this file
`/plugins/hypervisors/vmware/src/main/java/com/cloud/hypervisor/vmware/resource/VmwareResource.java`

```
if (addVif) {
    plugPublicNic(vmMo, vlanId, ip);
    publicNicInfo = vmMo.getNicDeviceIndex(publicNeworkName);
    if (publicNicInfo.first().intValue() >= 0) {
        networkUsage(controlIp, "addVif", "eth" + publicNicInfo.first());
    }
}
```
Whenever a new public nic in VR is needed, plugPublicNic is called.
and plugPublicNic get nic infos via vmware API and did not sort the result. (should be `vmMo.getNicDevices(true)`)
`VirtualDevice[] nicDevices = vmMo.getNicDevices();`

You sort the nic devices in `vmMo.getNicDeviceIndex(publicNeworkName);` like below, why not in `plugPublicNic()`???
`List<VirtualDevice> nics = getNicDevices(true);`

##### STEPS TO REPRODUCE

a normal VR in vcenter should looks like this
![pic2](https://user-images.githubusercontent.com/25361271/89614125-be851500-d8be-11ea-9532-8b8e7499d221.PNG)
this is vmware mob and a vmware api query to the config.hardware.device of the VR should return the same result.

But after something (maybe vcenter restart or esxi host upgrade or etc, we are not sure the exact trigger), it changed like
![pic3](https://user-images.githubusercontent.com/25361271/89614359-381d0300-d8bf-11ea-89a6-feba352bc1b1.PNG)
Then if you trying to use a IP from new CIDR, cloudstack will call plugPublicNic(vmMo, vlanId, ip); to plug the new nic.
plugPublicNic try to get nic list with
`VirtualDevice[] nicDevices = vmMo.getNicDevices();`
and try to connect new port group to 
`VirtualEthernetCard device = (VirtualEthernetCard) nicDevices[nicIndex];` 
(nicIndex will be 3 if eth3(device[4003]) should be next nic)
But because nicDevices looks like 
`[device[4006],device[4005],device[4003],device[4002],device[4000],device[4001],device[4004]]`
nicDevices[3] return device[4002].
Then plugPublicNic will overwrite everything in eth2, and internet access would be down and impact every VM below it.

##### EXPECTED RESULTS

~~~
4003 SHOULD be connected to 2nd public network
~~~

##### ACTUAL RESULTS

~~~
2nd is connected to 4002 and original 4002 configuration is overwrited.
~~~

**Comment by DaanHoogland** [comment] 2020-08-05 12:19
@echoidcf I formatted your description somewhat, but am not entirely clear on the issue yet. sounds seriour can you try to edit your description to be conclusive for anyone picking this up, please?

**Comment by echoidcf** [comment] 2020-08-07 06:22
> @echoidcf I formatted your description somewhat, but am not entirely clear on the issue yet. sounds seriour can you try to edit your description to be conclusive for anyone picking this up, please?

Thank you. I edit the post and add some image, should be better now.

**Comment by rhtyd** [comment] 2020-08-07 07:35
Thanks @echoidcf 
Ping @Spaceman1984 @DaanHoogland or @Pearl1594 @shwstppr - can you have a look at this, we already have example code?

**Comment by Spaceman1984** [comment] 2020-08-07 08:40
@rhtyd I'll take a look

**Comment by rhtyd** [comment] 2020-08-10 07:33
@Spaceman1984 please liase with @Pearl1594 as to who may be picking this up, thanks.

**Comment by Spaceman1984** [comment] 2020-08-11 09:38
@rhtyd, I'm on this one

**Comment by Spaceman1984** [comment] 2020-08-12 09:59
> But after something (maybe vcenter restart or esxi host upgrade or etc, we are not sure the exact trigger), it changed like

@echoidcf I need to know how to get it into this state^^ (restarting the host didn't change the order).
I have found the piece of code you mentioned inside prepareNetworkElementCommand() which is called when a VR is started.
I'm not sure how to get plugPublicNic() called, is there a specific action you take to have addVif be set to true? 

```
if (addVif) {
    plugPublicNic(vmMo, vlanId, ip);
    ...
}
```

From the code it seems as if plugPublicNic() is called when there are no public networks on vsphere.

**Comment by rhtyd** [comment] 2020-08-13 10:47
cc @Pearl1594 can you review @Spaceman1984 's comment and create a PR

**Comment by echoidcf** [comment] 2020-08-18 02:52
> From the code it seems as if plugPublicNic() is called when there are no public networks on vsphere.

When associate a new IP and this IP belongs to a new public network, 
~~~
vmMo.getNicDeviceIndex(publicNeworkName);
~~~
will return -1 and addVif is true, then plugPublicNic() is called.

**Comment by Spaceman1984** [comment] 2020-08-20 05:47
@echoidcf These are the steps I took to try to reproduce this error and was unsuccessful:

* Place a breakpoint in code on the first line inside plugPublicNic() method.
* Deploy a vmware zone.
* Wait for the system VMs to come up, connect and the built-in template to download and install.
* Deploy a new instance using the built-in template.
* Wait for the instance to get deployed.

* Create a new account with admin privileges.
* Create a new public ip range and assign to newly created account.
* Log out and log in with new user.
* Deploy an instance.
* Wait for the instance to get deployed.

In this process the plugPublicNic() method was never called because addVif was always false at the point when the new instance was deployed.

Please post steps how to reproduce.

**Comment by echoidcf** [comment] 2020-08-25 09:25
@Spaceman1984
I think there is some misunderstanding here.
How to call plugPublicNic() is not the concern here, and it is not the problem.
The problem is something wrong happened AFTER the plugPublicNic is called, not how to call it.

If you want to trigger plugPublicNic(), you may try process below
1. add at least TWO public networks in cloudstack
2. associate new IP to VR UNTIL it begin to use IP from second network. (small networks may help)
and voila, plugPublicNic is called.

The real problem is vcenter return [config.hardware.device] may not in original order as I showed above. To fix that, in plugPublicNic() you should use

~~~
VirtualDevice[] nicDevices = vmMo.getNicDevices(true);
~~~
instead of
~~~
VirtualDevice[] nicDevices = vmMo.getNicDevices();
~~~

**Comment by rhtyd** [comment] 2020-08-27 10:09
@echoidcf can you share details on which specific version of CloudStack you're using?

**Comment by echoidcf** [comment] 2020-08-28 09:36
Cloudstack 4.7 (but all version should be affected)
Vmware/vcenter 6.5

The problem is we don't know the exact procedure to make VCenter change the device order like I showed. Maybe a upgrade or   a restart or a failover or something like that. But it do happened (in our production environment about 8k VRs looks like this ).
And cloudstack can simply use 
~~~
VirtualDevice[] nicDevices = vmMo.getNicDevices(true);
~~~
to prevent the problem without side effects.

**Comment by rhtyd** [comment] 2020-09-22 07:52
I did static code analysis and see no harm in including the change as long as regression tests pass. I'll raise a PR

**Closed** 2020-09-24 05:29 UTC
Labels: Severity:Major, component:virtual-router, component:vmware, type:bug
