### ISSUE TITLE
DRS failed for cluster if have another cluster in zone

### ISSUE THREAD

**Issue by yashi4engg** [apache/cloudstack#8629] opened 2024-02-08 16:17 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### SUMMARY
We have zone1 where we have two clusters ex- cluster01 and cluster02 , 
Where cluster01 have 3 hypervisors with same h/w model and cluster02 has one hypervisor with dfifferent h/w model. 
I have enabled drs setiings in globals setting and then disbaled it for cluster02 in cluster setting "drs.automatic.enable -- false" but enabled for cluster01 .

In the above scenario drs plan failed with below logs - 

2024-02-08 10:26:33,532 DEBUG [c.c.s.ManagementServerImpl] (VMSchedulerPollTask:ctx-0bba1590) (logid:f0f7966b) Hosts having capacity and suitable for migration: [Host {"id":25,"name":"node-cluster01","type":"Routing","uuid":"5d145861-e4ad-4f94-a805-266711321d59"}, Host {"id":40,"name":"node-cluster02","type":"Routing","uuid":"66b47d2a-b047-452c-b5d3-65c160666b50"}, Host {"id":48,"name":"node-cluster01","type":"Routing","uuid":"da1be373-cd08-4ae1-948f-7592daabb3fc"}]
2024-02-08 10:26:33,535 ERROR [o.a.c.c.ClusterDrsServiceImpl] (VMSchedulerPollTask:ctx-0bba1590) (logid:f0f7966b) Unable to generate DRS plans for cluster Cluster-Z01 [id=5366c5fb-0ed0-4caf-b2c7-93ebea15a717]

If i disable host from cluster02 our drs works  as expected and migrated VMs based on load . But when we have both clusters and all nodes in cluster enabled its failed to generate plan. 

Below are cluster level settings for reference from DB. 
621 |          1 | drs.automatic.enable                                               | true                                                 |
| 622 |          1 | drs.automatic.interval                                             | 10                                                   |
| 623 |          1 | drs.imbalance                                                      | 0.4                                                  |
| 624 |         16 | drs.automatic.enable                                               | false

Even tried by keep it disabled in global settings and then enable it for just one cluster in cluster settings. 

As our use case is where we have multiple clusters in same zone with different type of h/w. 

##### EXPECTED RESULTS

~~~

~~~

~~~

**Comment by rohityadavcloud** [comment] 2024-02-08 17:43
cc @vishesh92

**Comment by vishesh92** [comment] 2024-02-08 20:30
@yashi4engg I am not able to reproduce the issue. DRS runs independently for each cluster and this shouldn't be happening.

Can you share the complete logs including the error as well as more details about your clusters?

**Comment by yashi4engg** [comment] 2024-02-08 21:16
@vishesh92  -- While trying to reproduce above error I am in another issue where when trying to migrate VMs back to one node getting below error - '

2024-02-08 16:12:14,043 INFO  [o.a.c.f.j.i.AsyncJobMonitor] (Work-Job-Executor-4:ctx-d7001bd1 job-297243/job-297244) (logid:71937cca) Remove job-297244 from job monitoring
2024-02-08 16:12:14,081 ERROR [c.c.a.ApiAsyncJobDispatcher] (API-Job-Executor-4:ctx-e6ce6a44 job-297243) (logid:71937cca) Unexpected exception while executing org.apache.cloudstack.api.command.admin.vm.MigrateVMCmd
com.cloud.utils.exception.CloudRuntimeException: API failed due to: {"message":"The license has expired","httpStatusCode":500,"errorCode":159}
	at org.apache.cloudstack.storage.datastore.driver.ScaleIOPrimaryDataStoreDriver.grantAccess(ScaleIOPrimaryDataStoreDriver.java:206)
	at org.apache.cloudstack.storage.volume.VolumeServiceImpl.grantAccess(VolumeServiceImpl.java:249)
	at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.prepareForMigration(VolumeOrchestrator.java:1512)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy227.prepareForMigration(Unknown Source)
	at com.cloud.vm.VirtualMachineManagerImpl.migrate(VirtualMachineManagerImpl.java:2731)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrate(VirtualMachineManagerImpl.java:2680)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrate(VirtualMachineManagerImpl.java:5484)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
	at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5581)
	at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:654)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:602)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.cloudstack.api.ServerApiException: API failed due to: {"message":"The license has expired","httpStatusCode":500,"errorCode":159}
	at org.apache.cloudstack.storage.datastore.client.ScaleIOGatewayClientImpl.checkResponseOK(ScaleIOGatewayClientImpl.java:263)
	at org.apache.cloudstack.storage.datastore.client.ScaleIOGatewayClientImpl.processResponse(ScaleIOGatewayClientImpl.java:359)
	at org.apache.cloudstack.storage.datastore.client.ScaleIOGatewayClientImpl.post(ScaleIOGatewayClientImpl.java:342)
	... 39 more

**Comment by vishesh92** [comment] 2024-02-12 19:26
@yashi4engg The error log you have shared seems to be truncated. Can you share the complete error log?
Also, a cloudstack cluster supports only one hypervisor. It's possible the error is happening because of your current setup. The complete error logs might help in identifying the issue.

**Comment by yashi4engg** [comment] 2024-02-14 14:33
We were able to fix above errors and good to close this. 

Now DRS is working as expected for us . It was due to zone level storage pool.

**Comment by yashi4engg** [comment] 2024-04-16 16:16
@vishesh92  -- it works fine where we have primary storage as NFS ..But its not working where we are using OCFS2 FS as primary storage pool in cluster.Even while generating DRS plan manually i am not seeing error it shows success but not getting any plan . 

below are logs - 
[root@test01 ~]# cat /var/log/cloudstack/management/management-server.log |grep -i edcf30ae
2024-04-16 10:43:57,568 DEBUG [o.a.c.c.ClusterDrsServiceImpl] (VMSchedulerPollTask:ctx-cf16f762) (logid:edcf30ae) ClusterDRS.poll is being called at 2024-04-16 14:44:00 GMT
2024-04-16 10:43:57,579 DEBUG [o.a.c.c.ClusterDrsServiceImpl] (VMSchedulerPollTask:ctx-cf16f762) (logid:edcf30ae) Removed 0 old drs migration plans
[root@test01 ~]# cat /var/log/cloudstack/management/management-server.log |grep -i edcf30ae
2024-04-16 10:43:57,568 DEBUG [o.a.c.c.ClusterDrsServiceImpl] (VMSchedulerPollTask:ctx-cf16f762) (logid:edcf30ae) ClusterDRS.poll is being called at 2024-04-16 14:44:00 GMT
2024-04-16 10:43:57,579 DEBUG [o.a.c.c.ClusterDrsServiceImpl] (VMSchedulerPollTask:ctx-cf16f762) (logid:edcf30ae) Removed 0 old drs migration plans


where as in my cluster VM count is like, i set drs.imbalance to 1.0 as well - 
node1 - 150VM 
node2 - 150 VM
node3 - 1 VM

**Comment by vishesh92** [comment] 2024-06-08 09:08
@yashi4engg Are you able to manually migrate a VM to another host in your cluster?

**Comment by vishesh92** [comment] 2024-06-13 09:49
@yashi4engg It's good to know that you are interested in DRS. But please open a different issue or a discussion if the problem is different. It makes it easier for the community to manage the issues.

There were some changes in https://github.com/apache/cloudstack/pull/8521 which will be released as part of 4.19.1.0 release. I am not sure if this will fix your issue or not. You can try out the current 4.19 branch to check.

Apart from this can you share the below information?
* Which `drs.algorithm` are you using?
* Are all the hosts in the cluster homogeneous? Details about the host & VMs CPU/memory deployed in the cluster.

**Comment by DaanHoogland** [comment] 2024-06-18 06:30
@yashi4engg do you have the possibility to test PR #9243?

**Comment by sureshanaparti** [comment] 2024-06-25 20:42
Closing this, fixed in #9245. @yashi4engg you can create another issue with any other DRS issues/improvements.

**Closed by sureshanaparti** 2024-06-25 20:42 UTC
Labels: component:drs
