### ISSUE TITLE
usage server broken in 4.12.0.0

### ISSUE THREAD

**Issue by konstantinjfk** [apache/cloudstack#3203] opened 2019-03-08 09:22 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME
Usage server
~~~

~~~

##### CLOUDSTACK VERSION

version 4.12, downloaded from official repo 

##### CONFIGURATION
vanilla install

##### OS / ENVIRONMENT
Centos 7

##### SUMMARY
Usage server not starting jobs and ignore any db.usage settings

[root@ref-trl-1013-k-M7-apanic-mgmt1 usage]# grep -i usage /etc/cloudstack/usage/db.properties | grep invalid
db.usage.name=invalid_database_name
db.usage.port=invalid_port
db.usage.username=invalid_username
db.usage.password=invalid_password!
[root@ref-trl-1013-k-M7-apanic-mgmt1 usage]# tail -n 5 /var/log/cloudstack/usage/usage.log
2019-03-07 22:40:36,738 INFO  [cloud.usage.UsageManagerImpl] (main:null) (logid:) Implementation Version is 4.12.0.0
2019-03-07 22:40:37,569 DEBUG [cloud.usage.UsageManagerImpl] (main:null) (logid:) Usage stats aggregation time zone: GMT
2019-03-07 22:40:37,570 DEBUG [cloud.usage.UsageManagerImpl] (main:null) (logid:) Execution Time: Thu Mar 07 22:28:00 UTC 2019
2019-03-07 22:40:37,570 DEBUG [cloud.usage.UsageManagerImpl] (main:null) (logid:) Current Time: Thu Mar 07 22:40:37 UTC 2019
2019-03-07 22:40:37,575 INFO  [cloud.usage.UsageServer] (main:null) (logid:) UsageServer ready..

##### STEPS TO REPRODUCE
try to install usage server from http://download.cloudstack.org/centos7/4.12/
and force it to proceed with usage records, no luck
My info here in user mail list
http://mail-archives.apache.org/mod_mbox/cloudstack-users/201903.mbox/%3CVI1PR07MB4816C12D23D511AD0904D9D9E44C0%40VI1PR07MB4816.eurprd07.prod.outlook.com%3E

##### EXPECTED RESULTS

~~~
usage server need to be fixed. That is show stopper for the release
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by andrijapanicsb** [comment] 2019-03-08 11:22
Confirmed the issue myself as well. 
Changed to DB properties (setting invalid user/pass/ip/port) and immediately restarting usage server did NOT raise an exception, but after leaving it over night, and restarting it again in the morning (usage server), it did detect invalid settings, and logged lines "failing back to default settings of cloud/cloud/localhost/3306 - which happened to be in place in my test env)

Additional info,  after setting aggregation period to 60 (execute usage jobs every hour) - usage server never actually run a job even after 8h...

**Comment by konstantinjfk** [comment] 2019-03-08 11:36
Here is 4.12.0.0 debug and trace log files, as requested

Not so much info here

https://pastebin.com/89XycZgq


Is you can see, I updated usage.stats.job.exec.time every time before usage server start to force job start

There is nothing after line

(main:null) (logid:) UsageServer ready...

in both cases.

in the same time the version 4.11.2 with same approach, when I changed usage.stats.job.exec.time to the next minute at the start moment gave me this result:

https://pastebin.com/DiLU2vHn

As you can see, the job started and proceed as it should be

I made the test on same VM, by replacing the repos from 11.2.0 to 12.0.0 and back and reinstalling usage server without any changes to other software

bug is in cloudstack-usage-4.12.0.0-1.el7.centos.x86_64
this version works fine cloudstack-usage-4.11.2.0-1.el7.centos.x86_64

**Comment by ustcweizhou** [comment] 2019-03-08 14:05
@konstantinjfk /etc/cloudstack/usage/db.properties should be linked to /etc/cloudstack/management/db.properties
```
# ls -l /etc/cloudstack/usage/db.properties
lrwxrwxrwx 1 root root 40 Feb 28 09:55 /etc/cloudstack/usage/db.properties -> /etc/cloudstack/management/db.properties
```

**Comment by GabrielBrascher** [comment] 2019-03-08 20:23
The error is happening since when we migrated to systemd service. I will link a PR fixing it as soon as possible.

**Comment by GabrielBrascher** [comment] 2019-03-11 03:43
@konstantinjfk @andrijapanic please review PR #3207.

**Comment by GabrielBrascher** [comment] 2019-03-15 15:07
#3210 fixes this issue and it has been merged. Thanks for reporting this issue. RC5 is available for VOTE under the mail `[VOTE] Apache CloudStack 4.12.0.0 [RC5]`, sent to _users_ and _dev_ CloudStack mailing lists.

Git Branch: 4.12.0.0-RC20190314T1011
https://github.com/apache/cloudstack/tree/4.12.0.0-RC20190314T1011
https://gitbox.apache.org/repos/asf?p=cloudstack.git;a=shortlog;h=refs/heads/4.12.0.0-RC20190314T1011

Commit: a137398bf106028d2fd5344d599fcd2b560d2944

Source release for 4.12.0.0-RC20190314T1011:
https://dist.apache.org/repos/dist/dev/cloudstack/4.12.0.0/

PGP release keys (signed using 25908455):
https://dist.apache.org/repos/dist/release/cloudstack/KEYS

The vote will be open for 3 business days (until 19th March).

**Closed by GabrielBrascher** 2019-03-15 15:07 UTC
Labels: BLOCKER, bug, usage-server
