### ISSUE TITLE
dozens WARN messages:  Commit called when it is not a transaction

### ISSUE THREAD

**Issue by izenk** [apache/cloudstack#3051] opened 2018-11-23 10:01 UTC
##### ISSUE TYPE

 * Other

##### COMPONENT NAME

~~~
Management Server
~~~

##### CLOUDSTACK VERSION

~~~
4.11.1
~~~

##### OS / ENVIRONMENT

CentOS 7.4

##### SUMMARY

There are a lot of WARN messages in management server log
~~~
2018-11-23 10:58:35,883 WARN  [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ae5916c5) (logid:216ab687) txn: Commit called when it is not a transaction:
2018-11-23 10:58:35,917 WARN  [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ae5916c5) (logid:216ab687) txn: Commit called when it is not a transaction:
2018-11-23 10:58:35,920 WARN  [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ae5916c5) (logid:216ab687) txn: Commit called when it is not a transaction:
2018-11-23 10:58:35,954 WARN  [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ae5916c5) (logid:216ab687) txn: Commit called when it is not a transaction:
2018-11-23 10:58:35,957 WARN  [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ae5916c5) (logid:216ab687) txn: Commit called when it is not a transaction:
2018-11-23 10:58:35,991 WARN  [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ae5916c5) (logid:216ab687) txn: Commit called when it is not a transaction:
2018-11-23 10:58:35,994 WARN  [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ae5916c5) (logid:216ab687) txn: Commit called when it is not a transaction:
2018-11-23 10:58:36,028 WARN  [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ae5916c5) (logid:216ab687) txn: Commit called when it is not a transaction:
2018-11-23 10:58:36,031 WARN  [c.c.u.d.T.Transaction] (ResourceCountChecker-1:ctx-ae5916c5) (logid:216ab687) txn: Commit called when it is not a transaction:
~~~

**Comment by rhtyd** [comment] 2018-11-23 13:08
Can you test 4.11.2? This was likely fixed in 4.11.2.

**Comment by rhtyd** [comment] 2019-05-27 13:44
Probably a non-issue, needs testing on latest master.

**Comment by rhtyd** [comment] 2019-06-25 10:30
Not able to reproduce it.

**Closed by rhtyd** 2019-06-25 10:30 UTC
