### ISSUE TITLE
secondarystoragevm dont trigger when something (ISO or Template) is uploaded 

### ISSUE THREAD

**Issue by abdelouahabb** [apache/cloudstack#5315] opened 2021-08-16 02:07 UTC
Cloudstack 4.15.1

I try to upload an ISO to create a VM,
But there is a problem, it seems SSVM dont get triggered as there is nothing happening, result, nothing is uploaded, but from the interface, everything went fine !

![Screenshot_20210816_025414](https://user-images.githubusercontent.com/2527234/129501866-411b74b7-ec9c-4e74-ae52-508a17ba6874.png)

Here is the error : 

![iso](https://user-images.githubusercontent.com/2527234/129501884-c110b727-dadc-4bc2-bf46-d4452624f25c.png)

And 

![systemvm](https://user-images.githubusercontent.com/2527234/129501899-18c07923-d310-40eb-b651-40784c94860f.png)

And when I did the debug, nothing is wrong with the SSVM

![isooo](https://user-images.githubusercontent.com/2527234/129501943-d34c1a02-1e88-4fa9-adb1-61c1c8a68e29.png)

And the log like nothing is happening from inside the SSVM
![Screenshot_20210816_030446](https://user-images.githubusercontent.com/2527234/129501996-7398e770-1ae4-4108-85d7-e2a7d5d0bf41.png)

from the MS

![Screenshot_20210816_030653](https://user-images.githubusercontent.com/2527234/129502133-a31a00e5-8ea1-4fd7-bb22-274aebc06a6d.png)

Update :

It seems it got uploaded when i tried `/usr/share/cloudstack-common/scripts/storage/secondary/installIso.sh` script, (did a `find` command and found it in the secondary mount point), but I cant find it displayed

![Screenshot_20210816_043134](https://user-images.githubusercontent.com/2527234/129508021-ca3c75ec-a02a-4ed7-aec5-5d25f9150521.png)

![Screenshot_20210816_045054](https://user-images.githubusercontent.com/2527234/129509133-b403e543-a2c4-4ec8-a8d8-b4cd3cbbfdda.png)

But display nothing

![Screenshot_20210816_043210](https://user-images.githubusercontent.com/2527234/129508073-aa314a43-0da3-41c0-b47a-6312a998406f.png)

![Screenshot_20210816_043516](https://user-images.githubusercontent.com/2527234/129508199-83973697-414f-4e98-b426-26bd39b4803b.png)

**Comment by weizhouapache** [comment] 2021-08-16 09:17
@abdelouahabb 
have you uploaded SSL certificates for systemvms ?
refer to https://www.shapeblue.com/securing-cloudstack-4-11-with-https-tls/

**Comment by abdelouahabb** [comment] 2021-08-16 13:40
> @abdelouahabb
> have you uploaded SSL certificates for systemvms ?
> refer to https://www.shapeblue.com/securing-cloudstack-4-11-with-https-tls/

Why this is not disabled by default, and in all tutorials there is nothing about this important notice ?

The first thing anyone will do, is to upload an iso or an old virtual disk, and because there is no certificate (and all tutorials dont talk about this), he will be stuck ?

**Comment by abdelouahabb** [comment] 2021-08-17 03:11
Update,
Followed the tutorial [This one uses the new interface](http://docs.cloudstack.apache.org/en/latest/adminguide/systemvm.html?highlight=ssl#using-a-ssl-certificate-for-the-console-proxy) and dident work, From [Here, I cant use a self signe certificate (need to buy one ?)](https://cwiki.apache.org/confluence/display/CLOUDSTACK/Procedure+to+Replace+realhostip.com+with+Your+Own+Domain+Name) , 

So, I disabled the settings and it seems this is the default :

> **NOTE - In case you don't want SSL communication for the impacted functionalities you may disable SSL completely by setting `secstorage.encrypt.copy to "false",` and changing `consoleproxy.url.domain to empty.`** and still getting the error ...
![Screenshot_20210817_035441](https://user-images.githubusercontent.com/2527234/129657537-1c92ac9c-4e60-4293-b3e4-a2da3d335d1d.png)

The error happens as soon as I click on Upload, it seems it doesent event get to the server (tried on Chrome and Firefox, same error) !
![Screenshot_20210817_041040](https://user-images.githubusercontent.com/2527234/129657822-1312051c-e2bf-4fe3-a773-a9bb1c11da8c.png)

**Comment by weizhouapache** [comment] 2021-08-17 14:25
> Update,
> Followed the tutorial [This one uses the new interface](http://docs.cloudstack.apache.org/en/latest/adminguide/systemvm.html?highlight=ssl#using-a-ssl-certificate-for-the-console-proxy) and dident work, From [Here, I cant use a self signed certificate (need to buy one ?)](https://cwiki.apache.org/confluence/display/CLOUDSTACK/Procedure+to+Replace+realhostip.com+with+Your+Own+Domain+Name) ,
> 
> So, I disabled the settings and it seems this is the default :
> 
> > **NOTE - In case you don't want SSL communication for the impacted functionalities you may disable SSL completely by setting `secstorage.encrypt.copy to "false",` and changing `consoleproxy.url.domain to empty.`** and still getting the error ...
> > ![Screenshot_20210817_035441](https://user-images.githubusercontent.com/2527234/129657537-1c92ac9c-4e60-4293-b3e4-a2da3d335d1d.png)
> 
> The error happens as soon as I click on Upload, it seems it doesent event get to the server (tried on Chrome and Firefox, same error) !
> ![Screenshot_20210817_041040](https://user-images.githubusercontent.com/2527234/129657822-1312051c-e2bf-4fe3-a773-a9bb1c11da8c.png)
> 
> Is there a way I can debug this to see explicit error ?

@abdelouahabb as far as I know, you need to enable ssl to support uploading template/iso from local.

**Comment by abdelouahabb** [comment] 2021-08-18 01:13
> > Update,
> > Followed the tutorial [This one uses the new interface](http://docs.cloudstack.apache.org/en/latest/adminguide/systemvm.html?highlight=ssl#using-a-ssl-certificate-for-the-console-proxy) and dident work, From [Here, I cant use a self signed certificate (need to buy one ?)](https://cwiki.apache.org/confluence/display/CLOUDSTACK/Procedure+to+Replace+realhostip.com+with+Your+Own+Domain+Name) ,
> > So, I disabled the settings and it seems this is the default :
> > > **NOTE - In case you don't want SSL communication for the impacted functionalities you may disable SSL completely by setting `secstorage.encrypt.copy to "false",` and changing `consoleproxy.url.domain to empty.`** and still getting the error ...
> > > ![Screenshot_20210817_035441](https://user-images.githubusercontent.com/2527234/129657537-1c92ac9c-4e60-4293-b3e4-a2da3d335d1d.png)
> > 
> > 
> > The error happens as soon as I click on Upload, it seems it doesent event get to the server (tried on Chrome and Firefox, same error) !
> > ![Screenshot_20210817_041040](https://user-images.githubusercontent.com/2527234/129657822-1312051c-e2bf-4fe3-a773-a9bb1c11da8c.png)
> > Is there a way I can debug this to see explicit error ?
> 
> @abdelouahabb as far as I know, you need to enable ssl to support uploading template/iso from local.

So does it means, it cant be used in closed network with a self signed certificate or using an IP instead of DNS ?

**Comment by Hudratronium** [comment] 2021-09-25 23:43
The "trick" is to download an existing templete from the ssvm
take a look at the following link - there the needed steps are descriped as well the actual "cause".

https://github.com/apache/cloudstack/issues/4169

**Comment by abdelouahabb** [comment] 2021-09-27 01:10
> The "trick" is to download an existing templete from the ssvm
> take a look at the following link - there the needed steps are descriped as well the actual "cause".
> 
> #4169

But this will be perfect if it is a simple choice to enable/disable tls ?

**Comment by Hudratronium** [comment] 2021-09-27 11:18
I guess this is going into the "convenience vs security" discussion. I can see your point - i've had the same trouble. But i can also understand why it is realized.
Other thing would be to integrate a "new" certificate. But well, someone would need to sponsor this i guess.
It would be a feature mainly used in non-productive environments - so for testing and validation purposes.
Support your opinion regarding the docs - you can contribute to the docs and throw in some sentences about this topic if you would like to.

**Comment by MejdiB** [comment] 2021-12-16 14:04
I am getting the same error, no matter if I enable ssl for secstorage or not. Under Infrastructure --> SSL certificate I have uploaded a certificate for consoleproxy and secstorage vm. Both system vms have a fqdn. The Console Proxy works fine with SSL, but uploading an ISO file is not working.

**Comment by rohityadavcloud** [comment] 2022-08-17 12:20
We're not able to reproduce this, any further updates on this @abdelouahabb @MejdiB @Hudratronium ?

**Comment by Hudratronium** [comment] 2022-08-17 20:16
@rohityadavcloud Can't give any news on this, as we didn't needed to build up a complete new environment since then.
Just a wild guess as i don't know the test environment:
Did you check that the "*.realhostip.com" - certificate is not somewhere defined in the browser certificate store as an trusted certificate or exception?
Basically the mentioned workaround was / is  exactly this:
- Browse the public side of the SVMM
- When the warning appears, that the certificate isn't valid --> confirm you are excepting it
- Use the browsersession to upload an Image as the certificate is now trusted

**Comment by MejdiB** [comment] 2022-08-26 10:20
@rohityadavcloud After a fresh ACS 4.16.1 installation we uploaded the certificates again for SSVM and CPVM. Local upload of volumes and ISOs is now working.

**Comment by rohityadavcloud** [comment] 2022-08-26 11:00
Thanks @MejdiB let's close this as env issue since you're not able to reproduce the issue now and it's working as expected.

**Closed by rohityadavcloud** 2022-08-26 11:00 UTC
