### ISSUE TITLE
An error occurred when creating and mounting a 3T disk. The device 0 is invalid

### ISSUE THREAD

**Issue by itgyn** [apache/cloudstack#6494] opened 2022-06-24 03:34 UTC
##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~
api
~~~

##### CLOUDSTACK VERSION

~~~
4.17
~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~
An error occurred when creating and mounting a 3T disk. The device 0 is invalid
~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by shwstppr** [comment] 2022-06-24 07:34
@itgyn can you please share more details such as hypervisor, error from management and agent (if applicable) logs, etc

**Comment by itgyn** [comment] 2022-06-24 07:40
> @itgyn can you please share more details such as hypervisor, error from management and agent (if applicable) logs, etc
Mount disks larger than 3T on cloudstack. Vmware6.7 error message for Virtualization: failed to create volume: Java lang.runtimeexception: invalid configuration for device '0'.

**Comment by harikrishna-patnala** [comment] 2022-07-07 05:54
Hi @itgyn, I've tried to create and attach a 3TB disk to a VM and is successful. Can you please try it again with a new VM and check if the issue is consistent across all VMs and disks. 
Can you also check if this is something related to this article https://kb.vmware.com/s/article/77134. I've tried both with 6.7u3 and 7.0 versions, it worked fine.

**Comment by itgyn** [comment] 2022-07-07 06:17
Thank you very much. My version of wmware is a little low. Mine is 6.5

**Comment by harikrishna-patnala** [comment] 2022-07-07 06:26
Is this reproducible with other VMs?

**Comment by itgyn** [comment] 2022-07-07 06:34
Yes, it's OK to expand the data disk by 3T, but as long as the disk is attached to the virtual machine for the first time, it will report that device 0 is invalid

**Comment by harikrishna-patnala** [comment] 2022-07-07 07:28
I've tried with 6.5 version too and it worked fine. Can you try with some other setup or upgrade your Vmware version and check once.
I'm assuming you have already checked what I've asked,
1. You could reproduce the issue with any VM.
2. You are observing only with 3TB disks, lower size disks are attaching fine.

Please check various combinations of tests please provide some pinpointers to the issue, since I could not reproduce the issue.

**Comment by itgyn** [comment] 2022-07-07 07:31
Do you operate through cloudstack?

**Comment by harikrishna-patnala** [comment] 2022-07-07 07:34
Yes, creating VM, disks, attach, detach operations I'm trying from CloudStack. 
Aren't you trying these from CloudStack ?

**Comment by rohityadavcloud** [comment] 2022-07-07 07:34
Hi @itgyn yes, we're the contributors (committers and PMCs) of the project. Could you check if this relates to your issue https://github.com/apache/cloudstack/issues/6492

We're assuming this is a data disk that you've created and attached, @harikrishna-patnala did you try the same (i.e. create 3T datadisk and attach to a VM?).

**Comment by itgyn** [comment] 2022-07-07 07:36
Thank you very much. Let me verify it here

**Comment by harikrishna-patnala** [comment] 2022-07-26 03:57
@itgyn I'm closing this issue as I could not reproduce it. Please feel free to reopen if you still face the issue with CloudStack.

**Closed by harikrishna-patnala** 2022-07-26 03:57 UTC
