### ISSUE TITLE
[Vmware] ISO gets detached after stop and start VM

### ISSUE THREAD

**Issue by nvazquez** [apache/cloudstack#4082] opened 2020-05-12 16:33 UTC
ISO is detached after stop and start a VM

##### ISSUE TYPE
 * Bug Report

##### COMPONENT NAME
~~~
API, UI
~~~

##### CLOUDSTACK VERSION
~~~
4.13.0.0
~~~

##### OS / ENVIRONMENT
Vmware hypervisor -  tested on version 6.7

##### SUMMARY
After stopping a VM with ISO attached, the ISO remains attached, however after starting the VM then the ISO is detached. **(then detach ISO also fails)**

After starting the VM - CloudStack shows the ISO is attached:
![image](https://user-images.githubusercontent.com/5295080/81720276-8fdcd700-9454-11ea-9856-f8b6acba63f9.png)

vCenter shows no ISO attached:
![image](https://user-images.githubusercontent.com/5295080/81720374-b6027700-9454-11ea-9041-8464c39dc0c0.png)

##### STEPS TO REPRODUCE
~~~
Deploy VM
Attach ISO
Stop VM
Start VM
~~~

##### EXPECTED RESULTS
~~~
ISO is attached
~~~

##### ACTUAL RESULTS
~~~
ISO shown as attached in CloudStack but actually not attached (images above)
~~~

**Comment by Spaceman1984** [comment] 2020-05-20 11:47
Tested in 4.13.1.0 and master, not an issue. Only reproducible in 4.13.0.0

**Comment by andrijapanicsb** [comment] 2020-06-02 12:10
> Tested in 4.13.1.0 and master, not an issue. Only reproducible in 4.13.0.0

@Spaceman1984 were you able to reproduce the issue in 4.13.0.0?

**Comment by Spaceman1984** [comment] 2020-06-02 12:12
Yes @andrijapanicsb

**Comment by andrijapanicsb** [comment] 2020-06-02 12:47
Observation on 4.14:

- CentOS 5.5 default template (no VMware tools)

VM is rebooted via ACS GUI (Reboot Instance) - API call is sent to VMware to reboot guest OS, but since VMware tools are NOT running, vSphere (6.7 !) decides to "Reset Virtual Machine"
This looks to be different then the Power Off / Power On actions in vSphere (6.7 U3 tested), because the ISO is still marked to NOT be connected on power on, but the ISO is still mounted/attached and the VM can boot from this ISO.

The versions before 6.7 might have different behaviour here - so still the proper way to fix this is to make sure that when ISO is attached via ACS, not only it's attached ad-hoc to the VM, but that also the "Connect at Power On" is active/checked.

**Comment by andrijapanicsb** [comment] 2020-06-02 13:13
The user was testing 4.13.0.0 with vSphere 6.0 and 6.7xxx and when VM power reset happens, the ISO path is still present, but the ISO is NOT "Connected"

**Comment by rhtyd** [comment] 2020-08-19 09:10
@Spaceman1984 does it apply to 4.14 or master? If not, can we close it?

**Comment by Spaceman1984** [comment] 2020-08-20 10:26
I will test with 4.14 and latest master.

**Comment by rhtyd** [comment] 2020-08-27 10:24
Closing on @Spaceman1984 's remarks

**Closed by rhtyd** 2020-08-27 10:24 UTC
Labels: Severity:Major, component:vmware
