### ISSUE TITLE
Instructions required to run reproducible system integration tests or their subset against a test instance on a custom configuration

### ISSUE THREAD

**Issue by synergiator** [apache/cloudstack#8179] opened 2023-11-02 13:04 UTC
##### ISSUE TYPE
 * Other

##### COMPONENT NAME
~~~
Sytem integation testing wrt general /all
~~~

##### CLOUDSTACK VERSION

~~~
4.17.1 and upwards
~~~

##### SUMMARY

Requirement: need to run existing system integration tests, or their subset, against an existing test instance.
One main feature is that it uses vmware hypervisor.
What needs to be done to setup a test system and configure it to access that test instance?

##### STEPS TO REPRODUCE
What I have done so far: followed a GitHub workflow test iteration e.g.

~~~
# https://github.com/apache/cloudstack/actions/runs/5963475928/workflow
...
mvn clean install -am -Dsimulator -Dnoredist -P developer,systemvm -pl plugins/hypervisors/kvm
mvn clean install -am -Dsimulator -Dnoredist -P developer,systemvm -pl plugins/hypervisors/vmware

~~~

Also, I've tried to run a Python test manually in a cloned repo for the branch 4.17.1:
~~~
> python3 test_volumes.py
~~~

##### EXPECTED RESULTS
I thought that anything will happen, ending in an error like "can't access test system" or similar.

##### ACTUAL RESULTS
Immediate process breakup:
~~~
> mvn clean install -am -Dsimulator -Dnoredist -P developer,systemvm -pl plugins/hypervisors/vmware
> org.apache.maven.MavenExecutionException: Could not find the selected project in the reactor: plugins/hypervisors/
~~~
For the manual test:
~~~
> python3 test_volumes.py
> [WARNING]: cannot initiate Sentry error reporting: [Errno 6] No such device or address. (UserWarning)
> ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)

~~~

##### Final thoughts
As it seems [1] the jinja dependency error comes from the fact that the environment uses Flask 1.x. and Jinja2 3.x which are not compatible through the reqired "escape" component by Flask which has been dropped in Jinja.

[1] https://stackoverflow.com/questions/71718167/importerror-cannot-import-name-escape-from-jinja2

**Comment by DaanHoogland** [comment] 2023-11-02 14:18
@synergiator
1. as for the first error , i think the issue is that -pl doesn't take a directory but a project name
2. the second, the tests are not plain python but nosetests. I poften have to repeat a single test in our lab and use https://github.com/DaanHoogland/trivia/blob/main/singletest.sh . It does some magic around environ definition that you'll have to mimic so the tests know what for instance you hypervisor type and MS IP are. There are some pages on https://cwiki.apache.org/confluence/display/CLOUDSTACK/QA around this. Some may be outdated but its a good starting point. (be grateful if you poinnt uus to improvements)

**Comment by DaanHoogland** [comment] 2024-01-12 15:19
@synergiator I will close this issue. please reopen if you think it still needs addressing or open a new one if you will.

**Closed by DaanHoogland** 2024-01-12 15:19 UTC
Labels: type:question, component:build
