### ISSUE TITLE
Host metrics show wrong total memory and memory allocation

### ISSUE THREAD

**Issue by Overv** [apache/cloudstack#2684] opened 2018-05-30 15:31 UTC
Our CloudStack 4.10 setup shows the right overall resource metrics in the system capacity listing on the frontpage of the dashboard, but the individual host metrics show very strange values for the memory availability:

![image](https://user-images.githubusercontent.com/285063/40730501-17ddef70-642f-11e8-8cbb-9d6f722de70a.png)

As for the API call, the `memoryTotal` and `memoryAllocated` fields have the value `0`, but strangely the `memorywithoverprovisioning` does show the right value albeit in a different format:

![image](https://user-images.githubusercontent.com/285063/40730560-3f638cbc-642f-11e8-8922-6c3e761fc285.png)

The hosts here are all hosts running CentOS with KVM virtualization.

**Comment by rhtyd** [comment] 2018-05-31 08:29
@Overv what is the `ram` in the hosts table when you added the KVM host?
/cc @PaulAngus @DaanHoogland @borisstoyanov

**Comment by Overv** [comment] 2018-05-31 08:33
In the hosts table the variable `ram` is set to the correct value of `66363973632`, `dom0_memory` is `0`.

**Comment by rhtyd** [comment] 2018-05-31 08:59
@Overv can you do a `list hosts` and `list hostsmetrics` API and share if you see difference in the host total?

**Comment by Overv** [comment] 2018-05-31 10:39
`list hosts` shows

* `memoryallocated=0`
* `memorytotal=0`
* `memoryused=1172013056`
* `memorywithoverprovisioning=6.6363974E10`.

`list hostsmetrics` shows

* `memoryallocated=0`
* `memoryallocatedgb=0.00GB`
* `memorytotal=0`
* `memorytotalgb=0.00GB (x 1.0)`
* `memoryused=1171718144`
* `memoryusedgb=1.09GB`

**Comment by rhtyd** [comment] 2018-05-31 10:42
Thanks for sharing @Overv. The `total` memory value from listHosts and listHostsMetrics is taken from `ram` column of the cloud.hosts table. If you're seeing the value to be 0, we'll need to replicate/investigate this issue. @borisstoyanov can you advise if you seen something like this? /cc @PaulAngus @DaanHoogland

**Comment by rhtyd** [comment] 2018-05-31 10:43
@Overv I re-read your issue statement, are you able to replicate this issue with 4.11 (either 4.11.0.0 or 4.11.1.0-rc1)? 4.10 likely has a bug that was fixed in 4.11+ branch.

**Comment by Overv** [comment] 2018-05-31 16:50
@rhtyd Unfortunately we are currently unable to run 4.11 due to other bugs. Could you point to a commit or issue that may have fixed this problem?

**Comment by rhtyd** [comment] 2018-09-18 10:58
There were several fixes in 4.11, please test in 4.11 and advise how to reproduce @GabrielBrascher @Overv. Thanks.

**Comment by rhtyd** [comment] 2018-10-30 07:14
Can you comment if you can reproduce this with 4.11 @GabrielBrascher @Overv ?

**Comment by rhtyd** [comment] 2018-12-06 19:53
Unable to reproduce with 4.11.2.0, kindly re-open with reproduction steps and upgrade to 4.11.2.0.

**Closed by rhtyd** 2018-12-06 19:53 UTC
