### ISSUE TITLE
UI Login issue when logging out from configuration tab

### ISSUE THREAD

**Issue by rohityadavcloud** [apache/cloudstack#7187] opened 2023-02-10 07:50 UTC
Steps to reproduce:

1. Log in as root admin "admin" account
2.  Go to the global settings (configuration) page
3.  Log out, you'll see some error on loading setting
4. Now you cannot log in, any input fails unless you refresh the page

##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
main/4.18
~~~

**Comment by davidjumani** [comment] 2023-02-13 04:55
@rohityadavcloud I'm unable to reproduce this on latest main. Can you pl check and get back ? Thanks

**Comment by harikrishna-patnala** [comment] 2023-02-13 05:46
@davidjumani I've faced the issue and the reason is list configuration API is called after logout.
I tried to fix it in #7197 PR, please review that.

![image](https://user-images.githubusercontent.com/3348673/218380289-18cc92a6-5b50-4dd7-befa-3289fd4e6e73.png)

**Comment by DaanHoogland** [comment] 2023-02-13 08:01
fixed by #7197

**Closed by DaanHoogland** 2023-02-13 08:01 UTC
Labels: component:UI

**Comment by rohityadavcloud** [comment] 2023-02-13 08:42
Thanks @harikrishna-patnala
