### ISSUE TITLE
No way to fix errors after a failure on 'Add zone' dialog

### ISSUE THREAD

**Issue by vladimirpetrov** [apache/cloudstack#7194] opened 2023-02-10 16:09 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18 nightly
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

If there's a problem during the 'Add zone' process and the user tries to go back to fix them, the dialog gets stuck.

##### STEPS TO REPRODUCE

~~~
Try to add a new advanced (core) zone and deliberately leave some errors in the dialog. After the error message while creating the zone, try to fix them.
~~~

##### EXPECTED RESULTS

~~~
There should be a way to fix the errors.
~~~

##### ACTUAL RESULTS

~~~
The dialog gets stuck with no way to fix the errors. NOTE: It works fine on 4.17.
~~~

One example of an error during zone creation:
![image](https://user-images.githubusercontent.com/12384665/218138806-ee1b9250-3838-4cd7-954b-26fa661bfb61.png)

and the dialog when you try to fix the error:
![image](https://user-images.githubusercontent.com/12384665/218138896-a561cd6c-6bfe-42cc-82a8-2291ae7ebf3a.png)

another example - after a different kind of error:
![image](https://user-images.githubusercontent.com/12384665/218139066-052adfc4-c2c4-49fd-8f86-d88aa291e7a6.png)

**Comment by weizhouapache** [comment] 2023-02-11 08:52
I have faced the same issue

**Comment by rohityadavcloud** [comment] 2023-02-13 08:43
Sounds like a regression

**Comment by DaanHoogland** [comment] 2023-02-13 08:57
Yes @rohityadavcloud , @vladimirpetrov confirmed Friday it did not occur on 4.17

**Comment by weizhouapache** [comment] 2023-02-13 09:03
> Yes @rohityadavcloud , @vladimirpetrov confirmed Friday it did not occur on 4.17

@DaanHoogland yes, it is a regression. I might be caused by tungsten UI. let me check

**Comment by DaanHoogland** [comment] 2023-02-13 10:43
> > Yes @rohityadavcloud , @vladimirpetrov confirmed Friday it did not occur on 4.17
> 
> @DaanHoogland yes, it is a regression. I might be caused by tungsten UI. let me check

no, it was there bofer the tungsten ui was merged

**Comment by shwstppr** [comment] 2023-02-13 11:19
This seems to be brought by #6840. Looking into it

**Closed** 2023-02-13 12:06 UTC
Labels: component:UI
