### ISSUE TITLE
Error when 'createNetwork' with VXLAN: "VLAN requested but URI is not in the expected format"

### ISSUE THREAD

**Issue by GabrielBrascher** [apache/cloudstack#5071] opened 2021-06-03 13:45 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.15.0.0
~~~

##### CONFIGURATION

- Hypervisor: KVM;
- Network: Advanced network;
- Isolation method: VXLAN.

##### OS / ENVIRONMENT

N/A

##### SUMMARY

We are facing some issues when creating new networks on the CloudStack `4.15.0.0` (and they extend to `4.15.1 RC1`, as well as `4.16-SNAPSHOT`); prior to upgrading the same network creation would work; as we had addressed issue #3040 via PR #4190.

This issue seems to be caused due to a validation added in https://github.com/apache/cloudstack/pull/4040. The respective validation checks explicitly for VLAN; source code line can be found at [NetworkDaoImpl.java#L783](https://github.com/apache/cloudstack/blob/937def533aa11b45974ffb82aac14a4da4fc7750/engine/schema/src/main/java/com/cloud/network/dao/NetworkDaoImpl.java#L783)
~~~
    public List<NetworkVO> listByPhysicalNetworkPvlan(long physicalNetworkId, String broadcastUri) {
        final URI searchUri = BroadcastDomainType.fromString(broadcastUri);
->      if (!searchUri.getScheme().equalsIgnoreCase("vlan")) {
            throw new CloudRuntimeException("VLAN requested but URI is not in the expected format: " + searchUri.toString());
        }
        ...
    }
~~~

##### STEPS TO REPRODUCE

~~~
1. Set a Zone with a physical network isolated via VXLAN
2. Create Network passing VLAN ID (either as 'vlan=vxlan://VID' or simply 'vlan=VID')
~~~

##### EXPECTED RESULTS

~~~
The network is created with broadcast URI of vxlan://VID
~~~

##### ACTUAL RESULTS

~~~
Network fails to be created.

LOG:
2021-06-03 11:09:55,724 ERROR [c.c.a.ApiServer] (qtp1665620686-39719:ctx-bf7efb52 ctx-c73431d6 ctx-c4105005) (logid:2252fead) unhandled exception executing api command: [Ljava.lang.String;@6b3403ea
com.cloud.utils.exception.CloudRuntimeException: VLAN requested but URI is not in the expected format: vxlan://525
        at com.cloud.network.dao.NetworkDaoImpl.listByPhysicalNetworkPvlan(NetworkDaoImpl.java:784)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at com.cloud.utils.db.TransactionContextInterceptor.invoke(TransactionContextInterceptor.java:34)
~~~

**Comment by rhtyd** [comment] 2021-06-03 14:07
@GabrielBrascher can you check if it affects 4.15.1.0RC1 too?

**Comment by rhtyd** [comment] 2021-06-03 14:16
cc @weizhouapache

**Comment by wido** [comment] 2021-06-03 14:35
> @GabrielBrascher can you check if it affects 4.15.1.0RC1 too?

Afaik it does

**Comment by weizhouapache** [comment] 2021-06-03 15:19
@rhtyd this seems like a critical issue introduced in 4.15 (#4040 as Gabriel said). I have tested 4.14 which works fine.

**Comment by rhtyd** [comment] 2021-06-03 15:29
@GabrielBrascher are you working on a PR to fix the issue?

**Comment by GabrielBrascher** [comment] 2021-06-03 20:33
@rhtyd I am sorry for the delay. PR ##5074 is out.
I appreciate any test & review :+1:

**Comment by weizhouapache** [comment] 2021-06-04 09:34
@GabrielBrascher 
I was trying to reproduce this issue, but the following works for me
(1) create an advanced zone, use VXLAN for guest networks
(2) create an isolated network, create a vm on it.
both succeed. the bridge information on hosts look good also.

could you give more information of your setup ?
it would be better to share more  logs. Thank you.

**Comment by GabrielBrascher** [comment] 2021-06-04 14:18
@weizhouapache here follows some details:

### Environment
1. CloudStack version: `4.15.0.0` & `4.15.1.0 RC1`
2. Virtualization: KVM
3. Network: Advanced Network with Security Group enabled
4. Isolation: VXLAN

### Cases where I could reproduce the issue
#### 1. Default Guest network is being created while deploying a new Zone via UI wizard:
Command:
```
command=createNetwork
name=defaultGuestNetwork
displaytext=defaultGuestNetwork
zoneid=0f715648-ac24-443d-bbb0-bc51b3c055b9
networkofferingid=6b8dde01-f47a-4dcf-9156-57c4fba9a968
gateway=192.168.100.1
netmask=255.255.255.0
startip=192.168.100.50
endip=192.168.100.99
vlan=0
```
Log:
```
2021-06-03 21:24:49,144 DEBUG [c.c.a.ApiServlet] (qtp2109798150-18:ctx-03f9860b) (logid:2f1fa8b3) ===START===  192.168.100.1 -- GET  zoneid=0f715648-ac24-443d-bbb0-bc51b3c055b9&name=defaultGuestNetwork&displaytext=defaultGuestNetwork&networkofferingid=6b8dde01-f47a-4dcf-9156-57c4fba9a968&gateway=192.168.100.1&netmask=255.255.255.0&startip=192.168.100.50&endip=192.168.100.99&vlan=0&command=createNetwork&response=json
...
...
2021-06-03 21:24:49,299 DEBUG [c.c.a.ApiServlet] (qtp2109798150-16:ctx-44362283 ctx-5eb8df22) (logid:02838213) ===END===  192.168.100.1 -- GET  id=f29edbca-0669-45fb-936e-66ac8784f966&state=Enabled&command=updateNetworkServiceProvider&response=json
2021-06-03 21:24:49,331 DEBUG [c.c.n.NetworkServiceImpl] (API-Job-Executor-10:ctx-582a6615 job-16 ctx-297fe6cd) (logid:f6921c72) trying to update the state of the service provider id=5 on physical network: 200 to state: Enabled
2021-06-03 21:24:49,337 DEBUG [c.c.u.d.T.Transaction] (qtp2109798150-18:ctx-03f9860b ctx-6124ca66) (logid:2f1fa8b3) Rolling back the transaction: Time = 86 Name =  qtp2109798150-18; called by -TransactionLegacy.rollback:888-TransactionLegacy.removeUpTo:831-TransactionLegacy.close:655-Transaction.execute:38-Transaction.execute:47-NetworkOrchestrator.createGuestNetwork:2569-NetworkOrchestrator.createGuestNetwork:2327-NetworkServiceImpl$4.doInTransaction:1502-NetworkServiceImpl$4.doInTransaction:1450-Transaction.execute:40-NetworkServiceImpl.commitNetwork:1450-NetworkServiceImpl.createGuestNetwork:1366
2021-06-03 21:24:49,358 ERROR [c.c.a.ApiServer] (qtp2109798150-18:ctx-03f9860b ctx-6124ca66) (logid:2f1fa8b3) unhandled exception executing api command: [Ljava.lang.String;@56cdd438
com.cloud.utils.exception.CloudRuntimeException: VLAN requested but URI is not in the expected format: vxlan://0
        at com.cloud.network.dao.NetworkDaoImpl.listByPhysicalNetworkPvlan(NetworkDaoImpl.java:784)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
#### 2. creating a new network on an existing Zone (that had been deployed before upgrading to 4.15.0.0)
##### 2.1 via cloudmonkey
Command:
```
create network displaynetwork=true displaytext="New Network" name="New Network" netmask=255.255.255.128 startip=<start-ip> endip=<end-key> gateway=<gateway-ip> vlan=vxlan://123 ip6cidr=<ipv6-cidr> ip6gateway=<ipv6-gateway> networkofferingid=<offering-id> physicalnetworkid=<physical-network-id> zoneid=<zone-id> account=<account-id> domainid=<domain-id>
Error: (HTTP 530, error code 4250) VLAN requested but URI is not in the expected format: vxlan://123
```
Log:
```
2021-06-03 11:09:55,614 DEBUG [c.c.a.ApiServlet] (qtp1665620686-39719:ctx-bf7efb52) (logid:2252fead) ===START=== account=<account-id>&apiKey=<api-key>&command=cre
ateNetwork&displaynetwork=true&displaytext=New+Network&domainid=<domain-id>&endip=<end-key>&gateway=<gateway-ip>&ip6cidr=<ipv6-cidr>&ip6gateway=<ipv6-gateway>&name=New+Network&netmask=255.255.255.
128&networkofferingid=<offering-id>&physicalnetworkid=<physical-network-id>&response=json&startip=<start-ip>&vlan=vxlan%3A%2F%2F123&zoneid=<zone-id>&signature=<signature>
...
...
2021-06-03 11:09:55,724 ERROR [c.c.a.ApiServer] (qtp1665620686-39719:ctx-bf7efb52 ctx-c73431d6 ctx-c4105005) (logid:2252fead) unhandled exception executing api command: [Ljava.lang.String;@6b3403ea
com.cloud.utils.exception.CloudRuntimeException: VLAN requested but URI is not in the expected format: vxlan://123
        at com.cloud.network.dao.NetworkDaoImpl.listByPhysicalNetworkPvlan(NetworkDaoImpl.java:784)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

##### 2.2 via UI
![vxlan-test](https://user-images.githubusercontent.com/5025148/120815526-48752d00-c526-11eb-9db2-4fa4aedcd0d3.jpg)

![vxlan-test-error](https://user-images.githubusercontent.com/5025148/120815538-4ca14a80-c526-11eb-9eae-d0ad01eb679e.jpg)

Log:
```
2021-06-04 16:12:31,123 DEBUG [c.c.a.ApiServlet] (qtp1484673893-19:ctx-41aea465) (logid:c7cf5089) ===START===  192.168.100.1 -- GET  zoneId=4842bfa7-7bd9-471a-bf2a-53ca36aa9e32&name=Test&displayText=Test&networkOfferingId=5a2bbf72-e75b-4d05-8534-beffba874a58&physicalnetworkid=636dabaa-a42e-4415-bec5-a6aa5e273866&vlan=1&bypassvlanoverlapcheck=false&acltype=domain&gateway=192.168.100.1&netmask=255.255.255.0&startip=192.168.100.100&endip=192.168.100.149&command=createNetwork&response=json
2021-06-04 16:12:31,138 DEBUG [c.c.a.ApiServer] (qtp1484673893-19:ctx-41aea465 ctx-8e816eb9) (logid:c7cf5089) CIDRs from which account 'Acct[c1fcecaa-c424-11eb-a265-5254009b3036-admin]' is allowed to perform API calls: 0.0.0.0/0,::/0
2021-06-04 16:12:31,180 DEBUG [c.c.u.AccountManagerImpl] (qtp1484673893-19:ctx-41aea465 ctx-8e816eb9) (logid:c7cf5089) Access granted to Acct[c1fcecaa-c424-11eb-a265-5254009b3036-admin] to [Network Offering [7-Guest-DefaultSharedNetworkOffering] by AffinityGroupAccessChecker
2021-06-04 16:12:31,255 DEBUG [c.c.u.d.T.Transaction] (qtp1484673893-19:ctx-41aea465 ctx-8e816eb9) (logid:c7cf5089) Rolling back the transaction: Time = 53 Name =  qtp1484673893-19; called by -TransactionLegacy.rollback:888-TransactionLegacy.removeUpTo:831-TransactionLegacy.close:655-Transaction.execute:38-Transaction.execute:47-NetworkOrchestrator.createGuestNetwork:2572-NetworkOrchestrator.createGuestNetwork:2327-NetworkServiceImpl$4.doInTransaction:1502-NetworkServiceImpl$4.doInTransaction:1450-Transaction.execute:40-NetworkServiceImpl.commitNetwork:1450-NetworkServiceImpl.createGuestNetwork:1366
2021-06-04 16:12:31,270 ERROR [c.c.a.ApiServer] (qtp1484673893-19:ctx-41aea465 ctx-8e816eb9) (logid:c7cf5089) unhandled exception executing api command: [Ljava.lang.String;@4959b691
com.cloud.utils.exception.CloudRuntimeException: VLAN requested but URI is not in the expected format: vxlan://1
        at com.cloud.network.dao.NetworkDaoImpl.listByPhysicalNetworkPvlan(NetworkDaoImpl.java:784)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
```

**Comment by rhtyd** [comment] 2021-06-04 14:34
Thanks @GabrielBrascher by networks it wasn't clear if you meant Shared network or isolated network. Does this feature work in 4.14 or before?

**Comment by GabrielBrascher** [comment] 2021-06-04 14:39
@rhtyd ah that's the case indeed, shared networks.

It was working in 4.13.1.0; I did not test in 4.14.

**Comment by weizhouapache** [comment] 2021-06-04 15:08
@GabrielBrascher thanks.
I can reproduce the issue when create shared network with vxlan in advanced zone.
I will test the fix.

**Comment by rhtyd** [comment] 2021-06-05 16:55
Fixed by https://github.com/apache/cloudstack/pull/5074

**Closed by rhtyd** 2021-06-05 16:55 UTC
Labels: component:advanced-networking, component:kvm
