### ISSUE TITLE
Zones are returned in a random order

### ISSUE THREAD

**Issue by dpassante** [apache/cloudstack#3934] opened 2020-03-04 17:02 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
API
~~~

##### CLOUDSTACK VERSION

~~~
4.13.0.0
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

`listZones` returns the zones in a "random" order when it has not been explicitly defined with the new sort key feature.

This impacts the correct functioning of the Ansible Cloudstack modules which use the first zone if no zone parameter is given.

##### STEPS TO REPRODUCE

Keep zones unsorted:
~~~
mysql> select id, name, sort_key from data_center;
+----+----------------------------+----------+
| id | name                       | sort_key |
+----+----------------------------+----------+
|  1 | Sandbox-simulator-basic    |        0 |
|  2 | Sandbox-simulator-advanced |        0 |
+----+----------------------------+----------+
2 rows in set (0.00 sec)
~~~

And use a playbook in which the `zone` param is not given.
Several calls to `listZones` also do the trick.

##### EXPECTED RESULTS

A list of zones sorted by SQL ID when no sort key are configured to avoid breaking some existing Ansible deployments.

Ensure that a sort key is automatically incremented for new zones and existing zones in the case of a Cloudstack upgrade could also be a nice feature.

##### ACTUAL RESULTS

~~~
$ for in in `seq 1 1 10`; do cs listZones |grep -m1 name; done
      "name": "Sandbox-simulator-basic",
      "name": "Sandbox-simulator-basic",
      "name": "Sandbox-simulator-basic",
      "name": "Sandbox-simulator-basic",
      "name": "Sandbox-simulator-basic",
      "name": "Sandbox-simulator-basic",
      "name": "Sandbox-simulator-advanced",
      "name": "Sandbox-simulator-advanced",
      "name": "Sandbox-simulator-advanced",
      "name": "Sandbox-simulator-advanced",
~~~

**Comment by dpassante** [comment] 2020-03-05 14:56
In fact, the "problem" seems to come from the fact that zones are created with the sort key 0 which has priority by default.

~~~
+----+--------------------------------------+----------+
| id | name                                 | sort_key |
+----+--------------------------------------+----------+
|  1 | Sandbox-simulator-basic              |        0 |
|  2 | Sandbox-simulator-advanced           |        0 |
|  3 | ansible-test-dpassante-55511421-zone |        0 |
|  4 | ansible-test-dpassante-46776470-zone |        0 |
+----+--------------------------------------+----------+
~~~

The sort keys are not unique, we also have the same behavior when we assign the same rank to 2 zones from the API.

Once the sorting has been done, the new zones are returned first.
~~~
+----+--------------------------------------+----------+
| id | name                                 | sort_key |
+----+--------------------------------------+----------+
|  1 | Sandbox-simulator-basic              |        1 |
|  2 | Sandbox-simulator-advanced           |        2 |
|  3 | ansible-test-dpassante-91763618-zone |        0 |
|  4 | ansible-test-dpassante-38650808-zone |        0 |
+----+--------------------------------------+----------+
~~~

~~~
$ cs listZones |grep name
      "name": "ansible-test-dpassante-38650808-zone",
      "name": "ansible-test-dpassante-91763618-zone",
      "name": "Sandbox-simulator-basic",
      "name": "Sandbox-simulator-advanced",
~~~

**Comment by rhtyd** [comment] 2020-08-05 08:41
@dpassante I tested 4.14/master I'm not able to see this. In UI as root admin you can re-order the zones and the order is honoured.

**Comment by rhtyd** [comment] 2020-08-12 09:16
Tested latest master, could not see the issue.

**Comment by resmo** [comment] 2020-09-25 06:15
I see this with in 4.13.1 

# vmsnapshot test revert snapshot failed

note the zone that chates from basic to advance from first test to second test.
```
TASK [cs_vmsnapshot : test revert snapshot] ************************************
changed: [testhost] => {"account": "admin", "api_http_method": "get", "api_key": "DL3Be8XtxsrKJOMRIIPR_2LUdknE5n8V33u41NWaetVcnKAQTeQhkDDVKAJCIyHV1I4fY3Phw8B49BpSnfLKtg", "api_region": "cloudstack", "api_timeout": 60, "api_url": "http://cloudstack-sim:8888/client/api", "api_verify_ssl_cert": null, "changed": true, "created": "2020-09-24T22:12:33+0000", "current": true, "display_name": "ansible-test-fv-az176-89231118_snapshot", "domain": "ROOT", "id": "230bab25-dcd6-4641-97c5-79396730eef6", "name": "i-2-12-QA_VS_20200924221233", "state": "Ready", "tags": [], "type": "DiskAndMemory", "zone": "Sandbox-simulator-basic"}

TASK [cs_vmsnapshot : verify test revert snapshot] *****************************
ok: [testhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [cs_vmsnapshot : test remove snapshot in check mode] **********************
fatal: [testhost]: FAILED! => {"api_http_method": "get", "api_key": "DL3Be8XtxsrKJOMRIIPR_2LUdknE5n8V33u41NWaetVcnKAQTeQhkDDVKAJCIyHV1I4fY3Phw8B49BpSnfLKtg", "api_region": "cloudstack", "api_timeout": 60, "api_url": "http://cloudstack-sim:8888/client/api", "api_verify_ssl_cert": null, "changed": false, "msg": "Virtual machine 'ansible-test-fv-az176-89231118-vm-snapshot' not found", "zone": "Sandbox-simulator-advanced"}
```

but seems not to happen always, another test run passes.
```
 TASK [cs_vmsnapshot : test remove snapshot in check mode] **********************
changed: [testhost] => {"account": "admin", "api_http_method": "get", "api_key": "DL3Be8XtxsrKJOMRIIPR_2LUdknE5n8V33u41NWaetVcnKAQTeQhkDDVKAJCIyHV1I4fY3Phw8B49BpSnfLKtg", "api_region": "cloudstack", "api_timeout": 60, "api_url": "http://cloudstack-sim:8888/client/api", "api_verify_ssl_cert": null, "changed": true, "created": "2020-09-24T22:10:49+0000", "current": true, "display_name": "ansible-test-fv-az76-30345916_snapshot", "domain": "ROOT", "id": "4013a799-6d7c-442c-8906-1a6162e3086e", "name": "i-2-14-QA_VS_20200924221049", "state": "Ready", "tags": [], "type": "DiskAndMemory", "zone": "Sandbox-simulator-basic"}
```

**Comment by rvalle** [comment] 2020-09-28 10:27
@resmo @rhtyd 

The result that @resmo expect, or ansible modules expect, would require zones to be sorted by the expression (sortkey,id), as you know when sortkey has the same value, id is used... etc.

So I have been looking at the code to check what the actual implemented order criteria is:

looks to me like the method is here: https://github.com/apache/cloudstack/blob/82b6971258a2f63360dbd0cb404fcf87669a5327/server/src/main/java/com/cloud/api/query/QueryManagerImpl.java#L3053

But this method seems to rely on an utility: 

https://github.com/apache/cloudstack/blob/82b6971258a2f63360dbd0cb404fcf87669a5327/server/src/main/java/com/cloud/api/query/QueryManagerImpl.java#L3075

Which seems to take a single field as order to build the underlying SQL.

This utility would need to be restructured so to allow more than one field to be specified as order key.

On the other hand @resmo, are you sure this has ever worked? I mean that cloudstack has returned zones in a deterministic order in the past? It is common for databases not to assure any row order when no order clause is specified but still to return the rows in the order they were created...

**Comment by weizhouapache** [comment] 2020-09-28 10:53
@rvalle agrees. It should be a regression issue caused by #3242
sort_key are all 0 in cloud.data_center table.

**Comment by DaanHoogland** [comment] 2020-11-04 10:01
@resmo @dpassante do you have a fix or work around? it seems to me not a serious issue but please correct me on that.
@rhtyd @shwstppr @davidjumani is sort order still used the same way in primate? should the default be -1 instead of 0 for instance?

**Comment by resmo** [comment] 2020-11-04 13:07
@DaanHoogland well, we have to make the previous optional zone argument a required argument in almost all modules. This will break backwards compatibly, which means we make most likely many users angry.

You can call this ""work around" I call it a bad user experience for a "fix" introduced by cloudstack and which should be fixed by cloudstack and not by its clients or users.

**Comment by weizhouapache** [comment] 2020-11-04 13:27
@resmo this workaround should work for you.

```
UPDATE `cloud`.`data_center` SET `sort_key` = `id` WHERE `sort_key` = 0;
```
this change will break the ordering of zones if users set sort_key to a non-zero value and use sort_key to order zones. so I will not sure if we can merge this change into 4.14.1.0 or 4.15.0.0

this issue might exists with template, disk offering, service offering, network offering as well.

**Comment by resmo** [comment] 2020-11-04 13:59
@weizhouapache no, this won't work for me. 

I am not referring to one single specific installation. I am speaking of the API clients and ansible integration relying on the API to behave predicable and stable, now and in the future. It is not the first time I fixed regressions of the API in API clients and ansible modules.

> this issue might exists with template, disk offering, service offering, network offering as well.

As a cloudstack apache member, I won't accept we break the API on purpose and let users work around it. The fact, this issue exists not only for zones but for other resources makes it even worse!

**Comment by weizhouapache** [comment] 2020-11-05 08:08
> @weizhouapache no, this won't work for me.
> 
> I am not referring to one single specific installation. I am speaking of the API clients and ansible integration relying on the API to behave predicable and stable, now and in the future. It is not the first time I fixed regressions of the API in API clients and ansible modules.
> 
> > this issue might exists with template, disk offering, service offering, network offering as well.
> 
> As a cloudstack apache member, I won't accept we break the API on purpose and let users work around it. The fact, this issue exists not only for zones but for other resources makes it even worse!

@resmo I mean the sql change should fix the issue that "zones are returned in random order' of existing environment.
If you do not have your own fork and use the official release, there is no way to make sql change during process managed by ansible, then you have to wait for next official release, which could have a fix for this issue (either this db change or other api/java change).

**Comment by DaanHoogland** [comment] 2020-11-06 08:08
I like @weizhouapache 's id to set sort_key to id for all sortable resources, as a quick solution. I do wonder whether they should be sorted in the system at all. The sql would be half of the work, the runtime insertions will need to be implemented like that as well.

**Comment by resmo** [comment] 2020-11-06 08:26
> If you do not have your own fork and use the official release, there is no way to make sql change during process managed by ansible, then you have to wait for next official release, which could have a fix for this issue (either this db change or other api/java change).

probably misunderstanding, ansible modules as clients interacting wiht API of cloudstack https://galaxy.ansible.com/ngine_io/cloudstack rely on a stable API. Once a cloudstack user upgrades to a newer cloudstack version, all clients, be it an ansible module or a library or a cloudmonkey cli should still work as before unless we, as a cloudstack devs, make the decision to break the API. That is what I wanted to point out.

**Comment by resmo** [comment] 2020-11-06 08:28
also see #2735 for another example of breaking the API

**Comment by resmo** [comment] 2020-11-06 08:34
@weizhouapache if this is fixed in any near future release, I would be happy.

**Closed** 2020-11-25 10:00 UTC
Labels: type:bug, type:regression
