### ISSUE TITLE
4.17.1.0 registor iso image  Connection refused (Connection refused)

### ISSUE THREAD

**Issue by 1450793561** [apache/cloudstack#6789] opened 2022-09-30 06:08 UTC
4.17.1.0 版本注册iso镜像 转态总是连接失败Connection refused (Connection refused)

也将这个配置修改secstorage.allowed.internal.sites为0.0.0.0/32都不好使，求指点

**Comment by DaanHoogland** [comment] 2022-09-30 09:59
![image](https://user-images.githubusercontent.com/2486961/193245842-43ebf695-f1c4-47e1-a88e-eff564365744.png)

**Comment by weizhouapache** [comment] 2022-09-30 10:22
@1450793561 
the problem might be caused by secstorage.allowed.internal.sites
to confirm it, can you log into secondary storage vm (SSVM) and share the result of command `route -n` ?

**Comment by nvazquez** [comment] 2022-09-30 10:36
Hi @1450793561 can you please update the title and description to English?

**Comment by DaanHoogland** [comment] 2022-09-30 10:43
@1450793561 after getting some explanation from @weizhouapache about the chinese, I think your problem is the cidr 0.0.0.0/32. Can you try with 0.0.0.0/0? that should work better.

**Comment by 1450793561** [comment] 2022-10-08 05:21
update parameter 'secstorage.allowed.internal.sites' is being  0.0.0.0/0 that not well

**Comment by 1450793561** [comment] 2022-10-08 08:12
The global configuration has been changed to 0.0.0.0/16. The iso image is registered or the connection is [rejected]
![企业微信截图_20221008161019](https://user-images.githubusercontent.com/31468018/194697462-e6d7591d-e908-4a13-b104-a66c356d3991.png)

**Comment by DaanHoogland** [comment] 2022-10-10 19:40
@1450793561 the cidr 0.0.0.0/16 would mean all adresses starting with 0.0... this is not a sensible cidr for this setting. Use 0.0.0.0/0 or when you have such a cidr for  them it would look like a.b.c.d/32 or f.g.h.0/24

**Comment by 1450793561** [comment] 2022-10-13 09:23
@weizhouapache 

in version 4.15.2.0,changed the parameter 'secstorage.allowed.internal.sites' be 0.0.0.0/0,register iso You'll see the download progress immediately
![微信图片_20221013171925](https://user-images.githubusercontent.com/31468018/195557318-61ed5b07-6203-4432-bdb9-0fac58b05b9a.png)

**Comment by weizhouapache** [comment] 2022-10-13 09:34
> @weizhouapache
> 
> in version 4.15.2.0,changed the parameter 'secstorage.allowed.internal.sites' be 0.0.0.0/0,register iso You'll see the download progress immediately，please see the fllowing screenshots.why is version 4.17 not working???
> 
> ![微信图片_20221013171925](https://user-images.githubusercontent.com/31468018/195557318-61ed5b07-6203-4432-bdb9-0fac58b05b9a.png)

@1450793561 
if you can open the console of Secondary Storage VM of 4.17.1.0, can you share the screenshots of following commands ?

# wget http://xxxxxx.iso
# ip route

**Comment by 1450793561** [comment] 2022-10-14 08:34
@weizhouapache 

It's really strange, I just tried to register iso successfully, the same operation steps

**Comment by 1450793561** [comment] 2022-11-04 03:23
Reinstall it again and modify global configuration secstorage. Charges. Internal sites' be 0.0.0.0/0 succeeded

**Comment by DaanHoogland** [comment] 2022-11-07 10:49
@1450793561 can we close this?

**Closed** 2023-01-10 15:46 UTC
Labels: type:question
