### ISSUE TITLE
Upgrade failing from 4.12 to 4.13

### ISSUE THREAD

**Issue by belperite** [apache/cloudstack#3614] opened 2019-10-02 09:14 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Upgrade failing from 4.12 to 4.13
~~~

##### CLOUDSTACK VERSION

~~~
4.13
~~~

##### CONFIGURATION

KVM Hypervisor, management server on same machine as hypervisor, advanced networking.

##### OS / ENVIRONMENT

OS is Ubuntu Bionic

##### SUMMARY

I am attempting to upgrade from 4.12 to 4.13, however the upgrade is failing with:
`2019-10-02 09:55:38,966 ERROR [c.c.u.DatabaseUpgradeChecker] (main:null) (logid:) Unable to upgrade the database
com.cloud.utils.exception.CloudRuntimeException: 4.13.0.0KVM SystemVm template not found. Cannot upgrade system Vms
	at com.cloud.upgrade.dao.Upgrade41200to41300.updateSystemVmTemplates(Upgrade41200to41300.java:210)
	at com.cloud.upgrade.dao.Upgrade41200to41300.performDataMigration(Upgrade41200to41300.java:67)
`
The one which currently exists on the system is systemvmtemplate-4.11.3-kvm. The documentation specifically states that "System VM Template upgrade is not required when upgrading from 4.12.x to 4.13.0.0.". Indeed, there appears to be no later version than this to download.

##### STEPS TO REPRODUCE

Run through upgrade instructions here:

http://docs.cloudstack.apache.org/en/4.13.0.0/upgrading/upgrade/upgrade-4.12.html

~~~

~~~

##### EXPECTED RESULTS

The upgrade to succeed.
~~~

~~~

##### ACTUAL RESULTS

The upgrade failed.

~~~

~~~

**Comment by rhtyd** [comment] 2019-10-02 09:17
Cc @PaulAngus @andrijapanicsb

**Comment by rhtyd** [comment] 2019-10-02 09:18
@belperite you need to setup the 4.11.3 systemvmtemplate prior to upgrading to 4.13 from any version.

**Comment by belperite** [comment] 2019-10-02 10:44
@rhtyd Thanks! I had to go back to the beginning with a DB backup, then add the new systemvm template through the UI (not through the cloud-install-sys-tmplt script as I had tried initially), then do the upgrade again and it seemed to work this time. It may be an idea to update the documentation to this effect? I was previously on 4.11.2, so did not upgrade at first because of:

![cs-noupgrade](https://user-images.githubusercontent.com/33836503/66038408-f5a1d180-e509-11e9-8683-5e4b22447453.png)

**Comment by PaulAngus** [comment] 2019-10-02 12:43
Ah, I see the issue here, 4.12 came out before 4.11.3 so if you jumped 4.11.2 ->4.12, you wouldn't have the 4.11.3 template.
If you upgraded 4.11.2->4.11.3 -> 4.12 you would have the 4.11.3 template.

**Comment by belperite** [comment] 2019-10-02 12:52
@PaulAngus Yes that's right. Possibly a small documentation tweak would avoid others coming across the issue?

**Comment by PaulAngus** [comment] 2019-10-02 16:01
I've created a PR to fix this:
https://github.com/apache/cloudstack-documentation/pull/72

Built docs can be reviewed here:
https://acs-www.shapeblue.com/docs/pr72/upgrading/upgrade/upgrade-4.12.html

![image](https://user-images.githubusercontent.com/4810220/66060753-197b0c80-e536-11e9-9d78-357ce00d4f4b.png)

**Comment by rhtyd** [comment] 2019-10-03 09:50
Paul's PR has been merged, closing this. Website would be updated soon, in not done already.

**Closed by rhtyd** 2019-10-03 09:50 UTC

**Comment by tarmof** [comment] 2019-10-08 11:33
Hello, is it any possibility do this via console or direct database modification?
I cannot start version 4.12 cloudstack-management any more.
It gives error;
2019-10-08 01:00:15,775 DEBUG [o.a.c.f.c.i.ConfigDepotImpl] (main:null) (logid:) Retrieving keys from RootCAProvider
2019-10-08 01:00:15,803 DEBUG [o.a.c.s.l.r.ExtensionRegistry] (main:null) (logid:) Registering extension [RootCAProvider] in [Ca Providers Registry]
2019-10-08 01:00:15,803 DEBUG [o.a.c.s.l.r.RegistryLifecycle] (main:null) (logid:) Registered org.apache.cloudstack.ca.provider.RootCAProvider@20e4e27f
2019-10-08 01:00:15,803 INFO  [o.a.c.s.l.CloudStackExtendedLifeCycle] (main:null) (logid:) Configuring CloudStack Components
2019-10-08 01:00:15,828 WARN  [o.a.c.s.m.c.ResourceApplicationContext] (main:null) (logid:) Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean '
cloudStackLifeCycle'; nested exception is java.lang.NullPointerException
2019-10-08 01:00:15,829 WARN  [o.e.j.w.WebAppContext] (main:null) (logid:) Failed startup of context o.e.j.w.WebAppContext@58fdd99{/client,file:///usr/share/cloudstack-management/webapp/,UNAVAILABLE}{/usr/share/cloudstack-management/webapp}
org.springframework.context.ApplicationContextException: Failed to start bean 'cloudStackLifeCycle'; nested exception is java.lang.NullPointerException
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:186)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:52)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:358)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:159)
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:884)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContext(DefaultModuleDefinitionSet.java:145)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet$2.with(DefaultModuleDefinitionSet.java:122)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:245)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:250)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.withModule(DefaultModuleDefinitionSet.java:233)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.loadContexts(DefaultModuleDefinitionSet.java:117)
        at org.apache.cloudstack.spring.module.model.impl.DefaultModuleDefinitionSet.load(DefaultModuleDefinitionSet.java:79)
        at org.apache.cloudstack.spring.module.factory.ModuleBasedContextFactory.loadModules(ModuleBasedContextFactory.java:37)
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.init(CloudStackSpringContext.java:71)
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:58)
        at org.apache.cloudstack.spring.module.factory.CloudStackSpringContext.<init>(CloudStackSpringContext.java:62)
        at org.apache.cloudstack.spring.module.web.CloudStackContextLoaderListener.contextInitialized(CloudStackContextLoaderListener.java:52)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:532)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:344)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1515)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1477)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:261)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:273)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:115)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:133)
        at org.eclipse.jetty.server.Server.start(Server.java:418)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:107)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
        at org.eclipse.jetty.server.Server.doStart(Server.java:385)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.apache.cloudstack.ServerDaemon.start(ServerDaemon.java:186)
        at org.apache.cloudstack.ServerDaemon.main(ServerDaemon.java:103)
Caused by: java.lang.NullPointerException
        at org.apache.cloudstack.utils.security.CertUtils.pemToPublicKey(CertUtils.java:145)
        at org.apache.cloudstack.ca.provider.RootCAProvider.loadRootCAKeyPair(RootCAProvider.java:335)
        at org.apache.cloudstack.ca.provider.RootCAProvider.setupCA(RootCAProvider.java:381)
        ... 55 more
2019-10-08 01:00:15,831 INFO  [o.e.j.s.h.ContextHandler] (main:null) (logid:) Started o.e.j.s.h.MovedContextHandler@679b62af{/,null,AVAILABLE}
2019-10-08 01:00:15,850 INFO  [o.e.j.s.AbstractConnector] (main:null) (logid:) Started ServerConnector@1a1d6a08{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-10-08 01:00:15,850 INFO  [o.e.j.s.Server] (main:null) (logid:) Started @22604ms
