### ISSUE TITLE
NFS Cluster-wide storage capacity calculation and overprovisioning

### ISSUE THREAD

**Issue by bwsw** [apache/cloudstack#3447] opened 2019-07-01 03:55 UTC
##### ISSUE TYPE

 * Bug Report
 
##### COMPONENT NAME

~~~
Core, KVM, NFS
~~~

##### CLOUDSTACK VERSION

~~~
4.11.2
~~~

##### CONFIGURATION

Cloudstack with KVM and NFS

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

When NFS cluster-wide primary storage is used, the capacity limitations are calculated wrong way:
* storage.overprovisioning.factor configured for the storage is not taken into account;

##### STEPS TO REPRODUCE

Create storage with ` storage.overprovisioning.factor` set to `4`, fill it with thin volumes, detect when it stops to provision new volumes.

##### EXPECTED RESULTS

~~~
Per-storage overprovisioning setting should be taken into consideration
~~~

##### ACTUAL RESULTS

~~~
Per-storage overprovisioning setting is not taken into consideration
~~~

**Comment by shwstppr** [comment] 2019-07-04 11:59
Unable to reproduce on master. _Per-storage overprovisioning setting is considered on master_.
![Screenshot from 2019-07-04 17-01-49](https://user-images.githubusercontent.com/153340/60663694-933f2380-9e7d-11e9-9d00-a8824b55dd77.png)
![Screenshot from 2019-07-04 17-02-21](https://user-images.githubusercontent.com/153340/60663705-989c6e00-9e7d-11e9-950f-439a3e0c1f19.png)


```
2019-07-04 17:26:53,451 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-17:ctx-87980313 job-181/job-182 ctx-e8c132ff) (logid:4e2e7043) Destination pool id: 2
2019-07-04 17:26:53,454 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-17:ctx-87980313 job-181/job-182 ctx-e8c132ff) (logid:4e2e7043) Pool ID for the volume with ID 35 is null
2019-07-04 17:26:53,455 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-17:ctx-87980313 job-181/job-182 ctx-e8c132ff) (logid:4e2e7043) Found storage pool Primary1 of type NetworkFilesystem with over-provisioning factor 4
2019-07-04 17:26:53,455 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-17:ctx-87980313 job-181/job-182 ctx-e8c132ff) (logid:4e2e7043) Total over-provisioned capacity calculated is 4 * 100256448512
2019-07-04 17:26:53,455 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-17:ctx-87980313 job-181/job-182 ctx-e8c132ff) (logid:4e2e7043) Total capacity of the pool Primary1 with ID 2 is 401025794048
2019-07-04 17:26:53,455 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-17:ctx-87980313 job-181/job-182 ctx-e8c132ff) (logid:4e2e7043) Checking pool: 2 for storage allocation , maxSize : 401025794048, totalAllocatedSize : 354639560704, askingSize : 107374182400, allocated disable threshold: 0.95
2019-07-04 17:26:53,455 DEBUG [c.c.s.StorageManagerImpl] (Work-Job-Executor-17:ctx-87980313 job-181/job-182 ctx-e8c132ff) (logid:4e2e7043) Insufficient un-allocated capacity on: 2 for storage allocation since its allocated percentage: 1.1520798660863698 has crossed the allocated pool.storage.allocated.capacity.disablethreshold: 0.95, skipping this pool
```

**Comment by rhtyd** [comment] 2019-07-09 07:26
Closing on your testing and remark @shwstppr 
Kindly re-open if this is reproduced with 4.13+

**Closed by rhtyd** 2019-07-09 07:26 UTC
