### ISSUE TITLE
FibreChannelAdaptor disconnectPhysicalDiskByPath should not always return true

### ISSUE THREAD

**Issue by rp-** [apache/cloudstack#8789] opened 2024-03-14 11:45 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
KVM-Storage
~~~

##### CLOUDSTACK VERSION

~~~
4.19.0
~~~

##### SUMMARY

I'm not pointing fingers as the Linstor driver also needs a fix for that(comming), but
`disconnectPhysicalDiskByPath` should only return true if it is able to handle that path.
Currently it tries to handle every path and if it is used as the first entry in the StorageadaptorMap it will always "win",
even if it isn't the driver device.
Also the formatting looks a bit off in that method.

https://github.com/apache/cloudstack/blob/e87c6cfcb1d6ec722dc7f8f6d4579b585e5bb87e/plugins/hypervisors/kvm/src/main/java/com/cloud/hypervisor/kvm/storage/MultipathSCSIAdapterBase.java#L225

##### STEPS TO REPRODUCE

~~~
Have a non FibreChannel primary storage and stop/move a VM to another host.
disconnectbyPath will be called and if FibreChannel adaptor is 1. in the Map it will take over the disconnect call.
~~~

##### EXPECTED RESULTS

~~~
FibreChannel driver only handling paths belonging to it
~~~

##### ACTUAL RESULTS

~~~

~~~

@rg9975

**Comment by harikrishna-patnala** [comment] 2024-06-10 11:35
@rp- I see the following part has be already handled in the PR #8889 
 public boolean disconnectPhysicalDiskByPath(String localPath) { 

I'm trying to fix the case of running into the loop of all adapters by somehow passing the storage pool type to that caller cleanup() method but this is touching all over the code (which I fear it creates other regressions), instead I feel we can keep it the current way only since Fibrechannel adapter has already fixed. Whats your thoughts @rp-

**Comment by harikrishna-patnala** [comment] 2024-06-11 04:13
Thanks @rp- let me add a clear java doc for that purpose and explaining the possible bug.

**Comment by rohityadavcloud** [comment] 2024-06-11 09:15
Javadoc addressed by https://github.com/apache/cloudstack/pull/9210

**Closed** 2024-06-11 09:34 UTC
