### ISSUE TITLE
Bad/no input validation

### ISSUE THREAD

**Issue by ngrosc** [apache/cloudstack#8455] opened 2024-01-08 06:42 UTC
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.17.2
~~~

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Stacktrace shown when using special characters

##### STEPS TO REPRODUCE

~~~
Create a project
create a new project role
Enter some special characters like "'">*)asdf-${{<%[%'"}}%\" for description and role name. 
Assign a new rule
~~~

##### EXPECTED RESULTS

~~~
UI does not accept invalid characters/encodes them or shows an error
~~~

##### ACTUAL RESULTS

~~~
Stacktrace is shown:
TypeError: Cannot read properties of undefined (reading 'description')
    at https://portal.netcloud.cloud/client/js/chunk-5bb1f237.2b1722b7.js:1:12466
    at a (https://portal.netcloud.cloud/client/js/vendors.66cf1d0f.js:57:109955)
    at https://portal.netcloud.cloud/client/js/vendors.66cf1d0f.js:70:180767
    at Proxy.flatMap (<anonymous>)
    at Q (https://portal.netcloud.cloud/client/js/vendors.66cf1d0f.js:70:180738)
    at te (https://portal.netcloud.cloud/client/js/vendors.66cf1d0f.js:70:181204)
    at Proxy.render (https://portal.netcloud.cloud/client/js/vendors.66cf1d0f.js:70:182279)
    at yn (https://portal.netcloud.cloud/client/js/vendors.66cf1d0f.js:57:110259)
    at oe.e [as fn] (https://portal.netcloud.cloud/client/js/vendors.66cf1d0f.js:57:141197)
    at oe.run (https://portal.netcloud.cloud/client/js/vendors.66cf1d0f.js:57:96000)
~~~

**Comment by kiranchavala** [comment] 2024-01-09 06:58
@ngrosc I am not able to reproduce the issue on 4.18 or 4.19 rc1

Able to create role with special characters

![Screenshot 2024-01-09 at 12 26 13 PM](https://github.com/apache/cloudstack/assets/1401014/a372ff91-bc7f-48c8-84e7-8dd994545a63)

**Comment by DaanHoogland** [comment] 2024-01-23 13:05
@ngrosc can you try a newer version?

**Comment by sureshanaparti** [comment] 2024-05-23 13:50
Hi @ngrosc Have you tried with newer version of CloudStack as Daan advised?

**Comment by DaanHoogland** [comment] 2024-06-18 09:11
@ngrosc closing this as it seems to be solved. I have not found the change that solved it. Feel free to update/re-open.

**Closed by DaanHoogland** 2024-06-18 09:11 UTC
Labels: component:UI, status:needs-reproducing, affects:4.17.2
