### ISSUE TITLE
GSoC 2021 Idea: Support Multiple SSH Keys for VMs

### ISSUE THREAD

**Issue by davidjumani** [apache/cloudstack#4813] opened 2021-03-15 04:21 UTC
## Background

As of now, ACS supports only a single SSH key to be added / reset on a VM.
This proposes the support of multiple SSH Keys

## Proposed Tasks

- Understand basic ACS
- Understand basic cloud-init
- Setup a basic ACS Environment
- Modify the existing API or add a new one
- Change the service layer and DB to allow multiple SSH Keys
- Tweak the VR if needed

## Proposed Mentor

David Jumani (david.jumani@shapeblue.com)
Rohit Yadav (rohit@apache.org)

## Difficulty

Medium

**Comment by weizhouapache** [comment] 2021-03-15 08:34
@davidjumani good idea 💯 
it is in our backlog for many years

**Comment by bickrombishsass** [comment] 2021-03-31 08:58
Hello. I have made an Azure student account and trying to understand the functioning and other relevant things that will be needed for this project. 
I am looking forward to writing a project proposal.

**Comment by davidjumani** [comment] 2021-03-31 14:22
Hi @bickrombishsass I've sent you a mail that'll help you get started. Feel free to ping me if you need anything else

**Comment by bickrombishsass** [comment] 2021-04-02 14:10
Hello. I have written a draft proposal. Should I post it on the GSoC page for you to check? 
also. Do you have any specific format for the proposal?

**Comment by rhtyd** [comment] 2021-04-05 06:48
Hi @bickrombishsass thanks for your interest.

I would advise that you read the community GSoC guidelines (https://community.apache.org/gsoc.html), join the dev mailing list (http://cloudstack.apache.org/mailing-lists.html) to discuss your GSoC idea/proposal/application, and start drafting your application (for example https://google.github.io/gsocguides/student/proposal-example-1). With your proposed mentor (see email above), start an early discussion with them and you can ask them to review your application draft (for example, compose your draft and share with a Google doc).

You can refer to the CloudStack course to help you draft your application and learn how to build something in CloudStack https://github.com/shapeblue/hackerbook

**Comment by bickrombishsass** [comment] 2021-04-05 12:38
Hello mentors.
I have submitted the draft proposal. 
@rhtyd @davidjumani

**Comment by bickrombishsass** [comment] 2021-04-10 05:20
@rhtyd @davidjumani pls let me know if more changes needed on the proposal.

**Comment by neogismm** [comment] 2022-01-20 06:48
Hello community. I wanted to know if the issue is still open as it's labelled for GSOC 21. I'm looking forward to contribute to ACS as a mentee in GSOC 22.
Thanks.

**Comment by rohityadavcloud** [comment] 2022-01-20 06:51
This is already addressed @neogismm in the last gsoc21. I'll close this, as the PR is open.

**Closed by rohityadavcloud** 2022-01-20 06:51 UTC
Labels: type:improvement, gsoc2021
